### ISSUE TITLE
Add linter support for bicep language

### ISSUE THREAD

**Issue by t3mi** [oxsecurity/megalinter#1017]
Please consider adding support for [linting](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/linter) [bicep](https://github.com/Azure/bicep) files in addition to ARM templates.

**Comment by nvuillam** [comment]
Interesting, TODO when we have some bandwith :)

Or you can also make a PR :)

**Comment by t3mi** [comment]
not stale

**Comment by nvuillam** [comment]
Agreed :)
Let's hope someone (me or other) find time someday soon to add it :)

**Comment by t3mi** [comment]
not stale

**Comment by omusavi** [comment]
Reopening - I have a branch with the WIP version of this, hoping to PR soon

https://github.com/omusavi/megalinter/tree/bicep-linter
