### ISSUE TITLE
Remove Support for rstcheck and rstfmt

### ISSUE THREAD

**Issue by Kurt-von-Laven** [oxsecurity/megalinter#1139]
**Is your feature request related to a problem? Please describe.**
A test failure in rstfmt is preventing us from upgrading to Python 3.10.

**Describe the solution you'd like**
Remove support for rstcheck and rstfmt in our v6 release.

**Describe alternatives you've considered**
We could either alternatively or additionally open issues requesting that rstcheck and rstfmt support Python 3.10.

**Additional context**
> [StackOverflow has 1,155 questions tagged reStructuredText](https://stackoverflow.com/questions/tagged/restructuredtext), so it sounds like it's a documentation format that is essentially only used by a small handful of Python developers. There were only 8 hits for [rstcheck](https://stackoverflow.com/search?q=rstcheck), so it looks like most folks using reStructuredText don't use rstcheck, and like you say the project is no longer seeing releases. rstfmt had a release 3 months ago, but [their README](https://github.com/dzhu/rstfmt#rstfmt-a-formatter-for-restructuredtext) opens with: "Highly experimental and unstable. Do not depend on this yet." My intuition overall is that MegaLinter users as a whole will probably prefer having a lot of tools that play nice together out of the box to having even more tools but also more headaches. On top of that, we could easily end up getting completely bogged down by maintenance if we aren't careful. I'm sure we will hear from our users if reStructuredText is very important to them. ~ https://github.com/megalinter/megalinter/pull/834#issuecomment-1003259619

**Comment by Kurt-von-Laven** [comment]
Noting for anyone who may be following this issue that rstfmt has been temporarily disabled.

**Comment by nvuillam** [comment]
RSTCHECK is upgraded, RSTFMT has been removed from v6 :)
