### ISSUE TITLE
Allow to run with podman instead of docker.

### ISSUE THREAD

**Issue by andho** [oxsecurity/megalinter#1160]
**Is your feature request related to a problem? Please describe.**
I am shifting from docker to podman for rootless containers but mega-linter uses docker.

**Describe the solution you'd like**
Megalinter can allow the user to choose the container runtime (docker or podman) during project setup (or user can add to the config manually). If podman is chosen, megalinter will replace docker with podman when running.

**Describe alternatives you've considered**
Let user define docker binary. As podman is compatible with docker in terms of usage (sub command, flags and arguments) this should work, but need further testing.

**Additional context**
-

**Comment by nvuillam** [comment]
I have not used podman yet but I'm oepn to the idea :)

Can you provide an example of CI configuration using podman that could be generated ?
Or are you talking about mega-linter-runner that embeds a `docker run` command ?

**Comment by andho** [comment]
Hi, I'll update something here in a few days. Thanks for the reply.

**Comment by andho** [comment]
I'll see if I can do a PR when I'm free. Will close this for now.

**Comment by TimonLukas** [comment]
I was able to get Megalinter to use Podman by symlinking the docker executable to it and running a podman service to expose a socket:

```shell
ln -s /usr/bin/podman /usr/bin/local/docker
podman system service unix:///var/run/docker.sock -t 0 &
```

However the runner doesn't actually finish, for me it seems to get stuck at the some point every time. It's almost done, and I have a bunch of individual linter logs, but the final console report isn't generated.

**Comment by Kurt-von-Laven** [comment]
I'm not sure if this applies to your situation, but rootless containers were the OP's motivation for using Podman. Docker has a [rootless mode](https://docs.docker.com/engine/security/rootless/) as well, and [rootless-docker](https://github.com/ScribeMD/rootless-docker) lets you use Docker's rootless mode on GitHub Actions if either of those are of use to you. I am afraid I don't have any experience with Podman, but I'm guessing you would need to open a shell in the container and use some debugging tools. For almost any MegaLinter-related debugging, I recommend setting [`LOG_LEVEL=DEBUG`](https://megalinter.github.io/latest/configuration/). I actually take it as an encouraging sign that you got it to run almost to the end considering that MegaLinter has never been tested on Podman to my knowledge.

**Comment by nvuillam** [comment]
@hinricht are you able to run MegaLinter docker image directly with podman ? ([example of raw call with docker](https://megalinter.io/latest/install-docker/))

If yes and if you can provide the command line, we could update mega-linter-runner so it can call podman and not docker :)

**Comment by hinricht** [comment]
Oh wait, I found a way to run mega-linter with podman. I needed to activate the **user** socket like this:

```
$ systemctl --user start podman.socket
$ systemctl --user status podman.socket
● podman.socket - Podman API Socket
     Loaded: loaded (/usr/lib/systemd/user/podman.socket; disabled; preset: enabled)
     Active: active (listening) since Tue 2023-08-01 12:21:49 CEST; 4min 25s ago
   Triggers: ● podman.service
       Docs: man:podman-system-service(1)
     Listen: /run/user/1000/podman/podman.sock (Stream)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/podman.socket

Aug 01 12:21:49 panza systemd[875]: Listening on Podman API Socket.
$ docker run --rm -v /run/user/1000/podman/podman.sock:/var/run/docker.sock:rw -v $(pwd):/tmp/lint:rw oxsecurity/megalinter:v7
Skipped setting git safe.directory DEFAULT_WORKSPACE:  ...
Setting git safe.directory default: /github/workspace ...
Setting git safe.directory to /tmp/lint ...
[MegaLinter init] ONE-SHOT RUN
[config] Environment variables only (no config file found in /tmp/lint)
...
```

**Comment by nvuillam** [comment]
Seems great :)

Docker is docker is used with very few linters (only swiftlint that does not very well I think), so you can also try without the -v argument, it might work even without your workaround :)

**Comment by MRDGH2821** [comment]
Seems like the runner is still using using docker specific stuff despite specifying podman

```log
bunx mega-linter-runner --container-engine podman
Pulling docker image ghcr.io/oxsecurity/megalinter:v9 ...
INFO: this operation can be long during the first use of mega-linter-runner
The next runs, it will be immediate (thanks to docker cache !)
Trying to pull ghcr.io/oxsecurity/megalinter:v9...
Getting image source signatures
Copying blob 48efa03bfc79 skipped: already exists
Copying blob 48efa03bfc79 skipped: already exists
Copying blob 48efa03bfc79 skipped: already exists
Copying blob 622a7f9ba01c skipped: already exists
Copying blob 421d265e1f85 skipped: already exists
Copying blob 83de195a066c skipped: already exists
Copying blob 1815bedfe4fd skipped: already exists
Copying blob 4f4fb700ef54 skipped: already exists
Copying blob 27902a29cdb6 skipped: already exists
Copying blob 727c63559362 skipped: already exists
Copying blob cd4029dde8d6 skipped: already exists
Copying blob 89ae14e67821 skipped: already exists
Copying blob 92489e35088a skipped: already exists
Copying blob 4f4fb700ef54 skipped: already exists
Copying blob bafef4f1a46c skipped: already exists
Copying config 66f21e45a3 done   |
Writing manifest to image destination
66f21e45a3f3848cb76ee138f3aad0ac2845b98adce5e9cde9cef737bb04f799
Command: podman run --platform linux/amd64 --rm -v /var/run/docker.sock:/var/run/docker.sock:rw -v /home/mr-fw16/Projects/Source-Codes/copier-mr-minimal:/tmp/lint:rw ghcr.io/oxsecurity/megalinter:v9
Error: statfs /var/run/docker.sock: permission denied
```

**Comment by MRDGH2821** [comment]
I found a workaround!

```sh
podman run --platform linux/amd64 --rm -v $(pwd):/tmp/lint:z ghcr.io/oxsecurity/megalinter:v9 

# optional to add: --userns=keep-id
```
That `:z` flag appeases to SELinux. Ran this command in fresh install of Fedora 44
