### ISSUE TITLE
Why do you use .python-lint instead of pylintrc

### ISSUE THREAD

**Issue by kkaiser** [oxsecurity/megalinter#1307]
Dear all,

thanks for this great project. My question is basically in the title. The default configuration file for pylint is [pylintrc](https://github.com/PyCQA/pylint/blob/main/pylintrc) which you even [link to](https://github.com/megalinter/megalinter/blob/a843206cb8290fbf711fbfb46667a91fae70d504/docs/descriptors/python_pylint.md?plain=1#L14) in your docs but you use a different configuration file called .python-lint.

The main issue with this if I want to run pylint locally using the CLI of my machine I will get errors that are already ignored. Then I have to set the option `--rcfile=.python-lint`. Same counts for the IDE, e.g. in VS Code:
```json
"python.linting.pylintArgs": [
    "--rcfile=.python-lint"
],
```

**Comment by nvuillam** [comment]
You're absolutely right, .python-lint is a legacy from Super-Linter , but shoudl be renamed into `.pytlintrc` :)

Will do that in the next release :)

**Comment by nvuillam** [comment]
@kkaiser solved in v6, now default pylint config file name is `.pylintrc` :)

https://oxsecurity.github.io/megalinter/latest/descriptors/python_pylint/
