### ISSUE TITLE
Salesforce SFDX CLI Update message confuses the regex parser

### ISSUE THREAD

**Issue by mcdcb** [oxsecurity/megalinter#1398]
**Describe the bug**
We're trying to run the Salesforce SFDX linter suite and it looks like it's failing because the megalinter parser tries to parse the update warning from sfdx-cli. (We expect to see one issue with the code but it returns nothing but the green check)

The exact error message: ```Unable to extract version with regex re.compile('(?<=@salesforce/sfdx-scanner )\\d+(\\.\\d+)+') from  ›   Warning: sfdx-cli update available from 7.144.2 to 7.145.0.```

**To Reproduce**

1. Go to megalinter results
2. Click on logs
3. Scroll down to `SALESFORCE_SFDX_SCANNER_AURA` results
4. See error `no plugins installed` (screenshot attached)

**Expected behavior**
Either the parsing should ignore the `sfdx-cli` update message, or the `sfdx update` command should be run each time to ensure we're on the latest version.

The parsing code seems to be here: https://github.com/megalinter/megalinter/blob/main/megalinter/Linter.py#L715

**Screenshots**
Added screenshot of the error ![Screen Shot 2022-04-09 at 9 52 15 AM](https://user-images.githubusercontent.com/70228750/162583757-f553eb84-800d-49ce-a730-ba68884b8a38.png)

**Additional context**
We think this is the root issue, but happy to be wrong :)

**Comment by nmhegde-cb** [comment]
I'm seeing a similar issue. I have attached the log files from the resulting run.
[mega-linter.log](https://github.com/megalinter/megalinter/files/8506874/mega-linter.log)
[SUCCESS-SALESFORCE_SFDX_SCANNER_APEX.log](https://github.com/megalinter/megalinter/files/8506879/SUCCESS-SALESFORCE_SFDX_SCANNER_APEX.log)
[SUCCESS-SALESFORCE_SFDX_SCANNER_AURA.log](https://github.com/megalinter/megalinter/files/8506880/SUCCESS-SALESFORCE_SFDX_SCANNER_AURA.log)
[SUCCESS-SALESFORCE_SFDX_SCANNER_LWC.log](https://github.com/megalinter/megalinter/files/8506881/SUCCESS-SALESFORCE_SFDX_SCANNER_LWC.log)

**Comment by nvuillam** [comment]
According to your logs, the issue is more than sfdx-scanner is not installed than the not retrievable version :/

What version of MegaLinter are you using ?

**Comment by nmhegde-cb** [comment]
I tried both the Beta & v5 version. It seems like it's happening for both of the versions.

**Comment by nvuillam** [comment]
I'm currently stucked on git safe.directory hell https://github.com/megalinter/megalinter/issues/1416 but i'll try to look on this issue later if someone does not find a solution before :)
