### ISSUE TITLE
Vulnerabilities in python:3.9.7-alpine3.13 base image

### ISSUE THREAD

**Issue by fredrondina** [oxsecurity/megalinter#1406]
Hey all, loving the tool. Just wanted to bring some security vulnerabilities snyk.io found in the python:3.9.7-alpine3.13 base image.

There are 8 vulnerabilities listed as `critical` coming from the `expat` package in the alpine:3.13 image.

https://snyk.io/vuln/alpine%3A3.13%3Aexpat

Critical Vulnerabilities Found

- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2342171
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2342172
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2342173
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2406625
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2406626
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2407739
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2407752
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2407757

This was found on the python flavor, but I believe this applies to all flavors.

**Comment by nvuillam** [comment]
Thanks for the tip, I'll do that asap :)

I don't think such vulnerability could affect MegaLinter users, but better safe than sorry 😄

**Comment by nvuillam** [comment]
Fixed in V6 :)
