### ISSUE TITLE
Limit list of files to already committed and tracked by GIT repo. Use "git ls-tree" as INCLUDE filter

### ISSUE THREAD

**Issue by needleshaped** [oxsecurity/megalinter#1439]
**Is your feature request related to a problem? Please describe.**
Problem symptomatic: very often in CI/CD pipeline additional files and folders appear, that we need to exclude.
In centralized CI that runs against different frameworks/languages. it is necessary to exclude multiple different folders: (node_modules,build,conda,.git,... ) with a risk always present for another unnecessary files to come into picture, thus requiring maintenance.
N.B. In CI 100% of use cases are based on GIT repository.

**Describe the solution you'd like**
Whitelisting once instead of blacklisting multiple times.

Add option to limit files to ONLY those commited to GIT repository. No additional configuration of includes/excludes will be required. No need to maintain such configuration.

`git ls-tree --full-tree -r --name-only HEAD` will do. `git ls-files` also does it job, but will include staged files (which in general should not happen, but makes ls-tree cleaner solution). See https://stackoverflow.com/questions/8533202/list-files-in-local-git-repo for a discussion.

A. add method as alternative to `list_files_all` (https://github.com/megalinter/megalinter/blob/main/megalinter/MegaLinter.py).
B. add additional option: INCLUDE_GITCOMMITED_ONLY (or similar name) to use this new method instead of `list_files_all`.

**Describe alternatives you've considered**
```
      -e IGNORE_GITIGNORED_FILES=true \
      -e IGNORE_GENERATED_FILES=true \
      -e EXCLUDED_DIRECTORIES=node_modules,build,conda,.git \
```

**Additional context**
Similar approach (whitelisting once exactly what IS needed) is common when using .gitignore, .dockerignore

**Comment by nvuillam** [comment]
Your proposition seems extremely interesting, in terms en maintenance effort + file listing performances :)

I think that to ensure ascending compatibility (some people also use MegaLinter locally and we don't know the state of their repo, or even if there is one) we could implement `FILE_LISTING_METHOD` with values `git_committed` or `browse_directory` (default) , and if it is `git_cimmitted`,  list_files_all would call `git ls-tree --full-tree -r --name-only HEAD`

Would you like to become a contributor, and make a PR  or do you prefer that me or someone else find the time to implement and test such implementation ?

Also: to improve current behaviour, if you have in mind more directories to exclude, don't hesitate to add them with a PR [here](https://github.com/megalinter/megalinter/blob/2322c9e52caa33aecb4a10846d57d658e0e70022/megalinter/utils.py#L43)

**Comment by unchris** [comment]
Apologies if this feature has been implemented since the issue went stale; I did look at the configuration documentation, but haven't seen anything similar.

To approximate the requested behaviour, run `git clean -fd` before running megalinter (or any linter, really). 

It will delete any untracked and ignored files recursively from your project (assuming you are in the root of a git repository).

 If you need to delete more (or less), look at the `-x`, `-X`, and `-e` [options](https://git-scm.com/docs/git-clean).

**Comment by needleshaped** [comment]
@unchris For CI/CD this essentially means 
- running before building (obviously), and 
- storing cache outside of workspace (otherwise it will be deleted). 
  Which is valid option, but requires additional configuration for every type of builds - and makes it hidden/indirect dependency for optimal configuration. That means each and every user will have configure this, increasing learning curve.
  
Thus I still believe, that making a default option is optimal way. The only consideration I have here is performance of filtering, how will it work on extremely large GIT repos.

P.S. I will attempt to make a PR in future.
