### ISSUE TITLE
Black, Flake8, mypy, and Pylint Error On Structural Pattern Matching

### ISSUE THREAD

**Issue by Kurt-von-Laven** [oxsecurity/megalinter#1446]
**Describe the bug**
Any Python 3.10 code containing the new [structural pattern matching syntax](https://peps.python.org/pep-0636/) breaks all four Python linters that build an AST.

**To Reproduce**

1. Run the Python flavor of MegaLinter on a project containing a `test.py` with the following contents: 

    ```python
    x = "hello"
    match x:
        case "hello":
            print("Hello world")
        case "goodbye":
            print("Goodbye, cruel world")
    ```

1. Black complains:

    ```
    error: cannot format /tmp/lint/test.py cannot use --safe with this file; failed to parse source file AST: invalid syntax (<unknown>, line 2)
    This could be caused by running Black with an older Python version that does not support new syntax used in your source file."
    ```

1. Flake8 complains:

    ```
    /tmp/lint/test.py:2:7: E999 SyntaxError: invalid syntax
    ```

1. Pylint combines pieces of the previous two error messages into a single Franken-error:

    ```
    /tmp/lint/test.py:2:7: E0001: invalid syntax (<unknown>, line 2) (syntax-error)
    ```

1. mypy complains in its own special way:

    ```
    ❌ [ERROR] for workspace /tmp/lint
    Linter raw log:
    error: --install-types failed (no mypy cache directory)
    ```

**Expected behavior**
All linters pass (or at least don't raise syntax errors).

**Screenshots**

**Additional context**
I have not fully investigated support for structural pattern matching in all of these linters, but for sure at least Black and mypy support basic cases by now at the versions MegaLinter pulls in. I am running Python 3.10 locally. Hence, I suspect the issue is as Black describes: the linters are being run by Python 3.9. It might be nice to be able to use the local version of Python, but I could imagine that quickly becoming a nightmare. More realistically, I wonder if upgrading the [base Docker image](https://github.com/megalinter/megalinter/blob/b23e3fac2921a18838bc971336592b62541edb95/Dockerfile#L28) for all flavors to Python 3.10.4 would address this? If that seems plausible, I can open a PR and give it a try. I conveniently have a local branch with some Python 3.10 syntax to test it with.

**Comment by Kurt-von-Laven** [comment]
@nvuillam, I am happy to take a stab at this one. Does my proposed approach of upgrading the base Docker image seem plausible to you, or am I barking up the wrong tree?

**Comment by nvuillam** [comment]
@Kurt-von-Laven I agree that base docker image should be upgraded for a while now ;)

**Comment by Kurt-von-Laven** [comment]
Thank you! I will give this a shot. All of these Docker-related pain points are making me want to experiment with porting to asdf at some point, but that will be a much larger effort, and may have some drawbacks I haven't foreseen.

**Comment by Kurt-von-Laven** [comment]
Fixed in v6 by @nvuillam!
