### ISSUE TITLE
Provide a Version with debian base image

### ISSUE THREAD

**Issue by Bastlwastl42** [oxsecurity/megalinter#1447]
**Is your feature request related to a problem? Please describe.**
Using the current alpine based docker image for python project causes huge build times for medium size python projects. 

**Describe the solution you'd like**
I tried to include a private debian version in my work project, find the result on my dockerhub: https://hub.docker.com/r/bastlwastl/megalinter-debian
The image is working fine in our python project and build times for linting are much, much faster.

**Describe alternatives you've considered**
so far i tried for debians bullseye and bullseye-slim python containers as base images. The Dockerfile is rather rough and would require some polishing, especially since i removed some tricky parts with PHP8 for time reasons.

**Comment by nvuillam** [comment]
Alpine is the smallest linux base image possible... how could debian be faster to download?

**Comment by Bastlwastl42** [comment]
I'm basing my observation on e.g. [this article](https://pythonspeed.com/articles/alpine-docker-python). In our project, we build/run pip within the megalinter image in order for the many linter to check, if import statements are correct. Running pip within an alpine image (more specifically, the megalinter image) took us several hours for packages like spacy and scipy. The download time itself is fine, and agreed, the debian base image is larger (my repo tells me, the compressed final image size is somewhere between 2 and 3 gb). But i download once on the CI Server, but might build within the image several times.
Admittedly, i'm talking about edge cases:
- this only happens for distinct packages
- only when our CI decides to rebuild this step, which for a prototype phase, when requirements are fluctuating, quite often.

I started this issue because i didn't saw a discussion or hint, but i'm open to the fact, that we're using this wrong. 

In another note: I saw in the Dockerfile many supporting interpreters and compilers my project might not need. Like, there is PHP7 and 8 installed in the image, but i'm running a 'pure' python project. Maybe there is room for optimizing in that direction, e.g. slimming down for commonly used programming languages.

**Comment by nvuillam** [comment]
I'm not sure I understand... do you build MegaLinter ? Why don't you use MegaLinter docker images on docker hub ?

About the execution time, please can you share the results table so we can see which linter takes so many time ?

You can also use Flavors that contain less linters, maybe python one ? https://megalinter.github.io/latest/flavors/python/#readme

**Comment by Bastlwastl42** [comment]
Alright, let's have a look at how we use the megalinter on our CI. Here is the relevant part on the dockerfile, but reduced only slightly to be of general use/without project specifics:

`### LINTER IMAGE ###############################################################
FROM megalinter/megalinter:v5.6.0 as linter
# Install python requirements
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt 
`
The Jenkins CI then run the default /entrypoint.sh. The interesting project requirements are e.g. spacy and scipy. As far as i understand alpine, there is basically more stuff to be build compared to debian. You can try to run on a 'simple' build on the python images provided as alpine and debian. E.g.
`docker run --rm python:3-alpine sh -c 'pip install spacy scipy'`
vs 
`docker run --rm python:3-bullseye bash -c 'pip install spacy scipy'`
Despite the fact that my simple code not running very smoothly on the alpine example, the time difference in regards to the build is obvious. 

Thanks for pointing out the python flavors, i'll look into that (in regards to size limitations)

**Comment by nvuillam** [comment]
That's the first time I see MegaLinter being used as base image ^^
Why not separating Linting and the rest of your build process in different stages ?
You could have something like 

```groovy
stage('Parallel Stuff')
{
    parallel
    {
      // Lint with MegaLinter: https://megalinter.github.io/
      stage('MegaLinter') {
          agent {
              docker {
                  image 'megalinter/megalinter:v5'
                  args "-u root -e VALIDATE_ALL_CODEBASE=true -v ${WORKSPACE}:/tmp/lint --entrypoint=''"
                  reuseNode true
              }
          }
          steps {
              sh '/entrypoint.sh'
          }
          post {
              always {
                  archiveArtifacts allowEmptyArchive: true, artifacts: 'mega-linter.log,report/**/*', defaultExcludes: false, followSymlinks: false  
              }
          }
      }
      stage('Your build') { 
            agent { dockerfile { label 'docker'; filename 'Dockerfile'; } }
            steps { 
                 // whatever you need here with 
             } 
      }
    }
}
```

**Comment by Bastlwastl42** [comment]
True, however, we build within the image so pylint can check for the import statements to be correct. By just binding in the project code, i expect this to fail for any 3rd-party import?

I'll have a look if this would work for our project next monday. Thank you for your time and effort, really appreciated 😃

**Comment by Kurt-von-Laven** [comment]
Is there a reason I'm missing that you couldn't simply install all of your dependencies before running MegaLinter since you presumably have to install them at some point in your CI pipeline regardless? [Here](https://github.com/marketplace/actions/pre-commit-optimized-for-scribemd-pre-commit-hooks) is a very simple example of a GitHub action that runs MegaLinter as a pre-commit hook, but you could of course run MegaLinter directly (like the [MegaLinter GitHub action](https://github.com/marketplace/actions/megalinter) but for your CI platform). The most relevant portions are [installing Python dependencies from cache using Poetry](https://github.com/ScribeMD/pre-commit-action/blob/0961135554853a13d318896366288293ee24bfe8/action.yaml#L32-L39), [using Docker in rootless mode](https://github.com/ScribeMD/pre-commit-action/blob/0961135554853a13d318896366288293ee24bfe8/action.yaml#L56-L57) to avoid permission issues that I suspect are specific to GitHub Actions, and [caching all Docker images](https://github.com/ScribeMD/pre-commit-action/blob/0961135554853a13d318896366288293ee24bfe8/action.yaml#L58-L61) (such as the Python flavor of MegaLinter) if you find that speeds up your pipeline. In case you are concerned about missing out on some linters by using a flavor, I recommend setting `FAIL_IF_MISSING_LINTER_IN_FLAVOR: true` in your `.mega-linter.yaml`.

**Comment by nvuillam** [comment]
If you need to install additional dependencies within MegaLinter you can also do that using PRE_COMMANDS :)

https://megalinter.github.io/latest/configuration/#pre-commands

**Comment by Bastlwastl42** [comment]
@Kurt-von-Laven The issue is not with the runtime of the linters boundled within megalinter, the issue is with the alpine base image of megalinter, which performs (somewhat) poorly upon installing the required project dependencies, i.e. the ones used in my code in python. If this is not conducted, i expect some of the linters to fail because they are unable to check the import statements from 3rd parties because they are simply not installed. 
Also, i'm not sure how much your proposed solution depends on Github specifics, but we're using Jenkins as CI.

@nvuillam I'll have to check if this is something that helps, but i expect similar results in terms of runtime, because building the required packages in an alpine base image just takes that long. By including this, i probably make it worse because then i install the packages with every run. Now, there is the docker caching reducing unnecessary re-builds. As said above, if there are many chances in the project requirements, like during initial prototyping and placing around with dependencies, that's quite a bummer.

**Comment by nvuillam** [comment]
@Bastlwastl42 if you use PRE_COMMANDS, you will be able to use MegaLinter docker image without building it, and during each run you'll install just the few additional dependencies you need, so it should be way faster than when you build image :)

**Comment by Kurt-von-Laven** [comment]
Assuming Jenkins CI has some similar caching facility, it should be pretty similar conceptually if not syntactically. You can even cache the packages installed via PRE_COMMANDS.

**Comment by Bastlwastl42** [comment]
Unfortunately, i haven't found the time to prepare example and demo cases to progress this discussion. Not sure if i will within the time given. We are successfully using a version of the megalinter based on debian for our python project, links are found above. 
Thanks for the answers and comments.

**Comment by nvuillam** [comment]
I'm glad to know you succeeded to make your use case work :)

**Comment by eitsupi** [comment]
Simple question: isn't the MegaLinter image so large that the size difference between alpine and debian slim seems trivial?

**Comment by nvuillam** [comment]
Flavors are less large ^^
And it's not because we can do even larger than we should :)
