### ISSUE TITLE
Clear report directory before each run

### ISSUE THREAD

**Issue by dschveninger** [oxsecurity/megalinter#1502]
Is there anyway through configuration that you can have the report directory cleared before each run?

**Comment by Kurt-von-Laven** [comment]
Great question. Not presently, but happy to accept a pull request or else I will get to this eventually. In the meantime my team uses a Bash alias for this purpose.

**Comment by dschveninger** [comment]
We will review the code and submit a PR.

**Comment by Kurt-von-Laven** [comment]
Do you or @nvuillam know of a reason it would be desirable to leave the `report` directory from a previous run around (the present behavior)? I am tempted to say this change doesn't even need to be configurable.

**Comment by nvuillam** [comment]
I prefer to have a vonfig variable telling to clear report folder before running linters, because i know some use cases in v6 where sarif report file name is customized, so we have different darif report files in the same report folder :)

What about a CLEAR_REPORT_FOLDER config var ? :)
