### ISSUE TITLE
`FAIL_IF_UPDATED_SOURCES` False Positives On Unstaged Changes

### ISSUE THREAD

**Issue by Kurt-von-Laven** [oxsecurity/megalinter#1513]
**Describe the bug**
When there are unstaged changes, running MegaLinter with `FAIL_IF_UPDATED_SOURCES: true` always results in a failure.

**To Reproduce**

1. Set `FAIL_IF_UPDATED_SOURCES: true` in `.mega-linter.yaml`.
2. Make some change, and don't stage it.
3. Run MegaLinter (e.g., `npx mega-linter-runner`).
4. MegaLinter fails claiming that sources were modified.

**Expected behavior**
MegaLinter succeeds when sources were not modified.

**Additional context**
This predominantly affects those who are running MegaLinter locally, but don't use [pre-commit](https://pre-commit.com/) since one rarely has unstaged changes in CI. I suspect MegaLinter may be using `git diff` to detect whether any files were changed. One way that could be made more reliable is to stash unstaged changes first, but that introduces the possibility of a conflict between automatic fixes and popping the stash at the end. Pre-commit does exactly that, and rolls back automated fixes in the event of a conflict. Tools that automatically fix files probably tend to expose whether they changed anything (e.g., via their exit code), but looking at all of the exit codes seems like a tedious approach. Another approach might be to compute a checksum of the sources before and after running MegaLinter, but that sounds very slow. In the meantime, I suggest that those who desire `FAIL_IF_UPDATED_SOURCES: true` when running locally use [the pre-commit hook](https://megalinter.github.io/latest/mega-linter-runner/#pre-commit-hook) and not set `FAIL_IF_UPDATED_SOURCES: true`.

**Comment by nvuillam** [comment]
I don't see how we could detect updates without using git diff :/
Or maybe by starting with a git diff at the beginning, storing the files list, and ignore them ?
But if an initial updated file is later updated by megalinter, we wouldn't detect such updates :/

**Comment by Kurt-von-Laven** [comment]
Basically, we could improve our detection by stashing unstaged changes before we run since we rely on the assumption of an initially clean working tree and have the capacity to enforce it.

**Comment by nvuillam** [comment]
I don't think a linter, even MegaLinter, should perform git "update" operations (when applying fixes from github actions, it is another action that performs the new commit, not MegaLinter one)

But if you want to add some behaviour in mega-linter-runner, and only if there is some extra argument not active by default, I'm ok with it ^^

**Comment by Kurt-von-Laven** [comment]
The thinking is that we would pop the stash afterwards, returning the clone to its original state. It's not without complexity though since the user can kill the run or the automated fixes can conflict with popping the stash and need to be undone. It's definitely not a topic I feel strongly about. Users who want this behavior can simply use the pre-commit hook, so I am perfectly happy to leave it at that if nobody has a need for it in mega-linter-runner when run standalone.
