### ISSUE TITLE
Megalinter takes too long to process

### ISSUE THREAD

**Issue by milica-nikolic** [oxsecurity/megalinter#1526]
Hi there,

I have implemented megalinter in my project's pipeline but for some reason it take way to long (a hour long) and throws some weird error.

I am using megalinter/megalinter:v5 image in my job in pipeline.

Here is configuration file of megalinter:

```
# Configuration file for Mega-Linter
DISABLE:
  - SPELL
DISABLE_LINTERS:
  - DOCKERFILE_HADOLINT
  - YAML_V8R
  - YAML_YAMLLINT
IGNORE_GITIGNORED_FILES: true
PARALLEL: true
```

Here is output at the end of pipeline:

![megalinterError](https://user-images.githubusercontent.com/57385004/173539187-ce87666a-2ff3-4e55-b0c4-f5bdd1c63164.JPG)

Any kind of help would be appreciated.

**Comment by nvuillam** [comment]
The problem is that MegaLinter calls dotnet format file by file.
I'll check to call it with a list of files :)
Meanwhile, you can indeed disable it :/

**Comment by milica-nikolic** [comment]
Thanks @Kurt-von-Laven  and @nvuillam for your answers. At the end I took best of both and disabled dotnet-format while implementing CSharpier in my pipeline.

Looking forward for next version where dotnet-format will work properly. 😎

**Comment by Kurt-von-Laven** [comment]
That is helpful to know. I will also add that I personally have been much happier with CSharpier since it automatically fixes all issues it detects.
