### ISSUE TITLE
Implementation of Dockerfile Security with Megalinter

### ISSUE THREAD

**Issue by romelBen** [oxsecurity/megalinter#1529]
I have been enjoying using Megalinter in my projects for CI/CD pipelines and came across additional tools for Docker specifically that would be great for Megalinter.

I believe [trivy](https://github.com/aquasecurity/trivy),[Anchore](https://github.com/anchore/anchore-engine), [docker-bench-security](https://github.com/docker/docker-bench-security), and [Clair](https://github.com/quay/clair) to name a few that can help with security with Dockerfiles. Would like to know your ideas on this if this can be implemented.

Thanks!

**Comment by nvuillam** [comment]
@romelBen trivy is already integrated within v6, that will be released within the next weeks :)
There will also be lots of surprises about security :)

**Comment by Kurt-von-Laven** [comment]
Thanks to the hard work of @nvuillam and others, v6 was just released with trivy!
