### ISSUE TITLE
Linters with warnings only

### ISSUE THREAD

**Issue by dschveninger** [oxsecurity/megalinter#1541]
Some linters allow you to config some rules as warnings, golangci-lint is an example.  If the linters only has warnings and the process returns code is 0 the linter is marked success and the warning are lost in the linter logs. The only way to get the extra data is to place detailed report on which does for all linters and provides too much data.

I was thinking we could create a cli_lint_warning_count: regex_number and cli_lint_warnings_regex: "Total warnings found: ([0-9]+)" to the descriptor schema and linter that have warning can add those values and we can add a method to count warnings.  If warnings only exists we can provide the linter details.

If this sound like an idea you would like to consider we will do a more details response with the scope of changes.

**Comment by Kurt-von-Laven** [comment]
This sounds sensible to me. What do you think, @nvuillam?

**Comment by nvuillam** [comment]
Sounds nice :)
It would require an important evolution in architecture, but I think it's doable with V6 (soon) , as SARIF output allows warning.

**Comment by Kurt-von-Laven** [comment]
@dschveninger, as we are all in agreement, we would certainly welcome any more detailed proposal you find time to put together.
