### ISSUE TITLE
The lint modes must be documented

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#1544]
Otherwise, we waste a lot of time debugging filters for files, directories, etc... Without really understanding what is going on.

@nvuillam Exactly the same thing happened to me as this comment: https://github.com/megalinter/megalinter/issues/932#issuecomment-961905761

In other words, the difference in all these parameters is not at all clear. Clearly the correct use of these parameters depends on the lint modes.

I think that it is necessary to explain very well what is project mode, file mode, etc... In this comment I have been able to find something: https://github.com/megalinter/megalinter/issues/932#issuecomment-961885010

As suggested by @beatcracker the correct place to explain all this or at least part of it, would be: https://megalinter.github.io/supported-linters/

**Comment by nvuillam** [comment]
@bdovaz  Finally done :)

https://oxsecurity.github.io/megalinter/beta/configuration/#cli-lint-mode
