### ISSUE TITLE
V6 release is today !

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#1568]
In order to prepare the near future release of MegaLinter V6, no Pull Request will be merged until then (with automatically generated code and doc, managing the conflicts between main and v6_dev is too time consuming)

But that does not mean that you can't submit new ones ... they'll just be validated and merged later :)

Best regards

Nicolas

**Comment by Kurt-von-Laven** [comment]
Good call!

**Comment by echoix** [comment]
Feature freeze, code freeze, merge windows, etc. are all common in some projects, so there's nothing wrong of not keeping up!

Hope to see v6 some day!

**Comment by nvuillam** [comment]
Thanks for your understanding :)
v6 in planned in 2 weeks :)

**Comment by nvuillam** [comment]
v6 will be released today :)

I'll post here when completed :)

**Comment by nvuillam** [comment]
Release (almost) complete
There are a few bugs in internal CI but they shoud not prevent to use ML v6 :)
