### ISSUE TITLE
Full support for checkov

### ISSUE THREAD

**Issue by dschveninger** [oxsecurity/megalinter#1569]
The Terraform descriptor uses the checkov policy checker but just for *.tf files. https://github.com/megalinter/megalinter/blob/main/megalinter/descriptors/terraform.megalinter-descriptor.yml#L116.

I was wondering since checkov is already installed if we could use the policy checker (linter) directly by added an other descriptor like copyandpaste?  If not we can just do a plugin I thought I would ask since the program is already installed.

Checkov https://github.com/bridgecrewio/checkov as policies for 
[Terraform](https://terraform.io/), 
[Terraform plan](https://github.com/bridgecrewio/checkov/blob/master/docs/7.Scan%20Examples/Terraform%20Plan%20Scanning.md), [Cloudformation](https://github.com/bridgecrewio/checkov/blob/master/docs/7.Scan%20Examples/Cloudformation.md), 
[AWS SAM](https://github.com/bridgecrewio/checkov/blob/master/docs/7.Scan%20Examples/AWS%20SAM.md), 
[Kubernetes](https://github.com/bridgecrewio/checkov/blob/master/docs/7.Scan%20Examples/Kubernetes.md), 
[Helm charts](https://github.com/bridgecrewio/checkov/blob/master/docs/7.Scan%20Examples/Helm.md), 
[Kustomize](https://github.com/bridgecrewio/checkov/blob/master/docs/7.Scan%20Examples/Kustomize.md), 
[Dockerfile](https://github.com/bridgecrewio/checkov/blob/master/docs/7.Scan%20Examples/Dockerfile.md), 
[Serverless](https://github.com/bridgecrewio/checkov/blob/master/docs/7.Scan%20Examples/Serverless%20Framework.md), 
[Bicep](https://github.com/bridgecrewio/checkov/blob/master/docs/7.Scan%20Examples/Bicep.md), 
[OpenAPI](https://github.com/bridgecrewio/checkov/blob/master/docs/7.Scan%20Examples/OpenAPI.md) or 
[ARM Templates](https://github.com/bridgecrewio/checkov/blob/master/docs/7.Scan%20Examples/Azure%20ARM%20templates.md) 
and detects security and compliance misconfigurations using graph-based scanning.

**Comment by Kurt-von-Laven** [comment]
You can configure MegaLinter to run any linter on any set of file extensions. No plugin needed. See #782 for a similar example.

**Comment by dschveninger** [comment]
thank you

**Comment by nvuillam** [comment]
@dschveninger it's on its way :)
