### ISSUE TITLE
Update Secret Lint 

### ISSUE THREAD

**Issue by maxthetechie** [oxsecurity/megalinter#1577]
Hi, 

I have noticed, that the megalinter is using Secret Lint version 4.1.0. 
Currently Secret Lint is available in version 5.2.3

Can you please update or is there anything, that causes problems with newer versions?

Cheers

**Comment by nvuillam** [comment]
it will be done in V6 that will be released soon :)

**Comment by nvuillam** [comment]
@maxthetechie secretlint is now with 5.2.3 in MegaLinter v6 :)
