### ISSUE TITLE
Add proselint as a supported checker

### ISSUE THREAD

**Issue by harleypig** [oxsecurity/megalinter#1578]
[proselint](http://proselint.com) is a linter for textfiles (can be used with markdown files as well).

proselint is *not* a grammar checker. It looks for "usage: redundancy, jargon, illogic, clichés, sexism, misspelling, inconsistency, misuse of symbols, malapropisms, oxymorons, security gaffes, hedging, apologizing, pretension ..."

**Comment by nvuillam** [comment]
That seems to be a good idea :)
What files should we run on ?
.md + .txt ?

**Comment by harleypig** [comment]
That's what I usually use it on.

**Comment by nvuillam** [comment]
@harleypig it is not available in oxsecurity/megalinter:beta version :)
https://oxsecurity.github.io/megalinter/beta/descriptors/spell_proselint/

**Comment by nvuillam** [comment]
You're welcome :)
It has awful performances... i may disable it by default someday, or put it only in doc flavor , because on MegaLinter repo it took 500 seconds with all the MD files in the documentation ^^

**Comment by harleypig** [comment]
Hmmm ... I use it with vim/syntastic and it's fairly quick on a per-file basis and the ci tests take a long time to run anyway, so I never noticed. I'd be curious to see how fast it was after the megalinter corpus has been linted (and some checks ignored).

I don't see an issue with it being disabled by default ... that length of tiem would be offputting for new users. :/
