### ISSUE TITLE
v8r failing as using dynamic URL for schema

### ISSUE THREAD

**Issue by schorlton** [oxsecurity/megalinter#1591]
Running `v5.17.0` in docker.

```bash
[v8r] .mega-linter.yml - ERROR - 1 error(s)
--Error detail:
ℹ️ Found schema in https://www.schemastore.org/api/json/catalog.json ...
Validating /builds/test/.mega-linter.yml against schema from https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json ...
Errors:
[
  {
    keyword: 'enum',
    dataPath: '.DISABLE_LINTERS[0]',
    schemaPath: '#/definitions/enum_linter_keys/enum',
    params: { allowedValues: [Array] },
    message: 'should be equal to one of the allowed values'
  }
]
❌ /builds/test/.mega-linter.yml is invalid
```

I assume because the schema was updated for v6, and the URL is not pinned to a version, it now broke schema validation. Thanks again!!!

**Comment by nvuillam** [comment]
I spent from 9:00 AM to 00:AM doing the migration... some little bugs may be remaining, I apologize ^^
Please can you upgrade to v6 using `npx mega-linter-runner --upgrade` and provide feedback ?

**Comment by echoix** [comment]
At least it is possible to add multiple versions to the json schema store, like 

https://github.com/SchemaStore/schemastore/blob/d1c8216bffc976a4a12df72ad54c7c9a251cd22c/src/api/json/catalog.json#L25-L35
```json
    {
      "name": ".agripparc.json",
      "description": "JSON schema for the Agrippa config file",
      "fileMatch": [".agripparc.json", "agripparc.json"],
      "url": "https://json.schemastore.org/agripparc-1.4.json",
      "versions": {
        "1.2": "https://json.schemastore.org/agripparc-1.2.json",
        "1.3": "https://json.schemastore.org/agripparc-1.3.json",
        "1.4": "https://json.schemastore.org/agripparc-1.4.json"
      }
    },
```
Or this: https://github.com/SchemaStore/schemastore/blob/d1c8216bffc976a4a12df72ad54c7c9a251cd22c/src/api/json/catalog.json#L2682-L2691
```json
    {
      "name": "theme.json",
      "description": "WordPress block theme global settings and styles configuration file",
      "fileMatch": ["theme.json"],
      "url": "https://schemas.wp.org/trunk/theme.json",
      "versions": {
        "v1": "https://raw.githubusercontent.com/WordPress/gutenberg/b40b61fabf13a6229c616527689d9a7024f81535/schemas/json/theme.json",
        "trunk": "https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/theme.json"
      }
    },
```
or even this: https://github.com/SchemaStore/schemastore/blob/d1c8216bffc976a4a12df72ad54c7c9a251cd22c/src/api/json/catalog.json#L2076-L2085
```json
    {
      "name": "package.manifest",
      "description": "Umbraco package configuration file",
      "fileMatch": ["package.manifest"],
      "url": "https://json.schemastore.org/package.manifest.json",
      "versions": {
        "8.0.0": "https://json.schemastore.org/package.manifest-8.0.0.json",
        "7.0.0": "https://json.schemastore.org/package.manifest-7.0.0.json"
      }
    },
```

**Comment by echoix** [comment]
An easy fix for tonight might be to just commit in main the old schema, and have the v6 breaking instead of the whole v5 userbase, but it's not a real solution is these users want to try v6.

**Comment by nvuillam** [comment]
Yes but how does the IDE know which version to use ? :/

The delta is really not big... except for DOCKERFILE_DOCKERFILELINT and RST_RSTFMT , the content is the same ^^
I don't plan to maintain v5... so if people want to keep using it, the solution is simple:
```yaml
DISABLE_LINTERS:
- JSON_V8R
- YAML_V8R
```

But if i'm provided the missing values, I can also add them back in latest JSON schema to avoid blocking issues ^^

**Comment by echoix** [comment]
Since it's only a schema to help edit, and it was available for last version, isn't there no reason to remove these lines? 

The config schema could then be the sum of all v6 configs, and the remaining of v5, so none is missing. 

For the IDE choosing versions, for the YAML to be enforced/checked with vscode for example, the YAML extension (Red Hat), when clicking in the bottom bar on megalinter configuration (the schema type), you have an option to select another version, or any schema in fact. 

For json files it might be possible to include it in the file itself, but I'm not sure.

**Comment by nvuillam** [comment]
Not sure v8r (JSON/YAML schema analyzer in MegaLinter) cares about version :/

A big part of the schema is automatically generated during build, so it's not as easy to bring back all v5 properties :/ 
I never thought that people used DOCKERFILELINT or RSTFMT, but maybe there are other cases, let's wait for @schorlton 's reply and the solution shoud be quick (no need to make a release, with schemastore.com just a new commit will be enough)

**Comment by nvuillam** [comment]
Just brought back the keys for removed / renamed descriptors and linters
If they were used just to be disabled, it should do the job !

https://github.com/oxsecurity/megalinter/commit/1b15cdc096a2672c254135b8b15912165118086c

**Comment by schorlton** [comment]
Thanks for such a quick fix! Yes I had disabled `DOCKERFILE_DOCKERFILELINT` as I knew it would be deprecated for v6. Your fix seems to have restored v5 functionality.
