### ISSUE TITLE
MegaLinter v6 has been released !

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#1592]
After being promised for months now, **MegaLinter v6 has finally been released** :)

You can see all the updates in the release notes -> https://github.com/oxsecurity/megalinter/releases/tag/v6.0.0

Just run `npx mega-linter-runner@latest --upgrade` to use it :) ([troubleshooting](https://github.com/oxsecurity/megalinter/issues/1592#issuecomment-1183792890))

Some linters has been removed, so if you referred to them in your configuration, you'll have to remove them
- `DOCKERFILE_DOCKERFILELINT` : It was not maintained anymore and hadolint much more efficient
- `RST_RSTFMT` : It was highly experimental and not maintained anymore

On some big repos, some of the new linters can be slow (like REPOSITORY_GITLEAKS) or too noisy ( like REPOSITORY_SEMGREP), don't hesitate to disable them using `DISABLE_LINTERS` property in `.mega-linter.yml`: You only can decide the linters you need !

If you see any bug/issue, please let us know !

Best regards

MegaLinter maintainers & [OX Security](https://www.ox.security/?ref=megalinter) team

**Wanna know why MegaLinter has joined OX Security ? Please read the following article :)** 

**https://nicolas.vuillamy.fr/megalinter-sells-his-soul-and-joins-ox-security-2a91a0027628**

Edit: **Known issues**:

- Redirection of github action megalinter/megalinter to oxsecurity/megalinter
  - GitHub deprecated automated redirections for GitHub Actions, so you need to replace `megalinter/megalinter` by ` oxsecurity/megalinter`, even if you don't want to migrate to v6 yet

- PRE_COMMANDS using `npm install`. **Fixed in v6.0.4**
  - temp fix by adding `cd /node-deps && npm install xxx ...`. This will be automatically added soon  (#1258)

- mega-linter-runner does not upgrade report folder for uploading artifacts (#1609) **Fixed in v6.0.5**
  - workaround: replace manually report by megalinter-reports

**Comment by lolrenx** [comment]
Félicitations! Et merci de perpétuer l'esprit OSS malgré le changement de giron de Megalinter 👍

**Comment by nvuillam** [comment]
> The repo path change broke all my github actions...
> 
> Congrats on V6 and the new managers!

What did break exactly ?
There is an automatic redirection between old repo and new repo :/
If you give more details we may find a solution ^^

**Comment by syncdk** [comment]
Yeah it broke for us also:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1489861/178374509-2ed9e528-2518-4125-8762-1dcf7690fd32.png">

Perhaps redirection doesn't work when using workflows that are centralized, e.g. we have our workflow that uses megalinter in a "workflows" repo that is then used by our other repos.

**Comment by syncdk** [comment]
Seems as redirects don't work for actions at all, by design: 

https://github.com/actions/runner/issues/1695

**Comment by nvuillam** [comment]
@syncdk when I migrated from nvuillam to megalinter it worked like a charm, I did not expect this one, sorry 😭

**Comment by Kurt-von-Laven** [comment]
Yeah, it appears that GitHub changed this behavior between the time of the two migrations. I didn't notice since we use the [pre-commit hook](https://oxsecurity.github.io/megalinter/latest/mega-linter-runner/#pre-commit-hook).

**Comment by andrewvaughan** [comment]
Running `npx mega-linter-runner` still pulls the container:

```
Pulling docker image megalinter/megalinter:v5 ... 
```

Doing `npx mega-linter-runner --upgrade` and running again doesn't seem to do anything. Is this user error or is something up?

**Comment by nvuillam** [comment]
@andrewvaughan I think you have a previous version in cache.

Please can you try `npm uninstall mega-linter-runner`, then `npm mega-linter-runner --upgrade` again ?

And if it still does not work, you can try npm `i mega-linter-runner -g` then m`ega-linter-runner --upgrade`

**Comment by andrewvaughan** [comment]
That worked, thanks!

**Comment by mohsin996** [comment]
The repo path changes broke our GitHub actions as well, but we made changes here in the workflow.
From 
` uses: megalinter/megalinter@v5`
To
`uses: oxsecurity/megalinter@v6`

Followed this [doc](https://raw.githubusercontent.com/oxsecurity/megalinter/main/TEMPLATES/mega-linter.yml)

**Comment by nvuillam** [comment]
@mohsin996 that's what `mega-linter-runner --upgrade` does for you :)

It also adds `megalinter-reports` in `.gitignore` file , as the report folder has changed in v6 :)

**Comment by llaville** [comment]
@nvuillam Is there any reason why `MARKDOWN_REMARK_LINT` was disabled in v6 (see https://oxsecurity.github.io/megalinter/latest/descriptors/markdown_remark_lint/)

Using locally to test my migration from v5 to v6

```
----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2022-10-23T22:50:51Z
 - Image Revision: f58627d
 - Image Version: v6
----------------------------------------------------------------------------------------------------
The MegaLinter documentation can be found at:
 - https://oxsecurity.github.io/megalinter/latest
----------------------------------------------------------------------------------------------------
MegaLinter initialization

MARKDOWN_REMARK_LINT has been temporary disabled in MegaLinter, please use a previous MegaLinter version or wait for the next one !
```

**Comment by nvuillam** [comment]
@onemec now that python packages are installed in virtualenvs, it may be possible :)

Let's see what CI job says in the pull request :) https://github.com/oxsecurity/megalinter/pull/2035

**Comment by nvuillam** [comment]
@onemec rstfmt is back in beta version, and soon in next release :)
