### ISSUE TITLE
Request new MegaLinter flavor : Flutter

### ISSUE THREAD

**Issue by Shi-Raida** [oxsecurity/megalinter#1595]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

C_CPPLINT, COPYPASTE_JSCPD, CPP_CPPLINT, CREDENTIALS_SECRETLINT, DART_DARTANALYZER, GIT_GIT_DIFF, GROOVY_NPM_GROOVY_LINT, HTML_HTMLHINT, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, KOTLIN_KTLINT, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, SPELL_MISSPELL, SPELL_CSPELL, XML_XMLLINT, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by Kurt-von-Laven** [comment]
Do you have a proposed name for the flavor?

**Comment by nvuillam** [comment]
I removed DART flavor in V6 because no one was using it ^^
Are there lots of projects using C++ and dart/flutter ?
