### ISSUE TITLE
PRE_COMMANDS environment variable syntax

### ISSUE THREAD

**Issue by timothysparg** [oxsecurity/megalinter#1605]
It appears that you should be able to set [PRE_COMMANDS as an environment variable](https://oxsecurity.github.io/megalinter/beta/configuration/), but I can't seem to get the syntax worked out, could somebody enlighten me as to how it should look?

It would appear that you need to pass it in as some kind of structured format, as I get the following stacktrace when I try use a normal string:
```
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/run.py", line 9, in <module>
    linter = megalinter.Megalinter({"cli": True})
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/MegaLinter.py", line 114, in __init__
    self.pre_commands_results = pre_post_factory.run_pre_commands(self)
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/pre_post_factory.py", line 13, in run_pre_commands
    return run_pre_post_commands("PRE_COMMANDS", "[Pre]", mega_linter)
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/pre_post_factory.py", line 42, in run_pre_post_commands
    return run_commands(pre_or_post_commands, log_key, mega_linter)
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/pre_post_factory.py", line 52, in run_commands
    pre_command_result = run_command(command_info, log_key, mega_linter)
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/pre_post_factory.py", line 60, in run_command
    if command_info.get("cwd", "root") == "workspace":
AttributeError: 'str' object has no attribute 'get'
```

My latest attempts where to try and use a JSON syntax, but this doesn't seem to be the correct approach either

`[{"cwd": "workspace", "command:": "echo \"hello world\""}] `

**Comment by Kurt-von-Laven** [comment]
I also struggled with this, and we would gladly accept a pull request to improve the pertinent documentation. This is the syntax we have been using in our MegaLinter config files:

```yaml
*_PRE_COMMANDS:
  - command: echo hello world
```

**Comment by nvuillam** [comment]
We use [get_list method](https://github.com/oxsecurity/megalinter/blob/93707a051084b64bedeb011ea94d8d71998338bf/megalinter/config.py#L121) to get PRE_COMMANDS value
When it is defined as ENV var, it's just a split on `,`, so it works with list of strings, but it can not work with list of objects (like PRE_COMMANDS)

I'll try to check if I can have a different behaviour if the string starts with [

**Comment by timothysparg** [comment]
> I also struggled with this, and we would gladly accept a pull request to improve the pertinent documentation. This is the syntax we have been using in our MegaLinter config files:
> 
> ```yaml
> *_PRE_COMMANDS:
>   - command: echo hello world
> ```
> 
> I have never even tried setting this via an environment variable, but if someone gets that working, I would be curious to learn how they did it.

This is what I do as well but because I'm trying to workaround some git shenanigans in a repository, I also have to inject an environment variable. 
I would prefer that this workaround only exists for our CI, as this means that we can't run locally without editing the config file.

```yaml
PRE_COMMANDS: #$REPO_TOKEN is injected in the megaLinter workflow
  - command: git config --global url."https://oauth2:$REPO_TOKEN@github.com".insteadOf ssh://git@github.com
 ```

**Comment by timothysparg** [comment]
@nvuillam oh wow, super fast turn around, just tried this with 6.0.4, and it works great!

my syntax (for Github Actions) was as follows
```yaml
        env:
          PRE_COMMANDS: >-
            [{"cwd": "workspace", "command": "git config --global url.\"https://oauth2:${{ secrets. REPO_TOKEN }}@github.com\".insteadOf ssh://git@github.com"}]
```

**Comment by nvuillam** [comment]
@timothysparg > I'm glad it works :) You can star the repo if you like 😇

**Comment by nvuillam** [comment]
@johnkk84 I don't know this syntax, but you can define multiple commands in your .mega-linter.yml file :)

Examples on https://megalinter.io/latest/config-precommands/#pre-commands

**Comment by nvuillam** [comment]
@johnkk84 thanks for the precision :)
