### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by ProfXponent** [oxsecurity/megalinter#1616]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

ACTION_ACTIONLINT, HTML_HTMLHINT, JAVASCRIPT_ES, JAVASCRIPT_STANDARD, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, OPENAPI_SPECTRAL, REPOSITORY_DEVSKIM, REPOSITORY_DUSTILOCK, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_SECRETLINT, REPOSITORY_SEMGREP, REPOSITORY_SYFT, REPOSITORY_TRIVY, TYPESCRIPT_ES, TYPESCRIPT_STANDARD, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by Kurt-von-Laven** [comment]
Would you like to propose a name for the flavor?

**Comment by nvuillam** [comment]
Aren't all these linters in JavaScript flavor ? ^^

**Comment by ProfXponent** [comment]
Yeah I just found it, you can close this
