### ISSUE TITLE
feature request: add Makefile linter

### ISSUE THREAD

**Issue by wesley-dean** [oxsecurity/megalinter#1627]
**Is your feature request related to a problem? Please describe.**

As a developer who uses Makefiles to coordinate building, testing, packaging, and deploying (distributing) source code, so that I may adhere to testable best-practices regarding Makefiles, I would like to add support for a Makefile linter to Megalinter.

**Describe the solution you'd like**

There currently exists tools that perform linting on Makefiles such as `checkmake` by Daniel Schauenberg (@mrtazz) that's written in Go.  There are also packages available on [packagecloud](https://packagecloud.io/mrtazz/checkmake) not to mention @cytopia 's [repo](https://github.com/cytopia/docker-checkmake) and corresponding [image on Dockerhub](https://hub.docker.com/r/cytopia/checkmake).

Not being deeply knowledgeable about how to add this functionality to Megalinter myself (you may recall how it went the last time I tried to contribute something), I'm afraid that it's improbable that I'll be able to meaningfully help in the of this beyond doing some research, digging up links, etc..

**Describe alternatives you've considered**

Currently, I run Checkmake directly on my system when I see that a developer has updated a Makefile and I copypasta the results as a comment on their Pull Requests.  One could (but I haven't) setup a separate GitHub action to do the linting and post the results.

**Additional context**

This is not a priority request and I certainly do not wish to detract from the amazing work being done on v6.

**Comment by nvuillam** [comment]
Are you talking about this one ? https://github.com/mrtazz/checkmake

That could be doable :)

**Comment by nvuillam** [comment]
The doc is not really clear about how to install via commande line on alpine

Once they reply it should be quite easy :)

https://github.com/mrtazz/checkmake/issues/71

**Comment by nvuillam** [comment]
@wesley-dean it's done :)

https://oxsecurity.github.io/megalinter/beta/descriptors/makefile_checkmake/

Please can you check with oxsecurity/megalinter@beta ? :)

**Comment by wesley-dean-flexion** [comment]
@nvuillam I was able to bump to `@beta` and it worked perfectly!

https://github.com/IMLS/estimating-wifi/runs/7583627032?check_suite_focus=true

**Comment by nvuillam** [comment]
Great, thanks for the feedback :)
It will be delivered in MegaLinter v6.2.0 :) (today or tomorrow)
