### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by cjbarth** [oxsecurity/megalinter#1632]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_PYLINT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_BANDIT, PYTHON_MYPY, ACTION_ACTIONLINT, COPYPASTE_JSCPD, CSHARP_DOTNET_FORMAT, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, REPOSITORY_DEVSKIM, REPOSITORY_DUSTILOCK, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_SECRETLINT, REPOSITORY_SEMGREP, REPOSITORY_SYFT, REPOSITORY_TRIVY, SPELL_MISSPELL, SPELL_CSPELL, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
So you mean a flavor python + C-like languages ? :)

**Comment by cjbarth** [comment]
I'm not exactly sure what I mean. I saw that message, like things to be faster, and so followed the instructions (clicked the link). I do have some JS/TS, some Python, and some C# in a certain code-base.
