### ISSUE TITLE
devskim not ignoreing node_modules

### ISSUE THREAD

**Issue by cjbarth** [oxsecurity/megalinter#1634]
**Describe the bug**
All linters appear to ignore files and folders listed in .gitignore, except for devskim

**To Reproduce**

1. Make sure that there is something in node_modules/
2. Make sure that .gitignore includes node_modules/
3. Run all linters
4. Note that only devskim finds errors in node_modules

**Expected behavior**
Errors in node_modules shouldn't be reported on, or ideally, shouldn't be scanned.

**Screenshots**
This goes on for 100s of lines:

```console
❌ Linted [REPOSITORY] files with [devskim]: Found 752 error(s) - (72.6s)
- Using [devskim v0.6.9] https://oxsecurity.github.io/megalinter/latest/v6/descriptors/repository_devskim
- MegaLinter key: [REPOSITORY_DEVSKIM]
- Rules config: identified by [devskim]
--Error detail:
/tmp/lint/node_modules/agent-base/package.json:32:13:32:20 [Moderate] DS137138 Insecure URL
/tmp/lint/node_modules/abbrev/package.json:22:14:22:56 [Important] DS173237 Do not store tokens or keys in source code.
/tmp/lint/node_modules/agent-base/package.json:26:14:26:56 [Important] DS173237 Do not store tokens or keys in source code.
/tmp/lint/node_modules/agentkeepalive/package.json:23:14:23:56 [Important] DS173237 Do not store tokens or keys in source code.
/tmp/lint/node_modules/aggregate-error/package.json:22:14:22:56 [Important] DS173237 Do not store tokens or keys in source code.
```

Here is my .gitignore:

```console
.vscode/
.idea/
node_modules/
tmp/
megalinter-reports/
```

**Additional context**
It appears that this should already work correctly based on https://github.com/microsoft/DevSkim/pull/170. Also, it seems a related problem has appeared before: https://github.com/oxsecurity/megalinter/issues/1603.

**Comment by nvuillam** [comment]
It seems to be a DevSkim issue, not a MegaLinter one as we include latest version of DevSkim :/
