### ISSUE TITLE
semgrep vs gitleaks

### ISSUE THREAD

**Issue by cjbarth** [oxsecurity/megalinter#1635]
**Describe the bug**
With a default config, semgrep detects the .gitleaks.toml file as a problem.

**To Reproduce**

1. Default install
2. Copy configs to root of project folder, which includes `.gitleaks.toml`
3. Run

**Expected behavior**
A default config shouldn't have one linter flagging the config of another linter.

**Screenshots**
```console
❌ Linted [REPOSITORY] files with [semgrep]: Found 2 error(s) - (44.07s)
- Using [semgrep v0.103.0] https://oxsecurity.github.io/megalinter/latest/v6/descriptors/repository_semgrep
- MegaLinter key: [REPOSITORY_SEMGREP]
- Rules config: identified by [semgrep]
--Error detail:
METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

Fetching rules from https://semgrep.dev/registry.

Scanning across multiple languages:
    <multilang> |  54 rules × 284 files
           json |   4 rules ×  10 files
         csharp |  40 rules ×   6 files
           yaml |  23 rules ×   5 files
         python | 282 rules ×   2 files


Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Scan skipped: 1 files larger than 1.0 MB
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1204 rules on 142 files: 2 findings.

Findings:

  /tmp/lint/.gitleaks.toml
     generic.secrets.security.detected-google-gcm-service-account.detected-google-gcm-service-account
        Google (GCM) Service account detected
        Details: https://sg.run/6nXj

         78┆ regex = '''"type": "service_account"'''
```

**Comment by nvuillam** [comment]
I think SEMGREP rule way too many rules by default, in a next minor version we should probably disable it by default if there are no semgrep rulesets defined locally in the repo
Meanwhile, you can either:
- define semgrep rulesets locally
- disable semgrep by adding in your .mega-linter.yml file:

```yaml
DISABLE_LINTERS:
- REPOSITORY_SEMGREP
```

You can also make it non blocking using:

```yaml
DISABLE_ERRORS_LINTERS:
- REPOSITORY_SEMGREP
```

**Comment by iggy** [comment]
Since we're talking about semgrep checking files it probably shouldn't be by default... It should probably ignore `/github/workspace/github/workspace/megalinter-reports` by default

**Comment by ivanbaldo** [comment]
I did enable it adding this to my .gitlab-ci.yml file:
`REPOSITORY_SEMGREP_RULESETS: "auto"`

In a small repo it didn't find any false positives.
