### ISSUE TITLE
Have a consistent way to disable writing down reports to the report output folder

### ISSUE THREAD

**Issue by kfot** [oxsecurity/megalinter#1638]
**Is your feature request related to a problem? Please describe.**
I would like to have the option to disable local reporters writing to the mounted directory `REPORT_OUTPUT_FOLDER`. 
This step is caused by the access permission issues caused by docker writing to the mounted directory as `nobody:nogroup` which enforces some extra setup & cleanup steps (directory must exists and be writable by everyone). I use megalinter and megalinter-runner dozens times a day but I do not make any use of the locally written reports and I do not need them, this step is redundant in my workflow.

**Describe the solution you'd like**
It would be nice to officially extend the behavior of `REPORT_OUTPUT_FOLDER` by having it accept a value like `false`.
Right now (as for v6.1.0) passing `false` is an undocumented feature which partially works - it does not break the execution by insufficient access to the `REPORT_OUTPUT_FOLDER`, does not create any new files, however the console log displays things like:
```
::set-output name=has_updated_sources::0
[Updated Sources Reporter] copied 1 fixed source files in folder false/updated_sources.
Download it from artifacts then copy-paste it in your local repo to apply linters updates
```

**Describe alternatives you've considered**
Manually disabling local reporters that are enabled by default (text, IDE, sources). it works fine but the configuration is not consistent with `DISABLE_LINTERS` mapping, where I can simply list the names of the linters I want to disable.

**Additional context**
My `.mega-linter.yml` file https://pastebin.com/FEZZ8LHS

**Comment by nvuillam** [comment]
Please can you try with the following config variables ?

```yaml
LOG_FILE: none
TEXT_REPORTER: false
UPDATED_SOURCES_REPORTER: false
CONFIG_REPORTER: fase
```

**Comment by kfot** [comment]
@nvuillam ML with your config will still require writable access to the `megalinter-reports` directory. 
```
Setting git safe.directory default: /github/workspace ...
Setting git safe.directory to /tmp/lint ...
[MegaLinter init] ONE-SHOT RUN
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/megalinter/run.py", line 9, in <module>
    linter = megalinter.Megalinter({"cli": True})
  File "/megalinter/MegaLinter.py", line 60, in __init__
    self.initialize_output()
  File "/megalinter/MegaLinter.py", line 688, in initialize_output
    os.makedirs(self.report_folder, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/lint/megalinter-reports'
```

The only way so far to that I am aware of to skip that requirement is to have the setting mentioned in the original post
```
REPORT_OUTPUT_FOLDER: false
```
The two missing pieces are:
1. **The setting's behavior is not documented**
2. It does not disable the local reporters. Without `false`-ing them explicitly, I'm getting log entries like below even though that they do not create any new reports and the reporters might not have access to the `megalinter-reports` directory at all (I have also verified that). To get rid of these logs I need to disable the local reporters explicitly and that seems redundant.
```
::set-output name=has_updated_sources::0
[Updated Sources Reporter] copied 1 fixed source files in folder false/updated_sources.
Download it from artifacts then copy-paste it in your local repo to apply linters updates
```

I would like to ask to document the current behavior of `REPORT_OUTPUT_FOLDER: false` if that's expected and eventually extend it with disabling the local reporters.

**Comment by nvuillam** [comment]
I tried something with https://github.com/oxsecurity/megalinter/pull/1676 (work with REPORT_OUTPUT_FOLDER = false or none

Please can you try with oxsecurity:megalinter:beta ?

**Comment by kfot** [comment]
@nvuillam I verified with v6.2.0, unfortunately Updated Sources logs mentioned in my previous [post](https://github.com/oxsecurity/megalinter/issues/1638#issuecomment-1199201191) are still present.

**Comment by kfot** [comment]
I do not have `UPDATED_SOURCES_REPORTER` key at all, I hoped to have it disabled simply by having `REPORT_OUTPUT_FOLDER: false` or `none` . I tested it with mega-linter-runner. The reports are not generated, nor the path is (shouldn't and exception be raised at this moment?), it's all about these logs that are misleading...

> It would be interesting to know what is the updated file, because if you have APPLY_FIXES: none, no linter is supposed to update anything

So, the answer is: only one file was generated by Update Sources reporter, `megalinter-reports/updated_sources/.mega-linter.yml`, and its content is identical with the original `.mega-linter.yml`

**Comment by nvuillam** [comment]
Thanks for the feedback:)
I'll manage to test REPORT_OUTPUT_FOLDER 
everywhere we write a file :)
