### ISSUE TITLE
Missing summary table in Github pull request comment

### ISSUE THREAD

**Issue by hmG3** [oxsecurity/megalinter#1640]
**Describe the bug**
Github Comment Reporter doesn't render a summary markdown table as a PR comment if only one linter is enabled.

**To Reproduce**

1. Enable only one linter in the config file (for me it was RUBY_RUBOCOP but the actual linter doesn't matter)
2. Perform Megalinter run in Github Actions (flavor image doesn't matter) for a PR, so it finishes and prints the summary table in the console via Console Reporter. Notice the comment: `[GitHub Comment Reporter] Posted summary as a comment on company/project #PR1`
4. Navigate to the PR and see missing table in PR comment, despite the table exists in the console

**Expected behavior**
Github Comment Reporter should render the summary table for any number of enabled linters and any execution status.

**Screenshots**
![chrome_5QkChXNAH1](https://user-images.githubusercontent.com/3061260/180612546-04a4467d-cc38-4a53-b1da-327e71baa90b.png)
![chrome_fixNJ1MEwP](https://user-images.githubusercontent.com/3061260/180612590-57ad36b4-a93c-490c-b397-874586965ec6.png)

**Additional context**
After investigating and debugging the current `main` branch, I found how the table should be generated. However the next line https://github.com/oxsecurity/megalinter/blob/21e87f70dc5a5e8a600a5672a92b9a69ea800ddd/megalinter/utils_reporter.py#L71 apparently has unexpected behavior in `else` case. If one linter is enabled, it overwrites the whole table content with empty string and thus we have the missing table. I tried to wrap `os.linesep + if-else` block in parentheses or even remove it - in both cases, it began to work as expected.

**Comment by Kurt-von-Laven** [comment]
Sounds like you already got it working, so if you are willing to open a pull request with your changes, that would be greatly appreciated!
