### ISSUE TITLE
why megalinter scans all files in my Azure repo instead of modified or added files?

### ISSUE THREAD

**Issue by PardisTV** [oxsecurity/megalinter#1647]
i am trying to use mega linter in our Azure git repo and I want it to just scan the modified and added files but for some reason it scans the whole repo. am I doing something wrong? i used the below configurations:
for _.mega-linter.yaml_ :

````
SHOW_ELAPSED_TIME: true
APPLY_FIXES: all
DISABLE_LINTERS:
  - TERRAFORM_TERRASCAN
  - SPELL_CSPELL
  - ENV_DOTENV_LINTER
  - PYTHON_BLACK
  - BASH_EXEC
  - SQL_SQLFLUFF
  - DOCKERFILE_HADOLINT
  - JAVA_CHECKSTYLE
  - JAVASCRIPT_STANDARD
  - TYPESCRIPT_STANDARD
  - COPYPASTE_JSCPD
  - KUBERNETES_KUBEVAL
  - ACTION_ACTIONLINT
FILTER_REGEX_EXCLUDE: |
  Kubernetes/
  *Chart.yaml
  *templates/
  *values.yaml
  *values.*.yaml
PARALLEL: true
FILEIO_REPORTER: false
DISABLE:
  - COPYPASTE
````

and for _megalinter.yaml:_

```
trigger: none
pool:
  vmImage: ubuntu-latest
stages:
  - stage:
    jobs:
      - job: megalinter
        displayName: MegaLinter
        steps:
          - script: |
              docker pull oxsecurity/megalinter:v6.1.0
              docker run -v $(System.DefaultWorkingDirectory):/tmp/lint oxsecurity/megalinter:v6.1.0 \
              -e APPLY_FIXES=all \
              -e APPLY_FIXES__EVENT=pull_request \
              -e APPLY_FIXES_MODE=commit \
              -e MEGALINTER_CONFIG='.mega-linter.yml' \
              -e IGNORE_GITIGNORED_FILES=true \
              -e VALIDATE_ALL_CODEBASE=false
            displayName: 'Code Scan using MegaLinter'
```

**Comment by nvuillam** [comment]
Whe  git operations are not possible MegaLinter switches by default on a full scan

I think you should use fetchDepth, because a comparison is done with the main git branch to identify the delta list of files, so you need more than your current branch

https://stackoverflow.com/a/54232685/7113625

**Comment by PardisTV** [comment]
thank you for the advise.
can you also please advise if the automatic fixing error part is going to work only in github action but not in azure pipeline. right?

**Comment by PardisTV** [comment]
Thank you for your reply but we have more than 1 branch and I raised a pull request but it is still the same

**Comment by nvuillam** [comment]
@PardisTV can you check in full log if there is `Unable to list updated files from git diff. Switch to VALIDATE_ALL_CODE_BASE=true` ?

If not found, it means that ENV var VALIDATE_ALL_CODE_BASE=true is not found in the config

**Comment by PardisTV** [comment]
@nvuillam it's not found in the log. as you can see I have already put the config and to make sure i have put it in .mega-linter.yaml file as well but no difference. what should I do to make it easy for mega linter to find the env variable?

**Comment by nvuillam** [comment]
I think the issue is from the order of arguments in docker run

https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

-e arguments must come before the image name, not after

**Comment by PardisTV** [comment]
@nvuillam  Thank you for your reply. it worked for me :)
