### ISSUE TITLE
CSpellLinter not generating sample .cspell.json file?

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#1654]
Why is this code not being called? I am not getting anywhere the .cspell.json file with the suggested words.

https://github.com/oxsecurity/megalinter/blob/main/megalinter/linters/CSpellLinter.py#L19

**Comment by nvuillam** [comment]
It is called :)
Did you check in megalinter-reports ?

**Comment by bdovaz** [comment]
But where should it be? In which path / file?

I also have a problem which is that it does not generate the megalinter.log file and I can only see the console, why can it be? It only happens in v6

**Comment by nvuillam** [comment]
report folder has been renamed into megalinter-reports file ( I fixed the upgrader in latest v6 patch)

So you may have to update your Github Actions Workflow to replace `report` by `mralinter-reports` in the upload artifacts step :)

**Comment by bdovaz** [comment]
I have not explained well, I am running it locally (with docker image) and in the megalinter-reports folder I do not see that file:

![image](https://user-images.githubusercontent.com/950602/181015465-fcd119dc-87c2-4808-bc87-32effa2dfc86.png)

**Comment by nvuillam** [comment]
When you use TAP you disable TEXT_REPORTER, and .cspell.json is generated by TEXT_REPORTER :/

**Comment by nvuillam** [comment]
Maybe you can try to remove OUTPUT_FORMAT and use
``` yaml
TEXT_REPORTER: true
TAP_REPORTER: true
```

**Comment by bdovaz** [comment]
I still have this problem, v6 still maintains TAP_REPORTER so this bug should be fixed.:

https://github.com/oxsecurity/megalinter/pull/1625#issuecomment-1192331964

**Comment by bdovaz** [comment]
I have analyzed if I can use the SARIF reporter but I cannot because I have not found a utility that converts from SARIF to a format supported by Azure Pipelines:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml

That's why I'm tied at the moment to the TAP format and I need that fix I mentioned.

**Comment by echoix** [comment]
@bdovaz Could approaching the problem another way, like viewing the SARIF in Pipelines achieve what you need? 

For example, does looking at this extension (seems pretty popular) https://marketplace.visualstudio.com/items?itemName=sariftools.scans&ssr=false#overview help you out?

I didn't have the chance to work seriously with Azure Devops since it is called Azure DevOps, so I might be out of date :)

**Comment by bdovaz** [comment]
Created a PR @nvuillam https://github.com/oxsecurity/megalinter/pull/1657

**Comment by nvuillam** [comment]
Merged :)
