### ISSUE TITLE
cspell is very slow when scanning hundreds of files, we should optimize with --file-list

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#1655]
cspell allows a **--file-list** parameter:

https://github.com/streetsidesoftware/cspell/tree/main/packages/cspell#options

Right now it is running one command per file and is very inefficient...

Our repository has many files and it takes us more than half an hour to run megalinter in cspell alone.

```
[cspell] command: ['cspell', '-c', '/tmp/lint/.cspell.json', '/tmp/lint/myfile1']
[cspell] CWD: /
[cspell] result: 0 
1/1 ./tmp/lint/myfile1 580.26ms
CSpell: Files checked: 1, Issues found: 0 in 0 files

[cspell] command: ['cspell', '-c', '/tmp/lint/.cspell.json', '/tmp/lint/myfile2']
[cspell] CWD: /
[cspell] result: 0 
1/1 ./tmp/lint/myfile2 579.24ms
CSpell: Files checked: 1, Issues found: 0 in 0 files
```

**Comment by bdovaz** [comment]
A real example (**25 minutes** for 1600 files):

![image](https://user-images.githubusercontent.com/950602/181089143-9a59be8a-61f4-4f9c-a3fa-6ce904ae3502.png)

**Comment by bdovaz** [comment]
I ran a test with that parameter and it went to an incredible **13 seconds**

It is easy to use, just dump to a file all the file paths you get with after:

```
SPELL_CSPELL linter kept 1613 files after applying linter filters:
```

And then just:

cspell --file-list file_list.txt

What do you think @nvuillam?

**Comment by nvuillam** [comment]
That's only because you use TAP, else it cals everything once :)
But with all your ideas, why not becoming an active contributor ? You'd be welcomed:)

**Comment by bdovaz** [comment]
I am not understanding some things, why a reporter influences how linters are executed and the efficiency of them?

And in this case, where is the code you mention that when using TAP calls file by file and otherwise all at once? For the sake of understanding.

**Comment by bdovaz** [comment]
And if so, you should put a giant disclaimer saying that activating this reporter will affect the overall performance of the execution of the linters. I don't know if there are any other reporters that can also affect in this way.

**Comment by nvuillam** [comment]
Tap is built manually from the stdout result of a single lint
ML is not able to split... that's what sarif is for, but it's not available for all linters yet :/

**Comment by bdovaz** [comment]
As far as I understand you, the best thing to do for the moment is to use only TEXT_REPORTER and don't use TAP and SARIF... TAP for making everything very slow and SARIF for not being implemented in all linters and being in beta.

**Comment by bdovaz** [comment]
But I still can't get to generate the megalinter-reports/megalinter.log file.... And now I only have TEXT_REPORTER: true

**Comment by nvuillam** [comment]
- You can use TEXT_REPORTER with SARIF_REPORTER, but for the linters not able to output SARIF, you'll have only text output. You can also enable only linters managing SARIF, there are more and more ! ( see SARIF badges there -> https://oxsecurity.github.io/megalinter/latest/supported-linters/ )

- megalinter-reports/megalinter.log: this is a bug (v6 regression) that I try to solve in https://github.com/oxsecurity/megalinter/pull/1674

**Comment by nvuillam** [comment]
TAP documentation has been updated, explicitely saying that only slow mode with "file" is available when SARIF reporter is active ^^
There is no way to generate TAP files with list of files sent without parsing everything log of every linter... that's a development charge that I think so one will take, especially with SARIF more and more available :/

**Comment by nvuillam** [comment]
@bdovaz I tried to find SARIF to TAP converters on google, but without success
If you find or write one someday, please repoen this issue or post a new one, we could generate TAP from SARIF !
