### ISSUE TITLE
Running locally is very slow

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [oxsecurity/megalinter#1658]
I am running the megalinter locally on M1 Mac using `npx mega-linter-runner`

This takes >10 mins to complete, vs 1 min to complete when using the github action

I think this is because the megalinter is not using the config files in https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/ and it's linting files it shouldn't like python package files in venv

Do I need to do anything to ensure the megalinter using the config files in https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/?

Or should I install megalinter and not use the docker image? I'm wondering if the image is not optimised to run on ARM

**Comment by Kurt-von-Laven** [comment]
My understanding is that currently MegaLinter does not support ARM, so I am actually surprised that it worked at all. There is a pull request in progress to add ARM support: #1553. If you have bandwidth to help, please let them know on that thread.

**Comment by SoumayaMauthoorMOJ** [comment]
Ok thanks :-)
