### ISSUE TITLE
mega-linter-runner --install generates invalid Github Actions workflow

### ISSUE THREAD

**Issue by sammcj** [oxsecurity/megalinter#1662]
**Describe the bug**

`npx mega-linter-runner --install` adds invalid characters to the generated Github Actions workflow yaml, resulting in Github rejecting the workflow.

Examples:

https://github.com/sammcj/sqs-message-action/actions/runs/2750875544/workflow#L43

**To Reproduce**

1. `npx mega-linter-runner --install` 
2. 
```
? What is your project type ? Let MegaLinter suggest to me later (recommended)
? What CI/CD system do you use ? GitHub Actions
? Do you want to detect excessive copy-pastes ? No
? Do you want to detect spelling mistakes ? No
? Which MegaLinter version do you want to use ? v6 (Latest official release)
? What is the name of your repository default branch ? main
? Do you want MegaLinter to validate all source code or only updated one ? Validate only sources diff with master/main branch
? Do you want to automatically apply formatting and auto-fixes (--fix option of linters) ? Yes
? Do you want MegaLinter to upload reports on file.io ? (report is deleted after being downloaded once) No
? Do you want to see elapsed time by linter in logs ? Yes
? Do you want to connect to OX Security to secure your repository ? No
```
3. Open .github/workflows/mega-linter.yml
4. See invalid characters on line 43

**Expected behavior**

No invalid characters / a working workflow

**Screenshots**

![Screen Shot 2022-07-28 at 12 21 55 pm](https://user-images.githubusercontent.com/862951/181406816-64dfd30c-55c4-4ecb-b856-4cb8d9230a22.jpg)

![Screen Shot 2022-07-28 at 12 20 10 pm](https://user-images.githubusercontent.com/862951/181406822-d999b1ae-f21f-4c0d-bbc0-00036cbf967d.jpg)

I believe what should be generated was:

```
 VALIDATE_ALL_CODEBASE: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
```

**Additional context**

- macOS 12.5
- Standard English UTF8 charset

**Comment by nvuillam** [comment]
Good catch, thanks for reporting :)
