### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by sammcj** [oxsecurity/megalinter#1663]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

ACTION_ACTIONLINT, EDITORCONFIG_EDITORCONFIG_CHECKER, JAVASCRIPT_ES, JAVASCRIPT_STANDARD, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, REPOSITORY_DEVSKIM, REPOSITORY_DUSTILOCK, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_SECRETLINT, REPOSITORY_SEMGREP, REPOSITORY_SYFT, REPOSITORY_TRIVY, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by Kurt-von-Laven** [comment]
It seems like we should probably add a few linters to the existing JavaScript flavor. I have noticed a similar issue with the Python flavor where some of the recently added linters that should probably be included in it aren't.

**Comment by nvuillam** [comment]
@Kurt-von-Laven which ones ? :)

**Comment by Kurt-von-Laven** [comment]
I haven't investigated every flavor, but I get this error message when I try using the v6 JavaScript flavor:

```
MegaLinter flavor [javascript] does not contain linters REPOSITORY_DEVSKIM,REPOSITORY_DUSTILOCK,REPOSITORY_SYFT.
As they are not available in this docker image, they will not be processed
To solve this problem, please either: 
- use default flavor oxsecurity/megalinter
- add ignored linters in DISABLE or DISABLE_LINTERS variables in your .mega-linter.yml config file located in your root directory
- ignore this message by setting config variable FLAVOR_SUGGESTIONS to false
Missing linter and FAIL_IF_MISSING_LINTER_IN_FLAVOR has been set to "true": Stop run
```

Same deal when I use the Python flavor:

```
MegaLinter flavor [python] does not contain linters REPOSITORY_DEVSKIM,REPOSITORY_DUSTILOCK,REPOSITORY_SYFT.
As they are not available in this docker image, they will not be processed
To solve this problem, please either: 
- use default flavor oxsecurity/megalinter
- add ignored linters in DISABLE or DISABLE_LINTERS variables in your .mega-linter.yml config file located in your root directory
- ignore this message by setting config variable FLAVOR_SUGGESTIONS to false
Missing linter and FAIL_IF_MISSING_LINTER_IN_FLAVOR has been set to "true": Stop run
```

**Comment by nvuillam** [comment]
I think the message spears for itself ^^
`FAIL_IF_MISSING_LINTER_IN_FLAVOR: false` should do the job :)

**Comment by Kurt-von-Laven** [comment]
To clarify, we aren't in need of a workaround. I am just suggesting that if Devskim, Dustilock, and Syft all run on all files, then they should probably be included in all flavors (as opposed to creating brand new flavors that contain them).

**Comment by nvuillam** [comment]
I've added them for ox.security requirements, I think they should not make all ML images heavier ^^

**Comment by Kurt-von-Laven** [comment]
Oh, gotcha. It seems like `FAIL_IF_MISSING_FLAVOR_IN_LINTER` should have exceptions for these linters then or something since otherwise the config option will false positive on every flavor.

**Comment by nvuillam** [comment]
@Kurt-von-Laven good idea, done in next AutoUpdate linters PR :)

**Comment by Kurt-von-Laven** [comment]
@sammcj does that address your request?

**Comment by nvuillam** [comment]
I think that now the use of Javascript flavor should match the repo :) ( since MegaLinter v6.6.0)

Please reopen if there is still an issue :)

**Comment by sammcj** [comment]
Sorry @Kurt-von-Laven I missed the notification for your message 🤦 , Yes it does. Thanks all!!
