### ISSUE TITLE
Devskim does not respect excluded directories

### ISSUE THREAD

**Issue by schorlton** [oxsecurity/megalinter#1664]
As per title. Excluded directories were set with `FILTER_REGEX_EXCLUDE` in `.mega-linter.yml`. Instead, Devskim is linting everything.

Running `v6.1.0` using Docker. Thanks!!!

**Comment by nvuillam** [comment]
Linters using `project` CLI lint mode do not take in account FILTER_REGEX_EXCLUDE -> https://oxsecurity.github.io/megalinter/beta/configuration/#cli-lint-mode

About DevSkim, it seems that it uses local .gitignore file -> https://github.com/microsoft/DevSkim/issues/6
You can also add `REPOSITORY_DEVSKIM_ARGUMENTS: ["ignore-globs", "**/myfolder/*"]`

**Comment by schorlton** [comment]
What are your thoughts on autosetting command line arguments to meet the megalinter config for all linters using `project` lint mode, where possible? Then there could be a warning on any linters that cannot take arguments to narrow their input files (eg. They don't support excluding folders/files.

At the very least, I'd suggest a warning at run time that exclude dirs was set in the megalinter config but x,y,z tools which are scheduled to run cannot use this setting and will therefore lint everything.

**Comment by nvuillam** [comment]
I understand your frustration... it's doable, but ... it would require to be able to convert regular expressions into the exected format of each `project` cli_lint_mode linter... some are with .gitignore format, some others with arguments ....
That would require a huge work... so I don't say never... but it won't be for tomorrow either ^^
Maybe someday it could be easier if we switched from regexes to something like `.megalinterignore` with .gitignore format !

**Comment by Kurt-von-Laven** [comment]
Maybe if MegaLinter ultimately becomes a de facto linter standard/specification, such a feature would become trivial. I agree with @nvuillam though that we're far off from that point today.

**Comment by schorlton** [comment]
OK, thanks again for your consideration!

**Comment by nvuillam** [comment]
The regexes are an inheritance from super-linter (I plead guilty, I made the PR on super-linter 🤣), but I find their use quite boring, and not everyone is regex-fluent...
I think about .megalinterignore for quite some time now... maybe it's time :)

**Comment by ahmadnassri** [comment]
it doesn't seem that devskim is respecting the repo .gitignore file ... 

and adding additional ignore arguments using `REPOSITORY_DEVSKIM_ARGUMENTS` throws this error: 

```
❌ Linted [REPOSITORY] files with [devskim]: Found 2 error(s) - (0.46s)
- Using [devskim v0.6.9] https://oxsecurity.github.io/megalinter/v6.6.0/descriptors/repository_devskim
- MegaLinter key: [REPOSITORY_DEVSKIM]
- Rules config: identified by [devskim]
--Error detail:
Specify --help for a list of available options and commands.
Unhandled exception. Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unexpected value '**/megalinter-reports/**' for option 'ignore-globs'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.DevSkim.CLI.Program.Main(String[] args) in D:\a\1\s\DevSkim-DotNet\Microsoft.DevSkim.CLI\Program.cs:line 14
```

**Comment by nvuillam** [comment]
That's strange, it's supposed to work according to their example :/
https://github.com/microsoft/DevSkim/wiki/Analyze-Command#exclude-files-using-globs
