### ISSUE TITLE
Skip Trivy DB update?

### ISSUE THREAD

**Issue by schorlton** [oxsecurity/megalinter#1666]
Running v6.1.0 in Docker.

What are your thoughts on skipping trivy DB update? Should its linting not be tied to the megalinter version? If so, it seems like DB updates can be skipped in its config file: https://aquasecurity.github.io/trivy/v0.30.4/docs/references/customization/config-file/#db-options

Thanks!!

**Comment by nvuillam** [comment]
If there is a new [log4j-like](https://www.ncsc.gov.uk/information/log4j-vulnerability-what-everyone-needs-to-know) critical security issue, you'll be happy that MegaLinter detects it without waiting for the next release :)

But if you really want to disable it, please feel free to define a `trivy.yaml` file in your repo, with the following content:

```yaml
db:
  # Same as '--skip-db-update'
  # Default is false
  skip-update: true
```

You can also define variable `REPOSITORY_TRIVY_ARGUMENTS: ["--skip-db-update"]` in your local .mega-linter.yml file

**Comment by schorlton** [comment]
Thanks for your response! I'm not sure I totally agree but appreciate the thought. I think Megalinter's linting should be tied to its version. So if I run the `latest` docker image, great - I'll get that log4j-like issue detection as Megalinter will autobump trivy and hopefully release a new version which will get pulled in the latest tag. But if I want stable linting, running `v6.1.0` should always produce the same results.

You can envision many scenarios where linting using a stable rule set and analysis should be the default. First, debugging is really hard when the results are not reproducible. Second, most updates will not be critical security updates to linters but probably style linting rules, which I won't want to apply until I'm ready. Any way, just my two cents, and really appreciate the hard work to build such an amazing tool and respond to users :smile:

**Comment by nvuillam** [comment]
I don't think trivy cares about style ^^
As far as I know, only security linters auto-updates themselves before running, all "classic" linters and formatters ue the rules in the version installed in MegaLinter, so the with a ML version the results are always the same... except for some security linters... but security must be dealt seriously with :D (and to have even more security you can try https://www.ox.security who does much more than MegaLinter ^^ )

Thanks a lot for your feedback, it helps a lot when you spend a saturday evening maintaining MegaLinter lol

**Comment by Kurt-von-Laven** [comment]
I am not sure whether this answers your question, but are you aware of the configuration option `REPOSITORY_TRIVY_ARGUMENTS`? If you encountered the Trivy error at MegaLinter v6.1.0, I suggest attempting to reproduce it on the latest version. I doubt we can prioritize addressing issues with an outdated version of MegaLinter.

**Comment by bittner** [comment]
The output above is from the latest v6 Docker image on Docker Hub.

I was aware of the [`REPOSITORY_TRIVY_ARGUMENTS` option](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_trivy/), but didn't see a trivy CLI option to adjust the behavior. Digging deeper, I now found out there seems to be an option, as detailed by trivy's [vulnerability docs](https://aquasecurity.github.io/trivy/v0.34/docs/vulnerability/examples/db/): `--db-repository`

I'll try that out, thank you! And sorry for the noise.

**Comment by nvuillam** [comment]
Having trivy db in docker image would probably enhance performance for all uses ... If initial trivy install does not already does that ^^

**Comment by ReneRebsdorf** [comment]
> Having trivy db in docker image would probably enhance performance for all uses ... If initial trivy install does not already does that ^^

@nvuillam What are your thoughts wrt. this comment, and the nature somewhat-of-age issue from @schorlton , now we are still experiencing all the throttling issues from https://github.com/aquasecurity/trivy/discussions/8009

It seems if megalinter received a patch update when any of its linters were updated, and included a cache of this, all these problems would be mitigated, with a performance increase, and support for air-gapped environments and such?

**Comment by nvuillam** [comment]
@ReneRebsdorf sine the trivy unstability mess, Trivy databases are added in MegaLinter image at build stage

The behavior is the following with MegaLinter 8.3.0 : try several times to download latest databases, and if failed, use the stored database by using `--skip-db-update` and `--skip-check-update`

If you want to use cached database from the start, you can use `REPOSITORY_TRIVY_ARGUMENTS: ["--skip-db-update","--skip-check-update"]` in your .mega-linter.yml config file

**Comment by ReneRebsdorf** [comment]
> @ReneRebsdorf since the trivy unstability mess, Trivy databases are added in MegaLinter image at build stage
> 
> The behavior is the following with MegaLinter 8.3.0 : try several times to download latest databases, and if failed, use the stored database by using `--skip-db-update` and `--skip-check-update`
> 
> If you want to use cached database from the start, you can use `REPOSITORY_TRIVY_ARGUMENTS: ["--skip-db-update","--skip-check-update"]` in your .mega-linter.yml config file

@nvuillam  Thank you for the quick reply.
I am fairly certain I saw it was unable to download after 5 attempts, and then failed to run the linter, e.g. didn't use the cache after failing to download. the message was no database was found/available. I think this was using mega linter runner.

Is there something I should do to ensure the behaviour you describe, or should it be the default?

I will collect more information and raise a new issue if this is the case, but just want to ensure I understood you correctly :)

**Comment by nvuillam** [comment]
@ReneRebsdorf are you sure you are using latest version 8.3.0 ?
The issue you describe is not supposed to happen there, but with trivy who knows... :/

If it happens plz can you share the MegaLinter log ?

**Comment by ReneRebsdorf** [comment]
@nvuillam it's a bit late here, I will try to reproduce tomorrow, given we got it several times a day it shouldn't be a problem.

**Comment by nvuillam** [comment]
It's late here too 😭 

Good night :)

**Comment by ReneRebsdorf** [comment]
@nvuillam Unable to reproduce, sorry for the noise.
Great work on this linter and your efforts towards the community on not just providing linting, but being in touch with the authors of linters.

**Comment by nvuillam** [comment]
@ReneRebsdorf I'm glad you can't reproduce, it means it probably works ;)

You're welcome, thanks for using MegaLinter :) ( don't hesitate to post about it on X / LinkedIn / BlueSky if that's your game ^^ )
