### ISSUE TITLE
Trivy does not respect excluded directories

### ISSUE THREAD

**Issue by schorlton** [oxsecurity/megalinter#1667]
As per title. Excluded directories were set with FILTER_REGEX_EXCLUDE in .mega-linter.yml. Instead, Trivy appears to be linting everything.

Running v6.1.0 using Docker. Thanks!!!

**Comment by nvuillam** [comment]
Linters using `project` CLI lint mode do not take in account FILTER_REGEX_EXCLUDE -> https://oxsecurity.github.io/megalinter/beta/configuration/#cli-lint-mode

About Trivy -> https://aquasecurity.github.io/trivy/v0.30.4/docs/secret/examples/#skip-directories

Example:  `REPOSITORY_TRIVY_ARGUMENTS: ["--skip-dirs", "./my-test-dir", "--skip-dirs", "./my-testing-cert/"]`
