### ISSUE TITLE
Sharing Linting configurations across multiple projects, locally and in github action

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [oxsecurity/megalinter#1669]
I can see that you specify linting config files in https://github.com/oxsecurity/megalinter/tree/main/TEMPLATES.

I would like to create a set of linting config files for my team which can be shared across multiple Github projects, when running megalinter locally, through pre-commit hook and in Github action.

Is that possible?

So for example I could create an internal composite github action within my organisation with all of the linting config files. All of the github repos could use this internal composite action. But how could I reference the linting config files from the docker image ?

**Comment by nvuillam** [comment]
@SoumayaMauthoorMOJ this is possible using EXTENDS in your .mega-linter.yml config file :)

Example of `.mega-linter.yml` with extension

```yaml
EXTENDS: https://raw.githubusercontent.com/lars-reimann/.github/main/.mega-linter.yml
```

There may be an issue with properties priority, if you see it please notify here -> https://github.com/oxsecurity/megalinter/issues/1516

You can also define ENV var `MEGALINTER_CONFIG` to use a remove .mega-linter.yml config file

Example: `MEGALINTER_CONFIGhttps://raw.githubusercontent.com/lars-reimann/.github/main/.mega-linter.yml`
