### ISSUE TITLE
Goodcheck linter cause an error no matter if it's disabled

### ISSUE THREAD

**Issue by leosuncin** [oxsecurity/megalinter#1684]
**Describe the bug**
Looks like MegaLinter is broken due to [goodcheck linter](https://oxsecurity.github.io/megalinter/v6-alpha/descriptors/repository_goodcheck/)

**To Reproduce**

1. Go to https://github.com/leosuncin/nest-auth-example/runs/7602758320
2. Expand the 'MegaLinter' step
3. Scroll down to 'MegaLinter initialization (expand for details)'
4. See the error

**Expected behavior**
The goodcheck linter is bypassed because I don't use it

**Screenshots**
![imagen](https://user-images.githubusercontent.com/4307697/182054784-5ecc402d-ab6a-4a88-bfc8-663679bf0d14.png)

**Additional context**
I tried to disable the linter but without success, the error continues.

The repository with the code: https://github.com/leosuncin/nest-auth-example

**Comment by nvuillam** [comment]
The issue is with REPOSITORY_SEMGREP, please can you disable it as a workaround until we fix the bug ? :/

**Comment by nvuillam** [comment]
This will be fixed in a 6.2.1 to come on within the next hours

**Comment by leosuncin** [comment]
> The issue is with REPOSITORY_SEMGREP, please can you disable it as a workaround until we fix the bug ? :/

Nope, that doesn't fix it https://github.com/leosuncin/nest-auth-example/runs/7605269733

**Comment by nvuillam** [comment]
@leosuncin v6.2.1 is currently being published, it will be fixed in a few dozen of minutes :)

**Comment by nvuillam** [comment]
@leosuncin javascript flavor v6.2.1 has been published, please can you run your job again and confirm that now it's ok ? :)
