### ISSUE TITLE
Running mega-linter-runner docker image locally without installing node.js

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [oxsecurity/megalinter#1688]
My team uses python predominantly. Is there a way of running the mega-linter-runner image locally without installing node.js?

**Comment by nvuillam** [comment]
It is possible... but less easy than with mega-linter-runner :)

2 solutions:
- raw docker run, for example: `docker run -v /your/local/repo/path:/tmp/lint -e LOG_LEVEL=DEBUG -e MYVAR=MYVALUE oxsecurity/megalinter:v6`
- create a shell or bat script that will build the raw docker run command, using `"$PWD"` for example (that's basically what does mega-linter-runner apart from the install and upgrade functions)

And even a third solution.... create a mega-linter-runner in python and publish it on https://pypi.org/ ? I'd love the accept the PR :)

**Comment by SoumayaMauthoorMOJ** [comment]
Are you sure the docker solution works? I get a FileNotFound error: 
![image](https://user-images.githubusercontent.com/95432492/182193292-e6078571-d78f-4c37-bac4-dd2b39885beb.png)

**Comment by nvuillam** [comment]
What if you use npx mega-linter-runner and copy/paste the docker command that is in output logs ?

**Comment by nvuillam** [comment]
I also see the warning saying that you are on arm64 (probably a Mac M1), you may try this workaround https://stackoverflow.com/a/67680194/7113625

**Comment by SoumayaMauthoorMOJ** [comment]
Sorry all working as expected now not sure why it wasn't working before! For future ref I used: 
```
docker run -v /your/local/repo/path::/tmp/lint:rw oxsecurity/megalinter-python:v6
```
About the arm64 architecture, I'm waiting for https://github.com/oxsecurity/megalinter/pull/1553 to get merged :-)

**Comment by nvuillam** [comment]
Good , glad you succeeded :)

**Comment by echoix** [comment]
> About the arm64 architecture, I'm waiting for https://github.com/oxsecurity/megalinter/pull/1553 to get merged :-) 

@SoumayaMauthoorMOJ I'm still pretty busy including weekends now, but when we will be ready to test really further, could I ping you to test out with your M1? I have a Raspberry Pi 4B to test out (if I create a new installation I could also use my weaker Raspberry Pi 3B+), but since it's not a "performing" device (see: micro SD card for storage), it won't be helpful for the performance testing, or full usage of many cores. An M1 could also test working with a Mac ;)

**Comment by SoumayaMauthoorMOJ** [comment]
Yes please :-)
