### ISSUE TITLE
Checkov fails when using `TERRAFORM_CHECKOV_CLI_LINT_MODE: project` because it keeps the file flag `-f`

### ISSUE THREAD

**Issue by dgteixeira** [oxsecurity/megalinter#1690]
**Is your feature request related to a problem? Please describe.**
Checkov plugin does not support the `TERRAFORM_CHECKOV_CLI_LINT_MODE: project` like detailed in the [doc](https://oxsecurity.github.io/megalinter/latest/descriptors/terraform_checkov/).

Error: `checkov: error: argument -f/--file: expected one argument`

Even when I choose `project`, I get the error that the `-f` flag requires an argument, when running checkov, like this:
![image](https://user-images.githubusercontent.com/48694843/182226783-2119b740-0509-4e23-8e75-d426c4a75f75.png)

**Describe the solution you'd like**
When we use the `TERRAFORM_CHECKOV_CLI_LINT_MODE: project`, it should replace the `-f` flag with ` -d .` to run in the root directory.
This should improve drastically the checkov run times within repos with lot of files.
Example: on our repo with 199 *.tf files, it takes almost 9 minutes to run with the `file` lint mode, but takes less than 15s on my laptop by running on the root directory.

**Describe alternatives you've considered**
We tried using KICKS, but has the same problem (takes a long time)

**Additional context**
Running checkov on a big-ish repository:
![image](https://user-images.githubusercontent.com/48694843/182227584-47ba0bf5-c221-45a8-8de3-aa56a5cdf1eb.png)

**Comment by nvuillam** [comment]
We definitely can do that :)
We could code the behaviour in python, but I think we could also do it by interpreting new descriptor properties...

**Comment by nvuillam** [comment]
let's even do better and call checkov on the whole repo not only for terraform files but for all of them :)

**Comment by dgteixeira** [comment]
> let's even do better and call checkov on the whole repo not only for terraform files but for all of them :)

Hey, thanks for the fast responses!

Yeah, what I usually do, locally, is invoke the following command:
`checkov -d .`

> the `-d` flag allows us to specify the directory in which we want to run checkov, as stated by its doc:
> checkov -h
> usage: checkov [-h] [-v] [-d DIRECTORY] [--add-check] [-f FILE] [--skip-path SKIP_PATH] [--external-checks-dir EXTERNAL_CHECKS_DIR] [--external-checks-git EXTERNAL_CHECKS_GIT] [-l]
>                [-o {cli,cyclonedx,json,junitxml,github_failed_only,sarif,csv}] [--output-file-path OUTPUT_FILE_PATH] [--output-bc-ids] [--include-all-checkov-policies] [--quiet]
>                [--compact]
>                [--framework {bitbucket_pipelines,circleci_pipelines,argo_workflows,arm,bicep,cloudformation,dockerfile,github_configuration,github_actions,gitlab_configuration,gitlab_ci,bitbucket_configuration,helm,json,yaml,kubernetes,kustomize,openapi,sca_package,sca_image,secrets,serverless,terraform,terraform_plan,all} [{bitbucket_pipelines,circleci_pipelines,argo_workflows,arm,bicep,cloudformation,dockerfile,github_configuration,github_actions,gitlab_configuration,gitlab_ci,bitbucket_configuration,helm,json,yaml,kubernetes,kustomize,openapi,sca_package,sca_image,secrets,serverless,terraform,terraform_plan,all} ...]]
>                [--skip-framework {bitbucket_pipelines,circleci_pipelines,argo_workflows,arm,bicep,cloudformation,dockerfile,github_configuration,github_actions,gitlab_configuration,gitlab_ci,bitbucket_configuration,helm,json,yaml,kubernetes,kustomize,openapi,sca_package,sca_image,secrets,serverless,terraform,terraform_plan} [{bitbucket_pipelines,circleci_pipelines,argo_workflows,arm,bicep,cloudformation,dockerfile,github_configuration,github_actions,gitlab_configuration,gitlab_ci,bitbucket_configuration,helm,json,yaml,kubernetes,kustomize,openapi,sca_package,sca_image,secrets,serverless,terraform,terraform_plan} ...]]
>                [-c CHECK] [--skip-check SKIP_CHECK] [--run-all-external-checks] [-s] [--soft-fail-on SOFT_FAIL_ON] [--hard-fail-on HARD_FAIL_ON] [--bc-api-key BC_API_KEY]
>                [--prisma-api-url PRISMA_API_URL] [--docker-image DOCKER_IMAGE] [--dockerfile-path DOCKERFILE_PATH] [--repo-id REPO_ID] [-b BRANCH] [--skip-download] [--no-guide]
>                [--skip-suppressions] [--skip-policy-download] [--skip-fixes] [--download-external-modules DOWNLOAD_EXTERNAL_MODULES] [--var-file VAR_FILE]
>                [--external-modules-download-path EXTERNAL_MODULES_DOWNLOAD_PATH] [--evaluate-variables EVALUATE_VARIABLES] [-ca CA_CERTIFICATE]
>                [--repo-root-for-plan-enrichment REPO_ROOT_FOR_PLAN_ENRICHMENT] [--config-file CONFIG_FILE] [--create-config CREATE_CONFIG] [--show-config] [--create-baseline]
>                [--baseline BASELINE] [--output-baseline-as-skipped] [--skip-cve-package SKIP_CVE_PACKAGE] [--policy-metadata-filter POLICY_METADATA_FILTER]
>                [--secrets-scan-file-type SECRETS_SCAN_FILE_TYPE]
> 
> Infrastructure as code static analysis
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   -v, --version         version
>   -d DIRECTORY, --directory DIRECTORY
>                         IaC root directory (can not be used together with --file).

However, it would be amazing, as a future improvement, if we could specify the path for the directory to run. It would be good within repositories that have multiple `root modules` in different folders.
