### ISSUE TITLE
VALIDATE_ALL_CODEBASE: false when running locally

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [oxsecurity/megalinter#1695]
I can see from https://github.com/oxsecurity/megalinter/issues/1647 that when you set VALIDATE_ALL_CODEBASE: false the megalinter action does a comparison with the main git branch to identify the delta list of files. What about when you run the megalinter locally e.g. through docker? How does megalinter container know which branch to compare with?

**Comment by Kurt-von-Laven** [comment]
The logic is the same when running locally. I don’t claim there are no differences between running locally and in CI, but mega-linter-runner is merely a CLI to the same MegaLinter that runs in CI. By default, we compare against `origin/HEAD`, which is Git’s way of saying “the branch that is currently checked out in the origin repository, meaning the remote repository that was cloned.” In the vast majority of cases, this is the default branch on your cloud-hosting provider (e.g., GitHub). You can always configure `DEFAULT_BRANCH` explicitly if desired.
