### ISSUE TITLE
Error: Invalid SARIF. Missing 'results' array in run.

### ISSUE THREAD

**Issue by wesley-dean-flexion** [oxsecurity/megalinter#1725]
**Describe the bug**

A run of Megalinter (still on `@v6`) spits out an error that the generated SARIF file is invalid with the following, semi-helpful message:

```
Uploading results
  Processing sarif files: ["megalinter-reports/megalinter-report.sarif"]
  Error: Invalid SARIF. Missing 'results' array in run.
  Error: Invalid SARIF. Missing 'results' array in run.
      at countResultsInSarif (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:[18](https://github.com/IMLS/estimating-wifi/runs/7748715810?check_suite_focus=true#step:11:19)0:[19](https://github.com/IMLS/estimating-wifi/runs/7748715810?check_suite_focus=true#step:11:20))
      at uploadFiles (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:283:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:139:12)
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:52:30)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:74:9)
```

I pulled down the megalinter-report.sarif file and used `jq` to determine which item in the `runs[]` list is missing a `results` key.  It's item 0 (go_revive):

```json
{
  "properties": {
    "megalinter": {
      "docUrl": "https://oxsecurity.github.io/megalinter/latest/descriptors/go_revive",
      "linterKey": "GO_REVIVE",
      "linterVersion": "0.0.0"
    }
  },
  "tool": {
    "driver": {
      "informationUri": "https://revive.run",
      "name": "revive (MegaLinter GO_REVIVE)",
      "rules": [
        {
          "helpUri": "https://revive.run/r#unexported-return",
          "id": "unexported-return",
          "properties": {
            "severity": "warning"
          }
        }
      ],
      "version": "0.0.0"
    }
  }
}
```

The remainder of the items in that `runs[]` list have either `results: []` or a dictionary with the relevant results.

**To Reproduce**

1. hmm...  I don't exactly know.  I'm thinking a run the uses revive which comes back with no results for the go_revive linter?

**Expected behavior**

Given the error message, I suspect that there ought to be a key with an array of results, even if that array is empty (e.g., `results: []`).

**Screenshots**

log of an applicable run: https://github.com/IMLS/estimating-wifi/runs/7748715810?check_suite_focus=true#step:11:17

**Additional context**

(insert flattery here)

I haven't gotten to `oxsecurity/megalinter:beta` (per #1702) yet so this may have been addressed already.

**Comment by wesley-dean-flexion** [comment]
confirmed that the issue presents on `oxsecurity/megalinter:beta`

**Comment by wesley-dean-flexion** [comment]
https://github.com/oxsecurity/megalinter/blob/main/megalinter/reporters/SarifReporter.py#L217

would adding a line like this: 

```python
                run["results"] = []
```
(i.e., if the conditional on line [203](https://github.com/oxsecurity/megalinter/blob/main/megalinter/reporters/SarifReporter.py#L203) is false, add an empty list to the `results` key) help?

**Comment by nvuillam** [comment]
Your proposition of fix is good, you can make. PR if you like , or I'll do it later ^^

**Comment by wesley-dean-flexion** [comment]
Ohhh boy!!  I get to make a PR!!!!  Let's see how badly I can screw this up!!!  :rofl:
