### ISSUE TITLE
Powershell linter throws error if the path it is analyzing has a space in it

### ISSUE THREAD

**Issue by brandonmcclure** [oxsecurity/megalinter#1728]
**Describe the bug**
When I configure the `POWERSHELL_POWERSHELL` linter via github CI and change a .ps1 file that has a space in it's file path, I get an error:
```
--Error detail:
Invoke-ScriptAnalyzer: A positional parameter cannot be found that accepts argument 'with'.
```

**To Reproduce**

I created a repository that reproduces the behavior I am seeing. https://github.com/brandonmcclure/megalinter_repro/pulls

**Expected behavior**
The linter to run in the same way it does for modified ps1 files that do not have a space in their path. See this PR for an example of success: https://github.com/brandonmcclure/megalinter_repro/pull/2

**Comment by Kurt-von-Laven** [comment]
Have you already attempted to reproduce this issue by running [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) directly?

**Comment by brandonmcclure** [comment]
I had not, but running these commands from that repo show it working/the same failure if there are no quotes around the file path. 

```
git checkout brandonmcclure-patch-1; Invoke-ScriptAnalyzer -Path '.\path with spaces\test.ps1'
```
I get the expected result, which is the output of failed rules. 

a file with no spaces works good as well/will not 
```
git checkout noSpaces; Invoke-ScriptAnalyzer -Path .\noSpaces.ps1
```

If I ommit the quotes I get an error, which is the same when[ running as an action.](https://github.com/brandonmcclure/megalinter_repro/runs/7754507755?check_suite_focus=true#step:4:96)
```
git checkout brandonmcclure-patch-1; Invoke-ScriptAnalyzer -Path .\path with spaces\test.ps1
```
```
Invoke-ScriptAnalyzer: A positional parameter cannot be found that accepts argument 'with'.
```

**Comment by Kurt-von-Laven** [comment]
Sounds like we are most likely omitting quotes when calling PSScriptAnalyzer then. Thank you for narrowing it down.

**Comment by nvuillam** [comment]
@brandonmcclure it should be ok now, please can you check with oxsecurity/megalinter:beta ?
