### ISSUE TITLE
Proselint introduction - has started failing on our builds.

### ISSUE THREAD

**Issue by chris-grabcad** [oxsecurity/megalinter#1744]
**Describe the bug**
Proselint was added as a defgault linter that seems to be always on by default. The introduction of an additional checker (that I don't think brings any real value to our processes) by default is a 

**To Reproduce**

1. Configure mega linter on several repos as github actions
2. Do nothing else

**Expected behavior**
No additional linters should appear and start complaining about "breakages"

**Additional context**
Proselint - seems to be particulary noisy and of questionable value - we're writing technical readmes for developers not prose for readers.

example: -
```
1_18.md:82:111: leonard.exclamation.30ppm More than 30 ppm of exclamations. Keep them under control.
1_18.md:212:60: lexical_illusions.misc There's a lexical illusion here: a word is repeated.
1_18.md:320:90: typography.symbols.multiplication_symbol Use the multiplication symbol ×, not the letter x.
zabbix_overview.md:42:13: typography.symbols.ellipsis '...' is an approximation, use the ellipsis symbol '…'.
zabbix_overview.md:48:13: typography.symbols.ellipsis '...' is an approximation, use the ellipsis symbol '…'.
aws_sso.md:31:57: lexical_illusions.misc There's a lexical illusion here: a word is repeated.
aws_sso.md:51:26: typography.symbols.curly_quotes Use curly quotes “”, not straight quotes "".
aws_sso.md:73:78: typography.symbols.sentence_spacing More than two spaces after the period; use 1 or 2.
aws_sso.md:123:55: typography.symbols.ellipsis '...' is an approximation, use the ellipsis symbol '…'.
aws_sso.md:160:71: lexical_illusions.misc There's a lexical illusion here: a word is repeated.
user_account.md:18:24: cliches.write_good 'keep an eye on' is a cliché.
```

at a time whilst we're trying to get developers in multiple countries to write documentation I can say we don't really care if someone: -

* uses `x` instead of `×` or 
* `...` instead of `…` - I mean seriously can you actually tell the difference?
* using curly quotes instead of straight quotes - for a codebase - sorry, nope that's just plain silly :-)

Our policy is we introduce linters if and **only if** they can be replicated in the developer's IDE, to help shift left and cut down on churn.

**Comment by nvuillam** [comment]
@chris-grabcad I added proselint after a request, but I agree that for most of the cases it's quite useless ^^

I deactivated for own MegaLinter megalinting and my other repos... and your issue confirms that it should be deactivated if not explicitely activated by the presence of a .proselintrc file in the repo

MegaLinter 6.5.0 will work like that, meanwhile you can disable by adding SPELL_PROSELINT in DISABLE_LINTERS property / env var
