### ISSUE TITLE
Missing OUTPUT_DETAIL variable

### ISSUE THREAD

**Issue by thomasboni** [oxsecurity/megalinter#1748]
I am updating Megalinter in [this Gitlab CI/CD job template](https://r2devops.io/_/r2devops-bot/mega_linter) from `v4` to `v6`.

To generate a report well-integrated in Gitlab, I use the `tap` output, I convert it to JUnit xml and then I inject it in Gitlab as report. In `v4`,  the variable `OUTPUT_DETAIL` was present to add error messages in tap files. The variable seems to be removed now. 

So my question is: how to get a detailed tap output in `v6` ?

**Comment by nvuillam** [comment]
@thomasboni OUTPUT_DETAIL is still here, but not in the documentation, as it was an inheritance from SuperLinter
For TAP reporter, you can use `TAP_REPORTER_OUTPUT_DETAIL: detailed` to make sure to not mess with other reporters ( that could also use OUTPUT_DETAIL)

Following our linkedIn conversation, TAP reporter still works as before, except that now the TAP files are in `$WORKSPACE/megalinter-reports/tap` (before it was in `$WORKSPACE/report/tap` )

**Comment by thomasboni** [comment]
Thanks, @nvuillam ! I'm going to test it with `OUTPUT_DETAIL` and `TAP_REPORTER_OUTPUT_DETAIL` set to `detailed`

**Comment by thomasboni** [comment]
It works with `TAP_REPORTER_OUTPUT_DETAIL` set to `detailed` ! Thanks :)

**Comment by thomasboni** [comment]
I can do a PR to document it in README, what do you think @nvuillam ?

**Comment by nvuillam** [comment]
@thomasboni I already updated the documentation in this PR -> https://github.com/oxsecurity/megalinter/pull/1749

But if you have propositions to make the doc even better, please be my guest and make a PR :)
