### ISSUE TITLE
Missing file in secretlint?

### ISSUE THREAD

**Issue by fabricesemti80** [oxsecurity/megalinter#1752]
**Describe the bug**

I am getting the following error during the workflow run:

```
...
❌ Linted [REPOSITORY] files with [secretlint]: Found 1 error(s) - (1.05s) (expand for details)
  - Using [secretlint v5.2.3] https://oxsecurity.github.io/megalinter/latest/v6.5.0/descriptors/repository_secretlint
  - MegaLinter key: [REPOSITORY_SECRETLINT]
  - Rules config: [.secretlintrc.json]
  - Ignore file: [/github/workspace/.github/linters/.secretlintignore]
  --Error detail:
  [Error: ENOENT: no such file or directory, open '/github/workspace/megalinter-reports/copy-paste/html/css/app.a4f483de.css'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/github/workspace/megalinter-reports/copy-paste/html/css/app.a4f483de.css'
  }
...
```

The file it refers to does not exist in my repo, not sure if it should...?

**To Reproduce**

**Expected behavior**

**Screenshots**

![error image](https://ibb.co/hmmZfR8)

**Additional context**

**Comment by nvuillam** [comment]
Please can you share your repo ?
I think that when .secretlintignore is at the root of the repo it works
It also must contain `megalinter-reports` because if secretlint is run after other linters (like jscpd, who produces the file you see), it tries to find secret in MegaLinter logs

**Comment by fabricesemti80** [comment]
Hi Nicholas,

Thanks for the quick reply!  

I will check your suggestion.

This is my repo: https://github.com/fabricesemti80/home-stack

Thanks,
Fabrice

**Comment by nvuillam** [comment]
@fabricesemti80 you can see how it has been solved in the template repo :)

https://github.com/k8s-at-home/flux-cluster-template/pull/421

**Comment by fabricesemti80** [comment]
Thanks @nvuillam . Just got around to sort it with a bit of trial-error. 
Appears to be working now, much obliged for your time, also keep up the good work!

T,
Fabrice

**Comment by nvuillam** [comment]
You're welcome :)
