### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by ottumm** [oxsecurity/megalinter#1760]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, ACTION_ACTIONLINT, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, DOCKERFILE_HADOLINT, MAKEFILE_CHECKMAKE, MARKDOWN_MARKDOWN_TABLE_FORMATTER, REPOSITORY_CHECKOV, REPOSITORY_DEVSKIM, REPOSITORY_DUSTILOCK, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_SECRETLINT, REPOSITORY_SYFT, REPOSITORY_TRIVY, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by Kurt-von-Laven** [comment]
This one is similar to #1632 in that it's sort of Python + C, but with Bash and Hadolint as well. I still favor an npx-esque install-precisely-the-needed-linters-on-the-fly approach over maintaining a wide fleet of flavors.

**Comment by ottumm** [comment]
Yeah I think it’s the `Makefile` that pushed us out of the standard Python flavor. Totally understand not wanting to make a custom flavor for this — the link just made it so easy to file the issue. =)

**Comment by nvuillam** [comment]
If it's the only blocking point, I can also add the Makefile linter within Python flavor :)

**Comment by ottumm** [comment]
@nvuillam that's perfect, thank you so much!

**Comment by nvuillam** [comment]
Should be ok with 6.6.0 :)
