### ISSUE TITLE
SonarQube format for SARIF enabled outputs.

### ISSUE THREAD

**Issue by janderssonse** [oxsecurity/megalinter#1776]
**Is your feature request related to a problem? Please describe.**

SonarQube is a major player with nice UI's, but  does not support SARIF (https://portal.productboard.com/sonarsource/3-sonarqube/c/328-sarif-report-import), instead they have a custom import format. It is quite similar to SARIF, https://docs.sonarqube.org/latest/analysis/generic-issue/ Therefore I think it would possible to until further, implement a SonarQube specific output as a flavor of the SARIF-output.

**Describe the solution you'd like**
Usecase example with the checkstyle plugin: -f SARIF /as extra argument to checkstyle linter/ currently gives a SARIF output for checkstyle, as expected.
An option, SONARQUBE_CUSTOM_FORMAT: true would adapt any SARIF-enabled linters output to Sonarqube custom format instead.

**Describe alternatives you've considered**
Maybe another option would be able to save the original linters output on run - would be handy until even more tools adapted SARIF for integrations. Just adding a subfolder "linter-original-output" under reports, if configured.
In my use case with checkstyle, it would contain checkstyle-results.xml etc when given checkstyle option -f XML and -o checkstyle-results.xml. This would add support for tools, like SonarQube, that allows for targeted imports of custom formats for specific linters.

**Additional context**

**Comment by nvuillam** [comment]
It would be quite easy to implement, but... if commercial companies want MegaLinter to redirect to them, some discussions should happen between them and OX Security, since MegaLinter is now an OX product :)

**Comment by janderssonse** [comment]
I see, I was just thinking it would be another motivator to spread usage (and ease) megalinter for end users. The best would of course be if any other companies in this space just supported SARIF import natively, for use end users at least.

**Comment by nvuillam** [comment]
SARIF became the standard SAST output format, so I think that indeed everyone should follow and implement it :)

Sonar seems to be a great tool but also seems similar to MegaLinter: "aggregate linters to generate reports" , and they have paid options, so I would find strange to advertise for a paying service while MegaLinter does the same (or even better ? 😇) for free
