### ISSUE TITLE
Suggestion: Document JDK_JAVA_OPTIONS for adjusting container JVM options (was: allow JAVA_OPTS...)

### ISSUE THREAD

**Issue by janderssonse** [oxsecurity/megalinter#1783]
**Is your feature request related to a problem? Please describe.**
Java linters like checkstyle are initiated with a java -jar call, but without the possibilty to set maximum mem set (-Xmx property) and alike currently (if I read the linter code correct).  Would be handy to have the option to set this for predicatble and fine tuning java mem usage

**Describe the solution you'd like**
Add an configurable environement variable JAVAOPTS, MEGALINTER_JAVA_OPTS or alike, that is evaluated before java -jar calls, ie something like $MEGALINTER_JAVA_OPTS java -jar or alike... .. . so that mem usage (for JAVA runs) can be predictable and tuned (in ci runs etc).

**Describe alternatives you've considered**
Go to bed, instead of spamming the Megalinter project with requests:) On a serious note, no I don't have any alternative suggestions.

**Comment by nvuillam** [comment]
Spamming MegaLinter with requests is the best way to make it evolve, so don't worry you can continue :)

Did you know about [PRE_COMMANDS](https://oxsecurity.github.io/megalinter/latest/configuration/#pre-commands) ?

I think something like the following code in `.mega-linter.yml` file would work for what you need to do :)

```yaml
PRE_COMMANDS:
  - command: export JAVA_OPTS="-Xmx24576M"
    cwd: "root"        # Will be run at the root of MegaLinter docker image
```

**Comment by janderssonse** [comment]
Great, i'll continue then:)

**Comment by janderssonse** [comment]
So i guess the option for example could be added under cli_lint_extra_args:
            -  {{JAVAOPTS}}
 28       - "-jar"
 29       - "/usr/bin/checkstyle"
 
 for checkstyle.
  pmd seems to be called with a .sh, script so it maybe it would have to be added in another way for that call.

**Comment by nvuillam** [comment]
@janderssonse did you try with pre_commands ?

I think it should work :)

https://stackoverflow.com/a/26396250/7113625

**Comment by practicalli-john** [comment]
`JDK_JAVA_OPTIONS` is the official Environment Variable since Java version 9 and should be used instead of the unofficial `JAVA_OPTS`

`JDK_JAVA_OPTIONS` will prepend options to the `java` command for setting resource limits.

When running in a container, The `-XX:` options, e.g. `XX:MaxRAMPercentage` should be used to set relative memory usage rather than the fixed values of `-Xmx`, as constraints on docker resources may change by the system deploying the container

I currently use the following in `Dockerfile` for production systems

```
ENV JDK_JAVA_OPTIONS "-XshowSettings:system -XX:+UseContainerSupport -XX:MaxRAMPercentage=90"

CMD ["java", "-jar", "api-service.jar"]
```

**Comment by nvuillam** [comment]
@practicalli-john thanks for the precisions :)

**Comment by janderssonse** [comment]
I forgot to try this! And Thanks @practicalli-john I had missed that new (well "new since v 9 :D) standard.  Giving that as en environment var to the containter just works. To verif with a really low vm fail example:

podman run --volume $(pwd):/repotocheck -e MEGALINTER_CONFIG='configs/mega-linter.yml' -e JDK_JAVA_OPTIONS="-Xmx1m" -e DEFAULT_WORKSPACE=/repotocheck -e LOG_LEVEL=INFO oxsecurity/megalinter:v6.13.0

and you should get something like this from PMD and checkstyle

NOTE: Picked up JDK_JAVA_OPTIONS: -Xmx1m
NOTE: Picked up JDK_JAVA_OPTIONS: -Xmx1m
Error occurred during initialization of VM
Too small maximum heap

Maybe this should be added to the docs as a friendly note (..if you want to set JVM options for, just add the JDK_JAVA_OPTIONS etc). 

Note: It did not work setting JDK_JAVA_OPTIONS from the PRE_COMMANDS: as described earlier in the thread for me though, maybe I missed something, but I tried a few variants and I could not get the JVM to pick it up.
