### ISSUE TITLE
Feature : add jscpd to flavor ci_light

### ISSUE THREAD

**Issue by lolrenx** [oxsecurity/megalinter#1787]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
add jscpd to flavor ci_light, copy paste detection is language agnostic

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nvuillam** [comment]
@lolrenx that seems an acceptable request :)

It will be available in next MegaLinter minor version :) ( and in beta before that ^^ )

**Comment by lolrenx** [comment]
Merci! Looking forward to that 👍

**Comment by Kurt-von-Laven** [comment]
Personally, I love jscpd, but fair warning to those using the ci_light flavor for the sake of minimizing MegaLinter's runtime that, despite jscpd's impressive optimizations, duplicate detection remains inherently one of the slowest linting tasks available. You (or others using the ci_light flavor) may wish to [tune jscpd](https://github.com/SchemaStore/schemastore/blob/98f76622ff79f38bfd0b484d76d9c388bf7cf24b/src/schemas/json/jscpd.json#L191-L403) at the cost of missing some duplicates, run ci_light [locally](https://oxsecurity.github.io/megalinter/latest/mega-linter-runner/) but all linters in CI, and/or simply skip jscpd in certain contexts.

**Comment by lolrenx** [comment]
makes sense, thank you. haven't run into performance issues with jscpd so far, but our repos are fairly small. Perhaps this caveat could be mentioned on the jscpd doc page for megalinter ?

**Comment by nvuillam** [comment]
The "light" in ci_light is more about image size than performances, if users want to improve them they can add COPYPASTE_JSCPD in DISABLE_LINTERS variable :)
