### ISSUE TITLE
Add support for Pytype and Pyright - the alternative python typing linters: 

### ISSUE THREAD

**Issue by kfot** [oxsecurity/megalinter#1794]
There are many typing linters for Python, mypy, the one already supported in MegaLinter, is the most popular but lacks in terms of development pace, maturity and some functionalities (i.e. is enforced). It would be great if a user could pick another linter

Implement support for:
*  https://github.com/google/pytype
* https://github.com/microsoft/pyright

**Comment by nvuillam** [comment]
That seems to be a good idea :)

Maybe you'd like to try to make a PR ? ^^

**Comment by nvuillam** [comment]
That seems to be a good idea :)

Maybe you'd like to try to make a PR ? ^^
