### ISSUE TITLE
Best way to get error summary

### ISSUE THREAD

**Issue by shiranr** [oxsecurity/megalinter#1795]
Hi,
I was wondering if there is a convenient way to see MegaLinters error summary separated from the rest of the logs.
For example, if I have a Link Check linter and one link failed out of hundreds, I need to find the failed link inside a very long log.
Thanks,
Shiran

**Comment by Kurt-von-Laven** [comment]
Yes, the individual logs are written to `megalinter-reports/linters_logs`. Alternatively, you could configure `LOG_LEVEL: WARN`, for example.

**Comment by shiranr** [comment]
Thanks @Kurt-von-Laven for the response.
It did help.
But I want to extend my question :) 
The[ Markdown link check Linter](https://oxsecurity.github.io/megalinter/5.12.0/descriptors/markdown_markdown_link_check/) has the option of --quiet is there a way to pass that to MegaLinter?

**Comment by Kurt-von-Laven** [comment]
Excellent. Ah, that's a good idea that we may copy in our own projects. Yes, from looking at the link you shared, you want to add the following to your MegaLinter config file:

```yaml
MARKDOWN_MARKDOWN_LINK_CHECK_ARGUMENTS: --quiet
```
