### ISSUE TITLE
Enabling SARIF_REPORTER overrides TEXT_REPORTER features

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#1822]
If I activate SARIF_REPORTER and TEXT_REPORTER at the same time, the following happens:
1. A folder "linters_logs" is created with all linters logs in *.log format (CORRECT).
2. A folder "sarif" is created with all the linters logs in *.sarif format (CORRECT).
3. A file "megalinter-report.sarif" is created in the root replacing the file "megalinter-report.log" (WRONG).

Why do I lose the complete log in text format which is equivalent to what is shown by console? It is very useful to inspect it later.

**Comment by nvuillam** [comment]
When we use SARIF reporter, we call the linters with arguments telling them to output the result in SARIF and not in "human readable" text

Calling twice the linters with text mode then SARIF mode would double the performances and that would be not acceptable, but I recently found [a library that seems to be able to convert SARIF to human text](https://github.com/psastras/sarif-rs/tree/HEAD/sarif-fmt), i've not tested it yet but  that could be an interesting evolution to implement someday on MegaLinter :)

**Comment by bdovaz** [comment]
Well, in the same way that you [documented several topics about the TAP reporter](https://github.com/oxsecurity/megalinter/issues/1655#issuecomment-1222427190), it should be documented that there are reporters that can "coexist" at the same time but others, as in this case TEXT vs SARIF, cannot. That is, if SARIF is activated, the text reporter stops working.

**Comment by Kurt-von-Laven** [comment]
Happy to accept a pull request to clarify this in the documentation. On a related note, I see that [docs/reporters.md](https://github.com/oxsecurity/megalinter/blob/d866e8a85d91ae009497d762a11e7066782a5144/docs/reporters.md)  is currently missing `SARIF`, so that is another place to update in addition to [docs/reporters/SarifReporter.md](https://github.com/oxsecurity/megalinter/blob/477a57f2f667776d0adfed6e263970f0e8ab00ef/docs/reporters/SarifReporter.md).

**Comment by nvuillam** [comment]
> Well, in the same way that you [documented several topics about the TAP reporter](https://github.com/oxsecurity/megalinter/issues/1655#issuecomment-1222427190), it should be documented that there are reporters that can "coexist" at the same time but others, as in this case TEXT vs SARIF, cannot. That is, if SARIF is activated, the text reporter stops working.

Text reporter just store the console output of linters, so technically it still works even if the content is sarif :D 
But I get your point, I hope that someday i'll find the time to implement the sarif-to-human for such case ^^
