### ISSUE TITLE
 Access to the path '/agent/_work/13/a/Changes/megalinter-reports/megalinter.log' is denied.

### ISSUE THREAD

**Issue by PardisTV** [oxsecurity/megalinter#1841]
Hi, i run mega linter in our azure repo. the problem is that most of the time i get this error even though i disabled the reporter.
` Access to the path '/agent/_work/13/a/Changes/megalinter-reports/megalinter.log' is denied.`

here's my configuration:

**_.mega-linter.yml:_**
````
---
APPLY_FIXES: none
SHOW_ELAPSED_TIME: true

DISABLE_LINTERS:
  - JAVA_CHECKSTYLE
  - JAVASCRIPT_STANDARD
  - TYPESCRIPT_STANDARD
  - CSHARP_DOTNET_FORMAT
  - SPELL_CSPELL
  - REPOSITORY_GIT_DIFF

FILTER_REGEX_EXCLUDE: |
  Kubernetes/
  *Chart.yaml
  *templates/
  *values.yaml
  *values.*.yaml

PARALLEL: true
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: true
REPORT_OUTPUT_FOLDER: none
LOG_FILE: none
TEXT_REPORTER: false
UPDATED_SOURCES_REPORTER: false
CONFIG_REPORTER: false
```
can you please help me with it?

**Comment by Kurt-von-Laven** [comment]
Does this error appear during the MegaLinter step or during a [post step](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops)?

**Comment by PardisTV** [comment]
Hi @Kurt-von-Laven, it's happening during initializing the job

**Comment by Kurt-von-Laven** [comment]
I am afraid I have no experience with Azure DevOps. What is causing the job initialization step to attempt to access `megalinter.log`? If MegaLinter isn't even running, I don't see its configuration being relevant.

**Comment by PardisTV** [comment]
Thanks @Kurt-von-Laven , the issue has been fixed by adding `-u $(id -u ${USER}):$(id -g ${USER})` to the docker configuration.

**Comment by Kurt-von-Laven** [comment]
Hooray! Are you running MegaLinter directly via the Docker image? If so, are you aware of mega-linter-runner?

**Comment by PardisTV** [comment]
@Kurt-von-Laven ,  oh actually i have the issue again after a few run :( 
i am using MegaLinter image inside a shell script. 

```
`function mega_linter_in_docker(){
    local root_folder=$1
    local change_dir=$2
    local docker_version="v6.8.0"
    docker run \
      -e MEGALINTER_CONFIG='.mega-linter.yml' \
      -v "${root_folder}"/"${change_dir}":/tmp/lint oxsecurity/megalinter:"${docker_version}" \
      -u $(id -u ${USER}):$(id -g ${USER})
}`
```

**Comment by Kurt-von-Laven** [comment]
It can be tricky to run MegaLinter via Docker directly. I recommend using [mega-linter-runner](https://oxsecurity.github.io/megalinter/latest/mega-linter-runner/) or [following this documentation](https://oxsecurity.github.io/megalinter/latest/installation/#azure-pipelines).

**Comment by PardisTV** [comment]
Thank you @Kurt-von-Laven , it has been fixed by adding another quote :) , i will close this issue now.
`-u "$(id -u "${USER}")":"$(id -g "${USER}")"`
