### ISSUE TITLE
Sarif-reporter: sarif/JAVA_CHECKSTYLE.sarif does not contain all errors found

### ISSUE THREAD

**Issue by janderssonse** [oxsecurity/megalinter#1842]
**Describe the bug**
When running 6.8.0 with sarif-reporter enabled and java checkstyle enabled on a Java-project and many checkstyle errors show in console and text logs, not all of them are found in the resulting sarif/JAVA_CHECKSTYLE.sarif - only one rules category of checkstyle errors is shown in this file. If those errors are fixed, only one other category will be in this report file. I'm guessing that this file is overwritten rather than appended or a list of only one category is picked and save to the report from the errors? I have not dived into to the code.

**To Reproduce**
Run megalinter 6.8.0 with default checkstyle and sarif-reporter enabled on a medium sized java-project having a few different rule categories of errors. Notice the amount and categories of found checkstyle errors in the summary and text log. Notice under megalinter-reports/sarif/JAVA_CHECKSTYLE.sarif that only a few of the errors is listed (for one rule category).

**Expected behavior**
All of the found checkstyle errors should also be found in the resulting sarif-file.

**Screenshots**

Many checkstyle errors found
![megalinter-summary](https://user-images.githubusercontent.com/37870813/189096208-c503f4d1-a8a8-485b-96f9-01c51af79ff0.png)

Only one of the categories and the errors belonging to that category to be found in the resulting sarif-file. (4 here, in the same category - based the summary and the textlogs it should be a lot more)
![megalinter-checkstyle-sarif-missing-posts](https://user-images.githubusercontent.com/37870813/189096281-6e7c5ab0-6fb4-49b0-8c85-03f4edc06067.png)

**Comment by nvuillam** [comment]
The mode "file" and not "list_of_files" is the cause of such issue, your analysis is good, indeed only the last SARIF of the last java file is returned

Do you know if checkstyle can take a list of files as parameters ? If yes it will be very simple to solve :)
