### ISSUE TITLE
How to configure linting of multi-module golang project? 

### ISSUE THREAD

**Issue by uthark** [oxsecurity/megalinter#1852]
I have a project that consists of several go modules each with its own go.mod file.
As of now, megalinter invokes each file separately and it fails because of missing other files.

**Comment by nvuillam** [comment]
We shouldn't have linters called file by file, I try to arrange that :)

**Comment by nvuillam** [comment]
@uthark please could you try again with oxsecurity/megalinter:beta ?

**Comment by uthark** [comment]
Sure thing. Will report the findings in this issue
