### ISSUE TITLE
Support for `.mega-linter.yml` Base Config File Re-location

### ISSUE THREAD

**Issue by comc** [oxsecurity/megalinter#1865]
The `MEGALINTER_CONFIG` environment variable should accept a relative path, e.g., `.github/config/.mega-linter.yml`, in order to re-locate the config file other than the project root, if so desired.

Currently, the variable only supports a standalone filename located in the repo root directory, or a remote URL.

**Comment by nvuillam** [comment]
@comc relative paths seems to work, several repos are using exactly what you want to do

Examples: 
- https://github.com/ahmadnassri/action-dotenv/blob/master/docker-compose.yml
- https://github.com/ahmadnassri/action-semantic-release/blob/master/docker-compose.yml
- https://github.com/ahgraber/homelab-gitops-k3s/blob/main/.taskfiles/LintTasks.yaml
- https://github.com/recursion-ninja/personal-website/blob/35e18c45591b477cee963d741c9b93e27b961166/.github/workflows/haskell.yaml#L347

Is your repo public so i could check ?

**Comment by comc** [comment]
Thanks for the examples. It helped me identify my issue.

**Comment by nvuillam** [comment]
You're welcome :)
