### ISSUE TITLE
arm-ttk linter throws error when the path it is analyzing has a space in it

### ISSUE THREAD

**Issue by BrunoJuchli** [oxsecurity/megalinter#1879]
**Describe the bug**
When the arm-ttk linter is enabled and there is an azure resource manager template file (*.arm.json) in a path containing a whitespace the linting errors out with an error like:

    [arm-ttk] src/Functions/Properties/ServiceDependencies/3rdpartyimporttest - Zip Deploy/appInsights1.arm.json - ERROR - 1 error(s)
    --Error detail:
    Test-AzTemplate: 
    Line |
       3 |  Test-AzTemplate @config -TemplatePath /github/workspace/src/Functions …
         |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         | A positional parameter cannot be found that accepts argument 'Deploy/appInsights1.arm.json'.

That is, megalinter fails to execute the linter.

**To Reproduce**

1. add a file like:
  /src/Foo/Properties/ServiceDepencencies/some folder path with space/appInsights1.arm.json
2. enable arm-ttk linter
3. lint
4. see error (megalinter fails to execute the linter)

**Expected behavior**
The linter should run

**Additional context**
The same problem also existed with the powershell linter, which was fixed: https://github.com/oxsecurity/megalinter/issues/1728

**Comment by Kurt-von-Laven** [comment]
Thank you for reporting this. To state the obvious, it sounds like we need to add some quotes somewhere.

**Comment by nvuillam** [comment]
@Kurt-von-Laven  I'm pretty sure that's here -> https://github.com/oxsecurity/megalinter/blob/d7f0b566911ea1ebe615e930c93baa683823b38f/megalinter/linters/ArmLinter.py#L15 :)

**Comment by nvuillam** [comment]
@BrunoJuchli it's solevd :) 
please can you confirm it works with oxsecurity/megalinter:beta ?

**Comment by BrunoJuchli** [comment]
@nvuillam 
Tested and it works :-)

**Comment by BrunoJuchli** [comment]
@nvuillam @Kurt-von-Laven 
I wanted to add:
Thank you for looking into this and fixing it! This was really quick, too! 🥇

**Comment by nvuillam** [comment]
@BrunoJuchli you're welcome, don't hesitate to star and share MegaLinter on social networks , the more users -> the more contributors and capabilities for MegaLinter :)
