### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by a0n** [oxsecurity/megalinter#1880]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

BASH_EXEC, BASH_SHELLCHECK, COPYPASTE_JSCPD, CSS_STYLELINT, CSS_SCSS_LINT, DOCKERFILE_HADOLINT, EDITORCONFIG_EDITORCONFIG_CHECKER, JAVASCRIPT_ES, JAVASCRIPT_STANDARD, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, REPOSITORY_CHECKOV, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY, RUBY_RUBOCOP, SPELL_MISSPELL, SPELL_CSPELL, SQL_SQL_LINT, SQL_TSQLLINT, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
Hmmm what's that repo containing javascript and ruby  ? :)

**Comment by nvuillam** [comment]
@a0n you can try cupcake flavor :)

https://oxsecurity.github.io/megalinter/latest/flavors/cupcake/
