### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by practicalli-john** [oxsecurity/megalinter#1909]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

CLOJURE_CLJ_KONDO, DOCKERFILE_HADOLINT, MAKEFILE_CHECKMAKE, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

> Alternatively, adding `MAKEFILE_CHECKMAKE` to the `java` flavor would allow the use of that flavor instead of the default.

Thank you.

**Comment by nvuillam** [comment]
@practicalli-john that seems a perfectly reasonable request :)

It's on its way and will be in the next release :)
