### ISSUE TITLE
Azure Comments reporter - Change status when all tests pass

### ISSUE THREAD

**Issue by TommyE123** [oxsecurity/megalinter#1915]
**Is your feature request related to a problem? Please describe.**
Thank you so much for implementing the Azure Comments reporter which we are now using on our PR’s in devops. 

Would it be possible though to set the status of the comment to something other than ‘Active’ when the all the tests pass? If like we do, you have your build policies set to having to resolve all comments this can become quite annoying when most of the time the Linters are passing!

**Describe the solution you'd like**
We’ve currently been manually setting the comment to Resolved however I’m open to setting it to something else if you feel appropriate?
Possibly ‘Bydesign = 5’ for when all the tests pass? 
(however, that’s not a selectable option on the manual dropdown so we'd have to test that it works!)

I think the below thread lists the possible status options we can choose from?
[CommentThreadStatus enum | Microsoft Learn](https://learn.microsoft.com/pt-br/javascript/api/azure-devops-extension-api/commentthreadstatus)

**Describe alternatives you've considered**
Make it a configurable option to do this if you would rather not set it to Bydesign or Resolved by default so users can have the choice maybe?

**Additional context**
N/A

Thanks again
Tom

**Comment by nvuillam** [comment]
@TommyE123 thanks for your nice feedback:)
I'm not a regular user of azure pipelines, I didn't know there was a status for comment :)
The API probably allows to send a status so in case there is no error, ok to set it as resolved :)

You can even make the pull request if you want :)

**Comment by nvuillam** [comment]
@TommyE123 this is done :)
It will be available in the next release, and if you are in a hurry you can already use it with `oxsecurity/megalinter:beta` :)

**Comment by TommyE123** [comment]
@nvuillam Thanks for making this change. 
I've done a simple test of this in the beta branch and its working as expected 👍 

Cheers
Tom

**Comment by nvuillam** [comment]
@TommyE123 thanks for your test and feedback :)
