### ISSUE TITLE
Pylint: Unrecognized option found: no-space-check

### ISSUE THREAD

**Issue by schorlton** [oxsecurity/megalinter#1923]
Running `oxsecurity/megalinter-python:v6.11.0` off docker. Hitting:

```bash
❌ Linted [PYTHON] files with [pylint]: Found 3 error(s) - (6.65s)
- Using [pylint v2.15.3] https://oxsecurity.github.io/megalinter/6.11.0/descriptors/python_pylint
- MegaLinter key: [PYTHON_PYLINT]
- Rules config: [.pylintrc]
- Number of files analyzed: [2]
--Error detail:
************* Module /action/lib/.automation/.pylintrc
/action/lib/.automation/.pylintrc:1:0: E0015: Unrecognized option found: no-space-check (unrecognized-option)
```

Thank you as always!!

**Comment by Kurt-von-Laven** [comment]
According to [the Pylint 2.6 release notes](https://pylint.pycqa.org/en/2.6/whatsnew/2.6.html#other-changes):
> The `no-space-check` option has been removed, it's no longer possible to consider empty line like a trailing-whitespace by using clever options.

**Comment by schorlton** [comment]
> According to [the Pylint 2.6 release notes](https://pylint.pycqa.org/en/2.6/whatsnew/2.6.html#other-changes):
> 
> > The `no-space-check` option has been removed, it's no longer possible to consider empty line like a trailing-whitespace by using clever options.

Sure, but megalinter shouldn't error on this? I'm just using vanilla megalinter...this seems like a megalinter bug?

**Comment by nvuillam** [comment]
@Kurt-von-Laven as we deliver a default .pylintrc file, shouldn't we remove `no-space-check` from it ?

**Comment by echoix** [comment]
Maybe have a reminder of pylint's breaking change in the release notes for now, while a complete solution is made.

It might be useful for repos where they have a customized config file or customized .pylintrc file, which we shouldn't change.

**Comment by Kurt-von-Laven** [comment]
This specific issue seems like a one line fix? I personally don’t think MegaLinter ought to be in the business of “redocumenting” our dependencies. We already have this issue thread in this case, and someone with questions about linters that don’t pertain to MegaLinter directly is likely going to be better served by going directly to the source.

**Comment by echoix** [comment]
> I personally don’t think MegaLinter ought to be in the business of “redocumenting” our dependencies. We already have this issue thread in this case, and someone with questions about linters that don’t pertain to MegaLinter directly is likely going to be better served by going directly to the source.

Sorry, I might not have been following for long enough to remember that case, even if I am subscribed to all activity on this repo for a little while. Thanks for the feedback!

**Comment by nvuillam** [comment]
I think the ones that could play more fair is... pylint that does not respect SEMVER :)

SEMVER means `Breaking change = major version` , so their 2.6 should be a a 3.0 :)

**Comment by Kurt-von-Laven** [comment]
> Sorry, I might not have been following for long enough to remember that case, even if I am subscribed to all activity on this repo for a little while. Thanks for the feedback!

Oh, I was merely referring to the thread we are currently having this discussion on. I think someone encountering the error in question who searches for `no-space-check` in conjunction with either Pylint or MegaLinter will find the answer they are looking for quickly.
