### ISSUE TITLE
Documentation links from 

### ISSUE THREAD

**Issue by girlpunk** [oxsecurity/megalinter#1936]
**Describe the bug**
Links to megalinter's documentation included in the console output have the wrong path, causing them to not load.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run any lint. For example, `docker run --rm -v $(pwd):/tmp/lint oxsecurity/megalinter:v6`
2. Observe that documentation links show (for example) [https://oxsecurity.github.io/megalinter/**latest/v6**/descriptors/markdown_markdown_table_formatter](https://oxsecurity.github.io/megalinter/latest/v6/descriptors/markdown_markdown_table_formatter)
3. Click on the documentation link
4. 404 page

**Expected behaviour**
The documentation should load

**Screenshots**
![image](https://user-images.githubusercontent.com/161093/194104980-45b1ad52-15c7-4249-b551-bf11afc4d622.png)

**Additional context**
Removing either `latest/` or `v6/` from the URL results in a working URL

**Comment by echoix** [comment]
Seems like the same problem as #1819, that was supposed to be fixed in #1854

However I see that I suspected that a more robust solution should be tackled as I wrote in a comment. It could be the time to take a better look. (I don't think I can this weekend)

**Comment by nvuillam** [comment]
I just made a test with v6 and urls look fine

![image](https://user-images.githubusercontent.com/17500430/200117674-a2660c5b-9e31-4d70-8444-9b013051552f.png)

@girlpunk are you sure the bug is still happening ?
If yes please notify and i'll reopen the issue :)
