### ISSUE TITLE
Create a PR with Megalinter fixes on repository 

### ISSUE THREAD

**Issue by Hareshraman** [oxsecurity/megalinter#1939]
Hi , i happened to integrate megalinter as a github workflow and used the base template available and edited a few configurations to maintain consistency across my repositories although as a part of template I do see 3 steps as a part of the job , which are

- Create Pull Request with applied fixes
- Create PR output
- Prepare Commit

i also have enabled the required environment variables fo

- APPLY_FIXES: all
- APPLY_FIXES_EVENT: pull_request
- APPLY_FIXES_MODE: pull_request

i have passed the right PAT token with the read and write access to repositories. May I know if these actions work as per expectation ?

# Create pull request if applicable (for now works only on PR from same repository, not from forks)
      - name: Create Pull Request with applied fixes
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          commit-message: "[MegaLinter] Apply linters automatic fixes"
          title: "[MegaLinter] Apply linters automatic fixes"
          labels: bot

# Create New PR Output
      - name: Create PR output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

# Push new commit if applicable (for now works only on PR from same repository, not from forks)
      - name: Prepare commit
        run: sudo chown -Rc $UID .git/
      - name: Commit and push applied linter fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "[MegaLinter] Apply linters fixes"

May I know in which step we are adding fixes to a PR ? is it an action ? or a step that I'm missing 

I even tried testing it with a echo step on a linux runner , even an echo step is skipped after archiving artifacts , removed archiving artifacts step too, after the Megalinter step all steps are skipped .

**Comment by Kurt-von-Laven** [comment]
Duplicate #1938.
