### ISSUE TITLE
False-negative for setuptools in CSpell

### ISSUE THREAD

**Issue by mwarres** [oxsecurity/megalinter#1942]
I'm getting a false-negative for CSpell when "setuptools" is removed from the custom dictionary; see ScribeMD/docker-cache#177. This only occurs when CSpell is run through MegaLinter via pre-commit (as it is in our CI pipeline), but not when CSpell is run through the command line or when CSpell is run through MegaLinter without pre-commit. 

A false-negative occurs in the following scenarios: 
- Running MegaLinter through [ScribeMD/docker-cache](https://github.com/ScribeMD/docker-cache)'s CI pipeline; see [our pre-commit config](https://github.com/ScribeMD/docker-cache/blob/main/.pre-commit-config.yaml), [CSpell config](https://github.com/ScribeMD/docker-cache/blob/main/cspell.config.yaml), and [MegaLinter config](https://github.com/ScribeMD/docker-cache/blob/main/.mega-linter.yaml).  We use the pre-commit hooks defined in [ScribeMD/pre-commit-hooks](https://github.com/ScribeMD/pre-commit-hooks/blob/main/.pre-commit-hooks.yaml).
- Running MegaLinter through pre-commit with `poetry run pre-commit run --all-files --hook-stage push` in [ScribeMD/docker-cache](https://github.com/ScribeMD/docker-cache)

The correct behavior (successfully catching setuptools as an unrecognized word) occurs in the following scenarios:
- Running CSpell directly in ScribeMD/docker-cache with `npx cspell "**"`
- Running MegaLinter directly in ScribeMD/docker-cache with:

  ```
  npx -- mega-linter-runner@v6.10.0 --containername megalinter-full --remove-container --fix \
    --env CLEAR_REPORT_FOLDER=true --env LOG_LEVEL=debug --flavor javascript --release v6.10.0 
  ```

  or with `LOG_LEVEL=warning`
- Running through our CI pipeline in other repos; see ScribeMD/.github#85
- Incorrectly changing [our pre-commit config](https://github.com/ScribeMD/docker-cache/blob/main/.pre-commit-config.yaml) so that instead of:

  ```yaml
  - id: megalinter-incremental
    args: &megalinter-args [--flavor, javascript, --release, v6.10.0, --env, LOG_LEVEL=debug]
  ```

  I had:

  ```yaml
  - id: megalinter-incremental
    args: &megalinter-args [--flavor, javascript, --release, v6.10.0, LOG_LEVEL=debug]
  ```

  and then running MegaLinter via pre-commit with the following command:
  `poetry run pre-commit run --all-files --hook-stage push`.

Expected behavior: CSpell should catch setuptools as an unrecognized word.  The output should include `/tmp/lint/poetry.toml:6:4 - Unknown word (setuptools)`. Note: I erroneously thought it was included in CSpell's `python` dictionary but it is not; it is in the `python-common` dictionary.

Additional pertinent information: after running `poetry run pre-commit run --all-files --hook-stage push` on ScribeMD/docker-cache, the `megalinter.log` consists of the following output: 
```
MARKDOWN_REMARK_LINT has been temporary disabled in MegaLinter, please use a previous MegaLinter version or wait for the next one !
[File listing] Input file /tmp/lint/"poetry.toml not found
[File listing] Input file /tmp/lint/src/post.ts" not found
```
I'm noticing the stray quotes in lines two and three.  Consequently, I suspect that this bug has something to do with the interaction of quotation marks in pre-commit and MegaLinter.

Thanks for looking into this! I'm curious to see what you think!!

**Comment by mwarres** [comment]
Thank you for fixing this!!!

**Comment by nvuillam** [comment]
@mwarres please can you confirm it's all ok with latest version ? :)

**Comment by mwarres** [comment]
Confirmed!!
