### ISSUE TITLE
Pyright reports an error when `PYTHON_PYRIGHT_CONFIG_FILE` is set

### ISSUE THREAD

**Issue by d-mankowski-synerise** [oxsecurity/megalinter#1946]
**Describe the bug**
Pyright reports an error when `PYTHON_PYRIGHT_CONFIG_FILE` is set

**To Reproduce**
- enable linter `PYTHON_PYRIGHT`
- set `PYTHON_PYRIGHT_CONFIG_FILE: .pyrightconfig.json` in `.mega-linter.yml`
- set `LINTER_RULES_PATH: .linters`
- create folder `.linters` and put there `.pyrightconfig.json`
- run linter
- it ends with the following message:

```
❌ Linted [PYTHON] files with [pyright]: Found 1 error(s) - (15.68s)
- Using [pyright v1.1.270] https://oxsecurity.github.io/megalinter/latest/descriptors/python_pyright
- MegaLinter key: [PYTHON_PYRIGHT]
- Rules config: [/.linters/.pyrightconfig.json]
- Number of files analyzed: [1]
--Error detail:
Unexpected option -c.
pyright --help for usage
```

It seems the proper option to specify config folder is `-p`, not `-c`:

```
❯ pyright --help | grep config
  -p,--project <FILE OR DIRECTORY>   Use the configuration file at this location
```

**Expected behavior**

**Screenshots**
<img width="714" alt="image" src="https://user-images.githubusercontent.com/101267779/194721428-0a315279-6c3d-4802-b858-d0a481caab15.png">

**Additional context**

```
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2022-10-03T06:14:22Z
 - Image Revision: 88a858e
 - Image Version: v6
 ```

**Comment by nvuillam** [comment]
Good catch :)
