### ISSUE TITLE
Add `kics` to `REPOSITORY`

### ISSUE THREAD

**Issue by d-mankowski-synerise** [oxsecurity/megalinter#1949]
**Is your feature request related to a problem? Please describe.**
`kics` is not Terraform-specific - it supports other IaC manifests like Ansible, Kubernetes, Pulumi and more. I don't see a reason to limit it, by default, only to `.tf` files. Right now I am running it in repos containing Ansible code and I just used `TERRAFORM_KICS_FILE_EXTENSIONS: ["*"]`, but this doesn't look nice.

**Describe the solution you'd like**
`kics` should be added to `REPOSITORY` and `TERRAFORM_KICS` should be removed in megalinter 7.0

**Describe alternatives you've considered**
Same thing as with `TERRAFORM_CHECKOV`

**Comment by nvuillam** [comment]
This shiuld indeed be done someday :)
Maybe you'd like to submit a PR ?

Note: to ensure ascending comptability, KICS can be put in REPOSITORY descriptor, but should remain anyway in TERRAFORM descriptor until next major version

**Comment by d-mankowski-synerise** [comment]
Sure, I will take a look next week, but I don't promise anything :)

**Comment by bdovaz** [comment]
@nvuillam isn't it time to do this? Now that you are thinking of raising the major verison.

**Comment by nvuillam** [comment]
Yes it is, like manyyy other stuff :D 

If someone finds the time I'll be glad to add it ^^

Else it will be for the next major ! (I simplified the process to release a major so we won't be stucked to "once a year" anymore )
