### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by hckhanh** [oxsecurity/megalinter#1953]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

JAVASCRIPT_STANDARD, RUST_CLIPPY, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by Kurt-von-Laven** [comment]
Are JavaScript and Rust typically used together?

**Comment by nvuillam** [comment]
@hckhanh you should try cupcake flavor :)

https://oxsecurity.github.io/megalinter/latest/flavors/cupcake/
