### ISSUE TITLE
Use Docker Credentials or Mirror for this GitHub Action

### ISSUE THREAD

**Issue by vyas-n** [oxsecurity/megalinter#1958]
**Is your feature request related to a problem? Please describe.**

I'm running into DockerHub's Rate limit when trying to use MegaLinter within a Monorepo.

**Describe the solution you'd like**

To either:
- Be able to pass DockerHub credentials during the GitHub Action Pull for this docker image.
- Pull from a different container registry with higher rate limits (GHCR, Quay, ...)
- Specify a Docker Registry Mirror with the GH Action.

**Describe alternatives you've considered**

None really come to mind, there isn't a configuration value in the GH Action or existing GH Issue to help.

**Additional context**

It appears that the GH Action pulls the docker image before any step in the workflow starts. As a result, it's not using the credentials from the [Docker Login GH Action](https://github.com/docker/login-action) and instead trying to pull the image unauthenticated from DockerHub.

**Comment by vyas-n** [comment]
Hi @Kurt-von-Laven,

Thanks for your quick response! 😄

I don't believe I can, my GitHub action runners are using this k8s controller to dynamically create runners: https://github.com/actions-runner-controller/actions-runner-controller

And GH Actions seems to pull actions images before starting the workflow, so a pre-pull would happen too late in the workflow.

**Comment by Kurt-von-Laven** [comment]
We would be happy to accept a pull request to add a `--registry` argument to mega-linter-runner.

**Comment by nvuillam** [comment]
It seems that you can login to docker hub from workflow or runner level (see end of article)

 https://link.medium.com/yggwK4tN2tb

**Comment by vyas-n** [comment]
Thanks @Kurt-von-Laven, I'll try to create a PR for specifying an alternate image registry.

@nvuillam, thanks for the solution, but it won't work in my situation. The article's solution would solve it if I was running EC2 instances as GH Actions Runners. However, the controller I'm using deploys runners in k8s and an equivalent pre-pull solution wouldn't work since the runners are ephemeral and get disposed and re-provisioned after every workflow.

**Comment by Kurt-von-Laven** [comment]
Awesome; there are some pointers to help you get started in #1472, but feel free to reach out with any questions you may have.

For the benefit of others who stumble upon this thread, mega-linter-runner has an undocumented [`--nodockerpull`](https://github.com/oxsecurity/megalinter/blob/2a6ddcdf8669be4546e50d9f578b770860c83f74/mega-linter-runner/lib/options.js#L88-L93) argument.

**Comment by nvuillam** [comment]
not stale, in case @vyas-n submits a PR someday :)
Don't hesitate to ask support :)

**Comment by Kurt-von-Laven** [comment]
That makes me wonder whether mega-linter-runner should pull from ghci.io by default?

**Comment by nvuillam** [comment]
@Kurt-von-Laven we could indeed add a --registry option and use ghcr.io by default

But for the moment, when building I only add docker pull stats from docker hub images, we would also need to find a way to get the stats for ghcr.io packages, I want to reach the 5 millions docker pulls someday 😄
