### ISSUE TITLE
DevSkim: Cannot use `--ignore-globs`: Get `Unexpected value` error

### ISSUE THREAD

**Issue by rasa** [oxsecurity/megalinter#1993]
**Describe the bug**

When I add
```
REPOSITORY_DEVSKIM_ARGUMENTS: '--ignore-globs **/.mypy_cache/**'
```
per https://github.com/oxsecurity/megalinter/blob/a47459fcb4521766738367f693b23bd98f9e164f/docs/descriptors/repository_devskim.md?plain=1#L5 , I get
```
Specify --help for a list of available options and commands.
[282](https://github.com/rasa/repo/actions/runs/3305948280/jobs/5456473365#step:4:298)
  Unhandled exception. Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unexpected value '**/megalinter-reports/**' for option 'ignore-globs'
[283](https://github.com/rasa/repo/actions/runs/3305948280/jobs/5456473365#step:4:299)
     at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
[284](https://github.com/rasa/repo/actions/runs/3305948280/jobs/5456473365#step:4:300)
     at Microsoft.DevSkim.CLI.Program.Main(String[] args) in D:\a\1\s\DevSkim-DotNet\Microsoft.DevSkim.CLI\Program.cs:line 14
```
as that option is already being used at https://github.com/oxsecurity/megalinter/blob/b8777b63abb3b10af7cac4cc44f44e9a3a766f1e/megalinter/descriptors/repository.megalinter-descriptor.yml#L73-L74

**To Reproduce**

See above.

**Expected behavior**

No error.

**Additional context**

1. It appears DevSkim only supports one `--ignore-globs`, that has comma-seperated directories. See 
https://github.com/microsoft/DevSkim/blob/e05884ff7291df00c6474a9e277e5071e77273ad/DevSkim-DotNet/Microsoft.DevSkim.CLI/Commands/AnalyzeCommand.cs#L56

2. Per https://github.com/microsoft/DevSkim/blob/main/DevSkim-DotNet/Microsoft.DevSkim.CLI/Commands/AnalyzeCommand.cs#L96
I tried using this [undocumented](https://github.com/microsoft/DevSkim/wiki/Analyze-Command) option:
```
REPOSITORY_DEVSKIM_ARGUMENTS: '--skip-git-ignored-files'
```
But there is no output, and no errors reported, even though it reports two errors without this option.

**Comment by rasa** [comment]
This was originally reported [here](https://github.com/oxsecurity/megalinter/issues/1664#issuecomment-1225042330).

**Comment by Kurt-von-Laven** [comment]
Thank you for the bug report. It feels like we shouldn't be hard-coding `--ignore-globs` since it can only be passed once. Normally we could set this value in an [override-able template config](https://github.com/oxsecurity/megalinter/tree/85ba950a4b679404b026f0d7e61b27234b6e7ce6/TEMPLATES), but it appears DevSkim doesn't support config files that govern command line options. Our community is one step ahead of us here though, because they requested support for parsing `.gitignore` in microsoft/DevSkim#148, so perhaps we could pass [the undocumented `--skip-git-ignored-files` option](https://github.com/microsoft/DevSkim/pull/390/commits/7b285c748f5126863af566bdf5a7fb2b1049c924#diff-5214447e5fe804b455ae7fc50b647aba76ca1b8fbb2086f5c30d92130704d595R94-R96) instead. Does that seem like a good solution?

**Comment by rasa** [comment]
> ... so perhaps we could pass [the undocumented `--skip-git-ignored-files` option](https://github.com/microsoft/DevSkim/pull/390/commits/7b285c748f5126863af566bdf5a7fb2b1049c924#diff-5214447e5fe804b455ae7fc50b647aba76ca1b8fbb2086f5c30d92130704d595R94-R96) instead. Does that seem like a good solution?

@Kurt-von-Laven Eventually, yes, but it appears MegaLinter is using version v0.6.9 of DevSkim, which was released on [19 Jan 2022](https://github.com/microsoft/DevSkim/releases/tag/v0.6.9). The `--skip-git-ignored-files` option was added on 11 Aug 2022, and in main and the [v0.7.6-alpha](https://github.com/microsoft/DevSkim/releases/tag/v0.7.6-alpha) tag in https://github.com/microsoft/DevSkim/commit/36bfd71a30c3f82ff7167cb117ae4339c96c78ef . I am not sure it's in the latest [v0.6.32](https://github.com/microsoft/DevSkim/releases/tag/v0.6.32) release.

**Comment by rasa** [comment]
This issue isn't stall. It's waiting on a fix upstream.

**Comment by nvuillam** [comment]
https://github.com/microsoft/DevSkim/issues/391

it should be ok now :)

now we have to apply it within ML... :)

**Comment by rasa** [comment]
Not stale. They still haven't released the fix. See https://github.com/microsoft/DevSkim/releases

**Comment by mockjv** [comment]
Is there any particular reason why Megalinter could introduce another variable/argument that would append to the existing "**/megalinter-report/**" entry?  In my particular case, I want to ignore something that is _not_ in my .gitignore.

**Comment by nvuillam** [comment]
What is the relation between reports and ignoring files ?

Maybe you'd like to use FILTER_REGEX_EXCLUDE ?

Please be more specific and give an example so we can help you :)

**Comment by girlpunk** [comment]
@nvuillam Ignoring the reports folder is automatically added to the devskim command by megalinter.

If you would like to ignore extra files (such as local configuration files that may contain fake secrets), the [configuration page linked in the megalinter documentation](REPOSITORY_DEVSKIM_ARGUMENTS) indicates to use the `-g` (`--ignore-globs`) flag. However as this has already been added, when megalinter adds it for a second time, the error occurs.

**Comment by rasa** [comment]
@girlpunk Yes, I also noted that the `--ignore-globs` is already being used by MegaLinter in my first post.

**Comment by nvuillam** [comment]
@girlpunk @rasa good remark, I'll remove the use of --ignore-globs so you can use it as you wish :)
