### ISSUE TITLE
CSpell doesn't allow to pass SPELL_CSPELL_FILE_EXTENSIONS argument?

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#1997]
It's not documented: https://oxsecurity.github.io/megalinter/latest/descriptors/spell_cspell/#readme

And of course it's because it's not in descriptor: https://github.com/oxsecurity/megalinter/blob/79fe208cb54ecb10f90e65b1bb8cc04065273832/megalinter/descriptors/spell.megalinter-descriptor.yml

Is it because of something in particular? Because it seems that it does support it: http://cspell.org/docs/globs/

**Comment by nvuillam** [comment]
language linters have a specific behaviour: they analyze files that are analysed by other linters

**Comment by bdovaz** [comment]
You mean if I throw these linters:
- json: with *.json
- yml: with *.yml
- cspell -> is going to be *.json, *.yml the filter?

Is this explained somewhere? It is not easy to understand.

Also, what happens if I only want to launch the cspell linter? In that case is it going to be *.* or *.*?

**Comment by nvuillam** [comment]
> Also, what happens if I only want to launch the cspell linter? In that case is it going to be * . *?

Nope, nothing will be linted ^^

https://github.com/oxsecurity/megalinter/issues/1976

And you're right, it should be explained somewhere.... and maybe we should manage that if FILE_EXTENSIONS is user-defined, it was taken in account except the default behaviour to use other linters files

**Comment by bdovaz** [comment]
I agree.

The parameter "SPELL_CSPELL_FILE_EXTENSIONS" (which does not exist now) should serve to override the current behavior that is not documented. If this parameter is defined, it overrides that behavior.

**Comment by nvuillam** [comment]
If you are in a mood for a PR... it will probably happen here :)

https://github.com/oxsecurity/megalinter/blob/cdaf93b40200d9177a8a58c04fe0a2bb7beb898c/megalinter/utils.py#L133

**Comment by bdovaz** [comment]
I would try but I don't feel comfortable with python (my world is in .NET) in terms of experience in it nor do I know the guts of megalinter to make this change....

I'll wait for when you can implement it.

**Comment by bdovaz** [comment]
@nvuillam I created a draft PR, can you help/guide me please? Thanks.

**Comment by bdovaz** [comment]
@nvuillam I see that you have merged it but I don't see that it appears in the beta documentation, shouldn't it show up?

https://oxsecurity.github.io/megalinter/beta/descriptors/spell_cspell/

I say this in case there is something missing in some descriptor or some condition of that PR that is not correct.

Thanks.
