### ISSUE TITLE
DEFAULT_WORKSPACE is prefixed to SARIF-output field uri but should not be.

### ISSUE THREAD

**Issue by janderssonse** [oxsecurity/megalinter#2006]
**Describe the bug**
DEFAULT_WORKSPACE is prefixed to uri in the SARIF-output, in my case, breaks SARIF-Viewer/VSCode, but would be the same for any alike setup.

**To Reproduce**
Example: 

Run the megalinter container, here standing in the root of the repo you want to check: 

1. podman run --volume $(pwd):/repo DEFAULT_WORKSPACE=/repo -e LOG_LEVEL=INFO oxsecurity/megalinter:v6.13.0
2. Open up your fav editor, for example VSCode, (with SARIF-Vieever extension installed)
3. Open a sarif file from VSCode.(from megalinter-reports/sarif
4. While rules are shown, notice VSCode cant find the path to the error. Look in the SARIF-FILE, see that all "uri"s have the DEFAULT_WORKSPACE prefixed to them., EG /repo/src/main etc. 
5. Removing the prefixed DEFAULT_WORKSPACE so we have expected src/main. Now it works!

**Expected behavior**
DEFAULT_WORKSPACE should not be prefixed to SARIF-output. This variable is something that most likely only exists during runtime generation, and makes the SARIF-output closely tied to that run.

**Comment by nvuillam** [comment]
There is already a replacement in generated SARIF for some values like /tmp/lint or /github/workspace 

The case with custom value is indeed not taken in account, we can arrange that ,:)

Meanwhile if you use /tmp/lint it will be ok :)

As some linters directly generate a SARIF file, content of SARIF folder may not be post-processed, you may directly use the unique SARIF file generated at report root :)

**Comment by janderssonse** [comment]
I will give this one a shot when I have the time. I had a look at the code, and I think this one could be implemented in the method fix_sarif_physical_location by just looking if the uri field starts with the same as DEFAULT_WORKSPACE, (if set) and if so, remove that prefix.

**Comment by janderssonse** [comment]
A small PR is now here https://github.com/oxsecurity/megalinter/pull/2119.
It is to be considerad as a partial fix.

That will fix the problem for the aggregated sarifreport.

However, to fully fix the problem, I suggest moving the whole run of the sarif-fixing logic in SarifReporter-class, to be run on the individiual sarif outputs. Ie to move the fix phase so it is done just somewhere around Linter.py, row 899,  with a call to a "normallize_sarif" which is basically the same logit that currently is happing in SarifReporter.py for cleaning up.

The benefits would be that both the indiividual sarif output files for each linteer and the end aggregate report would be useful!

If that sounds like a good idea, i could start creating an pr for adjusting an moving the sarif report cleanup method to that earlier phase instead.

**Comment by janderssonse** [comment]
@nvuillam Working on small pr for this, where the sarif-fix/normalization are done earlier in the phase (as above described, in practice just moves the logic call.) We'll see if you like it and if I get to finish it, and so on, but a small practical question here: currently the files are saved under the sarif-files folder under report folder. Would prefer that each of those is overwritten with the fixed/normalized version OR that the fixed version is also added with, for example a .normalized.sarif prefix? I.e

Would you prefer as now:
BASH_SHELLCHECK.sarif
JAVA_PMD.sarif.

where these two are "normalized" files 

OR

BASH_SHELLCHECK.sarif
BASH_SHELLCHECK.normalized.sarif
JAVA_PMD.sarif
JAVA_PMD.normalized.sarif

 ie doubles the number of files, but makes any bug-hunting easier in the future (if something is normalized to much :)

**Comment by nvuillam** [comment]
@janderssonse I'd prefer option 3 :)
Do not normalize initial sarif files by default (better perfs), but normalize them if there is a config var SARIF_REPORTER_NORMALIZE_LINTERS_OUTPUT set to true ? :)

**Comment by janderssonse** [comment]
Hi don't stale me yet. I did an working feature take a few weeks ago, I only need to get the time free to add as configurable, and test it bit more.
