### ISSUE TITLE
Linter to check spelling of file name?

### ISSUE THREAD

**Issue by kcfedun-fincad** [oxsecurity/megalinter#2009]
Hello,

Does MegaLinter support a linter that checks the spelling of file names?

**Comment by Kurt-von-Laven** [comment]
Not by default, but the wonderful maintainer of CSpell has published a variety of workarounds: streetsidesoftware/cspell#3063. I recommend upvoting the issue and/or chiming in if those don’t meet your needs.

**Comment by nvuillam** [comment]
> Not by default, but the wonderful maintainer of CSpell has published a variety of workarounds: streetsidesoftware/cspell#3063. I recommend upvoting the issue and/or chiming in if those don’t meet your needs.

MegaLinter also has great maintainers... We can probably do such thing natively in MegaLinter, maybe by generating a temporary text file with file names and add it to the list of files sent to cspell ^^

**Comment by Kurt-von-Laven** [comment]
It’s certainly doable, but given that Jason doesn’t seem opposed to adding such a feature to CSpell, that feels like a more appropriate home for this functionality?

**Comment by nvuillam** [comment]
The issue exists for 4 months, we can probably solve it in 2 hours within MegaLinter, let's allow ML to provide additional value to existing linters 😇

**Comment by Kurt-von-Laven** [comment]
I think the issue has been open because Jason himself has no particular need for this feature, and he raised some good questions about how to implement it correctly. I am not so sure it will be any less work to add a correct implementation to MegaLinter than directly to CSpell though?

**Comment by nvuillam** [comment]
More simple for me to do it in ML, where we already have the list of files so have only one case to manage ^^

**Comment by Kurt-von-Laven** [comment]
I see your point.
