### ISSUE TITLE
[clojure] add cljstyle format tool

### ISSUE THREAD

**Issue by practicalli-john** [oxsecurity/megalinter#2011]
Provide a format tool for the [Clojure language linters](https://oxsecurity.github.io/megalinter/latest/descriptors/clojure/)

#### Proposal
Add [cljstyle](https://github.com/greglook/cljstyle) to the Clojure language linters with a default configuration that matches the Clojure Style Guide (which it does by default)

[cljstyle](https://github.com/greglook/cljstyle) provides a binary to check and fix Clojure code (.clj, .cljs, .cljc, .edn) and can format code following the Clojure style guide.

[cljstyle](https://github.com/greglook/cljstyle) can be configured via the `.cljstyle` file, so can easily be configured by the end user as well as provide a default configuration
 - for example: https://github.com/practicalli/dotfiles/blob/main/.cljstyle

cljstyle is available as part of the [setup-clojure GitHub Action](https://github.com/marketplace/actions/setup-clojure), so having the same tool in MegaLinter would help with consistency and allowing easy migration path to MegaLinter if desired.

#### Alternatives
cljfmt is a library cljstyle was based on.  cljfmt is not availabe as a binary, so would either require building or uses as a library.

zprint is available as a binary, although it is a more general file formatting tool that requires more understanding to configure.  zprint may be a useful addition along with cljstyle, especially if a good default configuration can be defined.

**Comment by nvuillam** [comment]
Nice proposition :)

Can it take a list of files as arguments ?

Would you eventually like to make a PR ? :)

**Comment by practicalli-john** [comment]
> Nice proposition :)
Thank you

> Can it take a list of files as arguments ?
Yes, a specific file or set of files can be passed to `cljstyle`

> Would you eventually like to make a PR ? :)
I would be happy to take a look, although it will have to be in a few weeks as I have a pressing deadline for my current employer (and still have some covid symptoms - hence the slow reply)

**Comment by nvuillam** [comment]
@practicalli-john I know what it is... I understand, especially the part with being overloaded by tasks at our non-open-source jobs :)
I wish you to get better, good luck :)

I let this issue open, we'll see who will make the PR first ^^ ( it can also be another contributor ^^ )

**Comment by nvuillam** [comment]
I replied in the PR comments :)

**Comment by nvuillam** [comment]
Not stale :)
Let's make it pass someday:)

**Comment by nvuillam** [comment]
Passed :)
