### ISSUE TITLE
Markdownlint wrong version displayed on report

### ISSUE THREAD

**Issue by llaville** [oxsecurity/megalinter#2019]
**Describe the bug**
`mardownlint` version displayed seems invalid.

**To Reproduce**

1. Run command `docker run -v $(pwd):/tmp/lint -e LOG_LEVEL=INFO oxsecurity/megalinter-php:v6`
2. Checkout output report 
3. See version `0.32.2`

**Expected behavior**
Latest version available is `0.26.2` (see https://github.com/DavidAnson/markdownlint/releases/tag/v0.26.2)

**Screenshots**
```
Skipped setting git safe.directory DEFAULT_WORKSPACE:  ...
Setting git safe.directory default: /github/workspace ...
Setting git safe.directory to /tmp/lint ...
[MegaLinter init] ONE-SHOT RUN
[config] /tmp/lint/.mega-linter.yml + Environment variables
----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2022-10-23T22:50:51Z
 - Image Revision: f58627d
 - Image Version: v6
----------------------------------------------------------------------------------------------------

✅ Linted [MARKDOWN] files with [markdownlint]: Found 25 non blocking error(s) - (1.35s)
- Using [markdownlint v0.32.2] https://oxsecurity.github.io/megalinter/latest/descriptors/markdown_markdownlint
- MegaLinter key: [MARKDOWN_MARKDOWNLINT]
- Rules config: [/.github/linters/.markdown-lint.json]
- Number of files analyzed: [17]
--Error detail:
/tmp/lint/CHANGELOG-3.x.md:495:1 MD053/link-image-reference-definitions Link and image reference definitions should be needed [Unused link or image reference definition: "3.17.0"] [Context: "[3.17.0]: https://github.com/l..."]

```

**Additional context**
Gettings some error `MD053` that came with latest `markdownlint` release `v0.26.2` (see https://github.com/DavidAnson/markdownlint/commit/c5ca661b96ff993db9f8aa386d8dc3db3458c666) and available only since v0.26.0

When running with MegaLinter v5, in same context (source code to analyse, and `.mega-linter.yml` config file)
```
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2022-07-10T08:32:13Z
 - Image Revision: 7b2c5402f
 - Image Version: v5
----------------------------------------------------------------------------------------------------
```
I got also a strange version `v0.31.1` 
```
### Processed [MARKDOWN] files
- Using [markdownlint v0.31.1] https://megalinter.github.io/v5/descriptors/markdown_markdownlint
- MegaLinter key: [MARKDOWN_MARKDOWNLINT]
- Rules config: [/github/workspace/.github/linters/.markdown-lint.json]
- Number of files analyzed: [17]
✅ Linted [MARKDOWN] files with [markdownlint] successfully - (0.84s)
```

BUT notice here with v5 and a previous markdownlint version (probably lower than 0.26.0) because I got no errors MD053

**Comment by nvuillam** [comment]
The version you see is from markdownlint-cli (recommended in markdownlint doc)

It has markdownlint dependency https://github.com/igorshubovych/markdownlint-cli/blob/master/package.json

**Comment by llaville** [comment]
There is a confusion with url provided in https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/markdown.megalinter-descriptor.yml#L17

**Comment by nvuillam** [comment]
I updated the doc... can't really do more, there is no markdownlint-cli --version-markdownlint command :/
