### ISSUE TITLE
How to install additional dependencies for pylint in megalinter Docker

### ISSUE THREAD

**Issue by kkaiser** [oxsecurity/megalinter#2030]
Dear all,

Pylint has a rule that checks for imported packages to be available. Since megalinter uses isolated virtual environments for all packages (I like that) I wanted to ask if there is a best practice to install into that path: `/venvs/pylint/lib/python3.10/site-packages/`.

Background is that the naive way doesn't work:

```docker
FROM oxsecurity/megalinter-python:v6.13.0
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
```

After building the image and running the container we will get many errors:

```text
E0401: Unable to import 'pytest' (import-error)
```

Of course, it could be disabled. Better is however to install the extra dependencies. 

What is the best practice? Using `--target` in the pip command will work. Also having a `.pylintrc` with below content works:

```ini
[MASTER]
jobs = 4
unsafe-load-any-extension = true
init-hook="import sys; sys.path.insert(0, '/usr/local/lib/python3.10/site-packages/')"
```

But what would you recommend or is there a better way?

Thanks in advance!

**Comment by Kurt-von-Laven** [comment]
See https://github.com/oxsecurity/megalinter/issues/2017#issuecomment-1298771836 if you are able to wait until the next release. Otherwise, scroll up in that thread for discussion of a few options that work today.

**Comment by kkaiser** [comment]
For me it will be perfect to activate the venv in my own Dockerfile with masterlinter as base image. Didn't think of that thanks!

**Comment by neatcoder** [comment]
umm, was it really fixed? I recently started to get this error in pylint for my imported packages

**Comment by nvuillam** [comment]
@neatcoder did you try `pip install requirements.txt` or other python installation commands in [PRE_COMMANDS](https://megalinter.io/latest/config-precommands/) ?

**Comment by andrewvaughan** [comment]
> @neatcoder did you try `pip install requirements.txt` or other python installation commands in [PRE_COMMANDS](https://megalinter.io/latest/config-precommands/) ?

I'm battling this now, too. I use `poetry`. I've tried many, many things, including installing Poetry and dependencies in each individual virtual environment (oof).

/oxsecurity/megalinter/discussions/3291
