### ISSUE TITLE
Go revive linter is not work with V1.19

### ISSUE THREAD

**Issue by Malivix** [oxsecurity/megalinter#2031]
**Describe the bug**
When we use mega linter with revive linter it's raise error about generics and another weird thing version is not displayed in output of mega linter for revive (it show `Using [revive v0.0.0]`)

**To Reproduce**

1. Write a code with generics
2. run `npx mega-linter-runner -r v6.13.0` in your local for this project
3. you will see error like this:
```
 Linted [GO] files with [revive]: Found 1 non blocking error(s) - (7.0s)
- Using [revive v0.0.0] https://oxsecurity.github.io/megalinter/6.13.0/descriptors/go_revive
- MegaLinter key: [GO_REVIVE]
- Rules config: [/revive.toml]
- Number of files analyzed: [842]
--Error detail:
/tmp/lint/comet/utils/list.go:14:15: invalid file /tmp/lint/comet/utils/list.go: /tmp/lint/comet/utils/list.go:14:15: expected '(', found '['
```

**Expected behavior**
It should work because that code is working and correct. the other hand the version should be shown there not `Using [revive v0.0.0]`

**Additional context**
OSX with apple chip
node v16.16.0
mega linter v6.13.0 without flavor

**Comment by nvuillam** [comment]
That seems to be a simple parse error

If you run MegaLinter with `LOG_LEVEL: DEBUG` you'll see the exact command line, that will help to identify the difference between your local call and MegaLinter one

**Comment by Malivix** [comment]
so i tried and that cmd have only `-set_exit_status` and other files together:
```
['revive', '-set_exit_status', '-config', '/tmp/lint/revive.toml', '/tmp/lint/account-gateway/cmd/root.go', '/tmp/lint/account-gateway/cmd/serve.go', ... ]
```
so i run again localy 
```
revive -set_exit_status -config revive.toml comet/utils/list.go
```
first one have this output:
```
[revive] CWD: /
[revive] result: 1 /tmp/lint/comet/utils/list.go:14:15: invalid file /tmp/lint/comet/utils/list.go: /tmp/lint/comet/utils/list.go:14:15: expected '(', found '['

Linter version command: ['/go/bin/revive', '-version']
Linter version result: 0 version 1.2.4
```
and second one without any error
config file is same and my local version:
version 1.2.4

**Comment by nvuillam** [comment]
Another difference is absolute path vs relative... or maybe go version ?

About relative path I have a PR on the way but test cases make docker explode and kill the image.... tricky to solve :/

**Comment by Malivix** [comment]
So yes i found the issue it's about golang version 
`go version go1.17.10 linux/amd64`
how i can help to upgrade this in dockerfile?

**Comment by Malivix** [comment]
@nvuillam so i checked the repo and find that alpine version is problem
I have two solutions:

- depend on alpine version different go version are available if you want to install them by `apk` package manager, so we can move docker image to this version `python:3.10.4-alpine3.16` ( i don't know how to do this. is this tag constant or generated ...)
- another solution is compiling last golang version inside dockerfile (usually we do this in lower alpine versions)

let me know how i can help

**Comment by nvuillam** [comment]
@Malivix PR on the way, if CI jobs are ok i'll merge and it will be in next MegaLinter release :)

**Comment by nvuillam** [comment]
@Malivix MegaLinter beta is now based on python:3.10.4-alpine3.16

Please can you chek and confirm you do not have the issue anymore ?

**Comment by nvuillam** [comment]
( now go version is go 1.18.7-r0 )

**Comment by Malivix** [comment]
@nvuillam It seems the problem is fixed
