### ISSUE TITLE
Checkov Version Outdated

### ISSUE THREAD

**Issue by Kurt-von-Laven** [oxsecurity/megalinter#2043]
**Describe the bug**
The latest version of Checkov is presently [2.2.21](https://github.com/bridgecrewio/checkov/releases/tag/2.2.21), while [the version is MegaLinter is 2.1.244](https://oxsecurity.github.io/megalinter/6.13.0/descriptors/repository_checkov/).

**To Reproduce**

1. Navigate to [MegaLinter docs](https://oxsecurity.github.io/megalinter/6.13.0/descriptors/repository_checkov/).

**Expected behavior**
In only a month, Checkov has issued 20 releases, so they are a good candidate for automated releases. We recently transitioned to Renovate to address a similar issue internally, and it wasn't as smooth as I'd expected, but their team was extremely responsive to our bug reports, and we have been quite pleased overall with the reduction in manual labor relative to Dependabot.

**Additional context**
The majority of the time over the past year and a half, we have had to remain pinned to an old version of MegaLinter, because of some issue or another with a single linter, so it can hurt when the bug has been fixed upstream, but the fix hasn't been picked up. With complex enough projects, one ends up with overlapping periods of brokenness that indefinitely block upgrades or disabled linters. This has gradually led me to adopt the opinion that automatic updating should be a blocking prerequisite for addition of new linters to MegaLinter.

**Comment by nvuillam** [comment]
checkov is installed using pip, which has a higher version than the one retrieved in MegaLinter docker image...
I suspect it's because of MegaLinter base python version

**Comment by bdovaz** [comment]
@nvuillam What can we do to unlock this?

**Comment by nvuillam** [comment]
@bdovaz that's right ! They finally solved the issue preventing to upgrade python version, but there is no release onn pip yet
You may ask them for a release date if you want to know exactly when python upgrade will be able to be performed on MegaLinter

**Comment by bdovaz** [comment]
@nvuillam finally!!

https://github.com/jruere/multiprocessing-logging/issues/56#issuecomment-1418167389

**Comment by nvuillam** [comment]
Let's try to finally upgrade base docker image & associated python version ^^

**Comment by nvuillam** [comment]
Fixed by python upgrade :) checkov if now 2.2.341"

**Comment by Kurt-von-Laven** [comment]
Quoting @nvuillam here to correct my original issue description since I had incorrectly assumed that MegaLinter didn't have automated updates set up for Checkov:
> @Kurt-von-Laven checkov upgrade is automated from the beginning, but because of multiprocessing-logging crash with latest python version, it was "blocked" on its higher version compliant with our python version ^^
> Now python has been upgraded, it's all ok :)
