### ISSUE TITLE
Can only use standard as linter for typescript

### ISSUE THREAD

**Issue by KiritoStorm** [oxsecurity/megalinter#2044]
**Describe the bug**
Can't use any other linter for TypeScript then standard.

**To Reproduce**
Here is my startup command from a batch script:
```
docker run --rm -it -v %dir%:/workdir ^
           -e DEFAULT_WORKSPACE=/workdir ^
           -e ENABLE=TYPESCRIPT,CSS ^
           -e ENABLE_LINTERS=TYPESCRIPT_ES,CSS_STYLELINT ^
           -e DISABLE_LINTERS=CSS_SCSS_LINT ^
             oxsecurity/megalinter-javascript
```

**Expected behavior**
With this command I would expect that I can run the TYPESCRIPT_ES linter, but instead it runs standard.
When I remove the enable/language options, it doesn't lint Typescript at all, same thing happens with TYPESCRIPT_PRETTIER.

**Screenshots**

**Additional context**
I like standard, but the problem with standard is you can't adjust the rules, that's the whole sense about it.
There are 2 things that my team want's differently:
- Use [Semicolons](https://standardjs.com/rules.html#semicolons)
- No [space-before-function-paren](http://eslint.org/docs/rules/space-before-function-paren)

So the idea was to use [ESLint with modified standard rules](https://github.com/standard/eslint-config-standard-with-typescript).

### Other ideas:

- I guess with a custom linter we could also use something like [TypeScript ESLint](https://typescript-eslint.io) - or is that already TYPESCRIPT_ES?
- Standard for TypeScript [ts-standard](https://github.com/standard/ts-standard)
- Standard with custom tweaks [standardx](https://github.com/standard/standardx)
- Standard with semicolons [semistandard](https://github.com/standard/semistandard) / [ESLint semistandard](https://github.com/standard/eslint-config-semistandard).

Any ideas what would make the most sense in combination with MegaLinter?

**Comment by KiritoStorm** [comment]
I realized now was the problem was, I have forget to copy the config files. So it's not a bug, but I would be still interested in how the TYPESCRIPT_ES linter works.

**Comment by KiritoStorm** [comment]
I realized the problem was that I forgot to copy the config files.

**Comment by nvuillam** [comment]
All good ? :)

**Comment by KiritoStorm** [comment]
Yes, all good. :)
I was just a bit confused how I should use MegaLinter in combination with the mentioned linters.

It would be cool to have a bit more options in TypeScript, everything is JavaScript based:

- There is no good out of the box solution for TypeScript
  - You can't use other versions from standard. (ts-standard, semistandard...)
- I think it would make sense to support ts-standard or TypeScript ESLint.

[Here](https://typescript-eslint.io/docs/#step-2-configuration) is an example what you can do with TypeScript ESLint (.eslintrc.js), that has worked for me.

**Comment by nvuillam** [comment]
Typescript Eslint is already supported by MegaLinter :)

https://oxsecurity.github.io/megalinter/latest/descriptors/typescript_eslint/

**Comment by KiritoStorm** [comment]
Okay, it's a bit confusing because it looks exactly the same like the [JavaScript ESLint side](https://oxsecurity.github.io/megalinter/latest/descriptors/javascript_eslint/), but it's a different [project site](https://typescript-eslint.io).

So it would be helpful in my opinion to adjust the documentation. :)

**Comment by nvuillam** [comment]
This is the same eslint than for javascript, with typescript targetted eslint plugins :)

**Comment by nvuillam** [comment]
https://typescript-eslint.io/ is the project for eslint plugins made just for typescript ^^

**Comment by KiritoStorm** [comment]
Alright, thank you :)
