### ISSUE TITLE
shellcheck autofix

### ISSUE THREAD

**Issue by rnikoopour** [oxsecurity/megalinter#2049]
Hello All,

I'm unable to figure out how to get shellcheck to patch the code as part of the PR sent by the `megalinter` github action.

As far as I can tell, apply fixes from shell check requires outputting a diff using the `-f diff` flag, then applying the diff with `git apply`.  I am able to generate the diff by setting the appropriate env var to add `-f diff`.  I can see the output in the logs from `megalinter`.

Is there something I am missing that is configurable from within megalinter to auto apply the fixes from shellcheck?

I have the following env vars set for apply fixes:
```
APPLY_FIXES: all
APPLY_FIXES_EVENT: pull_request
APPLY_FIXES_MODE: pull_request
```

I'm getting a PR with changes from one of the other linters/formatters, but the changes from shellcheck don't make it in.

**Comment by nvuillam** [comment]
Please can yo ushare the command line to tell shellcheck to fix issues ?
We'll be glad to configure them in MegaLinter :)

**Comment by rnikoopour** [comment]
Per [this issue](https://github.com/koalaman/shellcheck/issues/1220) there isn't a direct solution inside of `shellcheck`.

However, [this response](https://github.com/koalaman/shellcheck/issues/1220#issuecomment-594811243) has a suggestion of doing:

`shellcheck -f diff <file> | git apply`

Maybe this kind of functionality could be configurable in `megalinter` by passing an environment variable `BASH_SHELLCHECK_GIT_APPLY_DIFF`.

We could write the diffs to a temp file and then run the `git apply` step with those files.

**Comment by nvuillam** [comment]
That's seems doable indeed :)
But to avoid regressions there are some things to check, like for example if it is possible to have multiple output (SARIF mode uses json output so we have to find a way to make work autofix + sarif output)
