### ISSUE TITLE
Upgrade Checkov to 2.2.43 

### ISSUE THREAD

**Issue by ashokm** [oxsecurity/megalinter#2068]
With `oxsecurity/megalinter-security:v6`, Checkov `v2.1.244` is being used.

```
 - Image Creation Date: 2022-11-06T10:21:30Z
 - Image Revision: 5f067f7
 - Image Version: v6
```

The latest [release](https://github.com/bridgecrewio/checkov/releases) of Checkov (at time of writing) is `v2.2.43`.

Can we get MegaLinter updated to make use of this version?

The Python Package of `v2.2.43` is also available: https://pypi.org/project/checkov/

**Comment by Kurt-von-Laven** [comment]
Duplicate #2043.
