### ISSUE TITLE
Prettier does not respect `.prettierignore`

### ISSUE THREAD

**Issue by Yann-J** [oxsecurity/megalinter#2070]
**Describe the bug**

When using one of the prettier linters (e.g. `YAML_PRETTIER` in my case) I noticed that `.prettierignore` does not seem to be respected.

The workarounds are not very satisfactory:

- Specifying the ignore patterns in `YAML_PRETTIER_FILTER_REGEX_EXCLUDE` - but that is a duplication with `.prettierignore` which is needed for e.g. IDE plugins
- Specify the full path to `.prettierignore` in `YAML_PRETTIER_ARGUMENTS: --ignore-path "/tmp/lint/.prettierignore"` - but this would break if the mount folder changes (I couldn't figure out how to use an env var for it).

**To Reproduce**

1. Project with the following file structure:
- bad
  - bad.yaml (content: wrongly-formed YAML)
- good
  - good.yaml (content: proper YAML)
- .mega-linter.yml
- .prettierignore (content: **/bad)
2. Mega-linter config:

```
ENABLE_LINTERS:
  - YAML_PRETTIER
```
4. Run mega-linter (will fail)
5. Add `YAML_PRETTIER_ARGUMENTS: --ignore-path "/tmp/lint/.prettierignore"` and re-run (will succeed)

**Expected behavior**

Ignore file on the project root should be respected

**Comment by nvuillam** [comment]
@Yann-J if you want to use .prettierignore, you can try the following config:

```yaml
YAML_PRETTIER_CLI_LINT_MODE: project   # Will not list files to send them as arguments, but run without file args at the root of the repo
```

**Comment by Yann-J** [comment]
Hey @nvuillam sorry for reopening this one, but after a bit more digging, I figured that `.prettierignore` is still supposed to be respected by the `prettier` CLI when specifying a list of files. The reason it's not being respected within megalinter is that the CLI is being run from a `CWD` of `/` instead of from the workspace root, and I'm not able to figure why or how to change that...

Any insights?

Here's the debug log when run with `YAML_PRETTIER_CLI_LINT_MODE: project` - we can see the `CWD` is my workspace - and `.prettierignore` is respected in this case:

```
[prettier] command: ['prettier', '--check']
[prettier] CWD: /tmp/lint
```

But when run in default (`list_of_files`) mode, the `CWD` is the root - `.prettierignore` is NOT respected in this case, but it is when I run the same command locally from my workspace:

```
[prettier] command: ['prettier', '--check', '/tmp/lint/.mega-linter.yml', '/tmp/lint/.pre-commit-config.yaml', '/tmp/lint/azure-pipelines.yml']
[prettier] CWD: /
```

Looking at [the code](https://github.com/oxsecurity/megalinter/blob/main/megalinter/Linter.py#L902) I'm not entirely sure how/why this happens, but is there a way to force the CLI to run from the workspace?

Thx!

**Comment by nvuillam** [comment]
@Yann-J are you using v7 ?

With v7, list_of_files mode is calles with the current workspace as CWD

**Comment by Yann-J** [comment]
Ah yes indeed, I was still on v6...
Perfect! looks like we can close this one!
