### ISSUE TITLE
Rome support

### ISSUE THREAD

**Issue by infectormp** [oxsecurity/megalinter#2082]
I Would suggest adding [Rome](https://github.com/rome/tools) support to Megalinter

Rome is a formatter, linter, bundler, and [more](https://rome.tools/) for JavaScript, TypeScript, JSON, HTML, Markdown, and CSS.

**Comment by nvuillam** [comment]
For the moment it is JS/TS only, but providing an alternative to eslint, prettier and standard can be interesting, especially if the performances are better :)

![image](https://user-images.githubusercontent.com/17500430/201726346-b1e68c5f-8469-4155-b5de-dcf25b2b8a99.png)

Only formatter and linter would be used, and bundling is not the job of MegaLinter ^^

Do you know if there are commands that can format and lint in an unique call ?

**Comment by infectormp** [comment]
> Do you know if there are commands that can format and lint in an unique call ?

Sorry, I don't know about such commands.

**Comment by nvuillam** [comment]
cc @EtienneDeneuve :)
