### ISSUE TITLE
[NEW LINTER] Add support for npm-package-json-lint

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [oxsecurity/megalinter#2092]
It would be nice to have configurable support for [https://npmpackagejsonlint.org/](https://npmpackagejsonlint.org/)

**Comment by nvuillam** [comment]
this linter seems useful and the repo is maintained, so I would accept a PR :)

It could probably be an update of [JSON descriptor](https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/json.megalinter-descriptor.yml), with additional property `active_only_if_file_found: ["package.json"]`

**Comment by AndreaPontrandolfo** [comment]
Currently being worked on. Definitly shouldn't be stale.

**Comment by bdovaz** [comment]
Included in v6.16.0
