### ISSUE TITLE
Incorrect configuration key values and missing text and icons on doc pages

### ISSUE THREAD

**Issue by ashokm** [oxsecurity/megalinter#2109]
Note that at time of writing, the 'latest' version is 'v6.15.0'.

On multiple doc pages, there seems to be incorrect configuration keys and on some pages missing icons and text.

For example:

Missing text and icon in https://oxsecurity.github.io/megalinter/latest/flavors/ci_light/:
![image](https://user-images.githubusercontent.com/1902568/202895154-232bbf33-2f5d-4e4c-a116-5e180c18424a.png)

![image](https://user-images.githubusercontent.com/1902568/203287981-9f752951-7b0b-4846-bce2-58d153dec2e8.png)

Incorrect configuration keys in https://oxsecurity.github.io/megalinter/latest/descriptors/repository/:
![image](https://user-images.githubusercontent.com/1902568/202895390-8fac6136-12b9-4456-b5d5-98602d1cd6a2.png)

https://oxsecurity.github.io/megalinter/latest/descriptors/ansible/ also shows the configuration key as `ANSIBLE` instead of `ANSIBLE_ANSIBLE_LINT`.

Here are some others with the same issue (not an exhaustive list, but hopefully this helps when debugging):

- https://oxsecurity.github.io/megalinter/latest/descriptors/yaml/
- https://oxsecurity.github.io/megalinter/latest/descriptors/json/
- https://oxsecurity.github.io/megalinter/latest/descriptors/xml/
- https://oxsecurity.github.io/megalinter/latest/descriptors/groovy/

Whereas on other pages, such as https://oxsecurity.github.io/megalinter/latest/descriptors/dockerfile/ and https://oxsecurity.github.io/megalinter/beta/descriptors/bash/, https://oxsecurity.github.io/megalinter/latest/descriptors/terraform/, the configuration key is correctly displayed.

**Comment by nvuillam** [comment]
Thanks for reporting, it's probably something from the (too big) [build.py](https://github.com/oxsecurity/megalinter/blob/main/.automation/build.py) script :/
