### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by alexberrios** [oxsecurity/megalinter#2112]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_PYLINT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_BANDIT, PYTHON_MYPY, PYTHON_PYRIGHT, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, COPYPASTE_JSCPD, DOCKERFILE_HADOLINT, JAVASCRIPT_STANDARD, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MAKEFILE_CHECKMAKE, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, OPENAPI_SPECTRAL, REPOSITORY_CHECKOV, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY, SPELL_MISSPELL, SPELL_CSPELL, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
Probbably you can try Cupcake flavor ? https://megalinter.io/latest/flavors/cupcake/
I think the only missing linter in such flavor is OPENAPI_SPECTRAL, do you really need it ?
