### ISSUE TITLE
Salesforce SFDX regex re.compile error breaks Github action

### ISSUE THREAD

**Issue by marco-audibene** [oxsecurity/megalinter#2118]
**Describe the bug**
I am trying to use MegaLinter GitHub action in `pull_request` creation and it gives a parsing failing on sfdx-cli. 

_Error messages:_
```
Unable to extract version with regex re.compile('(?<=@salesforce/sfdx-scanner )\\d+(\\.\\d+)+') from  ›   Warning: sfdx-cli update available from 7.178.0 to 7.179.0.
You acknowledge and agree that the CLI tool may collect usage information, user environment, and crash reports for the purposes of providing services or functions that are relevant to use of the CLI tool and product improvements.
```
The issue is that the `sfdx-scanner` does not work as it does not scan the files to analyse which it is supposed to ( it returns nothing but the green check).

**To Reproduce**
- Go to megalinter results
- Click on logs
- Scroll down to SALESFORCE_SFDX_SCANNER_APEX results
- See error no plugins installed (screenshot attached)

**Expected behavior**
No parsing error, and SALESFORCE_SFDX_SCANNER_APEX should scan the file reporting the violation.

**Screenshots**
![image](https://user-images.githubusercontent.com/81997403/205274992-c176d6c1-4dda-4e1c-8074-30835eb9da2a.png)

**Additional context**
While running locally it works, so it must be a GitHub action issue.

**Comment by marco-audibene** [comment]
Similar error was reported in [Salesforce SFDX CLI Update message confuses the regex parser](https://github.com/oxsecurity/megalinter/issues/1398)

**Comment by nvuillam** [comment]
It finds no sfdx plugins installed, that's quite intriguing...

Do you have the same issue with MegaLinter beta version ?

**Comment by marco-audibene** [comment]
> It finds no sfdx plugins installed, that's quite intriguing...
> 
> Do you have the same issue with MegaLinter beta version ?

@nvuillam yes same issue with MegaLinter beta version as well.

**Comment by marco-audibene** [comment]
@nvuillam adding comments to this issue as the bot closed it.
