### ISSUE TITLE
HTML email not rendering correctly

### ISSUE THREAD

**Issue by ashokm** [oxsecurity/megalinter#2120]
When using the [Azure Comment Reporter](https://github.com/oxsecurity/megalinter/blob/7afc354a10e696cec1c7985b4c1537261286071d/docs/reporters/AzureCommentReporter.md#configuration) to receive Pull Request and Email notifications, the Pull Request comments are being shown correctly, but the Email does not render the bold text or image correctly.

---

**Pull Request:** ✅
![image](https://user-images.githubusercontent.com/1902568/205639034-8b1f42ea-bc5d-4587-827d-b15b70c3ddd2.png)

**Email:** ❌
![image](https://user-images.githubusercontent.com/1902568/205639069-f85e92cb-4fb3-46d1-b300-b9056815832d.png)

---

**Version:**
```
 - Image Creation Date: 2022-11-23T22:14:25Z
 - Image Revision: d8612e7
 - Image Version: v6
```

**Comment by nvuillam** [comment]
@ashokm maybe Azure emails does not allow to display images externally stored ?

markdown is the following and seems correct:

 `_MegaLinter is graciously provided by [![OX Security](https://www.ox.security/wp-content/uploads/2022/06/logo.svg?ref=megalinter_comment)](https://www.ox.security/?ref=megalinter)_`

**Comment by nvuillam** [comment]
Got it, it seems markdown to email routine of Azure does not like some elements of Github Flavored Markdown

PR on its way, I simplified it, and added an option `REPORTERS_MARKDOWN_TYPE`,  to set to `simple` to avoid external images in PR/MR markdown comments.

**Comment by nvuillam** [comment]
@ashokm you can now test with MegaLinter beta + `REPORTERS_MARKDOWN_TYPE: simple`
