### ISSUE TITLE
golangci-lint giving "named files must all be in one directory" error

### ISSUE THREAD

**Issue by renxinhe** [oxsecurity/megalinter#2126]
**Describe the bug**

I enabled `golangci-lint` in our mono-repo, and I'm receiving a "named files must all be in one directory" error. All the megalinter config for golangci-lint is default as shown [in the mega-linter golangci-lint config page](https://megalinter.io/latest/descriptors/go_golangci_lint/).

The go linter was able to recognize all the *.go files, but still errored out:

```
❌ Linted [GO] files with [golangci-lint]: Found 1 error(s) - (0.35s)
- Using [golangci-lint v1.50.1] https://megalinter.io/latest/descriptors/go_golangci_lint
- MegaLinter key: [GO_GOLANGCI_LINT]
- Rules config: [/.golangci.yml]
- Number of files analyzed: [112]
--Error detail:
level=error msg="[linters_context] typechecking error: named files must all be in one directory; have /tmp/lint/mp/cmd/app/ and /tmp/lint/mp/config/"
```

For context, our repo is setup using the following structure, and I'm running mega-linter from the "repo/" directory.
```
repo/
  mp/
    cmd/app/
        main.go
    config/
        config.go
    .../
```

I could reproduce this error message if I run golangci-lint with the following arguments (simulating "list_of_files" mode):
```bash
repo$ golangci-lint run mp/cmd/app/main.go mp/config/config.go 
ERRO [linters context] typechecking error: named files must all be in one directory; have mp/cmd/app and mp/config 
```

**To Reproduce**

I simply enabled `golangci-lint ` in my ".mega-linter.yml" file, and ran it locally in bash:
```bash
repo$ mega-linter-runner
```

**Expected behavior**

Running golangci-lint locally _from the "repo/mp" directory_ without_ mega-linter passes:
```bash
repo/mp$ golangci-lint run ./...
<no output if successful>
```

**Ultimately, I'd like a way to run `golangci-lint run ./...` from the child directory "repo/mp/" even when mega-linter is ran from its parent directory "repo/".** How could I do this with the existing mega-linter configs?

**Comment by nvuillam** [comment]
You may try the following config:

```yaml
GO_GOLANGCI_LINT_CLI_LINT_MODE: project
GO_GOLANGCI_LINT_ARGUMENTS: ["./.."]
```

**Comment by janderssonse** [comment]
What worked for me:

GO_GOLANGCI_LINT_CLI_LINT_MODE: project 
GO_GOLANGCI_LINT_ARGUMENTS: ["run","./..."]
