### ISSUE TITLE
[flavor] add Makefile lint to documentation layer

### ISSUE THREAD

**Issue by practicalli-john** [oxsecurity/megalinter#2130]
**Is your feature request related to a problem? Please describe.**
I use `Makefile` tasks to generate technical documentation with MkDocs, although the documentation flavour does not currently support a linter for the `Makefile`

A Makefile task is used to generate a site with MkDocs and set a specific port for each project to locally server the resulting website, so more than one book can be worked on at once.

The Makefile also runs the `mega-linter-runner` with the specific flavor and passing a custom configuration

**Describe the solution you'd like**
Add MAKEFILE_CHECKMAKE linter to the documentation flavour (in a similar way to #1911 I assume)

**Describe alternatives you've considered**
Alternative would be to add Markdown linter support to the `ci_light` flavor (with spell check done via an editor as this flavor has not spell support)  

**Additional context**
I write a lot of tech docs and am using MkDocs with a Makefile on many open source technical books I've been writing for https://practical.li/

**Comment by nvuillam** [comment]
on the way :)
