### ISSUE TITLE
Why does the EXTENDS value have to be a url?

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2146]
I want in the same directory to have:

Base configuration:

.megalinter-base.yml

Both files use base configuration:

.megalinter-use-case1.yml
.megalinter-use-case2.yml

The 3 files are in the same directory but in none of the last 2 I can put:

EXTENDS: .megalinter-base.yml

I have to put a url necessarily.

Why?

**Comment by nvuillam** [comment]
`EXTENDS` property has been created to share a base MegaLinter configuration between repos :)

What is the use case that requires `EXTENDS` to target a local file ?

If you really need it, you can make a PR and add a condition `if extends_item.startswith("http"): .... else: ....` here :) https://github.com/oxsecurity/megalinter/blob/c13e920cea92c5276c1d25befe1d5b9561819c84/megalinter/config.py#L79

**Comment by bdovaz** [comment]
I have created a PR

My use case is that I want to have several Azure pipelines, each one with a different execution of megalinter due to the fact that there are some linters that take a long time to execute (the REPOSITORY ones that have lint_mode project) and I want to have a lighter .megalinter.yml and another complete one that executes at night. The 2 share practically everything so I want to use EXTENDS and repeat as little as possible.

**Comment by nvuillam** [comment]
That's indeed a good use case !

**Comment by nvuillam** [comment]
Fixed by #2151
