### ISSUE TITLE
Replace flake8/isort with Ruff

### ISSUE THREAD

**Issue by schorlton** [oxsecurity/megalinter#2153]
[Ruff](https://github.com/charliermarsh/ruff) seems like almost a drop-in replacement for flake8/isort, at 10X the speed and with additional features. It would also likely make images smaller. Would be great to replace these tools - thanks for your consideration!

**Comment by nvuillam** [comment]
As users already have their isort/flake8 config, we can't remove them without adding a breaking change, but Ruff could be added as an additional linter :)
