### ISSUE TITLE
Formatting powershell files with PSScriptAnalyzer

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2157]
There is an **Invoke-Formatter** function that expects to receive the contents of the file and returns the contents of the formatted file.

More information:

https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-formatter?view=ps-modules

@nvuillam How difficult would it be to implement? I see the linter implementation is here:

https://github.com/oxsecurity/megalinter/blob/v6.15.0/megalinter/linters/PowershellLinter.py

**Comment by nvuillam** [comment]
You could add an entry powershell_formatter in powershell descriptor: https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/powershell.megalinter-descriptor.yml

Some linters like powershell as complex so require a python class to build commands, so you may have to also create a PowershellFormatter class following the same model than [PowershellLinter class ](https://github.com/oxsecurity/megalinter/blob/main/megalinter/linters/PowershellLinter.py) ( or update PowershellLinter to add conditions using self.linter_name )

**Comment by bdovaz** [comment]
But apart from all that you have to create a logic to read and replace the contents of the file, right? Because that method expects the input of the file content and returns a string with the formatted content of the file. That is, it does not touch the file itself.

**Comment by nvuillam** [comment]
> But apart from all that you have to create a logic to read and replace the contents of the file, right? Because that method expects the input of the file content and returns a string with the formatted content of the file. That is, it does not touch the file itself.

This formatter is not able to format the files by itself ? :o

**Comment by bdovaz** [comment]
> This formatter is not able to format the files by itself ? :o

As you can see... No.

![image](https://user-images.githubusercontent.com/950602/208997438-f3f0e5a8-cfae-4c75-9b79-dccd26c26db7.png)

![image](https://user-images.githubusercontent.com/950602/208997585-d1f416a7-d5b1-4413-a24e-be3c1de19f2c.png)

**Comment by nvuillam** [comment]
That's a shame ^^
So it will require an update of core MegaLinter ^^
Maybe just an override of execute_lint_command ?

**Comment by Kurt-von-Laven** [comment]
Is it possible to override the file contents by piping the output of `Invoke-Formatter` back over the input file?

**Comment by bdovaz** [comment]
> That's a shame ^^ So it will require an update of core MegaLinter ^^ Or maybe just an override of execute_lint_command ? There is a similar issue with shellcheck

I understand that if there is any other case, as you mentioned, the logical thing to do is to solve it at another level so that both can take advantage of the solution and in the future if there is any other case, then also.

> Is it possible to override the file contents by piping the output of `Invoke-Formatter` back over the input file?

I don't have enough powershell scripting experience to answer that question 😅

**Comment by Kurt-von-Laven** [comment]
PowerShell supports many Bashisms these days, such as [`>`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection?view=powershell-7.3#long-description).

**Comment by echoix** [comment]
Before jumping to conclusions, let's take a second look at their docs and their repo. It's inconceivable that it works only like that.

So, I've taken a look, and it looks like it does indeed work as we expect of a linter. It is possible to specify a path, it mentions CI usage where the EnableExit has its exit code with the number of error records, and some rules can also fix the file. 

https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-scriptanalyzer?source=recommendations&view=ps-modules

The string input is only one way of using it, and corresponds to the example 9 of that same page.

**Comment by bdovaz** [comment]
@echoix we are speaking about Invoke-Formatter function:

https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-formatter?view=ps-modules

**Comment by bdovaz** [comment]
There is also -Fix in Invoke-ScriptAnalyzer, but with a different purpose:

https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-scriptanalyzer?view=ps-modules#-fix

One I understand is for code style formatting (Invoke-Formatter) and the other somehow corrects certain rules (Invoke-ScriptAnalyzer -Fix).

**Comment by nvuillam** [comment]
So its seems Microsoft linters developers have strange habits about fixing... :)

Does it also mean that linter formatting/fixes must be done file by file ? :o (too bad for performances ! )

I asked directly on the repo, let's see if someone can help us :) https://github.com/PowerShell/PSScriptAnalyzer/issues/1878

**Comment by bdovaz** [comment]
What do you all think? What do we do?

https://github.com/PowerShell/PSScriptAnalyzer/issues/1878#issuecomment-1362220974

**Comment by nvuillam** [comment]
I propose:
- add `-Fix` option on existing PSScriptAnalyzer (can be done in PowershellLinter.py by checking `self.apply_fixes is True` (requires also to define cli_lint_fix_arg_name: '-Fix` in descriptor)
- About formatting, my knownledge of Powershell scripting is close to zero... but it's probably possible to do something by defining POWERSHELL_FORMATTER linter + overriding methods on PowershellLinter.py

You seem to be very active these days, if you have available time the PRs are yours ^^

**Comment by echoix** [comment]
I suggest taking a look at this thread: https://github.com/PowerShell/PSScriptAnalyzer/issues/775

One of the issues that kinda sucks for all possibilities, is that there seems to be problems with keeping the original encoding of a file, if we do things naively. Either us, by wrapping the formater, or them, with the -Fix in the scriptanalyzer. Are we ready to impose an assumption for users on the output file type encoding (without warning)? Even the upstream project seem to accept it for the -Fix option. 


What I was thinking for just getting the Invoke-Formatter to work, is instead of coding some new Python, to just specify in the command to run an extra read and write (Get-Content, Set-Content for PowerShell). 
In the thread linked, there are a couple examples, like this for comparing if there is a change:
https://github.com/PowerShell/PSScriptAnalyzer/issues/775#issuecomment-397505757
Or this to read and write
https://github.com/PowerShell/PSScriptAnalyzer/issues/775#issuecomment-644664204

With the -Recurse, this corresponds roughly to our "folder" mode. I'm not really concerned about performance here, because I suspect that a little power shell script will be faster than Python code. PowerShell, especially since à loop would be jitted.

For a single file mode, it could be closer to this (but with an added Set-Content, and we add the path): 
https://github.com/PowerShell/PSScriptAnalyzer/issues/775#issuecomment-367455802

For a list of files mode, I was thinking that a solution could could be by using array splatting ([docs here](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.3#splatting-with-arrays)), to receive the list of files and to use a simple foreach to dispatch to the function, similarly I the preceding examples.

**Comment by bdovaz** [comment]
@echoix I am working on it since yesterday: https://github.com/oxsecurity/megalinter/pull/2176/

**Comment by Kurt-von-Laven** [comment]
> Are we ready to impose an assumption for users on the output file type encoding (without warning)? Even the upstream project seem to accept it for the -Fix option.

Personally, I find this acceptable on the basis that MegaLinter aggregates many linters, and they each have varying degrees of limitations. If someone doesn't want to use a linter that works in an undesirable way, they are encouraged to work with that project to enhance its functionality and/or disable it in the meantime. We have used PSSA without issue for quite a while, and we use pre-commit hooks to enforce the [file encoding](https://github.com/pre-commit/pre-commit-hooks/blob/f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9/README.md#fix-byte-order-marker), [line endings](https://github.com/pre-commit/pre-commit-hooks/blob/f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9/README.md#mixed-line-ending). and [terminal newline](https://github.com/pre-commit/pre-commit-hooks/blob/f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9/README.md#end-of-file-fixer). We also use [`.gitattributes`](https://git-scm.com/docs/gitattributes) and [`.editorconfig`](https://editorconfig.org/) files, which have some overlapping features. Clearly changing the output encoding without warning is not a desirable behavior, but it's straightforward and low effort to cope with, and PSSA offers many valuable features. The bad behavior is, admittedly, potentially confusing to detect, so it may be worth documenting on our end.

No strong opinion given my lack of PowerShell experience, but @echoix's suggestion of following the upstream repository's recommended PowerShell invokations seems likely to result in the simplest, most robust implementation. I see @bdovaz is invoking PowerShell from a short, simple Python script in their draft PR, which seems fine too.

**Comment by nvuillam** [comment]
Released in v6.17.0 :)
