### ISSUE TITLE
Config file is not found when mega-linter-runner is run locally

### ISSUE THREAD

**Issue by vegardhw** [oxsecurity/megalinter#2170]
I have a locally cloned repository and want to run mega-linter-runner manually on different folders before commit and PR on GitHub. I notice that the repository .mega-linter.yml is not picked up and used. Hence this message in mega-linter-runner startup log:

`[config] Environment variables only (no config file found in /tmp/lint)`

How can I force the use of existing .mega-linter.yml file with mega-linter-runner?

**Comment by vegardhw** [comment]
Solution 1 is the one that I tried myself. Should have mentioned that in the first place :) I am using the command "mega-linter-runner -p subfolder-to-check --remove-container". I notice that the megalinter-reports directory is created in that same targeted subfolder. Seems like it is running at root level from that subfolder after all...?

**Comment by nvuillam** [comment]
Yes, once MegaLinter starts from a folder, it can not go to upper ones because they are not accessible from docker volumes ^^

**Comment by vegardhw** [comment]
Ok. I guess as a workaround I can run from root level (without -p subfolder) and target subfolder only with FILTER_REGEX_INCLUDE parameter.

**Comment by nvuillam** [comment]
> Ok. I guess as a workaround I can run from root level (without -p subfolder) and target subfolder only with FILTER_REGEX_INCLUDE parameter.

It will work with linters using a list of files, but for linters running from the root folder it will take in account all folders under the root
