### ISSUE TITLE
SPELL_CSPELL_ANALYZE_FILE_NAMES missing in .mega-linter.yml schema

### ISSUE THREAD

**Issue by mbelangergit** [oxsecurity/megalinter#2178]
**Describe the bug**
While trying to workaround #2148 until release by setting `SPELL_CSPELL_ANALYZE_FILE_NAMES: false` in `.mega-linter.yml`, this addition in my `.mega-linter.yml` makes its own validation fail (by v8r).

**To Reproduce**

1. Add `SPELL_CSPELL_ANALYZE_FILE_NAMES: false` in `.mega-linter.yml`
2. Run MegaLinter (lint `.mega-linter.yml` using v8r)
4. See the invalid message

**Expected behavior**
The schema validation should pass

**Screenshots**

![image](https://user-images.githubusercontent.com/56379077/209406120-c7593afe-10f0-4478-b1b6-5169509d48f7.png)

![image](https://user-images.githubusercontent.com/56379077/209406562-0d0432c1-4d5c-433e-90b4-24c78bd5eacd.png)

**Additional context**
I also see the schema validation error in VS Code's Ret Hat YAML extension.

**Comment by mbelangergit** [comment]
On a side note, I found the existence of the new feature of spell checking the files (and folders) names today by testing how I can use MegaLinter in Azure DevOps. I'm using the container as described in the documentation on a sample repo that I have.

I have a sub folder called `adrs` holding some Architecture Decision Records (ADRs). `adrs` made the build fail. (I know, I can just rename my folder like most repos, storing their ADRs in a `adr` folder :wink:)
![image](https://user-images.githubusercontent.com/56379077/209408872-8bd74179-aaa5-4fe9-8b39-5b65dfa53816.png)

I have the exact same content in another GitHub repo (same content outside GitHub workflows vs Azure pipelines).

With both repos using MegaLinter v6.15.0, the failing spell check on folder name was raised only in the Azure pipeline. On the GitHub side, the "bad" folder name was not not flagged using the GitHub action. 

I may do some more tests and create another issue for that.

**Comment by nvuillam** [comment]
Good catch, json schema has been updated :)
