### ISSUE TITLE
kubeval no longer mantained

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2197]
https://github.com/instrumenta/kubeval/blob/master/README.md

It suggest using kubeconform which is already added in Megalinter as another linter.

@nvuillam what do you usually do in these cases? Leave it or remove it?

**Comment by nvuillam** [comment]
We can flag it as deprecated and disable it by default, but keep it available until the next major version :)

**Comment by bdovaz** [comment]
And how is that done? I mean, do you have a case where something similar has been done to see an example?

**Comment by nvuillam** [comment]
Here is an example PR :) 

https://github.com/oxsecurity/megalinter/pull/1692

**Comment by bdovaz** [comment]
@nvuillam I just looked at it but I see that the only thing that has been done is to put in "linter_text" a text saying that it is deprecated and with the recommendation.

But apart from that, wouldn't it be interesting in the schema of the linters to add a "deprecated: true" to be able to build in the scripts that generate markdown docs some kind of badge to indicate this in a clearer way?

Apart from that "deprecated" maybe add also a "deprecated_text" so that it can be created with markdown a kind of special warning box to be able to put a text like the one you have put of that PR that gives an alternative?

**Comment by bdovaz** [comment]
@nvuillam what do you think about the "deprecated" and "deprecated_text" fields I mention in the previous message? https://github.com/oxsecurity/megalinter/issues/2197#issuecomment-1367786660

If you give the go ahead I can start working on the PR these days.

**Comment by nvuillam** [comment]
@bdovaz ok for me, deprecated & deprecated text can be used in doc and even in reports to warn users :)
