### ISSUE TITLE
Improve the documentation of cli_lint_mode

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2202]
@nvuillam There are linters that support more than one mode such as:

https://github.com/oxsecurity/megalinter/blob/v6.17.0/megalinter/linters/JavaPmdLinter.py#L38

On the other hand, the "cli_lint_mode" field only supports one value and not N:

https://github.com/oxsecurity/megalinter/blob/v6.17.0/megalinter/descriptors/java.megalinter-descriptor.yml#L76

"cli_lint_mode" should be an array (and rename it to "cli_lint_modes") and add the modes supported (apart from another "cli_lint_mode_default" or similar)?

```yaml
cli_lint_modes:
  - file
  - list_of_files
  - project
cli_lint_mode_default: list_of_files
```

In the code that generates the documentation it assumes that if it is not of type "project" it will support everything and it does not have to:

https://github.com/oxsecurity/megalinter/blob/v6.17.0/.automation/build.py#L1246

The documentation should be generated based on what is in the descriptor. Right now it is misleading.

If you set "*_CLI_LINT_MODE" in a linter to a value that is not supported by the linter, what happens? Is there any code that controls this?

**Comment by nvuillam** [comment]
@bdovaz there is already a doc page about it :) https://megalinter.io/latest/configuration/#cli-lint-mode

It is not something usual to override cli_lint_mode, this mode is mainly for internal use :)

If a linter is defined with cli_lint_mode: project, it can not be overriden to file or list_of_files, or to from file to list_of_files -> https://github.com/oxsecurity/megalinter/blob/d2b1417774be5df5b9b263e7b80d72337d62fcd3/megalinter/Linter.py#L564

**Comment by bdovaz** [comment]
@nvuillam looking at that documentation (https://megalinter.io/latest/configuration/#cli-lint-mode) I see that:
1. if "cli_lint_mode: project" can be changed neither to file nor to list_of_files.
2. It does not explain that if "cli_lint_mode: file" can not be changed neither to list_of_files nor to project (in fact, this last one is not controlled in the code that you have put me, I understand that it is a bug...).

For example: https://megalinter.io/latest/descriptors/bicep_bicep_linter/#readme

It has "cli_lint_mode: file" in its descriptor but according to that documentation in the field "BICEP_BICEP_LINTER_CLI_LINT_MODE" it says that you can put any of those 3 values when it is not true.

![image](https://user-images.githubusercontent.com/950602/210112390-138468ae-62e9-4a00-a7ee-b584ef8a9df0.png)

That's why I still think 2 things can be done:
1. The logic that you have put (https://github.com/oxsecurity/megalinter/blob/d2b1417774be5df5b9b263e7b80d72337d62fcd3/megalinter/Linter.py#L564) apply it to the description field of each "*_CLI_LINT_MODE", that is to say, if for example it has declared "cli_lint_mode: file" that in the description field omits the phrases references to list_of_files or project.
2. Contemplate cases like JavaPmdLinter (I don't know if there are more) that contemplate more than one different lint_mode. Right now according to the code you have given me, it is assumed that if "cli_lint_mode: list_of_files" will support all 3 modes but it doesn't have to, there are CLIs of certain linters that maybe only support passing N files but not a directory.

**Comment by nvuillam** [comment]
1. Indeed, the JSON Schema + the doc should reflect the capabilities , it something that can be done in build.py :)

2. Most of linters work without file/folder arguments , and that it is how they are called with `cli_lint_mode: project`. Special cases are indeed not taken in account, but... workaround is possible with **_ARGUMENTS, and again, MegaLinter aims to provide linter calls in the most efficient way, so investing time to make all modes work for all linters is clearly not a priority ^^
