### ISSUE TITLE
Bypass file_contains_regex

### ISSUE THREAD

**Issue by louisLaporte** [oxsecurity/megalinter#2217]
I am using PERL_CRITIC linter and I would like to bypass the file_contains_regex variable. I don't know if there are any ways to achieve that using variables in .mega-linter.yml.
In https://github.com/oxsecurity/megalinter/blob/main/megalinter/utils.py#L63 there are 2 filters, by file extension and by shebang regex (in Perl context).
I don't get the reason why both filters are applied. Should it be better to get a condition for matching files like bellow?
```
for file in all_files:
    ....
    for file_extension in file_extensions:
        if not file_extension:
            # Check using file_contains_regex
        # Check using file_extension
```

**Comment by nvuillam** [comment]
This has been implemented like that because perl files can be defined in files without extensions, and the shebangs allows to identify the perl files within all those files without extension.

https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/perl.megalinter-descriptor.yml

I think the correct way would be to check the shebang only if files without extension, not for the files with extension .pl / .pm / .t ?

**Comment by louisLaporte** [comment]
Yes I do agree.

**Comment by louisLaporte** [comment]
Tested your branch on my side. It fix as expected the behavior.

Maybe another interesting point will be to use mime type(using https://pypi.org/project/python-libmagic/) instead of file extensions and shebang regex.

**Comment by nvuillam** [comment]
Thanks for the testing and the feedback :)

Using MimeType seems interesting, but very few linters use file content to know if a file must be kept for analysis or not, so I'm afraid that calling such lib on all found files would decrease performances (and there are also [other filtering criteria](https://github.com/oxsecurity/megalinter/blob/519be34b9312aeaf0dc808aa59e555f87851e835/megalinter/utils.py#L63))

**Comment by nvuillam** [comment]
PR merged, available in beta version in 30 mn :) (less for flavors)

**Comment by louisLaporte** [comment]
Thanks for your answer (makes sens)
