### ISSUE TITLE
Broken links to descriptors & linters in latest version doc

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#2234]
![image](https://user-images.githubusercontent.com/17500430/211175499-56d6f8c4-5d92-452d-bf37-75b206ac9e90.png)

![image](https://user-images.githubusercontent.com/17500430/211175504-28af0f2b-0d55-483e-a817-8a1df57c5305.png)

**Comment by bdovaz** [comment]
@nvuillam The latest version (6.18.0) is missing, isn't it?

![image](https://user-images.githubusercontent.com/950602/211198389-b0afccea-618b-46ee-b4c8-755d0da3bf3d.png)

**Comment by nvuillam** [comment]
It is latest :)

**Comment by nvuillam** [comment]
(better for SEO to have fix urls ^^)

**Comment by nvuillam** [comment]
Fixed directly in gh-pages :)
