### ISSUE TITLE
Support --format with xmllint

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2240]
@nvuillam has not raised this issue so far?

It looks like you can at least configure the indent with the `XMLLINT_INDENT` environment variable:

https://gnome.pages.gitlab.gnome.org/libxml2/xmllint.html

**Comment by nvuillam** [comment]
- I didn't know it was possible ... but i didn't check, xmllint is inherited from super-linter who can not apply updates

Maybe we should allow it but disable it by default?

**Comment by bdovaz** [comment]
@nvuillam Questions:
1. How do I disable it by default? In the descriptor I have added `cli_lint_fix_arg_name: "--format"`.
2. The environment variable `XMLLINT_INDENT` (string) is the one that controls the number of spaces:
    * How can I configure the linter so that this setting can be passed to it like any other linter configuration?
    * A class is needed for this, isn't it? Like a XmlLintLinter.py in order to redirect this configuration to this process

**Comment by nvuillam** [comment]
1. The current architecture does not allow to do that :D We have to think about it... maybe an additional variable XML_XMLLINT_AUTOFORMAT , that could be used in XmlLintLinter.py

2 descriptors allow to define custom variables :)
They will appear in the doc after build.sh --doc, but I'm not sure if it also updates JSON schema (in that case it must be done manually)

Example: https://github.com/oxsecurity/megalinter/blob/c5561aa7a644977620f16ee6d30278513adab1e6/megalinter/descriptors/spell.megalinter-descriptor.yml#L38
