### ISSUE TITLE
Powershell formatter formats even with APPLY_FIXES: none

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2241]
@nvuillam If I'm not mistaken, if that's not established, I shouldn't write anything, right? Or is it that formatters always write regardless of the value of APPLY_FIXES?

The way it's done it always writes the file, it would have to take into account the value of APPLY_FIXES, right? That is, here:

https://github.com/oxsecurity/megalinter/blob/main/megalinter/linters/PowershellLinter.py#L33

And depending on that value, it makes the pipe or not to the file that we follow here with respect to the pipe #2239

**Comment by nvuillam** [comment]
I think line 36 should be removed

![Screenshot_20230109-202849.png](https://user-images.githubusercontent.com/17500430/211391752-60ef03e8-5df7-414f-81c1-8a6a104ffa0b.png)

**Comment by bdovaz** [comment]
But Powershell Formatter does not have the `cli_lint_fix_arg_name` parameter defined so it will not go there anyway:

https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/powershell.megalinter-descriptor.yml

**Comment by nvuillam** [comment]
So you can add another condition with a elif: :)

**Comment by bdovaz** [comment]
@nvuillam I think I still don't understand you, the code currently looks like this:

![image](https://user-images.githubusercontent.com/950602/211404343-aa04c511-d561-4a2a-be0f-3206e2a888c0.png)

What do you want it to do? That condition the only thing that controls is to add or not the parameter of `cli_lint_fix_arg_name` but as I have already said to you, in the case of Powershell formatter, that parameter does not exist.

**Comment by nvuillam** [comment]
if self.linter_name == 'powrshell"
.......
elif self.linter_name == "powershell_linter"
......

:)

**Comment by bdovaz** [comment]
@nvuillam yes I understand that, what I don't understand is what you want me to put in the `elif` (the powershell formatter case) if there is no `cli_lint_fix_arg_name` which is what is added inside that `if` currently.

**Comment by nvuillam** [comment]
@bdovaz plz can you show me examples for command for 

- call powershell just to check if the formatting is ok, without applying it
- call powershell to apply formatting

**Comment by bdovaz** [comment]
@nvuillam as I said, this `Invoke-Formatter` command is "weird" in the fact that it expects the contents of a file and returns the contents of the formatted file.

Example from the documentation:

```powershell
$scriptDefinition = @''
function foo {
"hello"
  }
'@

Invoke-Formatter -ScriptDefinition $scriptDefinition
```

Source: https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-formatter?view=ps-modules#example-1-format-the-input-script-text-using-the-default-settings

That's why in the [linter code](https://github.com/oxsecurity/megalinter/blob/main/megalinter/linters/PowershellLinter.py#L33) we had to read the contents of the file and pipe to the file itself.

An example of just running it without writing to the file:

```powershell
Invoke-Formatter -ScriptDefinition (Get-Content -Path '$file' -Raw)
```

Writing to the file:

```powershell
Invoke-Formatter -ScriptDefinition (Get-Content -Path '$file' -Raw) > '$file'
```

**Comment by nvuillam** [comment]
@bdovaz , so can the if then elif manage such case ?

Maybe we could refactor the whole methode to have only one if by linter, it would add some copy pastes but i think it would be easier the maintain than to have multiple if linter then elif formatter etc....

**Comment by bdovaz** [comment]
@nvuillam I think I fixed it in this commit, no?

https://github.com/oxsecurity/megalinter/pull/2239/commits/ba2e214ea8e4b9014fa78bbdd3d4c03511b1c0c3

![image](https://user-images.githubusercontent.com/950602/211618678-1696d301-384c-45c7-851d-6f70c7f568a1.png)
