### ISSUE TITLE
Error when running on fresh install with a sudo-protected docker executable:

### ISSUE THREAD

**Issue by nicain** [oxsecurity/megalinter#2246]
What I tried: `npx mega-linter-runner`

What I got:
```
Pulling docker image oxsecurity/megalinter:v6 ... 
INFO: this operation can be long during the first use of mega-linter-runner
The next runs, it will be immediate (thanks to docker cache !)
WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=oxsecurity%2Fmegalinter&tag=v6": dial unix /var/run/docker.sock: connect: permission denied
```

How I fixed it: https://stackoverflow.com/a/54504083
`sudo setfacl --modify user:<user name or ID>:rw /var/run/docker.sock`

**Comment by Kurt-von-Laven** [comment]
I suspect this is a duplicate of #1975. Currently MegaLinter doesn't change the Docker user from its default of root. What is a sudo-protected Docker executable? I am only familiar with rootless docker, which we have been using successfully with MegaLinter. You can probably improve performance considerably by using a specific flavor.
