### ISSUE TITLE
dotnet-format scanning unchanged files when VALIDATE_ALL_CODEBASE: false

### ISSUE THREAD

**Issue by TommyE123** [oxsecurity/megalinter#2249]
**Describe the bug**
Since version V6.18.0, [dotnet-format] now scans and produces warnings on unchanged files. This is happening for both C# and VB files. (having VALIDATE_ALL_CODEBASE: false in the .mega-linter.yml file)

![image](https://user-images.githubusercontent.com/8810400/211788547-3b2920fe-dc0d-4038-bcc5-5868c289acaf.png)

This makes the reports almost unreadable in a legacy application where we are aware of issues but have not fixed them yet.
This doesn’t happen in previous versions prior to V6.18.0.
This is happening on an Azure devops pipeline.
We have also seen a major time duration jump between V6.17.0 and V6.18.0. Ive included a simple change below however we’ve seen much longer duration of runs with other similar changes.
The below is the same branch and code changes, with just the megalinter version number changed.

V6.18.0
 
![image](https://user-images.githubusercontent.com/8810400/211788564-6e558a36-cad2-499c-a724-3dc8efd47b96.png)

V6.17.0

![image](https://user-images.githubusercontent.com/8810400/211788600-180821cf-6022-4a67-8517-f88f8f1812de.png)

**To Reproduce**
Make a change to a c# or vb file and run MegaLinter in a azure devops pipeline.

**Expected behavior**
Unchanged files should not be scanned when VALIDATE_ALL_CODEBASE: false

**Comment by Kurt-von-Laven** [comment]
Thank you for the bug report. You might have a look at https://github.com/oxsecurity/megalinter/issues/2248#issuecomment-1378585049 to determine whether the workarounds I described there appeal to you.
