### ISSUE TITLE
Add Roslynator

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2269]
Project: https://github.com/JosefPihrt/Roslynator

Analyzers: https://github.com/JosefPihrt/Roslynator/blob/main/src/Analyzers/README.md

Refactorings: https://github.com/JosefPihrt/Roslynator/blob/main/src/Refactorings/README.md

Fixes: https://github.com/JosefPihrt/Roslynator/blob/main/src/CodeFixes/README.md

CLI docs: https://github.com/JosefPihrt/Roslynator/blob/main/docs/cli/README.md

**Comment by nvuillam** [comment]
Great idea to go even further in C# coverage in MegaLinter :)

**Comment by Kurt-von-Laven** [comment]
Neat find; I knew of Roslyn but not Roslynator.

**Comment by bdovaz** [comment]
cc: @nvuillam @echoix @Kurt-von-Laven 

So far I have not implemented it because I have encountered several problems in this issue over the last months: https://github.com/dotnet/roslynator/issues/1060

I have reached the point where from a Dockerfile (outside of megalinter) it works for me but:
1. This cli only works with *.sln or *.csproj files which are .NET solution / project files. The rest of the .NET linters work on *.cs files although I still think we should use them with *.csproj / *.sln because .NET linters by default the input is always going to be a solution or project because a *.cs file by definition "is nothing" without its project or solution.
2. It requires that a `dotnet restore` has been done *in the context of docker* before to download the NuGet packages because the cli requires them to get the information from the analyzers (the most relevant ones: Meziantou.Analyzer, SonarAnalyzer.CSharp, Roslynator.Analyzers, ...).

The second point is the most problematic because it implies that before executing the linter command itself we have to previously execute another `dotnet restore` command but as I said that it has to be done in the context of Docker, it is not enough for the user to do it on his own, we have to do it ourselves on linter side.

**Comment by Kurt-von-Laven** [comment]
1. I get what you mean about running on `*.csproj|*.sln` rather than `*.cs`. It's possible there are some exceptions out there, but in general that seems to be the preferred approach. I wonder if CSharpier is perfectly happy running on `*.cs` files?
2. I support running `dotnet restore` on our side, although I also don't have a great proposal for how exactly we ought to do this. I suspect this would also address #2868. I take it it wouldn't be sufficient to run `dotnet restore` in the Dockerfile (or that we already do this)?

**Comment by bdovaz** [comment]
@nvuillam can you answer what @Kurt-von-Laven and I asked? That is, how to execute the `dotnet restore` command prior to the linter command itself? Have you ever encountered that use case or any similar one?

I don't know how to move forward otherwise, I need your advice @nvuillam.

**Comment by nvuillam** [comment]
@bdovaz sorry for the delay, you're right to beep me it's kind of crazy these days/weeks/months :)

If you need to run a command before running a linter, you can define a before_lint_files in the linter python class, like for tflint :)

https://github.com/oxsecurity/megalinter/blob/main/megalinter/linters/TfLintLinter.py

**Comment by bdovaz** [comment]
But this function does not receive the input of the path to the file, the dotnet restore command needs this input.

**Comment by nvuillam** [comment]
Do you have an example of the full dotnet restore command that is required ?

Most of properties are available from python linter classes, there is probably a way !

**Comment by bdovaz** [comment]
@nvuillam the second example:

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore#examples

**Comment by echoix** [comment]
We have to note that its quite possible that not all project types, like WPF or winforms, would be able to run in a Linux environment. For the rest, it could work ;)
