### ISSUE TITLE
Sarif Reporter in Azure Devops with space in project name

### ISSUE THREAD

**Issue by EtienneDeneuve** [oxsecurity/megalinter#2300]
**Describe the bug**
Report in Azure Devops with Sarif reporter enabled can have broken link when the project have a whitespace in the name.

**Expected Behaviour**
Replace the whitespace with url encoded string '%20'

**Comment by 2022H1030042G** [comment]
Hi, I would like to work on this issue, is it available?

**Comment by EtienneDeneuve** [comment]
Normally, I fixed it already, but you can test
________________________________

**Comment by EtienneDeneuve** [comment]
If the image is build, for sure, I'll do it in the day

**Comment by nvuillam** [comment]
@EtienneDeneuve it is, ghcr.io is back for a while :)
