### ISSUE TITLE
Docker pull wont work with Version 6.19.0

### ISSUE THREAD

**Issue by FaserF** [oxsecurity/megalinter#2309]
**Describe the bug**
Docker image is not working within workflows anymore since the latest update.
It was working fine here: https://github.com/FaserF/hassio-addons/actions/runs/4096390323/jobs/7063992314 with the older version 6.18

**To Reproduce**

Create a github workflow which is using megalinter and let it try to run.

**Expected behavior**
The github workflow command to continue working and the pull to success

**Screenshots**

**Additional context**
```
Pull down action image 'oxsecurity/megalinter:v6.19.0'
  /usr/bin/docker pull oxsecurity/megalinter:v6.19.0
  Error response from daemon: manifest for oxsecurity/megalinter:v6.19.0 not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 6.111 seconds before retry.
  /usr/bin/docker pull oxsecurity/megalinter:v6.19.0
  Error response from daemon: manifest for oxsecurity/megalinter:v6.19.0 not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 1.1[4](https://github.com/Romanitho/Winget-AutoUpdate/actions/runs/4096540556/jobs/7064273673#step:2:4)9 seconds before retry.
  /usr/bin/docker pull oxsecurity/megalinter:v[6](https://github.com/Romanitho/Winget-AutoUpdate/actions/runs/4096540556/jobs/7064273673#step:2:6).1[9](https://github.com/Romanitho/Winget-AutoUpdate/actions/runs/4096540556/jobs/7064273673#step:2:9).0
  Error response from daemon: manifest for oxsecurity/megalinter:v6.19.0 not found: manifest unknown: manifest unknown
Error: Docker pull failed with exit code 1
```

Example: https://github.com/Romanitho/Winget-AutoUpdate/actions/runs/4096540556/jobs/7064273673

**Comment by nvuillam** [comment]
There is a slight delay between the release on GitHub and the release in Docker Hub

It should be ok now, please can you try again ?

**Comment by FaserF** [comment]
it is working now, thank you!
