### ISSUE TITLE
Why does shfmt require apk: go when a Docker install is used

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#2315]
I was analyzing megalinter's image sizes.
I observed that we install go (as the build system) from apk, which shouldn't be needed in production images since it's the packages needed to compile from source. Go binaries are static, single file, and can be easily compiled for (almost) all OSes. Installing Go from apk adds at least 384 MB in the usr/bin/lib/go folder (for the ci_light flavor)
Throughout many other questions that I'm going through to make sure that taking away go won't break anything, I want to ask:
 Why was there a comment/trace saying that shfmt required go, when we use it from a docker image?

**Comment by nvuillam** [comment]
I have no idea about shfmt, you probably can remove go without problem :)

About go, many linters are installed via go install, but if you know how to install a lighter go , it would be great for docker images sizes 😄

**Comment by echoix** [comment]
Yep, that's what I'm doing/looking at. Especially the revive, it has no reason to be compiled from source (without cleaning nor multistage build), while it is now correctly released automatically.

I was trying out the dive tool, and it's quite fun to use. It can also tell how much space is wasted (if one layer adds a file, and it is later deleted). It can also be used in CI to reject a build if the efficiency of an image isn't high enough, or too much space is wasted: https://github.com/wagoodman/dive#ci-integration

For example, ci_light wastes 16MB, but since it is 1.31 GB, its efficiency is 99%.
