### ISSUE TITLE
Redirect users to the correct Docker Hub page

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#2317]
It should be a good idea to add a reference to the current repo, or maybe more the Docker hub page of where the latest images are stored, possibly for all old flavours too. Currently, we see:
![image](https://user-images.githubusercontent.com/27212526/216863655-2ac352ce-3564-4d16-862b-e4730cb60d2e.png)

It could either be editing the "Readme" section of the Docker Hub repo's page, the description, or both.

Also, we could add an URL that can link back to the repo in the user profile:
![image](https://user-images.githubusercontent.com/27212526/216863926-0182df25-71c3-4dc7-8be6-82c05fb71f33.png)
like: 
![image](https://user-images.githubusercontent.com/27212526/216864034-cf00d4f1-6c89-45c0-84b5-e3264620d667.png)

This boring task should be a one-off.
It might even help a little with SEO, since we can't even find the image on the first try. And if I wasn't following the project since a long time, megalinter/megalinter seems more like the source of truth than oxsecurity/megalinter.
![image](https://user-images.githubusercontent.com/27212526/216864764-41370871-a753-440c-be13-1af1b5f40a03.png)

Oh and we also see in that search results that Mega-Linter is used, instead of "MegaLinter", the official name.

**Comment by nvuillam** [comment]
I didn't know I could edit docker image entries to add a readme, it's a good idea yes :)

**Comment by nvuillam** [comment]
![image](https://user-images.githubusercontent.com/17500430/217094802-5e9078ac-b345-4e5b-a901-4e4f5d31aed5.png)

![image](https://user-images.githubusercontent.com/17500430/217094932-f88fc8b8-38a7-4db3-a32a-198df4c3c436.png)


Better ? ^^
