### ISSUE TITLE
The URL of the packages that have a fixed version, is not well resolved in the documentation

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2335]
![image](https://user-images.githubusercontent.com/950602/217749331-e95563b1-5e90-412a-98f3-3fba9a227a8c.png)

Wrong url: https://pypi.org/project/pyright==1.1.270/

Correct url: https://pypi.org/project/pyright/

**Comment by bdovaz** [comment]
As far as I can see it goes further and can occur in more ecosystems:

https://github.com/oxsecurity/megalinter/blob/30ea6a3c0196722214fc089762513f6547cd86c6/.automation/build.py#L1863

**Comment by nvuillam** [comment]
Indeed, probably some split("==")[0] would help :)

**Comment by echoix** [comment]
Just thinking at a little larger picture. Why do we try to link to a pip page without having a dedicated url phe? Couldn't we just link to `linter_url`, where we are sure that it's valid?

https://github.com/oxsecurity/megalinter/blob/30ea6a3c0196722214fc089762513f6547cd86c6/megalinter/descriptors/python.megalinter-descriptor.yml#L304

**Comment by echoix** [comment]
And overall @bdovaz, you're doing a great job! The least I can do to help out is reading everything and responding if it can matter, I'm subscribed to all issues and PRs for more than a year.
