### ISSUE TITLE
Create a PR bot to run our `./build.sh` command [help wanted]

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#2351]
**Is your feature request related to a problem? Please describe.**
Making quick contributions can be hard for new users, or even maintainers, since we need to have a full (Linux) setup ready to run an update command to sync up the Dockerfiles (which is not that common for projects). 

**Describe the solution you'd like**
In some big repos over time, I often saw slack-like bots that you can post a command and it does tasks for you.
It would be nice to have a bot like this, so we could simply enter a comment with a single command saying to update the PR/sync the files by running our `./build.sh` command (on Linux), with the dependencies already defined in the task, and commit the new files to that PR.

**Describe alternatives you've considered**

During the last week, I tried to search for what tools like this exist, and I must not have used the good keywords, but didn't really find useful stuff in my quick searches.

**Additional context**

If anybody has some experience with tools like this and have opinions, or could guide us, or better, help us with a PR, it could be helpful here to reduce friction!

**Comment by nvuillam** [comment]
You mean a bot that will create new commits directly in forks ?
Such thing exist ? :)

**Comment by echoix** [comment]
Oh yah, I didn't think about the fork thing.

**Comment by nvuillam** [comment]
Most of the PRs are from forks , the internal contributor already know the drill ^^

**Comment by echoix** [comment]
I was thinking about that: ![image](https://user-images.githubusercontent.com/27212526/218274662-17017635-565c-4085-bfa8-84d5959ac06f.png)
or (I can'T refind what I was looking for)
but now I see it didn't need to commit when working...

That must be why it wasn't obvious to search for

**Comment by echoix** [comment]
I think I found something: https://github.com/peter-evans/slash-command-dispatch

**Comment by nvuillam** [comment]
It seems to trigger pipelines... but will it be able to add commits on forks ^^

**Comment by echoix** [comment]
I'm checking that...

**Comment by echoix** [comment]
I'm almost there. It "works" for the building part, I only need to finish fixing one thing to make the workflow not fail (I just didn't have any time left), and after that making the comment that is pasted cleaner.
It's kind of nice actually

**Comment by bdovaz** [comment]
I would add the `build.sh --doc` case for documentation, no?

**Comment by nvuillam** [comment]
Using --doc generate many conflicts, I prefer letting auto-update-linter job being the only one doing it :) (except us manually in some aases)

**Comment by echoix** [comment]
Ok, when you would want to use it manually, would you like to type it as /build doc or /docs (ie: as a variable argument or as a complete different command)

For now the plain build.sh changes the md docs for the linters.
