### ISSUE TITLE
Failing rm -rf of pycache in building images

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#2378]
**Describe the bug**
Multiple CI runs have failed today (commits in main) in the python installation steps.

**To Reproduce**

Here was an example of a failure, but not in main
https://github.com/oxsecurity/megalinter/actions/runs/4218033694/jobs/7322271457
![image](https://user-images.githubusercontent.com/27212526/219977773-666040d6-8134-4abc-bb1e-b05b629cfb98.png)

https://github.com/oxsecurity/megalinter/actions/runs/4217586513/jobs/7321474264
![image](https://user-images.githubusercontent.com/27212526/219978053-4d95f2a9-6a46-48a8-b73a-c558207c2a1e.png)

**Expected behavior**
Beta flavors should not fail because of cleaning steps in python?

**Screenshots**

https://github.com/oxsecurity/megalinter/actions/runs/4218033694/jobs/7322271457
![image](https://user-images.githubusercontent.com/27212526/219977773-666040d6-8134-4abc-bb1e-b05b629cfb98.png)

https://github.com/oxsecurity/megalinter/actions/runs/4217586513/jobs/7321474264
![image](https://user-images.githubusercontent.com/27212526/219978053-4d95f2a9-6a46-48a8-b73a-c558207c2a1e.png)
**Additional context**

**Comment by nvuillam** [comment]
I observed this one too, it seems to happen randomly :(

**Comment by echoix** [comment]
That means it's even worse..

**Comment by nvuillam** [comment]
What about a `| true` to avoid the crash ?
But it would just hide the problem under the carpet...

**Comment by echoix** [comment]
Or maybe look into not using root for pip, like --user? Or make a cache mount for the pip folder, so it wouldn't need to be deleted

**Comment by Kurt-von-Laven** [comment]
Passing `--user` to pip (or a similar approach) makes sense to me. It gets us one step closer towards not running as root.
