### ISSUE TITLE
About alpha workflows

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2396]
@nvuillam these 2 workflows I understand are not used and can be deleted? They have references to scripts that do not exist like `upload-docker.sh`.

https://github.com/oxsecurity/megalinter/blob/d4a9104751f70d9591af7f14ee71c3ce94068479/.github/workflows/deploy-ALPHA-flavors.yml

https://github.com/oxsecurity/megalinter/blob/d4a9104751f70d9591af7f14ee71c3ce94068479/.github/workflows/deploy-ALPHA.yml

**Comment by nvuillam** [comment]
Hmmm they should indeed be upgraded to use the docker action...

They are initially here for major upgrades that we want to test without breaking the normal application lifecycle

**Comment by bdovaz** [comment]
@nvuillam I close it because in some commit it seems that you fixed it but you didn't close this issue.

**Comment by nvuillam** [comment]
thanks :)
