### ISSUE TITLE
Vale prose style checker

### ISSUE THREAD

**Issue by wesley-dean-flexion** [oxsecurity/megalinter#2401]
**Is your feature request related to a problem? Please describe.**

I recently started using [Vale](https://vale.sh/) to scan the documentation I write to make it more readable and accessible.  So far, it's been pretty helpful at finding passive voice, sentences of excessive length, etc..  

**Describe the solution you'd like**

It would be nice if MegaLinter included a linter for prose in addition to the extant linters, perhaps included in the [documentation flavor](https://megalinter.io/latest/flavors/documentation/).

**Describe alternatives you've considered**

There exist a variety of mechanisms to accomplish this outside of MegaLinter, such as via Docker image ([jdkato/vale](https://hub.docker.com/r/jdkato/vale)) or GitHub Action ([LanguageTool with reviewdog](https://github.com/marketplace/actions/run-languagetool-with-reviewdog) or [vale-linter](https://github.com/marketplace/actions/vale-linter)).

Tangentially, before submitting this, I thought, "there are already actions to handle Vale -- this would be redundant!" and that would be a fair and reasonable response.  Then I thought about Hadolint, Checkov, and flake8, all of which have actions published in the GitHub Actions Marketplace.  As they're all included in MegaLinter, I think Vale's inclusion would be consistent with MegaLinter.

All of that said, I believe this feature suggestion -- in my humble opinion -- would likely be an extremely low-priority suggestion.

**Additional context**

Vale supports [JSON output](https://github.com/marketplace/actions/vale-linter) so a `jq` script may be able to coerce the results into something more-easily integrated with MegaLinter.

**Comment by nvuillam** [comment]
@wesley-dean-flexion this would indeed be a good addition for linting documentation :)
Would you be interested into making the PR ? :)

**Comment by wesley-dean-flexion** [comment]
I'm not opposed to it.  I'm looking through the `shellcheck` linter now to see how the magic happens and figure out if my thinking that a quick `jq` script would, in fact, work as-expected.

**Comment by nvuillam** [comment]
@wesley-dean-flexion you don't need json output to integrate within MegaLinter, while it's ok to not have sarif output :) ( and lots of linters do not have it yet)

**Comment by nvuillam** [comment]
As [proselint](https://megalinter.io/latest/descriptors/spell_proselint/) is already integrated and seems faster in vale, once vale is integrated we could deprecate proselint :)

**Comment by Kurt-von-Laven** [comment]
Yes, just want to second the doctrine of incremental progress in OSS. Generally way easier to fit smaller PRs into packed schedules then larger ones.

See #1744 for more details on proselint since it's disabled by default. @nvuillam, did you mean that Vale seems faster than proselint?

**Comment by wesley-dean-flexion** [comment]
![homer](https://user-images.githubusercontent.com/45051395/221965774-0975a76c-3fa8-46f9-86e5-3665efb254f8.gif)

**Comment by nvuillam** [comment]
@Kurt-von-Laven according to their doc, it is :)
![image](https://user-images.githubusercontent.com/17500430/221966957-43629062-71e8-4df6-9c23-8cc9e9a47e50.png)

We are a linters aggregator, so I have no problem with other linter aggregators haha ^^ ( for example, actionlint includes shellcheck ^^ )

If we win about performances, and have less linters to maintain, it's something that should be considered in vale is actively maintained :)

**Comment by nvuillam** [comment]
![image](https://user-images.githubusercontent.com/17500430/221967637-92ef5204-f390-4aff-bc4c-17b9e3a9befc.png)

and seeing their users, they seem much more famous that us haha ^^

**Comment by Kurt-von-Laven** [comment]
Vale and proselint both seem great, but I don't think either is an aggregator?

**Comment by nvuillam** [comment]
Seems so, multiple linters & technos

![image](https://user-images.githubusercontent.com/17500430/221968798-df8e3b8f-35a3-4333-b129-5a66390544e8.png)

**Comment by nvuillam** [comment]
It's not so clear... but it seems they recoded in go the engine of other linters & config :o

**Comment by Kurt-von-Laven** [comment]
[That](https://github.com/errata-ai/vale#mag-at-a-glance-vale-vs-) is a marketing grid comparing Vale to the alternatives.

**Comment by wesley-dean-flexion** [comment]
Ok.  Please don't laugh.  This is my first attempt and I'm sure I'm doing something wrong.

[megalinter/descriptors/spell.megalinter-descriptor.yml](https://github.com/wesley-dean-flexion/megalinter/blob/vale/megalinter/descriptors/spell.megalinter-descriptor.yml#L111-L149)

I ran the `build.sh` script and it didn't hate me.

My questions to you are:

- am I on the right track?
- what am I missing?
- I use `hadolint` as a basis; for the options that didn't work for vale, I removed the options from the configuration; is that correct?

Clearly it's not ready for a PR.  I'm just trying to figure out if I'm doing things correctly.

**Comment by nvuillam** [comment]
@wesley-dean-flexion We'll never laugh about anyone wanting to contribute to open-source projects, we prefer to thank them :)
I'll try to have a look today :)

@Kurt-von-Laven ok let's not deprecate proselint, but i'd really like to have vale in MegaLinter:)

**Comment by Kurt-von-Laven** [comment]
Yeah, 100% agree that we should accept Vale into the Alpaca's 🦙 embrace.

**Comment by wesley-dean-flexion** [comment]
The fatal error causing the Megalinter action to fail is being triggered

https://github.com/oxsecurity/megalinter/actions/runs/4308028827/jobs/7513810223#step:4:2803

```
465/660 ./megalinter/descriptors/spell.megalinter-descriptor.yml 242.24ms X
/github/workspace/megalinter/descriptors/spell.megalinter-descriptor.yml:132:16    - Unknown word (jdkato)     -- - FROM jdkato/vale:v2.22.0 as vale
  	 Suggestions: [jato, dato, jakarta, Jakarta, jurator]
```

jdkato is Joseph Kato, creator of Vale; `jdkato/vale` is the (official) Vale image published to Dockerhub.

**Comment by Kurt-von-Laven** [comment]
You can add the correct spelling to the list of CSpell exceptions. On mobile right now, but you can probably find the list pretty quickly via `git grep`. It looks something like [this](https://cspell.org/configuration/), only way longer.

**Comment by wesley-dean-flexion** [comment]
added it to `.github/linters/.cspell.json`
