### ISSUE TITLE
gitlab comment reporter, misleading error message

### ISSUE THREAD

**Issue by LBeaulaton** [oxsecurity/megalinter#2420]
For gitlab CI, if the access token is badly defined (see the correct way: https://github.com/oxsecurity/megalinter#gitlab-ci), the following line asks  for defining `GITLAB_MEGALINTER_ACCESS_TOKEN` while it should be `GITLAB_ACCESS_TOKEN_MEGALINTER`

https://github.com/oxsecurity/megalinter/blob/5e7d9e32964c0cedfe5048e8bd33a53a1a15d0e3/megalinter/reporters/GitlabCommentReporter.py#L169

Note also that in the readme you do not precise that the access token should have the appropriate role (when it is a project token and not a personal token like in the demo) to comment on a merge request (at least developer).

PS: thanks for your great job

**Comment by nvuillam** [comment]
@LBeaulaton good catch , thanks :)

Would you like to make a quick PR  ? :)

**Comment by LBeaulaton** [comment]
never done this, I can try

**Comment by nvuillam** [comment]
@LBeaulaton contributing to open source is a great experience :) ( be careful, if you're like me, once you'll start you'll never stop :D )

https://megalinter.io/latest/contributing/#submitting-a-pull-request

(as this is a very simple PR you may just fork, update the code and create a PR, no need to locally build )
