### ISSUE TITLE
Are `GITLAB_API_URL` and `GITLAB_SERVER_URL` still used?

### ISSUE THREAD

**Issue by LBeaulaton** [oxsecurity/megalinter#2423]
They are referenced in the [doc](https://github.com/oxsecurity/megalinter/blob/main/docs/reporters/GitlabCommentReporter.md) but do not seem to be used (neither in the [json descriptor file](https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json) nor in the [gitlab python reporter](https://github.com/oxsecurity/megalinter/blob/main/megalinter/reporters/GitlabCommentReporter.py).

If so this should be deleted in in the doc (I can do this PR if it helps)

**Comment by nvuillam** [comment]
Indeed we use `gitlab_server_url = config.get("CI_SERVER_URL", self.gitlab_server_url)`

We'll gladly accept your PR :) ( see ? Once you start contributing to open-source you can't stop 🤣  )
