### ISSUE TITLE
[v6.20.0] Console Reporter broken for PHP flavour

### ISSUE THREAD

**Issue by llaville** [oxsecurity/megalinter#2425]
**Describe the bug**
The summary table is not completed after an analysis.

**To Reproduce**

1. Download latest image of PHP flavour  with `docker pull oxsecurity/megalinter-php:v6` (digest: `sha256:b38beb2a78234c3719a473b318b9e67651f56423c9a0faf979a1a2c8c2b035d3`)
2. Run following command `sudo rm -rf megalinter-reports/ && time docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:rw -v $(pwd):/tmp/lint:rw oxsecurity/megalinter-php:v6` on a local git clone of my repository https://github.com/llaville/php-compatinfo-db (`master` branch)
3. See error

**Expected behavior**
As previous version a summary table complete.

**Screenshots**

![megalinter-620](https://user-images.githubusercontent.com/364342/223043870-0a6d2517-25f1-4c5d-8bab-42b23904644a.png)

**Additional context**
Local platform :  Ubuntu 22.04 LTS on WSL2

**Comment by llaville** [comment]
Here are results I got with previous version

```
----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2023-02-05T11:58:18Z
 - Image Revision: f8d535e
 - Image Version: v6
----------------------------------------------------------------------------------------------------
```

Docker image has disgest `sha256:2744b2f1d9e919e13d1190dfaaa95bee93d22d6828bd0e7449396ad7c555a1cc `

![megalinter-6](https://user-images.githubusercontent.com/364342/223045515-bcb847c0-1df8-4e1a-9a21-0003abe5bb10.png)

BTW v6.20.0 has header version identification changed. Now I got 
```
----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 
 - Image Revision: 0d699a348a2c104040efd78f2d2970e6ae8e5769
 - Image Version: 0d699a348a2c104040efd78f2d2970e6ae8e5769
----------------------------------------------------------------------------------------------------
```
Compare to previous version !

**Comment by llaville** [comment]
And summary table crash gave me other results each time I run it. Sometimes it break results after, sometimes I got this error 

```
+----SUMMARY------+----------------------+---------------+-------+-------+--------+--------------+
| Descriptor      | Linter               | Mode          | Files | Fixed | Errors | Elapsed time |
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/multiprocessing_logging-0.3.4-py3.11.egg/multiprocessing_logging.py", line 77, in _receive
    record = self.queue.get(timeout=0.2)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 117, in get
    res = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 215, in recv_bytes
    buf = self._recv_bytes(maxlength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 420, in _recv_bytes
    return self._recv(size)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 378, in _recv
    chunk = read(handle, remaining)
            ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer
Exception in thread mp-handler-0:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/multiprocessing_logging-0.3.4-py3.11.egg/multiprocessing_logging.py", line 77, in _receive
    record = self.queue.get(timeout=0.2)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 117, in get
    res = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 215, in recv_bytes
    buf = self._recv_bytes(maxlength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 420, in _recv_bytes
    return self._recv(size)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 378, in _recv
    chunk = read(handle, remaining)
            ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer

real    0m31.776s
user    0m0.096s
sys     0m0.132s
```

**Comment by Kurt-von-Laven** [comment]
This may be related to #2348. Which OS are you on, and are you using rootless or rootful Docker?

**Comment by Kurt-von-Laven** [comment]
That's great to hear. Actually the answer to my previous question may still be relevant to #2348.

**Comment by llaville** [comment]
I confim, each time I run with PARALLEL directive enabled, the console reporter crash.
Now I'll disable it by default to avoid issue with GitHub Workflow, and enable it locally : 

```
sudo rm -rf megalinter-reports/ && time docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:rw -v $(pwd):/tmp/lint:rw -e PARALLEL=true oxsecurity/megalinter-php:v6
```

**Comment by Kurt-von-Laven** [comment]
Makes sense. I meant this question though:

> Which OS are you on, and are you using rootless or rootful Docker?

**Comment by llaville** [comment]
Rootfull Docker (default) on Ubuntu 20.04.2 LTS WSL2

**Comment by Kurt-von-Laven** [comment]
Thank you! That helps confirm our theory that the v6.20.0 images can only be pulled using rootful Docker.

**Comment by nvuillam** [comment]
Grmblmblm I hope it's not related to [multiprocessing-logging](https://github.com/jruere/multiprocessing-logging)

**Comment by llaville** [comment]
FYI: I've just tested version 6.20.1, and this issue still exists !

But the creation date in header was fixed (thanks)

```
----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2023-03-07T19:35:10Z
 - Image Revision: 7411316caa2897b3839af1834e5fd8ebd5b7b81e
 - Image Version: 7411316caa2897b3839af1834e5fd8ebd5b7b81e
----------------------------------------------------------------------------------------------------
```

But, bad new, I've noticed that links to `https://megalinter.io/**/descriptors/**` were broken (404)

This is a chunk of report produced, but all links are affected !

![broken_links-megalinter-6201](https://user-images.githubusercontent.com/364342/223657526-0bf14426-ad05-429f-bf00-54e409b8d081.png)

**Comment by llaville** [comment]
Just to compare with previous release that did not have this issue 

```
----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2023-02-05T11:58:18Z
 - Image Revision: f8d535e
 - Image Version: v6
----------------------------------------------------------------------------------------------------
```
And all link to megalinter.io descriptors were not broken (usage of `latest` compare to hash version used in 6.20.1)

![v6 19](https://user-images.githubusercontent.com/364342/223660746-bc97bb12-e7c7-45a8-9f0c-a359453b48c1.png)

**Comment by llaville** [comment]
One possible reason, is that the latest release did not point to v6.20.1 (unavailable on https://megalinter.io)

![megalinter_io](https://user-images.githubusercontent.com/364342/223661751-3ae7a43a-0a52-485f-aceb-cf38b93980d8.png)

**Comment by nvuillam** [comment]
@llaville the latest release is always behind "latest", and becomes available in the list once there is a new release :)

It's because of the messy doc version management with [mike](https://github.com/jimporter/mike)

**Comment by llaville** [comment]
After a long period to retrieve full flavor docker image
```
Digest: sha256:fb88bc1c8af10fd31443789ba7390008bf257e1e32eb9da540495eb89a0cb9f8
Status: Downloaded newer image for oxsecurity/megalinter:v6
docker.io/oxsecurity/megalinter:v6

real    55m27.963s
user    0m1.304s
sys     0m1.784s
```
This issue affect all MegaLinter v6.20.1 versions (and not only the  PHP flavor)

I can confirm @nvuillam your intuition ([3 days ago](https://github.com/oxsecurity/megalinter/issues/2425#issuecomment-1456711689) !!!)

**Comment by nvuillam** [comment]
@llaville on what do you run MegaLinter ?
Parallel stuff seems to work verywhere , else we would have been flooded by issues... do you have a specific hardcore local config ? :(

**Comment by nvuillam** [comment]
If it is multiprocessing-logging, the maintainer took 4 months to accept the PR that fixed the bug, I was close to make a hard-fork :'(

**Comment by llaville** [comment]
[multiprocessing-logging](https://github.com/jruere/multiprocessing-logging#readme) seems not supporting Python 3.11 (https://github.com/jruere/multiprocessing-logging/blob/master/setup.py), while MegaLinter 6.20.x did it https://github.com/oxsecurity/megalinter/blob/main/Dockerfile#L47

**Comment by nvuillam** [comment]
@llaville if it was the case everywhere we wouldn't have any MegaLinter 6.20.x working :/

I posted an issue on the repo, maybe they can help :/

Meanwhile, you can remain with the PARALLEL: false workaround, but I understand that's is not good for perfs, especially if you run on an engine with more than 2 cores :/

**Comment by Kurt-von-Laven** [comment]
I just had a non-deterministic encounter with the same stack trace as @llaville while running the v6.20.1 JavaScript flavor on [ScribeMD/docker-cache](https://github.com/ScribeMD/docker-cache). The first time it showed up was also the first time I got ESLint running (although very badly since we're using Yarn, so it can't find any `tsconfig.json` installed via Yarn). That makes me worry that landing #2455 will exacerbate this bug for our JavaScript users who are using mega-linter-runner.
