### ISSUE TITLE
[v6.20.0] Running on Mac m1 no longer working

### ISSUE THREAD

**Issue by mikael-j-rich** [oxsecurity/megalinter#2427]
**Describe the bug**
Been running the linter locally on my Mac m1 using Rosetta and the megalinter-runner script has been working fine. Since v6.20.0 the script fails saying "no matching manifest for linux/arm64/v8 in the manifest list entries".

**To Reproduce**

1. Run npx megalinter-runner on Mac m1.

**Expected behavior**
I expect the image to be pulled and started on Docker.

**Comment by nvuillam** [comment]
We changed the way to build docker images, it could be related...

As we don't provide (yet) arm64 images, it should probably be solvable adding `--platform linux/x86_64/v8` to the docker pull

cf https://stackoverflow.com/a/67361161/7113625

**Comment by echoix** [comment]
Was v6.19.0 built with buildx?

**Comment by nvuillam** [comment]
@echoix yes but it was raw buildx , not docker build github action, which is here only since 6.20.0

**Comment by echoix** [comment]
Ok, that excludes one of my hypotheses. If we don't specify the platforms on the action, does it still build ?

**Comment by nvuillam** [comment]
Platforms are hardcoded in the action parameters.
So far only linux/amd64

![image](https://user-images.githubusercontent.com/17500430/223191809-b839809b-9e6f-457e-986b-ce8f3de81939.png)

**Comment by timgentry** [comment]
@nvuillam `npx mega-linter-runner@beta` worked for me, where `npx mega-linter-runner` was broken on an M1 Mac

**Comment by nvuillam** [comment]
@timgentry many thanks for your quick feedback !

**Comment by nvuillam** [comment]
> @nvuillam Sorry for the delay on feedback, you were to quick! 😄 

@timgentry that's ok, it takes a whole community to fix a bug 😅

**Comment by VictorRos** [comment]
Hello!
We are also using `MegaLinter` in our project.
Some of us use **Intel** chipsets while other use **Apple Silicon M1** chipsets.
Do you have a due date for an official patch `6.20.1` that will include this fix?
This way, we will all use the same version to validate rules.
Best regards,
Victor

**Comment by nvuillam** [comment]
@VictorRos we are trying to solve other issues, but if we don't succeed very quick we'll release a first patxh before
Probably tonight, hang on :)

**Comment by VictorRos** [comment]
Ok, thank you for the quick answer!
Good luck with the other issues ;)
