### ISSUE TITLE
[v6.20.0] Pre npm install not resolving.

### ISSUE THREAD

**Issue by mikael-j-rich** [oxsecurity/megalinter#2428]
**Describe the bug**
I run npm install for several eslint plugins and suddenly they stopped working. npm install is complaining about not being able to resolve stylelint correctly. I don't have stylelint as a dependency.

This causes the eslint plugins to not install.

**To Reproduce**

1. Add ```npm install @vue/eslint-config-typescript @vue/eslint-config-prettier``` in PRE_COMMANDS.
2. Run the linter

**Expected behavior**
The npm install should properly resolve.

**Screenshots**
<img width="1008" alt="Screenshot 2023-03-06 at 17 08 21" src="https://user-images.githubusercontent.com/84902744/223167441-5a948261-4f42-4ad9-8696-37ce07139bc8.png">

**Comment by nvuillam** [comment]
Hmmmm that's not good
Meanwhile we find a solution, can you try to add `--force` to your npm install PRE_COMMANDS ?

**Comment by mikael-j-rich** [comment]
@nvuillam sure, works like a charm for now! 😄

**Comment by nvuillam** [comment]
@mikael-j-rich that's ugly but does the job... we'll still try to find a fix anyway !

**Comment by mikael-j-rich** [comment]
I don't doubt it! Thanks for the quick response 😄

**Comment by nvuillam** [comment]
@mikael-j-rich please can you remove the --force and confirm that's ok with latest version? :) v6 ou v6.20.1

**Comment by mikael-j-rich** [comment]
@nvuillam Works like a charm! 😄 Thanks for the quick response and fix!

**Comment by nvuillam** [comment]
@mikael-j-rich I transfer your thanks to the great @echoix who solved the issue  ;)
