### ISSUE TITLE
Error running latest megalinter docker image in CircleCI

### ISSUE THREAD

**Issue by Ariana-Hlavaty-i2** [oxsecurity/megalinter#2429]
**Describe the bug**
Running the latest v6 docker image (published 2d ago) the build throws the following error:
```
0e6473d: Extracting [==================================================>]  44.44MB/44.44MBB

CircleCI was unable to start the container because of a userns remapping failure in Docker.

This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.

Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
Original error: CircleCI was unable to start the container because of a userns remapping failure in Docker.
```

**To Reproduce**

1. Create a config.yml for CircleCI
2. Use the as executor docker: image: oxsecurity/megalinter-documentation:v6
3. Run a build

**Expected behavior**
Megalinter to start and run checks

**Screenshots**

**Additional context**

**Comment by echoix** [comment]
Thanks for the additional context, that information helps us more ;) It's a know issue for 6.20.0, tracked in #2348

**Comment by echoix** [comment]
Duplicates #2348

**Comment by echoix** [comment]
Cc @nvuillam
