### ISSUE TITLE
Some issues with v6.20.0: Workarounds !

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#2431]
We have made many structural changes between v6.19.0 and 6.20.0 (including the use of [docker-build-push-action](https://github.com/docker/build-push-action) to build MegaLinter images), and unfortunately some issues has been identified.

We are actively working to solve them and release a patch, meanwhile you can either **use one of the workarounds**, or **downgrade to v6.19.0**

- https://github.com/oxsecurity/megalinter/issues/2427
  - Fixed, use `npx mega-linter-runner@beta` before a patch is released.
  - If you use manual docker pull, add `--platform linux/amd64` option
  - **Edit 07/03: Fixed in 6.20.1**

- https://github.com/oxsecurity/megalinter/issues/2428
  - Add `--force` to your npm install in PRE_COMMANDS
  - **Edit 07/03: Fixed in 6.20.1**

- https://github.com/oxsecurity/megalinter/issues/2425
  - Define`PARALLEL: false` in .mega-linter.yml config file or ENV variable

- https://github.com/oxsecurity/megalinter/issues/2348
  - No workaround yet
  - **Edit 07/03: Fixed in 6.20.1**

**Comment by Kurt-von-Laven** [comment]
I suspect the workaround for #2348 is to use rootful rather than rootless Docker, although I realize that may be too much security risk to be acceptable for some.

**Comment by nvuillam** [comment]
The issue has probably been suggested by @echoix : find the file(s) with uid > 10000 and chown it , but we have to find those hhffjvfoijveryj files...

**Comment by timgentry** [comment]
@nvuillam I think that's a typo and should be `npx mega-linter-runner@beta` (you're missing the `-`). Perhaps also include `npx` for clarity?

**Comment by llaville** [comment]
I confirm that issue 2425 should stay open (at least with v6.20.1)

**Comment by llaville** [comment]
As PARALLEL = true issue with at least PHP flavor is not solved, I think we should keep this report opened to not forget it !
