### ISSUE TITLE
Hadolint and Shellcheck unexpected errors (Apple chipsets M1, M2)

### ISSUE THREAD

**Issue by VictorRos** [oxsecurity/megalinter#2447]
I'm running **MegaLinter** on **MacBook Pro** with chipset **Apple M1 Pro**.

**Describe the bug**

Binary linters of **shellcheck** and **hadolint** print errors and failed MegaLinter.

**To Reproduce**

1. Run MegaLinter with flavors `documentation` or `javascript` (ones we use in my team)
2. MegaLinter print errors when running binary **shellcheck** and **hadolint**
3. MegaLinter failed because of those errors

**Expected behavior**

No errors when Hadolint and Shellcheck are running.

_I tried to use previous versions of `mega-linter-runner` NPM library and previous Docker images but I still got those errors, so I don't understand why I discovered them right now._

_The only reason is that I might have locally a more older version of the runner and docker image.
Unfortunately, I don't have the version from when it was working._

**Screenshots**

- **Hadolint**

![image](https://user-images.githubusercontent.com/6940422/223698911-32e7ce7f-b1eb-4b5e-8d57-dc6bfa312c25.png)

- **Shellcheck**

![image](https://user-images.githubusercontent.com/6940422/223698957-4c312746-96fa-4e6d-9366-2a0da83484e1.png)

**Additional context**

- Not working on **MacBook Pro** with **M1 Pro** chipset
- Working on **MacBook** Pro with **Intel** chipset
- Working on **Linux agents** in our **pipelines**

**Comment by VictorRos** [comment]
I connected to the Docker image and ran same commands MegaLinter does, and I got similar errors.

**Segmentation fault** for `hadolint`, and `shellcheck` process is **Killed**.

![image](https://user-images.githubusercontent.com/6940422/223738521-b75fc77a-6bfa-499f-a2fd-36d09ffd631b.png)

**Comment by VictorRos** [comment]
Possible related issues (similar errors):

- hadolint/hadolint#823
- hadolint/hadolint#897
- koalaman/shellcheck#2428
- koalaman/shellcheck#2680

The cause might not to be related to MegaLinter directly.

**Comment by echoix** [comment]
Try adding the amd64 platform argument to the run command,
Ie `docker run --platform linux/amd64` to the manual test you just made.

**Comment by nvuillam** [comment]
@VictorRos does it work with @echoix 's workaround ?

mega-linter-runner 6.20.1 now uses `--platform linux/amd64`  by default until we can manage multiplatform images

**Comment by VictorRos** [comment]
@echoix , @nvuillam
Hello, sorry for the delay in my answer.

I added option `--platform linux/amd64` in our project command.

Unfortunately, it's still failing on our **MacBook Pro M1**.

Command we use:

```shell
npx -y mega-linter-runner@6.20.1 \
  --release v6.20.1 \
  --flavor documentation \
  --containername mega-linter
```

With option `--platform linux/amd64`:

```shell
npx -y mega-linter-runner@6.20.1 \
  --platform linux/amd64 \
  --release v6.20.1 \
  --flavor documentation \
  --containername mega-linter
```

**Comment by EtienneDeneuve** [comment]
I'm working with @VictorRos, and I've the same issue on a M1 Pro with Ventura 13.3 beta 3.

I'll start the process in debug mode to see if something can be changed to fix the issue.

I'll try also using Podman to check if it's related to the docker engine

**Comment by EtienneDeneuve** [comment]
here is the "debug" output:

```
[hadolint] command: ['hadolint', '/tmp/lint/scripts/js/updateroles/Dockerfile']
[hadolint] CWD: /
[hadolint] result: -11 qemu: uncaught target signal 11 (Segmentation fault) - core dumped

Linter version command: ['/usr/bin/hadolint', '--version']
Linter version result: -11 qemu: uncaught target signal 11 (Segmentation fault) - core dumped

Unable to get version for linter [hadolint]
/usr/bin/hadolint --version returned output: (-11) qemu: uncaught target signal 11 (Segmentation fault) - core dumped

Unable to extract version with regex re.compile('\\d+(\\.\\d+)+') from ERROR
❌ Linted [DOCKERFILE] files with [hadolint]: Found 1 error(s) - (0.05s)
- Using [hadolint vERROR] https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/dockerfile_hadolint
- MegaLinter key: [DOCKERFILE_HADOLINT]
- Rules config: identified by [hadolint]
- Number of files analyzed: [1]
--Error detail:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

```

**Comment by echoix** [comment]
> I connected to the Docker image and ran same commands MegaLinter does, and I got similar errors.
> 
> 
> 
> **Segmentation fault** for `hadolint`, and `shellcheck` process is **Killed**.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/6940422/223739110-564669ea-88bc-4303-957b-eadf1e8c0de3.png)
> 
> 

This is the test I wanted to see with the --platform argument. 

The npx mega-linter-runner is a different program that helps launch the Docker container, but I don't expect it to forward that argument and make it work. 

Seeing qemu errors make me think that Rosetta 2 isn't being used, and that Docker maybe is trying to do some translation by itself (via Qemu), thus why I wanted to see what is the output of the same test, but by trying to force to use amd64

**Comment by EtienneDeneuve** [comment]
I tried with the "New virtualisation framework" & "Use Rosetta for x86/amd64 emulation on Apple Silicon" on the @VictorRos's repo (I work with him), @echoix and it's working.
I guess theses two linter have something wrong and make qemu crash.

**Comment by VictorRos** [comment]
@echoix Ok sorry, I completely misunderstood your instructions :D

I can confirm that using the trick @EtienneDeneuve did allow me to run **MegaLinter**.

Rosetta wasn't checked.

![Docker desktop](https://user-images.githubusercontent.com/6940422/224758682-ef0ecf5a-b84a-4dbc-bfc5-fdc65a8d35a2.png)

After enabling it and restarting Docker, now it's working better!

Sometimes this error appeared randomly (linter that failed is also random, in this screenshot it's `cspell`, but for next run it can be `secretlint`).

![image](https://user-images.githubusercontent.com/6940422/224759191-99655c3e-87d3-497d-bc20-73b07436a26d.png)

But it seems to be a well known problem :D

docker/roadmap#384
