### ISSUE TITLE
Not possible to pass array of values for envs with local runner (cli)

### ISSUE THREAD

**Issue by DariuszPorowski** [oxsecurity/megalinter#2448]
**Describe the bug**
Not possible to pass array of values for envs with local runner. According to docs [https://megalinter.io/latest/mega-linter-runner/#examples](https://megalinter.io/latest/mega-linter-runner/#examples) it should be supported.

**To Reproduce**

run local runner (cli):

```console
mega-linter-runner -e 'ENABLE=MARKDOWN,YAML'
```

Behind the hood, the runner splits env to two different docker envs.

```console
docker run -e ENABLE=MARKDOWN -e YAML oxsecurity/megalinter-documentation:v6
```

and megalinter runs only MARKDOWN linter

**Expected behavior**

MARKDOWN and YAML linters shoud run both, and docker command should looks like:

```console
docker run -e ENABLE=MARKDOWN,YAML oxsecurity/megalinter-documentation:v6
```

**Screenshots**

**Additional context**

Probably this causes the issue: https://github.com/oxsecurity/megalinter/blob/1d15a5e1a6135c90995722a0a72979eab40b8cfc/mega-linter-runner/lib/options.js#L22

according to lib's doc: https://github.com/gkz/optionator#option-properties

> concatRepeatedArrays is an optional boolean or tuple with boolean and options object (defaults to false) - when set to true and an option contains an array value and is repeated, the subsequent values for the flag will be appended rather than overwriting the original value - eg. option g of type [String]: -g a -g b -g c,d will result in ['a','b','c','d']

or lib's default value for `aliasSeparator`

https://github.com/gkz/optionator/blob/master/README.md#help-style-properties

**Comment by Kurt-von-Laven** [comment]
Duplicate of #1659. I won't close this though since we will gladly accept a PR to correct the documentation.

**Comment by echoix** [comment]
@Kurt-von-Laven has beaten me and found the other related issue before me. Especially see the resolution here https://github.com/oxsecurity/megalinter/issues/1659#issuecomment-1200473475

**Comment by DariuszPorowski** [comment]
@Kurt-von-Laven @echoix oh! Thank you, I tried to review some issues first and cannot find it. Used ENABLE keyword instead of DISABLE ;) Solution from https://github.com/oxsecurity/megalinter/issues/1659 works.
