### ISSUE TITLE
Reenable stylelint-config-sass-guidelines with their new v10.0.0 release

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#2460]
v10.0.0 is available now and supports stylelint v15: https://www.npmjs.com/package/stylelint-config-sass-guidelines/v/10.0.0
You can view the changelog here:  https://github.com/bjankord/stylelint-config-sass-guidelines/blob/main/CHANGELOG.md#1000

_Originally posted by @bjankord in https://github.com/bjankord/stylelint-config-sass-guidelines/issues/273#issuecomment-1467199277_

This tool had to be disabled in #2435, but now, a new release has been worked on tonight, including a fix for the incompatible stylelint. It could be re-added and look if it is still possible to install with the other packages.

**Comment by echoix** [comment]
Possibly, or that the omit dev was also added at that PR to reduce node modules, in hope to have less dependencies that could conflict or have permission problems.

Does the removed package have this dependency? If it's a real dependency, @nvuillam, should we add it to stylelint in its descriptor?

**Comment by nvuillam** [comment]
If new version avoids the dependency conflict with other npm packages, let's use it yes :)
