### ISSUE TITLE
Global .gitignore Not Incorporated with IGNORE_GITIGNORED_FILES: true

### ISSUE THREAD

**Issue by andrewvaughan** [oxsecurity/megalinter#2464]
**Describe the bug**
When running tests, megalinter does not include global gitignore rules that might be setup on the system.

**To Reproduce**
Create a file that is blocked by the global gitignore file, but not the local one, and it will fail.

**Expected behavior**
Global gitignore files should also be ignored.

**Additional context**
I believe this is a pretty easy problem to solve. Simply look up the git configuration on the running platform for the global gitignore by running:

```shell
git config --global core.excludesfile
```

If that configuration variable is set, include that ignore file in the Docker volume and ensure the megalinter ignore includes it. Alternatively, temporarily copy it into the instance (or however the gitignore logic is setup).

**Comment by Kurt-von-Laven** [comment]
I think we would also need to recurse up the user's filesystem for `.gitignore` files in ancestral directories and handle conflicts with the appropriate precedences to match Git's behavior? The drawback here (besides the significant complexity at least with what I am imagining) is that the existing behavior is helpful for ensuring projects are self-contained and treated consistently between developers.

**Comment by nvuillam** [comment]
@andrewvaughan meanwhile you can call `git config --global core.excludesfile` as a PRE_COMMAND :)

https://megalinter.io/latest/configuration/#pre-commands

**Comment by andrewvaughan** [comment]
> @andrewvaughan meanwhile you can call `git config --global core.excludesfile` as a PRE_COMMAND :)
> 
> 
> 
> https://megalinter.io/latest/configuration/#pre-commands

Seems like something that could be made a default, then?

**Comment by Kurt-von-Laven** [comment]
Personally, I don't feel that would be a better default for the reason I gave above.
