### ISSUE TITLE
bandit checks fail when configured to use pyproject.toml

### ISSUE THREAD

**Issue by andrewvaughan** [oxsecurity/megalinter#2465]
**Describe the bug**
bandit [supports](https://bandit.readthedocs.io/en/latest/config.html) the use of `pyproject.toml` as a configuration source. As such, I set my `.mega-linter.yml` file as follows:

```yml
# Bandit Configurations
PYTHON_BANDIT_CONFIG_FILE: pyproject.toml
```

However, when running megalinter, the following error occurs:

```
[MegaLinter/MegaLinter]   ❓  ::group::❌ Linted [PYTHON] files with [bandit]: Found 1 error(s) - (0.63s) (expand for details)
| - Using [bandit v1.7.4] https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/python_bandit
| - MegaLinter key: [PYTHON_BANDIT]
| - Rules config: [/Users/andrew/Repositories/Root & Blade, LLC/.github-private/pyproject.toml]
| - Number of files analyzed: [1]
| --Error detail:
| [main]        ERROR   /Users/andrew/Repositories/Root & Blade, LLC/.github-private/pyproject.toml : toml parser not available, reinstall with toml extra
```

**To Reproduce**

1. Add bandit as a linter
2. Set `PYTHON_BANDIT_CONFIG_FILE` to `pyproject.toml`
3. Run megalinter

**Expected behavior**
It should work with toml

**Additional context**
I believe the only thing required to be added is `bandit[toml]` to the flavor(s). For example, with poetry:

```shell
poetry add bandit[toml]
```

Or in the (ironically) `pyproject.toml` file:

```
bandit = {extras = ["toml"], version = "^1.7.5"}
```

**Comment by nvuillam** [comment]
We can do that :) (for the moment we have another issue blocking CI)

Meanwhile, you can call `pip install bandit[toml]` as a PRE_COMMAND :)

https://megalinter.io/latest/configuration/#pre-commands
