### ISSUE TITLE
Upgrade PHPLint to v9

### ISSUE THREAD

**Issue by llaville** [oxsecurity/megalinter#2483]
I think now we have PHP 8.1 as base version of MegaLinter v6, it's time to upgrade PHPLint from version 5.5 to 9.0

As I'm author of refactoring code to major version v9 of [PHPLint](https://github.com/overtrue/phplint), I wanted to said : 
- previous versions will be not supported in future months
- latest version 9.0.4 is now stable since at least one month 

Now about MegaLinter v6.

I've tried the recent version 6.21.0

```
 ----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2023-03-26T14:04:33Z
 - Image Revision: 66108018d9c2160896d8cf34d56f341592d23ffd
 - Image Version: 66108018d9c2160896d8cf34d56f341592d23ffd
----------------------------------------------------------------------------------------------------
The MegaLinter documentation can be found at:
 - https://megalinter.io/66108018d9c2160896d8cf34d56f341592d23ffd
```
And still have wrong links (that lead to 404) in Console Reporter on each linter
E.g: chunk of screenshot
![megalinter-v621](https://user-images.githubusercontent.com/364342/227858247-4949a940-32bb-469b-b346-9e02db2ef540.png)

 Strange because, when I rebuilt locally the PHP flavor, I've no such results. See in chunk of screenshot
![megalinter-v6_phplint-v9](https://user-images.githubusercontent.com/364342/227858521-5932180a-5643-4f94-b642-64438a404181.png)

My local command was : 
```
docker build -f flavors/php/Dockerfile --secret id=GITHUB_TOKEN,env=GITHUB_TOKEN .
```
With: `Docker version 23.0.1, build a5ee5b1` (docker buildkit enabled)

About MegaLinter v6 upgrade it will be more simple now, we previously used Composer only for PHPLint installation.
We can now remove it because it's no more necessary : PHIVE is able to install PHPLint v9

- https://github.com/oxsecurity/megalinter/blob/v6.21.0/megalinter/descriptors/php.megalinter-descriptor.yml#L20
- https://github.com/oxsecurity/megalinter/blob/v6.21.0/megalinter/descriptors/php.megalinter-descriptor.yml#L38

And PHIVE installation is much easier
Replace
https://github.com/oxsecurity/megalinter/blob/v6.21.0/megalinter/descriptors/php.megalinter-descriptor.yml#L38
By 
```
    install:
      dockerfile:
        - |
          RUN GITHUB_AUTH_TOKEN="$(cat /run/secrets/GITHUB_TOKEN)" && export GITHUB_AUTH_TOKEN && phive --no-progress install overtrue/phplint --force-accept-unsigned -g 
```

**Comment by llaville** [comment]
FYI: When I've rebuild PHP flavor locally, I got this final results (with warnings)

![warnings](https://user-images.githubusercontent.com/364342/227860761-2f75a144-3eba-4038-9127-20ef99b8a2db.png)

**Comment by nvuillam** [comment]
@llaville thanks a lot for the initiative :)

About the wrong links, it's only during dev branch build, not beta or release, right ?

About the warnings: it's because we join the RUN instructions and add comments within the Dockerfile and it seems it's forbidden... we should replace them by "echo" someday :)

**Comment by nvuillam** [comment]
https://github.com/hardisgroupcom/sfdx-hardis/actions/runs/4529862900/jobs/7978081998

Ouch indeed that's ugly :o :o 

Seems like a regression, I'll check that tonight

**Comment by llaville** [comment]
> Seems like a regression, I'll check that tonight

Exists since 6.20.0 (see https://github.com/oxsecurity/megalinter/issues/2425)
