### ISSUE TITLE
SQLFluff config changed with v2

### ISSUE THREAD

**Issue by tunetheweb** [oxsecurity/megalinter#2493]
The SQLFluff config changed quite a bit with v2. Here's the latest default: https://docs.sqlfluff.com/en/stable/configuration.html#default-configuration

Currently the template .sqlfluff file is all commented out in the two places it exists in this repo:
- https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/.sqlfluff
- https://github.com/oxsecurity/megalinter/blob/main/.automation/test/sql/.sqlfluff (though this one sets the dialect to `ansi`).

Should we upgrade the .sqlfluff files in this repo to commented out versions of the latest default-configuration? Baring in mind it might get out of sync again.
Or should we just have an empty file with a pointer to [the config docs](https://docs.sqlfluff.com/en/stable/configuration.html) and explaining how to configure it?

What's generally the preference for other linters? Is the template config file supposed to be a list of all the options but commented out, so people can uncomment them as they like without looking up the docs? Or is it preferred to have the minimal config needed and they can add more config as they please by looking up that linter's docs?

My preference would be a minimal file, with no config (except where necessary for the test file to set the dialect), and a comment to point them to the docs, to avoid maintenance of this in future.

**Comment by Kurt-von-Laven** [comment]
We have tended to attempt to default the linters to configs that are widely considered a desirable starting point. You are right that this does have the drawback of requiring additional maintenance, but one of the premises of MegaLinter is that it's preferable to distribute the cost of that basic upkeep across a community. In general, we have not aspired to include all linter options commented out in our template configs, and personally I don't find that especially worthwhile, particularly in an age where many IDEs are familiar with many of the config formats. We haven't been very consistent about it, but a link to the pertinent docs is a sensible thing to include in the templates.
