### ISSUE TITLE
Megalinter ignores .ps1 files

### ISSUE THREAD

**Issue by FaserF** [oxsecurity/megalinter#2497]
**Describe the bug**
I have no regex filter defined to exclude those files. But Megalinter just does not read the ps1 files from this project and therefore wont lint it. I am using Megalinter in another private repo with a similar Megalinter config and there everything works as expected.

**To Reproduce**
Have a look at the Megalinter log over here:  
https://github.com/Romanitho/Winget-AutoUpdate/actions/runs/4562835005/jobs/8050553981?pr=309#step:4:79
It says it checks for ps1 files, but it doesnt find even 1. But there are multiple ps1 files in the repo.

**Expected behavior**
PS1 file to get detected and linted afterwards.

**Screenshots**

**Additional context**
Megalinter config file: https://github.com/Romanitho/Winget-AutoUpdate/blob/main/.github/workflows/mega-linter.yml

**Comment by Kurt-von-Laven** [comment]
That job output is from an incremental run triggered by a pull request that only modified a single YAML file. Note https://github.com/Romanitho/Winget-AutoUpdate/blob/2e7f8ba28133971c3a0ff0631de7a1953d453730/.github/workflows/mega-linter.yml#L48. FYI: you are using the outdated megalinter/megalinter action rather than oxsecurity/megalinter, although this is presently asymptomatic.

**Comment by FaserF** [comment]
Thank you, I did never knew that. And also thanks for the extra hint 👍🏼

**Comment by Kurt-von-Laven** [comment]
That job output is from an incremental run triggered by a push to `main`. Incremental runs are relative to the default branch by default, so MegaLinter correctly calculates that there is no difference between `origin/HEAD` and `main`. Please replace `master` with `main` on the line I linked previously.

**Comment by FaserF** [comment]
Thank you very much for your explanation and patience. Now I have understood it.

**Comment by Kurt-von-Laven** [comment]
No problem. Let us know if you experience further issues!
