### ISSUE TITLE
markdown-link-check in megalinter ignores .markdown-link-check.json in 6.21.0

### ISSUE THREAD

**Issue by ruzickap** [oxsecurity/megalinter#2498]
**Describe the bug**
I'm using `.markdown-link-check.json` to configure MegaLinter's markdown-link-check checker.
The configuration file `.markdown-link-check.json` was used by the markdown-link-check, but something has changed in megalinter `6.21.0` and this config file is ignoerd in this version. 

There was some change in the `6.21.0` related to `markdown-link-check` but I'm not sure if it is relevant: https://github.com/oxsecurity/megalinter/pull/2479.

**To Reproduce**

Try to create `.markdown-link-check.json` https://github.com/ruzickap/ruzickap.github.io/blob/main/.markdown-link-check.json which should have some effect and then run with megalinter `6.20.1` vs `6.21.0`

**Expected behavior**

If `.markdown-link-check.json` file exists then MegaLinter's markdown-link-check checker should used it like if was before 6.21.0 version

**Comment by DariuszPorowski** [comment]
issue confirmed, @Kurt-von-Laven pls revert markdown-link-check to 3.10.3
