### ISSUE TITLE
False positive on CSpell due to @cspell/dict-win32 not being recognized

### ISSUE THREAD

**Issue by mwarres** [oxsecurity/megalinter#2500]
**Describe the bug**
When we run CSpell through MegaLinter in CI, "nanoserver" and "ltsc", which are words in the CSpell's `win32` dict, come up as false positives despite us having installed and configured the `win32` dict.

**To Reproduce**

1. Run `yarn init`.
1. Run `yarn add --dev @cspell/dict-win32@2.0.1`.
2. Paste in a minimal CSpell config that includes the CSpell win32 dict.
3. Paste in a minimal MegaLinter config.
4. Make a file containing the strings "ltsc" and "nanoserver".
5. Make a GitHub Action test workflow to run MegaLinter.
6. Push to GitHub and note that CSpell incorrectly fails on the words "ltsc" and "nanoserver".

Here is a [minimum reproduction](https://github.com/mwarres/CSpell-Bug)

Here is the PR where we had this problem: ScribeMD/docker-cache#475

**Expected behavior**
Expect CSpell to pass on the words "ltsc" and "nanoserver".

Thank you for your help!!!

**Comment by Kurt-von-Laven** [comment]
Notably, the issue does not occur when running CSpell directly (e.g., `npx cspell@6.31.1 .`). As a workaround, one can install the unbundled dictionary in question using a pre-command in one's MegaLinter config:

```yaml
SPELL_CSPELL_PRE_COMMANDS:
 - command: "npm install @cspell/dict-win32@2.0.1"
```

Does anyone have any theories as to why CSpell wouldn't be able to import a dictionary when run through MegaLinter?

**Comment by nvuillam** [comment]
I see you found a workaround, I close the issue :)
Please reopen if you think something can be done within MegaLinter (apart from adding all dictionaries by default in the docker image)

**Comment by Kurt-von-Laven** [comment]
Duplicate #1572 since this is also caused by the fact that CSpell can't see Yarn dependencies when not run via Yarn. This issue would also be addressed by accepting arrays in `_CLI_EXECUTABLE`, thereby allowing users to run CSpell via Yarn. Still open to better ideas.
