### ISSUE TITLE
Bot account for commits triggered by MegaLinter

### ISSUE THREAD

**Issue by lars-reimann** [oxsecurity/megalinter#2502]
**Is your feature request related to a problem? Please describe.**
The commits created when `APPLY_FIXES_MODE` is set to `commit` are by default attributed to `github-actions[bot]` and the author of the previous commit. I think it might be a decent advertisement if the commit were instead associated with the MegaLinter.

**Describe the solution you'd like**
Some other tools like `semantic-release` have an extra account for the commits they create (https://github.com/semantic-release-bot in this case). This account then shows up as a contributor to  a project.

![image](https://user-images.githubusercontent.com/2501322/229175300-c1d7dc32-191e-469a-8c7b-3d334736aac6.png)

MegaLinter could also have a [bot account](https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#personal-accounts) like `megalinter-bot`. When calling [stefanzweifel/git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action) in `.github/workflows/mega-linter.yml`, `commit_user_name` and `commit_user_email` could then be changed to point to this account.

**Additional context**

* [GitHub Account requirements](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-account-requirements):
  > You may maintain no more than one free machine account in addition to your free Personal Account.

**Comment by nvuillam** [comment]
That's a very interesting idea :)

Basically, you mean that if we create a second account named megalinter-bot, we just have to change the params sent to git-auto-commit-action, and that's all to see added commits performed by megalinter-bot ? No need for maintainers to provide the user some rights on their repo for example, as their PAT is enough  ?

**Comment by lars-reimann** [comment]
Yes, exactly.

**Comment by nvuillam** [comment]
It's on the way :)
