### ISSUE TITLE
Updating checkov version while keeping  megalinter release version

### ISSUE THREAD

**Issue by dgteixeira** [oxsecurity/megalinter#2503]
**Is your feature request related to a problem? Please describe.**
Whenever we upgrade megalinter's version in our GitHub actions, we get tons of new checkov validations, that are hard to manage so many at a single point in time.

This way, we would like to be able to get the daily checkov updates, while maintaining megalinter's version.

We are currently using megalinter as a reusable workflow for our company, being used by hundreds of repositories.

**Describe the solution you'd like**
I would like to be able, through a megalinter flag like `update_checkov_latest = true` on `.megalinter.yml`, to be able to use checkov's most recent version whenever the github triggers our megalinter github action.

**Describe alternatives you've considered**
We have thought about using `beta` version of megalinter, but that sometimes brings breaking changes, which then affects every single repository.
If we had a flag, in each repo stating if we want the latest checkov version, it would be each teams decision.

**Additional context**

On the latest megalinter upgrade, from `6.19.0` to `6.21.0` we got over 15 new validations across some repositories, that would be easier to manage if they would be caught whenever checkov launched them.

**Comment by nvuillam** [comment]
I think that the best is always to use latest version of MegaLinter, especially because of new security checks that are brought in each new ML version :)

If some linter (checkov or other) bothers you with issues that you consider bot relevant, you can make them not blocking using property DISABLE_ERRORS_LINTERS :)

https://megalinter.io/latest/configuration/#activation-and-deactivation

**Comment by Kurt-von-Laven** [comment]
He has a point that Checkov was on 2.1.244 from MegaLinter v6.11.0 through v6.19.0, inclusive, but I see that it's been upgraded in every release since then. I'm guessing I must have missed the fact that someone already automated Checkov updates? If so, this issue can probably be closed.

**Comment by nvuillam** [comment]
@Kurt-von-Laven checkov upgrade is automated from the beginning, but because of multiprocessing-logging crash with latest python version, it was "blocked" on its higher version compliant with our python version ^^
Now python has been upgraded, it's all ok :)

**Comment by Kurt-von-Laven** [comment]
Oh, I see. @dgteixeira, does that address your concern going forward?

**Comment by dgteixeira** [comment]
hey everyone, thanks a lot for your responses!

Yeah @Kurt-von-Laven, that actually addresses our concerns!
Since we use dependabot for our megalinter reusable workflow, we can closely keep track of the megalinter (and respective checkov) updates.

Since the checkov update issue was fixed, I believe that this won't be a big problem going forward.

I will close this issue now, thanks a lot for the help!
