### ISSUE TITLE
HTML comment being displayed on PR Reporter emails

### ISSUE THREAD

**Issue by ashokm** [oxsecurity/megalinter#2519]
Since [MegaLinter v6.22.1](https://github.com/oxsecurity/megalinter/releases/tag/v6.22.1), the PR HTML emails are now showing this at the end of the email body:
```
<!-- MegaLinter Status Report -->
```

**Comment by nvuillam** [comment]
If it is HTML, html comments should not be displayed:(

On which CI service do you see that ?

Please could you post a screenshot here ?

**Comment by nvuillam** [comment]
Fix is on its way :)

**Comment by nvuillam** [comment]
@ashokm it should be ok with latest patch :)
