### ISSUE TITLE
New linter idea: woke

### ISSUE THREAD

**Issue by DariuszPorowski** [oxsecurity/megalinter#2535]
**Is your feature request related to a problem? Please describe.**

Idea is to add https://github.com/get-woke/woke as part of the megalinter. Woke scans source code for non-inclusive language and suggest alternatives.

**Describe the solution you'd like**

woke part of megalinter

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by nvuillam** [comment]
I think it will be red for 99% of the repos, including MegaLinter, but progress is also driven by open source, so I'd be glad to accept the PR ;)

You can flag it as a formatter so it won't be blocking by default:)

**Comment by nvuillam** [comment]
@DariuszPorowski still interested to add this linter someday ? :)

**Comment by DariuszPorowski** [comment]
@nvuillam yep, even have (almost) working code... minor adjustments required, but before I open PR for this one i want to make sure this PR is closed: https://github.com/oxsecurity/megalinter/pull/2504 gentle follow-up for review :)

**Comment by nvuillam** [comment]
@DariuszPorowski I made too many (great !) enhancements , and now the current main branch is kind of broken ... so all PR CI jobs are broken ... but when I'll have solved https://github.com/oxsecurity/megalinter/pull/2611 , all the other PR's will be revived, including yours of course :)

**Comment by DariuszPorowski** [comment]
Just thinking more about this proposal... , woke is great but it looks like it's a stale project and not maintained anymore :(

**Comment by Kurt-von-Laven** [comment]
Thanks for letting us know. Yeah, that is an important consideration since we don't want our users stuck in a situation where a security vulnerability isn't addressed in a timely manner. Closing this issue for now then, but anyone should feel free to request that it be reopened if woke becomes actively maintained in the future.

**Comment by nvuillam** [comment]
@DariuszPorowski thanks for the heads up, indeed in v7 we remove linters not maintained for a while , so it would be sad to add a new one ^^
