### ISSUE TITLE
Azure comments reporter duplicates comments

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2545]
@nvuillam according to the code in theory it checks if it exists and if so tries to delete it before:

https://github.com/oxsecurity/megalinter/blob/8bec7d60318ebfd366ffc71374266659ba2cdb98/megalinter/reporters/AzureCommentReporter.py#L103

In my case, it is still there and creates a new one:

The problem of this apart from the flood of comments is that if you have a policy that forces to resolve the comments, if you make 10 push and generates 10 comments you have to mark the 10 as resolved...

**Comment by nvuillam** [comment]
@bdovaz I have several pro repos that work well with the removal of previous MegaLinter threads

Maybe it's something about the Build Service rights ?

**Comment by bdovaz** [comment]
@nvuillam should I see an error in the Azure DevOps Python library? Because if it's an error it's silent/non-harmful as everything "works", i.e. it doesn't delete the thread but it creates a new one.

How can I diagnose it to see if it is a permissions issue? Thanks!

**Comment by nvuillam** [comment]
I might have been a little bit lazy when implementing the update... I don't check for the API responses on this part :/

The solution would be to get the API result of calls to git_client.xxx in a variable, and display it as a warning when it is not the expected result

https://github.com/oxsecurity/megalinter/blob/8bec7d60318ebfd366ffc71374266659ba2cdb98/megalinter/reporters/AzureCommentReporter.py#L104

**Comment by bdovaz** [comment]
@nvuillam I'm taking a look at all this but I suspect that it's not actually showing an error, it has to be something else.....

Every time a request is made, if it failed for some reason, an exception should pop up:

https://github.com/microsoft/azure-devops-python-api/blob/252a2769de134f150ddbb38eb363a7a0f1f9b699/azure-devops/azure/devops/client.py#L68

https://github.com/microsoft/azure-devops-python-api/blob/252a2769de134f150ddbb38eb363a7a0f1f9b699/azure-devops/azure/devops/client.py#L263

Could it be that for some reason the reporter does not find the comment? Maybe this logic is failing in some cases?

https://github.com/oxsecurity/megalinter/blob/8bec7d60318ebfd366ffc71374266659ba2cdb98/megalinter/reporters/AzureCommentReporter.py#L92

How can I test this script on my own? How did you do the tests in a fast way?

**Comment by bdovaz** [comment]
@nvuillam I see that in this PR you made changes but apparently everything matches: #2521

**Comment by nvuillam** [comment]
I used MegaLinter on a professionnal project today... and comments were not duplicated ^^

Maybe something about rights... would it be possible that some user has the rights to post a new thread but not read existing ones ?

**Comment by bdovaz** [comment]
@nvuillam but did you read what I said? In the Python API depending on the status code throws exceptions.

In my case I don't get any exceptions, apparently it doesn't seem to be a permissions issue.

Anyway, as I have already said, can you think how I can run the reporter locally? How did you do it when you created this PR?

**Comment by nvuillam** [comment]
@bdovaz yes I read, but maybe you have access to the resource, not the content of the resource (which could be filtered), and that would just return an empty result, not an error

For my dev, I played with "quick build" commits and used the branch docker image for my tests :/

**Comment by bdovaz** [comment]
@nvuillam but what I do not understand is what permissions I have to check at the level of operations on threads? As far as I know, the only permissions that can be configured is at the repository operations level. The reporter uses the $(System.AccessToken) variable not a manually generated PAT with specific permissions.

In fact, in the documentation it does not mention anything about configuring permissions other than "Contribute to Pull Requests" as it is logical that it has it, however, this permission has nothing to do with what we are talking about.

https://megalinter.io/latest/reporters/AzureCommentReporter/

**Comment by nvuillam** [comment]
I am a beginner in azure permissions :/

I think the only way is to add debug logs to the reporter to see what those api return:/

**Comment by bdovaz** [comment]
It seems to be working fine now, I don't know the reason, if it comes back I will reopen it.

**Comment by nvuillam** [comment]
Cross-fingers ^^
