### ISSUE TITLE
Discussion on enabling merge queues

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#2554]
I wanted to collect thoughts on enabling merge queues for the megalinter repo.

It could maybe help out when I'm the weekends or near releases when we want to merge multiple PRs in a short lapse of time. We could add to a queue and "forget", ie, not go back to merge after waiting for another PR to finish.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

One situation that we might need to handle is that the temporary branches are read-only, so we must not have automatic fixes get applied.

But on the other hand, probably that the auto-update linters automatic PR when there is a push to main could be batched for a single merge queue, so not overloading our concurrent workers when we want to use them.

**Comment by nvuillam** [comment]
Interesting idea, I didn't know about this feature :)
But what would be the difference with merging 3 PR in the same 10 mn ? ( I happen to do that when CI test jobs are OK and I know that there won't be interferences between the PRs)

**Comment by echoix** [comment]
It will make the CI checks on all PRs, but by testing what the main will be when the PRs in front of it will be merged. If one PR's check fails, it is removed from the queue, and the other PRs in the queue continue to be checked (but with the will-be-main without that failing PR)

https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

That's what I understand

**Comment by Kurt-von-Laven** [comment]
@nvuillam, administrators can [use their special powers to bypass the merge queue at their discretion](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue#adding-a-pull-request-to-a-merge-queue).
