### ISSUE TITLE
Gitlab Reporter - error on multiple pipeline run  

### ISSUE THREAD

**Issue by GeneralLuzi** [oxsecurity/megalinter#2561]
**Describe the bug**
_First:_
I have a MR, in which the gitlab comment reporter successfully reported the summary of the mega-linter run into the comment section within this MR. After a second commit within this MR, the second mega-linter run should also report into the comment section within this MR, but it did not happen. What surprises me is the log of the pipeline, which confirm the successful comment to the MR:
```
GitlabCommentReporter run: [update-ca-certificates] in cwd [/]
GitlabCommentReporter 
[Gitlab Comment Reporter] Posted summary as comment on XXX-service #MR948
```

_Second:_
After several commits i got also this warning:
```
GitlabCommentReporter run: [update-ca-certificates] in cwd [/]
GitlabCommentReporter 
/megalinter/reporters/GitlabCommentReporter.py:123: UserWarning: Calling a `list()` method without specifying `get_all=True` or `iterator=True` will return a maximum of 20 items. Your query returned 20 of 22 items. See https://python-gitlab.readthedocs.io/en/v3.13.0/api-usage.html#pagination for more details. If this was done intentionally, then this warning can be supressed by adding the argument `get_all=False` to the `list()` call. (python-gitlab: /usr/local/lib/python3.11/site-packages/python_gitlab-3.13.0-py3.11.egg/gitlab/client.py:981)
  existing_comments = mr.notes.list()
[Gitlab Comment Reporter] Posted summary as comment on XXX-service #MR948
```

**To Reproduce**

1. Create MR
2. Verify, if the gitlab comment reporter successfully reported the summary of the mega-linter run into the comment 
3. Change something, e.g. within the config file of MegaLinter --> log level
4. Commit and let the pipeline finish
5. Verify, if the gitlab comment reporter successfully reported the summary of the second mega-linter run into the comment (in my case it doesent
6. repeat steps 3-6 as often you want

**Expected behavior**
Every gitlab comment reporter run should successfully report the summary of the mega-linter run into the comment of the MR.

**Screenshots**
no

**Additional context**
no

**Comment by nvuillam** [comment]
The first comment is edited with the new MegaLinter results, to avoid "spamming" the comments :)

But indeed it seems that as we retrieve only 20 comments, if the first one is not found, it's probably not edited !

Can you check again and confirm that the single MegaLinter comment contains the last status summary ?

If you really want a comment for each MegaLinter run, we could add an option but I don't think many people will use it

**Comment by GeneralLuzi** [comment]
I created a new MR to enabled MegaLinter. The first comment was created by MegaLinter. 

My Suggestions:
1. Please document this anti-spamming feature on the webpage.
2. Change the logs of the Megalinter run. They indicate the successful commenting within the MR not knowing of this anti-spam feature
4. New Feature "MegaLinter Widget on MR Summary page" instead of having comments. With this you are always the last run on the summary page
5. Alternative: New Property "Report only diffs": If a commit don't change the results of the previous MegaLinter result, I would not expect to get a comment. Really nice would be a new column to have the change, e.g. pmd Errors: 3 Previous: 2
6. Alternative: New Property "Skip-Next-Comments": I would like to change to "20" and adjust it to a number I like.

**Comment by nvuillam** [comment]
1 > In PR to come ( set `GITLAB_COMMENT_REPORTER_OVERWRITE_COMMENT: false` if you want one comment by MegaLinter run)

2 > In PR to come: Message different if new PR comment or updated PR comment

3 > Are you talking about [that](https://docs.gitlab.com/ee/development/fe_guide/merge_request_widget_extensions.html) ? If so, I don't have knownledge about it but I'd be happy to accept a PR :)

4 > That would require to store the results in JSON format between runs, and read them again to compare etc... If MegaLinter was a centralized SAAS Service it wouldn't be so complicated, but MegaLinter is just an open-source docker image posting comments... if you really want such functions, I'd advise you to use paying tools like SonarQube, CodeScene, Codeacy, etc...

5 > I don't understand the request: either you want to update existing comment, either you want to post a new one, so why changing the number of returned results ?
Note: in the PR to come, I added a parameter to list all notes so MegaLinter won't be limited to 20 anymore
