### ISSUE TITLE
write megalinter-reports as current user instead of root

### ISSUE THREAD

**Issue by gbrandt1** [oxsecurity/megalinter#2594]
i think it's quite annoying and unneccessary that megalinter-reports/ gets written as the root user.
especially for users that don't have sudo rights to fix it.
i guess this comes from running the docker container as root and ignoring the current user.

it would be better to either run as the current user, or change the owner of megalinter-reports to the current user by default.

a --user option should be added to mega-linter-runner.

cheers,
gerhard

**Comment by nvuillam** [comment]
Related to https://github.com/oxsecurity/megalinter/pull/1985
cc @Kurt-von-Laven

**Comment by Kurt-von-Laven** [comment]
Duplicate #1975. I recommend using rootless Docker in the meantime. See [ScribeMD/rootless-docker](https://github.com/ScribeMD/rootless-docker) for a GitHub Actions that does this.
