### ISSUE TITLE
`FileNotFoundError: [Errno 2]` when starting MegaLinter

### ISSUE THREAD

**Issue by RVetas** [oxsecurity/megalinter#2612]
**Describe the bug**
Every time I try to use mega-linter with its runner, or via docker, I get an error.

**To Reproduce**
**option 1**
run `npx mega-linter-runner --flavor ci_light`
**option 2**
run `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:rw -v /Users/myuser/myworkspace:/tmp/lint:rw oxsecurity/megalinter-ci_light:v6`

```
myuser % npx mega-linter-runner --flavor ci_light
Pulling docker image oxsecurity/megalinter-ci_light:v6 ... 
INFO: this operation can be long during the first use of mega-linter-runner
The next runs, it will be immediate (thanks to docker cache !)
v6: Pulling from oxsecurity/megalinter-ci_light
Digest: sha256:9c5732d3ec72418512120d4f19f335cf40cd6a37d4f3b1114e4047254f369430
Status: Image is up to date for oxsecurity/megalinter-ci_light:v6
docker.io/oxsecurity/megalinter-ci_light:v6
Command: docker run -v /var/run/docker.sock:/var/run/docker.sock:rw -v /Users/myuser/myworkspace:/tmp/lint:rw oxsecurity/megalinter-ci_light:v6
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Skipped setting git safe.directory DEFAULT_WORKSPACE:  ...
Setting git safe.directory default: /github/workspace ...
Setting git safe.directory to /tmp/lint ...
[MegaLinter init] ONE-SHOT RUN
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 9, in <module>
    linter = megalinter.Megalinter({"cli": True})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/MegaLinter.py", line 59, in __init__
    self.initialize_output()
  File "/megalinter/MegaLinter.py", line 737, in initialize_output
    os.makedirs(self.report_folder, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lint/megalinter-reports'
[config] Environment variables only (no config file found in /tmp/lint)
```
**Expected behavior**
Linter is working.

**Screenshots**
Screenshots is not applicable

**Additional context**
Mac Mini, Apple M1, macOS 12.6

**Comment by Kurt-von-Laven** [comment]
It seems like MegaLinter isn't finding a config file.

> Run `npx mega-linter-runner --install` to generate configuration files (you need [node.js](https://nodejs.org/en/) to be installed) ~ https://megalinter.io/6.22.2/quick-start/

**Comment by echoix** [comment]
It's pulling the amd64 image from a M1 mac, (arm64). @Kurt-von-Laven  What were the workaround steps that finally worked for others, for the time that we will come through the multi platform images?

**Comment by Kurt-von-Laven** [comment]
Good point! I still recommend running `npx mega-linter-runner --install`, but it's possible it isn't strictly necessary. Is https://github.com/oxsecurity/megalinter/issues/2427#issuecomment-1456554964 what you had in mind?

**Comment by echoix** [comment]
> Good point! I still recommend running `npx mega-linter-runner --install`, but it's possible it isn't strictly necessary. Is https://github.com/oxsecurity/megalinter/issues/2427#issuecomment-1456554964 what you had in mind?

If that works, yes that's what I had in mind. It's not the first time we get asked.

**Comment by nvuillam** [comment]
Maybe it is a write rights issue ? -> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lint/megalinter-reports'

Could eventually be solved by send REPORT_FOLDER=none

**Comment by RVetas** [comment]
Thanks for your answers, but I still struggle to run mega-linter.

> It seems like MegaLinter isn't finding a config file.
> Run npx mega-linter-runner --install to generate configuration files (you need [node.js](https://nodejs.org/en/) to be installed) ~ https://megalinter.io/6.22.2/quick-start/

I have configuration file in the directory where I start mega-linter (file called `.mega-linter.yml`), and I also tried to follow your advice running `--install` option. It didn't help.

> Could eventually be solved by send REPORT_FOLDER=none
I tried `REPORT_FOLDER: none` and `REPORT_FOLDER: false`, but it didn't work for me.

Do you have any other suggestions?

**Comment by Kurt-von-Laven** [comment]
Did you see the comment I linked to above?

**Comment by Kurt-von-Laven** [comment]
Good find. Have you already double-checked the permissions and ownership of the workspace?
