### ISSUE TITLE
Do not run the slash command dispatcher if the comment is not in a pull request

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#2614]
**Describe the bug**

The slash-command-dispatcher workflow runs on every single comment in the repo, and the github script step fails to find the PR fields when the issue is a real issue (instead of when the issue is a PR, like when we need to get the correct branch to checkout for the build command).

**To Reproduce**

1. Go to '…'
2. Click on '….'
3. Scroll down to '….'

**Expected behavior**

The solution might be to fix the github script, or limit the commands to only run on PR comments (thus preventing to use a command for issues in the future). For now, I'm thinking about the second option. 
Something adapted from: 
```yaml
if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')

```
As shown in https://dev.to/zirkelc/trigger-github-workflow-for-comment-on-pull-request-45l2

**Screenshots**

**Additional context**

**Comment by Kurt-von-Laven** [comment]
An `if` statement looks right to me and is [also recommended by the official GitHub Actions documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only).
