### ISSUE TITLE
fix: linter config file not found, `.github/linters/.eslintrc.yml`

### ISSUE THREAD

**Issue by seantrane** [oxsecurity/megalinter#2618]
**Describe the bug**
ESLint config is in standard, default location, but is not found by the `JAVASCRIPT_ES` activation.

**To Reproduce**

1. Store ESLint config in `.github/linters/.eslintrc.yml` file.
2. Run MegaLinter with `JAVASCRIPT` enabled.
3. Look for `[Activation] JAVASCRIPT_ES has been set to inactive` in the `stdout`.

**Expected behavior**
Find and load the config file.

**Screenshots**
<img width="972" alt="image" src="https://user-images.githubusercontent.com/1163842/236616285-23e9a506-185a-480d-b603-deecf0fe2e3e.png">

**Additional context**
I had a similar situation with Markdownlint, that I fixed by using `json` config file instead of `yml`. I will submit a separate issue for that.

**Comment by seantrane** [comment]
I tried using `.github/linters/.eslintrc.json` instead, but it did not find/load that config either. Only when I moved `.eslintrc.json` to repo root directory did it work as expected. I can confirm that the `.eslintrc.yml` file also worked when placed in repo root. So, it seems ESLint is not processing the `.github/linters` directory.

**Comment by nvuillam** [comment]
Please can you share your .mega-linter.yml config file ?

The unique default config file name is a known limitation, that we'll probably solve in a later version. ( for eslint, defaut config file name is .eslintrc.json )

You can also force the path to the config file using `JAVASCRIPT_ES_CONFIG_FILE` config var

-> https://megalinter.io/latest/descriptors/javascript_eslint/
