### ISSUE TITLE
golangci-lint: support autofix

### ISSUE THREAD

**Issue by seaneagan** [oxsecurity/megalinter#2679]
**Is your feature request related to a problem? Please describe.**
golangci-lint supports a --fix option, but it's not supported by megalinter:
https://golangci-lint.run/usage/configuration/#command-line-options

**Describe the solution you'd like**
APPLY_FIXES against GO_GOLANGCI_LINT results in `golangci-lint --fix ...`

**Describe alternatives you've considered**

Running golangci-lint manually outside megalinter

**Comment by echoix** [comment]
Since golang-ci is a Golang linter aggregator (compiled into one binary), and on their help page, they mention that the --fix option will work if it is supported by the linter, then for the tests file, we should find an error that is fixable by one of the linters to test that the option works when provided by MegaLinter.

**Comment by nvuillam** [comment]
I share @Kurt-von-Laven & @echoix 's opinion, that would be a good improvement :)

@seaneagan do you have an example of error that could be autofixed in this file ? https://github.com/oxsecurity/megalinter/blob/main/.automation/test/golang/golang_good_01.go

**Comment by seaneagan** [comment]
@nvuillam the unused variable check is enabled by default, and autofixing will remove the line where the variable is defined, so that might be a good option

**Comment by nvuillam** [comment]
Well, we'll see what CI jobs say in https://github.com/oxsecurity/megalinter/pull/2683 :)

**Comment by Kurt-von-Laven** [comment]
The call itself looks right to me based on [the docs](https://golangci-lint.run/usage/configuration#command-line-options), so I'm guessing we simply need a different example.

**Comment by seaneagan** [comment]
^ would also get rid of the deprecated linter usage (maligned, golint)

**Comment by nvuillam** [comment]
@seaneagan thanks, I try that :)

**Comment by nvuillam** [comment]
@seaneagan Still no fix with this update :/

https://github.com/oxsecurity/megalinter/actions/runs/5088248526/jobs/9144546351?pr=2683

Maybe you could try locally and provide the exact call and test file ?

**Comment by seaneagan** [comment]
sorry, i thought `unused` supported auto-fix but it doesn't, nor do any of the enabled by default linters. `gofmt` does though, so i'd suggest to add that to the list of `linters` in .golangci.yml.

Probably the most clear formatting mistake, which will get fixed by the above, will be to under-indent a line:
```
// This is a package comment
package main

import "fmt"

func nicolas() {
fmt.Println("hello world")
}
```

**Comment by nvuillam** [comment]
Thanks I try that :)

**Comment by nvuillam** [comment]
@seaneagan still KO :/

![image](https://github.com/oxsecurity/megalinter/assets/17500430/9c8fe2de-ab0f-465d-accc-5721da54eb65)

**Comment by seaneagan** [comment]
@nvuillam attempted to fix here: https://github.com/oxsecurity/megalinter/pull/2700

looks like it needs your approval to kick off the tests
