### ISSUE TITLE
MegaLinter V7 has been released :)

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#2692]
See release notes here -> https://github.com/oxsecurity/megalinter/releases/tag/v7.0.2

If you have any issue, please comment here :)

Click to see the video on Youtube, or check [LinkedIn post](https://www.linkedin.com/posts/nicolas-vuillamy_megalinter-v7-release-how-to-upgrade-activity-7069023353830789121-50p7?utm_source=share&utm_medium=member_desktop)

[![V7 release](https://img.youtube.com/vi/6NSBzq01S9g/0.jpg)](https://www.youtube.com/watch?v=6NSBzq01S9g)

## Impacting: Use of relative file paths to call linters

Now the linters are called with the relative file names, on contrary to the absolute file names used from the beginning of MegaLinter

Basically, for example we used to call `eslint /tmp/lint/myfolder/myfile.js` and now we call `eslint myfolder/myfile.js`

The only impacting issue seems to be with [PRE_COMMANDS](https://megalinter.io/latest/config-precommands/) that install additonal npm dependencies.

- pre-commands are executed in `/node-deps` ONLY if they contain `npm i` or `yarn add` AND if the cwd is "root" (which is by default). Before it used to be in `/node-deps` undepending the cwd value
- If they do not work with `cwd: root` , it will probably work with `cwd: workspace`
- If you see such impact on your repo , please notify here in a comment :)

### **Breaking changes**
  - **composer** is no longer in MegaLinter docker image. If you have PRE_COMMANDS using it, please install it previously with a PRE_COMMAND `apk install composer` (cf issue https://github.com/oxsecurity/megalinter/issues/2702 )

### **Pending**
  - Tiny issue with upgrader , check that the report folder is megalinter-reports before committing :) (Waiting for NPM internal bug fix)

### **Released in 7.0.3**
  - Issue with some regex values in FILTER_REGEX_EXCLUDE found by @ruzickap in https://github.com/oxsecurity/megalinter/issues/2697. Fixed in https://github.com/oxsecurity/megalinter/pull/2698

### **Released in 7.0.4**
  - tflint not working in v7.x.x (cf https://github.com/oxsecurity/megalinter/issues/2699). This is caused by GITHUB_TOKEN not sent anymore to `tflint --init`. This problem will be solved with PR https://github.com/oxsecurity/megalinter/pull/2703

**Comment by Kurt-von-Laven** [comment]
I still don't think we should change to `/node-deps` for Yarn commands. Yarn v2+ is installed locally, so it only makes sense to run Yarn commands in the workspace.

**Comment by nvuillam** [comment]
@Kurt-von-Laven if you define `cwd: workspace` in the workspace, it will be run in the workspace :)

**Comment by Kurt-von-Laven** [comment]
Right, but I don't see what purpose it could serve to `cd /node-deps` on `yarn add`.

**Comment by nvuillam** [comment]
@evg-tso released in 7.1.0 :)
