### ISSUE TITLE
Composer no longer available for PRE_COMMANDS in v7.0.x

### ISSUE THREAD

**Issue by iisisrael** [oxsecurity/megalinter#2702]
**Describe the bug**
Vendor packages need to be installed for PHPStan to analyze use of injected dependencies, and a `composer install` pre-command fails with a command not found error in v7.0.x.

**To Reproduce**

1. Configure a `PRE_COMMAND` in `.mega-linter.yml`
```
PRE_COMMANDS:
  - command: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --ignore-platform-req=ext-sockets --ignore-platform-req=ext-intl --ignore-platform-req=ext-fileinfo --ignore-platform-req=ext-sodium --ignore-platform-req=ext-posix --ignore-platform-req=ext-gd --ignore-platform-req=ext-xml
    cwd: "workspace"
```
2. Run version 7: `npx mega-linter-runner -r v7.0.3`
3. Note the output:
```
The MegaLinter documentation can be found at:
 - https://megalinter.io/7.0.3
----------------------------------------------------------------------------------------------------
MegaLinter initialization
MegaLinter will analyze workspace [/tmp/lint]

[Pre] run: [composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --ignore-platform-req=ext-sockets --ignore-platform-req=ext-intl --ignore-platform-req=ext-fileinfo --ignore-platform-req=ext-sodium --ignore-platform-req=ext-posix --ignore-platform-req=ext-gd --ignore-platform-req=ext-xml] in cwd [/tmp/lint]
[Pre] error:
/bin/bash: line 1: composer: command not found
```
4. Repeat on verson 6: `npx mega-linter-runner -r v6.22.2`
5. Note the output:
```
The MegaLinter documentation can be found at:
 - https://megalinter.io/6.22.2
----------------------------------------------------------------------------------------------------
MegaLinter initialization

[Pre] run: [composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --ignore-platform-req=ext-sockets --ignore-platform-req=ext-intl --ignore-platform-req=ext-fileinfo --ignore-platform-req=ext-sodium --ignore-platform-req=ext-posix --ignore-platform-req=ext-gd --ignore-platform-req=ext-xml] in cwd [/tmp/lint]
[Pre] Installing dependencies from lock file (including require-dev)
```

**Expected behavior**
Composer should install vendor packages on a pre-command.

**Comment by bdovaz** [comment]
Composer was removed when PHPLint was upgraded because it was the only one that used it and it was no longer needed in that case:

https://github.com/oxsecurity/megalinter/pull/2638/files#diff-ec327cc33365f46316d29b37a7ec42324bd935ed7114c8f9ea9c7febf1a10a83

@llaville who is the author of the PHPLint upgrade to v9 commented it, I have no experience in PHP linters so I followed his steps: https://github.com/oxsecurity/megalinter/issues/2483

cc @nvuillam @echoix @Kurt-von-Laven

**Comment by nvuillam** [comment]
@iisisrael I think if you add a PRE_COMMAND with `apk add composer` it should be ok :)

**Comment by nvuillam** [comment]
@iisisrael I'm glad your use case is solved :)
