### ISSUE TITLE
Devskim linter is failing is because it is identifying some key or token instances within the files generated by megalinter

### ISSUE THREAD

**Issue by Nadiahansen15** [oxsecurity/megalinter#2707]
Devskim linter is failing is because it is identifying some key or token instances within the files generated by megalinter, which are stored in the tmp/lint/.mypy_cache directory. These files are automatically created and managed by megalinter, and we do not have the ability to directly manipulate or influence them. Consequently, we have made the decision to disable the devskim linter temporarily, until a suitable resolution can be found.

<img width="461" alt="image" src="https://github.com/oxsecurity/megalinter/assets/50193195/ee98f61e-ec56-4a7e-9168-60ad8f55a297">

**Comment by Bigouden** [comment]
Temporary workaround

**Comment by nvuillam** [comment]
@Bigouden thanks for the workaround !
As mypy cache is probably boring to many linter, I wonder if making your workaround the default would help...

**Comment by Nadiahansen15** [comment]
I am still facing the same issue

**Comment by nvuillam** [comment]
@Nadiahansen15 do you still have DevSkim issues from Devskim with latest MegaLinter version whereas mypy cache is set our of the repo ?

**Comment by Nadiahansen15** [comment]
@nvuillam no it is no longer a problem

thank you

**Comment by nvuillam** [comment]
@Nadiahansen15 all good, thanks :)
