### ISSUE TITLE
Megalinter cannot post comments, but token has permissions?

### ISSUE THREAD

**Issue by lyricnz** [oxsecurity/megalinter#2711]
My GHA workflow includes:

```
jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions: write-all
```

and the run shows has the following permissions:

```
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```

But Megalinter still throws error:

```
[GitHub Comment Reporter] Unable to post pull request comment: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/issues#create-an-issue-comment"}.
To enable this function, please add permissions in your Github Actions Workflow:
permissions:
  issues: write
  pull-requests: write
```

Any ideas?

Sample run https://github.com/lyricnz/nbn-upgrade-map/actions/runs/5140357197/jobs/9251740644

**Comment by nvuillam** [comment]
@lyricnz GitHub comments reporter works if you have write permissions on the repo , but as your PR is from a fork, your GITHUB_TOKEN does not have permissions on the source repo :)

**Comment by lyricnz** [comment]
So it uses the source repo token, even though the action runs in the target repo?   Is the solution to use a PAT with access to the target repo?

**Comment by lyricnz** [comment]
This run _appears to be_ in the target repo. Same issue?
https://github.com/LukePrior/nbn-upgrade-map/actions/runs/5140357426/jobs/9251741121

**Comment by nvuillam** [comment]
I don't think repo owners will provide PAT to the fork owners , that wouldn't be much secure :D 

But if you want to see the comments, you can make another PR to your own fork repo, there you'll have the appropriate rights :)

**Comment by lyricnz** [comment]
I guess I just don't understand when it's going to commit (to a PR), when it's going to raise a PR, etc. Even when my PR with the deliberate formatting error was merged, nothing further happened. 

https://github.com/LukePrior/nbn-upgrade-map/pull/93
==> https://github.com/LukePrior/nbn-upgrade-map/actions/runs/5140799930

```
[Updated Sources Reporter] copied 1 fixed source files in folder /github/workspace/megalinter-reports/updated_sources.
Download it from artifacts then copy-paste it in your local repo to apply linters updates
```

**Comment by lyricnz** [comment]
I'll try APPLY_FIXES_EVENT: all

**Comment by lyricnz** [comment]
Saw the comment in the config file:
# Create pull request if applicable (for now works only on PR from same repository, not from forks)

**Comment by nvuillam** [comment]
Indeed MegaLinter is more powerful when you have write permissions to the main repo :)

It works as a standalone docker image, there is no "MegaLinter server" or "MegaLinter Github App" that could fetch your code and post comments or commits everywhere ^^
