### ISSUE TITLE
[clojure] cljstyle lint tool fails to run, unknown option -c

### ISSUE THREAD

**Issue by practicalli-john** [oxsecurity/megalinter#2716]
**Describe the bug**
cljstyle linter errors on unknown option "-c" with the MegaLinter v7 release.

Error occurs running mega-linter-runner locally or via MegaLinter GitHub Action, e.g. https://github.com/practicalli/clojure-cli-config/actions/runs/5159163975/jobs/9293737740

**To Reproduce**

1. Clone [practicalli/clojure-cli-config](https://github.com/practicalli/clojure-cli-config)
2. CLOJURE linter already enabled in `.github/config/megalinter.yaml` config
3. Ensure node.js is installed
4. Run `make lint` from the root of the cloned project, which run the megalinter using --flavor java
5. See error

**Expected behavior**
CLJSTYLE lint tool should run and with no errors reported

**Screenshots**

Output from running MegaLinter locally
```shell
❌ Linted [CLOJURE] files with [cljstyle]: Found 6 error(s) - (0.09s)
- Using [cljstyle v0.15.0] https://megalinter.io/7.0.4/descriptors/clojure_cljstyle
- MegaLinter key: [CLOJURE_CLJSTYLE]
- Rules config: [/.cljstyle]
- Number of files analyzed: [6]
[cljstyle] .github/config/clj-kondo-ci-config.edn - ERROR - 1 error(s)
--Error detail:
Unknown option: "-c"

[cljstyle] clojurescript-figwheel-experiments.edn - ERROR - 1 error(s)
--Error detail:
Unknown option: "-c"

[cljstyle] deps-deprecated.edn - ERROR - 1 error(s)
--Error detail:
Unknown option: "-c"

[cljstyle] deps.edn - ERROR - 1 error(s)
--Error detail:
Unknown option: "-c"

[cljstyle] rebel_readline.edn - ERROR - 1 error(s)
--Error detail:
Unknown option: "-c"

[cljstyle] tools/tools.edn - ERROR - 1 error(s)
--Error detail:
Unknown option: "-c"
```

**Additional context**
cljstyle linter added in PR https://github.com/oxsecurity/megalinter/pull/2115

**Comment by nvuillam** [comment]
@practicalli-john thanks for reporting, I think I found the issue: the default config argument name is `-c` , I try to remove it in a PR :)

**Comment by practicalli-john** [comment]
Thank you for the fast response.

cljstyle is working with the beta release when tested locally and picking up format issues correctly in my tests.

I'll document all the things done to make cljstyle work and see if I can add zprint as another clojure format tool.

Thank you for all the help getting this done.

**Comment by nvuillam** [comment]
You're welcome :)
