### ISSUE TITLE
Make container engine executable configurable by `mega-linter-runner`

### ISSUE THREAD

**Issue by sanmai-NL** [oxsecurity/megalinter#2723]
**Is your feature request related to a problem? Please describe.**
Some users don't use Docker Engine, but Podman, `nerdctl`, etc. Currently, to achieve that they have do tricks with `$PATH`, symlinks, etc.

**Describe the solution you'd like**
Make the container engine executable configurable, e.g., `docker` can be changed `podman` in the container engine invocation. Also make the parameters to be specified to the command and subcommand configurable.

**Describe alternatives you've considered**
I am working with the following work-around. This is pretty tricky, since some parameters have to be tailored to the `run` subcommand. This context discourages development of MegaLinter in the direction of portability.

```sh
#!/bin/sh
set -eux
if [ "$1" = 'run' ]; then
  shift
  exec podman run --security-opt label=disable --security-opt unmask=ALL --device /dev/fuse "$@"
else
  exec podman "$@"
fi
```

**Additional context**

**Comment by nvuillam** [comment]
@sanmai-NL MegaLinter is victim of its success, and its initial main use case ( that was to run on Github Actions or Gitlab CI ) is not just one of many other use cases :)

If you want to make PRs to mega-linter-runner to allow extra options that would make it compliant with podman or other container runners, they will be very welcome :)

**Comment by nvuillam** [comment]
@sanmai-NL would you be interested to make a PR ? :)

**Comment by sanmai-NL** [comment]
Yes, but I don't have time ...

**Comment by nvuillam** [comment]
That's what is great with open source contributions: there is no deadline ;)

**Comment by sanmai-NL** [comment]
Not stale

**Comment by nvuillam** [comment]
@sanmai-NL I reopen the issue, but my workload is crazy, someone else (you ? ^^) will have to make the PR :)
