### ISSUE TITLE
Verified creator flag in GitHub Marketplace

### ISSUE THREAD

**Issue by ruzickap** [oxsecurity/megalinter#2729]
Hello guys.

Would it be possible to make `oxsecurity/megalinter` marked as "Verified creator" please?

Example (https://github.com/marketplace/actions/renovate-bot-github-action):

![image](https://github.com/oxsecurity/megalinter/assets/1434387/1a6af1fe-fb73-4db3-b1e8-c3dc1f127a59)

Currently [MegaLinter](https://github.com/marketplace/actions/megalinter) doesn't have that "flag":

![image](https://github.com/oxsecurity/megalinter/assets/1434387/2343e54d-7001-4c0e-8f36-7ac98cc7dcb4)

Thank you...

**Comment by nvuillam** [comment]
That's a great idea :)

Now let's find how we can achieve that... :)

**Comment by ruzickap** [comment]
Thanks...
Are there any news?

**Comment by nvuillam** [comment]
@ruzickap in progress , thanks for reminding :)

**Comment by echoix** [comment]
Is it with that process that they can allow us to have a custom logo on the action?

**Comment by ruzickap** [comment]
Are there any news about it?

**Comment by nvuillam** [comment]
@ruzickap thanks for reminding :)

It is now ongoing, waiting for Github Approval :)

![image](https://github.com/oxsecurity/megalinter/assets/17500430/b8f01de7-d6cd-4111-bed9-3eb6caf7a61e)

**Comment by nvuillam** [comment]
ps: @ruzickap accept me on linkedIn if you want to be notified of any MegaLinter update in your feed ;)
