### ISSUE TITLE
New linter for toml files: `smol`

### ISSUE THREAD

**Issue by josecelano** [oxsecurity/megalinter#2732]
**Is your feature request related to a problem? Please describe.**

It's not a problem. I just would like to add a new linter for toml files.

**Describe the solution you'd like**

I would like to add a new linter: 

```s
taplo fmt --check Cargo.toml
```

**Describe alternatives you've considered**

I do not know any other toml file formatter.

**Additional context**

I think Toml files are very common in Rust. I want to format toml files in this project: https://github.com/torrust/torrust-index-backend/pull/116. I was considering adding taplo directly in a workflow but I would prefer to use MegaLinter because I can easily add more linter in the future.

**Comment by nvuillam** [comment]
hi @josecelano :)

taplo linter seems maintained, there is clearly a need to lint TOML files, so it seems to be a good candidate ! :)

https://github.com/tamasfe/taplo

My only question, on their README it says :

> The project is very young, so bugs and incomplete features are expected, so [any help is welcome](https://github.com/tamasfe/taplo/blob/master/CONTRIBUTING.md)!

> The correctness of the TOML parsing and decoding is not yet entirely guaranteed (as there is no official 1.0.0 compliance test suite yet).

As a taplo user, do you confirm that it is stable and evolved enough to be embedded in default MegaLinter, or maybe it is safer to just implement it as a [MegaLinter plugin](https://megalinter.io/latest/plugins/) before it is stabilized ?

**Comment by josecelano** [comment]
> hi @josecelano :)
> 
> taplo linter seems maintained, there is clearly a need to lint TOML files, so it seems to be a good candidate ! :)
> 
> https://github.com/tamasfe/taplo
> 
> My only question, on their README it says :
> 
> > The project is very young, so bugs and incomplete features are expected, so [any help is welcome](https://github.com/tamasfe/taplo/blob/master/CONTRIBUTING.md)!
> 
> > The correctness of the TOML parsing and decoding is not yet entirely guaranteed (as there is no official 1.0.0 compliance test suite yet).
> 
> As a taplo user, do you confirm that it is stable and evolved enough to be embedded in default MegaLinter, or maybe it is safer to just implement it as a [MegaLinter plugin](https://megalinter.io/latest/plugins/) before it is stabilized ?

Hi @nvuillam I'm not using it yet. I want to start using a toml formatted.

I did not know about plugins. I think a plugin would be ok. In fact, I do not know if there are other toml formatters that could be more mature or stable. I do not see many:

https://github.com/toml-lang/toml/issues/532

**Comment by nvuillam** [comment]
@josecelano I propose you to start with a plugin, then if we see it's great we move it as natively embedded linter ? :)

**Comment by vonbraunbates** [comment]
What's happened to supporting a(ny) TOML linter in Megalinter?  According to the Megalinter docs, we have some linters which only accept TOML config files (e.g [Black](https://megalinter.io/latest/descriptors/python_black/), [Ruff](https://megalinter.io/latest/descriptors/python_ruff/), [Gitleaks](https://megalinter.io/latest/descriptors/repository_gitleaks/)...) so it would be somewhat counter-intuitive to be unable to lint our own linter settings.

**Comment by echoix** [comment]
I or any of the maintainers here would be glad to review a PR for this. Is the status of taplo a bit better now?

**Comment by vonbraunbates** [comment]
Not a TOML expert (I'd never heard of it until I had to configure some linters), but I've done a quick round-up of parsers which support the TOML 1.0.0 standard and are recently maintained:

- https://github.com/ota-meshi/toml-eslint-parser was updated last month
- https://github.com/squirrelchat/smol-toml was udated 3 weeks ago
- https://github.com/tamasfe/taplo was updated last month but has 114 open issues

I suppose you should pick whichever integrates best with Megalinter, assuming any have reached a suitable stage of maturity. 🤷‍♀️ The ones I've ruled out are:

- https://github.com/sgarciac/bombadil is obsolete (doesn't support TOML 1.0.0)
- https://github.com/Gin-Quin/fast-toml is obsolete (doesn't support TOML 1.0.0)
- https://github.com/iarna/iarna-toml was last updated 2 years ago
- https://github.com/gscho/toml-lint was updated last year

**Comment by nvuillam** [comment]
@vonbraunbates many thanks for your benchmark :)

I'll write an issue on taplo repo to ask them if they can remove their warning message, as they now have 1.2K stars now :D

**Comment by echoix** [comment]
Taplo sadly doesn't seem like the best choice following this: https://github.com/tamasfe/taplo/issues/626#issuecomment-2184178594

**Comment by vonbraunbates** [comment]
@echoix fair enough.  What about https://github.com/ota-meshi/toml-eslint-parser or https://github.com/squirrelchat/smol-toml as options?

**Comment by vonbraunbates** [comment]
☝️ any updates on this please?  Currently Megalinter can't lint its own config files sine some linters only accept TOML config.

**Comment by nvuillam** [comment]
We could try smol :)

**Comment by vonbraunbates** [comment]
Should we change the title to `New linter for toml files: smol` then?

**Comment by nvuillam** [comment]
I don't see CLI instructions in the documentation...

I posted an issue to see if there is one, or if they are ok to build one :)

https://github.com/squirrelchat/smol-toml/issues/27
