### ISSUE TITLE
Add Gitpod for Easy Contributions

### ISSUE THREAD

**Issue by ThomasSanson** [oxsecurity/megalinter#2734]
**Is your feature request related to a problem? Please describe.**
Contributing to a new project often involves setting up a local development environment, which can be time-consuming and may deter potential contributors. This process can be particularly frustrating when the contributor simply wants to make a quick fix or add a small feature.

**Describe the solution you'd like**
I propose the addition of Gitpod to this project. Gitpod is a dev environment that spins up in seconds directly in your browser, allowing contributors to start coding immediately without the need to set up a local development environment. This would involve adding a `.gitpod.yml` file to configure the Gitpod workspace.

In addition, the contribution documentation located at [this link](https://github.com/oxsecurity/megalinter/blob/main/docs/contributing.md) would need to be updated to include instructions on how to use Gitpod for contributions.

**Describe alternatives you've considered**
An alternative could be to provide a detailed guide on setting up a local development environment for this project. However, this would still require time and effort on the part of the contributor, and would not provide the instant access that Gitpod offers.

**Additional context**
By lowering the barrier to entry for new contributors, we can encourage more participation in the project and potentially increase the speed and diversity of improvements and new features. I am happy to work on this if you agree.

**Comment by echoix** [comment]
I totally approve, that's what I use normally. I just don't configure it, and redo some steps to set the Python env and version, and install requirements.

Last time I tried the github codespaces with the devcontainers  contributed by a user didn't work, and couldn't load.

**Comment by ThomasSanson** [comment]
linked with #2399
