### ISSUE TITLE
Missing https://megalinter.io/7.1.0/ page

### ISSUE THREAD

**Issue by ashokm** [oxsecurity/megalinter#2743]
MegaLinter v7.1.0 has been [released](https://github.com/oxsecurity/megalinter/releases/tag/v7.1.0), but the https://megalinter.io site does not have 7.1.0 available in the dropdown:
![image](https://github.com/oxsecurity/megalinter/assets/1902568/8b923b2c-476a-4ac3-afae-e701620b5b08)
This results in https://megalinter.io/7.1.0/ not being available and redirects the user to https://megalinter.io/latest/

**Comment by nvuillam** [comment]
@ashokm documentation versioning is a little tricky... the latest version only exists at "latest" , so 7.1.0 will become available in the list only when 7.2.0 will be released !

I struggle to make the setup (as you can see in the Github Action Workflow -> https://github.com/oxsecurity/megalinter/blob/983cd4620e4f31e875a76515ac0c19bd1267bf32/.github/workflows/deploy-RELEASE.yml#L105 ) , to be honest I'm kind of afraid to touch it again :D
