### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by alamin655** [oxsecurity/megalinter#2750]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters: 

 - LUA_LUACHECK
 - RUST_CLIPPY
 - JAVASCRIPT_ES
 - CSS_STYLELINT
 - MARKDOWN_MARKDOWNLINT
 - YAML_YAMLLINT
 - HTML_DJLINT
 - ACTION_ACTIONLINT
 - DOCKERFILE_HADOLINT
 - SPELL_CSPELL

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
Mmmm what type of projects would use this flavor ?

Having Rust, LUA & javascript in the same repo doesn't look pretty common, is this a public project ?

**Comment by alamin655** [comment]
> Mmmm what type of projects would use this flavor ?
> 
> Having Rust, LUA & javascript in the same repo doesn't look pretty common, is this a public project ?

It is, indeed, a public project. A Rust-based metasearch engine.
https://github.com/neon-mmd/websurfx

**Comment by nvuillam** [comment]
I think that there is not enough projects of that type to create a new flavor with those linters

Do you really need to analyze LUA ?
If not, you can probably use RUST flavor :) 

https://megalinter.io/latest/flavors/rust/

**Comment by alamin655** [comment]
> I think that there is not enough projects of that type to create a new flavor with those linters
> 
> Do you really need to analyze LUA ? If not, you can probably use RUST flavor :)
> 
> https://megalinter.io/latest/flavors/rust/

But it doesn't have JS Linter.

**Comment by nvuillam** [comment]
@alamin655 indeed you can use MegaLinter own descriptors to add plugins, as they have the exact same format :)

**Comment by alamin655** [comment]
> @alamin655 indeed you can use MegaLinter own descriptors to add plugins, as they have the exact same format :)

Thank you for your help and this great tool.

**Comment by nvuillam** [comment]
@alamin655 you're welcome :)
