### ISSUE TITLE
v8r never displays errors even if there are errors

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2755]
It is forced not to display errors and is not configurable:

https://github.com/oxsecurity/megalinter/blob/dae6530e662c526c0509d69a7507a30544897d7d/megalinter/descriptors/yaml.megalinter-descriptor.yml#L99

I had to travel back in time to see when it was created and it was a very long time ago: https://github.com/oxsecurity/megalinter/pull/176

@nvuillam do you know why you did it? At least it should be configurable, right? Is there any example in another linter similar to this one?

**Comment by bdovaz** [comment]
I knew I forgot to clarify something and that is that the `-c` parameter in v8r has to do with something else:

![image](https://github.com/oxsecurity/megalinter/assets/950602/e02a11c8-71a4-4e40-9d33-cb45d85bccbf)

v8r automatically discovers the configuration file without doing anything:

![image](https://github.com/oxsecurity/megalinter/assets/950602/05eef323-67f5-48ce-8b8d-1e4d9a8837a1)

**Comment by bdovaz** [comment]
ping @nvuillam

**Comment by nvuillam** [comment]
@bdovaz the --ignore-errors is when there is no json schema found for the JSON/YML

But when a JSON schema is found, errors are displayed and return code = 1

Is it not the case anymore ?
