### ISSUE TITLE
v8r incorrectly adds the parameter -c

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#2756]
In https://github.com/oxsecurity/megalinter/pull/1982 I included in the descriptor the configuration file but only with the intention that it generates the associated documentation because if it has the `config_file_name` field it generates additional documentation.

But this causes it to erroneously add the `-c` parameter:

```
[v8r] command: ['v8r', '--ignore-errors', '-v', '-c', '/tmp/lint/.v8rrc.yml', 'file1.yml', 'file2.yml']
```

@nvuillam the only way to solve it is to create a class for this particular linter? There is no other way, is there?

**EDIT:**

I knew I forgot to clarify something and that is that the `-c` parameter in v8r has to do with something else:

![image](https://github.com/oxsecurity/megalinter/assets/950602/e02a11c8-71a4-4e40-9d33-cb45d85bccbf)

v8r automatically discovers the configuration file without doing anything:

![image](https://github.com/oxsecurity/megalinter/assets/950602/05eef323-67f5-48ce-8b8d-1e4d9a8837a1)

**Comment by nvuillam** [comment]
@bdovaz I think we can also add cli_config_arg_name = null is the descriptor :)
