### ISSUE TITLE
upgrade ansible-lint to latest

### ISSUE THREAD

**Issue by cloneluke** [oxsecurity/megalinter#2768]
**Is your feature request related to a problem? Please describe.**
There are a few critical bugs with ansible-lint 6.16.2 and would like to upgrade to latest to fix: https://github.com/ansible/ansible-lint/pull/3552
https://github.com/ansible/ansible-lint/pull/3527

**Describe the solution you'd like**
upgrade to latest https://github.com/ansible/ansible-lint/releases/tag/v6.17.2

**Describe alternatives you've considered**
no workarounds in ansible-lint

**Additional context**

**Comment by nvuillam** [comment]
@cloneluke ansible-lint was downgraded on purpose because of a crash with 6.17.0, but it seems it is fixed, let's see if CI jobs confirm that :)
