### ISSUE TITLE
devskim scans through linter cache of other linters

### ISSUE THREAD

**Issue by MRDGH2821** [oxsecurity/megalinter#2785]
**Describe the bug**
I have a repository which consists of codes of Java, Python, C & C++
So I'm using the default flavour of Mega Linter for this purpose.
Whenever I run Mega Linter, after mypy & ruff linters are done running and leaving behing their cache, devskim starts running & scans those cache folders & thus gives failure message.

As a remedy, I have put the cache folders in gitignore, `ADDITIONAL_EXCLUDED_DIRECTORIES` & `FILTER_REGEX_EXCLUDE`, but still devskim detects it.

**To Reproduce**
1. Have a code base with Python & some other programming language
2. Include Devskim, Ruff & Mypy linters (either implictily or explicitly)
3. Run Mega Linter

**Expected behavior**
Devskim should not be able to see any of those cache folders

**Screenshots**

In CI Mode:
![image](https://github.com/oxsecurity/megalinter/assets/46621001/e5eebd29-2775-478a-bee9-313ab50f4101)

In Local Mode:
![Screenshot 2023-07-11 190833](https://github.com/oxsecurity/megalinter/assets/46621001/67854cff-50da-4467-aeec-8cfcef11cf7e)

**Additional context**
This is my Repo - https://github.com/MRDGH2821/CodersPack
It doesn't require any specific API keys, so you can clone the repo and run mega linter locally

`.mega-linter.yml`
```yaml
APPLY_FIXES: all # all, none, or list of linter keys
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
CLEAR_REPORT_FOLDER: true
IGNORE_GITIGNORED_FILES: true
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - ".mypy_cache"
  - ".ruff_cache"
FILTER_REGEX_EXCLUDE: ".mypy_cache\/*|.ruff_cache\/*"
```
`.gitignore`
```
**/*.exe
.mypy_cache/
.ruff_cache/
megalinter-reports/
.pmdCache
```

CI Reports:
[MegaLinter reports (5).zip](https://github.com/oxsecurity/megalinter/files/12015365/MegaLinter.reports.5.zip)

**Comment by MRDGH2821** [comment]
I forgot to do my research on Devskim at Mega Linter website 😅
So I added the following config in `.mega-linter.yml`
```yaml
REPOSITORY_DEVSKIM_ARGUMENTS:
  - "--skip-git-ignored-files"
  - "--ignore-globs **/.mypy_cache/** , **/.ruff_cache/**"
 ```

But still I find errors locally (albeit an empty one):
![image](https://github.com/oxsecurity/megalinter/assets/46621001/67113547-2896-4b24-a555-43e4d4abe6f6)

Same goes for CI mode too:
![image](https://github.com/oxsecurity/megalinter/assets/46621001/20dd6a56-cc39-4be8-8a1a-d898aa9ce203)

CI Reports:
[MegaLinter reports (6).zip](https://github.com/oxsecurity/megalinter/files/12015504/MegaLinter.reports.6.zip)

**Comment by bradthurber** [comment]
@MRDGH2821, I am new to MegaLinter, but I think that #2764 may be involved somehow.

**Comment by MRDGH2821** [comment]
I think I should now rename this Issue (when I get back to PC) to `devskim throwing error even after the logs appear empty`

**Comment by MRDGH2821** [comment]
This issue is solved by adding the following config:

REPOSITORY_DEVSKIM_ARGUMENTS:
  - "--skip-git-ignored-files"
  - "--ignore-globs **/.mypy_cache/** , **/.ruff_cache/**"

**Comment by nvuillam** [comment]
Well done @MRDGH2821 , thanks for sharing the workaround with the community :)

**Comment by MRDGH2821** [comment]
You are welcome @nvuillam !

On that note, I feel that using this technique in other linters will help a lot, and would address #2764
