### ISSUE TITLE
Make issues

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#2791]
Does the makefile work on windows ? If not, it must be indicated in documentation :/

![image](https://github.com/oxsecurity/megalinter/assets/17500430/041d29b5-1588-42e8-bb69-b5ab76f491d3)

cc @ThomasSanson

**Comment by ThomasSanson** [comment]
Hmm, I'll make a note of that and have a look.

I'll need to find a Windows PC (which is uncommon around here) and give it a try!

For the first error, it says that python3.11 is missing (and probably python3-venv).

And for the second one, it's saying that sudo is missing.

Is it possible to try installing all three components on WSL2?

```bash
apt update && upgrade
apt install python3.11 python3-pip python3.11-venv sudo
```

**Comment by nvuillam** [comment]
@nvuillam WSL is not windows ^^
If it's not compliant with Windows, that can be ok, but in that case a clear message must tell it and redirect to the documentation explaining how to contribute without make stuff ^^

**Comment by echoix** [comment]
The windows setup you show is not pure windows setup. You show a mingw64 setup. For windows, there is also a WSL2 setup (WSL2 is a Linux running through Hyper-V, integrated, and the older WSL1 was something else that was a little less native linux, it had to be compiled for).

For now, it's not a surprise that the makefile is Linux only, there are many specific usages like "shell" "source" "sudo". Do we really have to try to fold ourselves to the specific requirements of a mingw environnement (vs minsys or wsl1 or wsl2).

**Comment by echoix** [comment]
Like it's simpler to use Gitpod on Windows in order to have a completely working env?

**Comment by ThomasSanson** [comment]
I plan to update the documentation to indicate that the Makefile section is currently not compatible with Windows. However, it's important to emphasise that a true developer doesn't work on Windows 😜.

On a more serious note, when we switch to Taskfile, it will be easier to handle different situations between Windows and Linux. At that point, we can implement more comprehensive modes.

However, I will need some help, please.

(P.S.: If I managed to switch my mother-in-law to Ubuntu, it's not for nothing 😉)

**Comment by nvuillam** [comment]
> However, it's important to emphasise that a true developer doesn't work on Windows 😜.

A true developer can develop on anything, even a raspberry pi 😄
