### ISSUE TITLE
Maintained version of misspell

### ISSUE THREAD

**Issue by girlpunk** [oxsecurity/megalinter#2823]
**Is your feature request related to a problem? Please describe.**
Misspell was previously removed as the original version, by client9, is not maintained. However, misspell provides a significantly better spelling check for code (such as variable names, etc) than any other linter offered by megalinter.

**Describe the solution you'd like**
Golang are maintaining a fork of misspell at [golangci/misspell](https://github.com/golangci/misspell). As such, I would like to suggest re-introducing misspell but from this fork rather than the original.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by girlpunk** [comment]
Still outstanding

**Comment by nvuillam** [comment]
@girlpunk the repo is still a fork, usually a hard-fork cuts links with the origin repo and announces it, do you think it would be possible that golang do that ?

**Comment by girlpunk** [comment]
I'm not sure unfortunately, beyond making use of it I don't have any relation with the fork.

**Comment by girlpunk** [comment]
Looks like they do intend to

https://github.com/golangci/misspell/issues/4#issuecomment-1687132016

**Comment by ldez** [comment]
Hello,

As you are using golangci-lint you are using already using our fork of misspell :smile: 

Hard forks are rare (at least on GitHub), we don't need to do that and it's weird regarding the original author.
Also being a "soft" fork allow users who are looking for a maintained fork to show our fork.

**Comment by nvuillam** [comment]
@ldez thanks for the precision :)

You might add in the README that you maintain this fork as the original repo is abandonware, so next person who wants to use it will already know ^^

Ps: cocorico 🐓

@girlpunk misspell is now eligible to be back within MegaLinter, woukd you like to make the PR ? :)
