### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by jmiller12-eogresources** [oxsecurity/megalinter#2829]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_PYLINT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_BANDIT, PYTHON_MYPY, PYTHON_PYRIGHT, PYTHON_RUFF, ACTION_ACTIONLINT, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, COPYPASTE_JSCPD, DOCKERFILE_HADOLINT, GO_GOLANGCI_LINT, GO_REVIVE, HTML_DJLINT, HTML_HTMLHINT, JAVASCRIPT_STANDARD, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MAKEFILE_CHECKMAKE, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, REPOSITORY_CHECKOV, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_KICS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY, TYPESCRIPT_STANDARD, XML_XMLLINT, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
Python + go ?

Why not, but please can you send links of multiple famous projects that use these stacks ?

Meanwhile, you can probably use cupcake flavor :)

https://megalinter.io/latest/flavors/cupcake/
