### ISSUE TITLE
TAP Reporter wrong YAML diagnostics format

### ISSUE THREAD

**Issue by maxilampert** [oxsecurity/megalinter#2835]
**Describe the bug**
I'm generating tap files to convert them to junit format for Azure DevOps this worked fine in the latest v6 release with v7 the conversion no longer works. I'm using tap-junit for the conversion.
The reason is the yaml diagnostics format characters have changed to a horizontal ellipsis instead of 3 dots which is required by the definition https://testanything.org/tap-version-14-specification.html

https://github.com/oxsecurity/megalinter/blob/504a03e2f0de7f76926cabedbbad842dc06e5752/megalinter/reporters/TapReporter.py#L69C76-L69C77

The issue has been introduced with #2568 

**To Reproduce**

1. Go to '…'
2. Click on '….'
3. Scroll down to '….'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nvuillam** [comment]
@maxilampert good catch, sorry for the bug !

PR on the way :)

**Comment by nvuillam** [comment]
Fix released in https://github.com/oxsecurity/megalinter/releases/tag/v7.2.1
