### ISSUE TITLE
Remove scss lint due to deprecation

### ISSUE THREAD

**Issue by waterfoul** [oxsecurity/megalinter#2840]
**Is your feature request related to a problem? Please describe.**
Due to the deprecation of ruby sass scss lint has also been deprecated. See https://github.com/sds/scss-lint for details

**Describe the solution you'd like**
Deprecate, then remove scss lint

**Describe alternatives you've considered**
Keep around a deprecated linter

**Comment by nvuillam** [comment]
@waterfoul you're totally right, thanks for the info !

I'll flag scss lint as deprecated and it will be removed in the next major version
