### ISSUE TITLE
MegaLinter 7.2.x - New Linters

### ISSUE THREAD

**Issue by VictorRos** [oxsecurity/megalinter#2844]
Hello!

MegaLinter `7.2.x` introduces 3 new linters:

- [lychee](https://megalinter.io/latest/descriptors/spell_lychee/) scans URLs and emails

   Markdown URLs scans is currently done by `markdown-link-check`

- [grype](https://megalinter.io/latest/descriptors/repository_grype/) is checking vulnerabilities like `checkov`

- [trufflehog](https://megalinter.io/latest/descriptors/repository_trufflehog/) is checking leaked credentials like `gitleaks`

How are they different from existing linters?

Should we replace the ones I mentioned with new ones? Or rather take time to configure them? Or worse case just disabling them?

My point is we might have false positives with similar linters if we don't configure them to trigger same errors when they are doing similar checks.
And it can been painfully to fine-tune the configuration.

What approach do you take when faced with this situation?

**Comment by nvuillam** [comment]
Hi Victor :)

Lychee scans links in all files whereas markdown-links-check just handles markdown :)
And lychee is much faster , so it's possible that markdown-links-check will be deprecated then removed in future major versions

About grype & trufflehog, they are indeed security linters than can check rules similar to gitleaks, checkov, kics, trivy...
Trufflehog directly interrogates the token providers (aws, GitHub, azure...) to see if they are active

In a general manner, nobody activate all rules of all linters , so if you think some of them are useless for your projects you can disable them or make them not blocking:)

**Comment by nvuillam** [comment]
Hi Victor :)

Lychee scans links in all files whereas markdown-links-check just handles markdown :)
And lychee is much faster , so it's possible that markdown-links-check will be deprecated then removed in future major versions

About grype & trufflehog, they are indeed security linters that can check rules similar to gitleaks, checkov, kics, trivy...
Trufflehog directly interrogates the token providers (aws, GitHub, azure...) to see if they are active

In a general manner, nobody activate all rules of all linters , so if you think some of them are useless for your projects you can disable them or make them not blocking:)
