### ISSUE TITLE
MegaLinter 7.2.x - Lychee - Link https://megalinter.io/config-file/ from .mega-linter.yaml is considered as an error

### ISSUE THREAD

**Issue by VictorRos** [oxsecurity/megalinter#2845]
**Describe the bug**

Link https://megalinter.io/config-file/ in file `.mega-linter.yaml` is a **404 not found** error for new linter [lychee](https://megalinter.io/latest/descriptors/spell_lychee/)

_Note:_ Calling https://megalinter.io/config-file/ in a browser redirects to https://megalinter.io/latest/config-file/

It may explain part of the problem.

**To Reproduce**

Run MegaLinter `7.2.x`.

In my case, MegaLinter `7.2.1`, current latest version.

**Expected behavior**

No error.

**Screenshots**

![image](https://github.com/oxsecurity/megalinter/assets/6940422/4d8b1abb-b2dc-45b4-85c4-2a3cd03aad58)

**Additional context**

None.

**Comment by daltonv** [comment]
I have also been seeing this exact issue.

**Comment by nvuillam** [comment]
You can run `npx mega-linter-runner@beta --upgrade` to solve the issue in your local config file :)
