### ISSUE TITLE
actionlint doesn't see property on action

### ISSUE THREAD

**Issue by mtirionMSFT** [oxsecurity/megalinter#2850]
**Describe the bug**
I'm using the GitHub standard actions/labeler@v4 in my workflow. The definition can be found here: https://github.com/actions/labeler. The https://github.com/actions/labeler/blob/main/action.yml has the 'dot' variable. 

The linter however says: 
input "dot" is not defined in action "actions/labeler@v4". available inputs are "configuration-path", "repo-token", "sync-labels" [action]
     |
  19 |           dot: true
     |           ^~~~

**To Reproduce**
Workflow:

name: "Pull Request Labeler"
on: pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: label-the-pr
        uses: actions/labeler@v4
        with:
          dot: true
          sync-labels: true

Run the linter. See the error.

**Expected behavior**
No error.

**Comment by nvuillam** [comment]
hi @mtirionMSFT , I think this is an issue for [actionlint](https://github.com/rhysd/actionlint) itself, because MegaLinter just calls it and do not alter its results :)

**Comment by mtirionMSFT** [comment]
You're completely right, my bad. Thanks :)

**Comment by nvuillam** [comment]
@mtirionMSFT no problem, i hope they'll be able to help you to solve your issue :)
