### ISSUE TITLE
Report in XML Nunit3?

### ISSUE THREAD

**Issue by hiran-filho** [oxsecurity/megalinter#2851]
Is there any functionality or provision for megainter to have a report in xml type NUnit3?

**Comment by nvuillam** [comment]
Hi @hiran-filho , thanks for your interest in MegaLinter !

Nunit seems to be more related to .NET test cases than SAST results, I'm not sure it is applicable to MegaLinter

Note: Common SAST results is [SARIF](https://sarifweb.azurewebsites.net/), which is supported by MegaLinter and more and more of its embedded linters

**Comment by hiran-filho** [comment]
@nvuillam, 
Thanks for your quick reply   
In my IT growth process, I'm growing in cloud infrastructure, that is, I'm increasing my knowledge of each provider, but I work using Azure Devops. In programming, I have some bash's scripts, so with a report in standardized JSON I would be able to assemble, with the help of an xml template, a report for this. I'm sorry if today I only have an idea and I haven't knowledge make it happen.
But do you intend to resume making the report in JSON or has it already been abandoned?
