### ISSUE TITLE
How to pass the BUILD_VERSION and MEGALINTER_FLAVOR arguments in .megalinter.yaml file?

### ISSUE THREAD

**Issue by jaskaran-virdi-imprivata** [oxsecurity/megalinter#2852]
**Describe the bug**
When running the megalinter locally, passing the `BUILD_VERSION` and `MEGALINTER_FLAVOR` as environment variables in the `.megalinter.yaml` file doesn't work. These variables get over-written by default arguments.

**To Reproduce**

1. Run `npx mega-linter-runner -e "'MEGALINTER_FLAVOR=ci_light'" -e "'LOG_LEVEL=DEBUG'" -e "'BUILD_VERSION=v7.2.0'"`
2. This works correctly. Can see the `MEGALINTER_FLAVOR =ci_light` and `BUILD_VERSION=v7.2.0` in the CLI logs.
3. Add `MEGALINTER_FLAVOR: ci_light` and `BUILD_VERSION: v7.2.0` to `.megalinter.yaml` file in the repository.
4. Run `npx-mega-linter-runner` on command line
5. The logs show `MEGALINTER_FLAVOR=all`, `BUILD_VERSION=v7.2.1`. The values have been over-written.

**Expected behavior**
After running step 4, the logs should show `MEGALINTER_FLAVOR=cli_light` and `BUILD_VERSION=v7.2.0`
**Screenshots**

**Additional context**

**Comment by jaskaran-virdi-imprivata** [comment]
Another relate issue when running megalinter on github actions - 

`❌ Linted [YAML] files with [v8r]: Found 1 error(s) - (3.76s) (expand for details)
  - Using [v8r v2.0.0] https://megalinter.io/7.2.0/descriptors/yaml_v8r
  - MegaLinter key: [YAML_V8R]
  - Rules config: identified by [v8r]
  - Number of files analyzed: [2]
  --Error detail:
  ℹ No config file found
  ℹ Processing ./.github/workflows/mega-linter.yml
  ℹ Found schema in https://www.schemastore.org/api/json/catalog.json ...
  ℹ Validating ./.github/workflows/mega-linter.yml against schema from https://json.schemastore.org/github-workflow.json ...
  ✔ ./.github/workflows/mega-linter.yml is valid
  
  ℹ Processing ./.mega-linter.yml
  ℹ Found schema in https://www.schemastore.org/api/json/catalog.json ...
  ℹ Validating ./.mega-linter.yml against schema from https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json ...
  ✖ ./.mega-linter.yml is invalid
  
  ./.mega-linter.yml# must NOT have additional properties
  ./.mega-linter.yml# must NOT have additional properties`
  
  When running megalinter on github actions, it validates the .megalinter.yml against json schema. That doesn't happen when running megalinter on local.

**Comment by nvuillam** [comment]
.mega-linter.yml is analyzed by MegaLinter when already running, you can't specify its version in it, but you can do it by :

- using the GitHub action version
- using arguments --flavor and --release with megalinter-runner :) (see examples here -> https://megalinter.io/latest/mega-linter-runner/#examples )

**Comment by nvuillam** [comment]
Note: The v8r error is probably related to a wrong property in your .mega-linter.yml file, if you share it we should be able to identify which one

**Comment by jaskaran-virdi-imprivata** [comment]
So, what I want to do is run the same release and flavor locally as what I have specified in the github action. The release and flavor to run should be setup automatically without having to specify it on the command line. 

For example: In the github action yaml file , I have : 
`- name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/flavors/
        uses: oxsecurity/megalinter/flavors/ci_light@v7.2.0`
        
To run the same config locally, I would have to do something like:
`npx mega-linter-runner --flavor ci_light  --release v7.2.0`

I would like the version and flavor of megalinter to be picked up automatically based on whichever repository it is running in.

In my use case, 
`npx mega-linter-runner` should run the megalinter with ci_light flavor and v7.2.0 release.

Do you have any recommendations on how to go about it?

**Comment by nvuillam** [comment]
Github Action and mega-linter-runner do not have the same entry point: 
- with Github Action the entry point is the docker image itself, as defined in the action.yml related to the Github Action version
- with mega-linter-runner, it's a npm package, that fetches the MegaLinter docker image

So if you really want to have the same call... for both CI and local, I don't see another choice than ... calling mega-linter-runner directly from your github action, instead of using ML GitHub Action

**Comment by nvuillam** [comment]
An alternative might also be to use [act](https://github.com/nektos/act) to run locally the ML GitHub Action, but I've not tested it myself

**Comment by jaskaran-virdi-imprivata** [comment]
I see. Regarding your comment about v8r error, I just added two environment variables - BUILD_VERSION and MEGALINTER_FLAVOR to the .mega-linter.yaml file. The github action throws the following error:

Linted [YAML] files with [v8r]: Found 1 error(s) - (3.76s) (expand for details)
  - Using [v8r v2.0.0] https://megalinter.io/7.2.0/descriptors/yaml_v8r
  - MegaLinter key: [YAML_V8R]
  - Rules config: identified by [v8r]
  - Number of files analyzed: [2]
  --Error detail:
  ℹ No config file found
  ℹ Processing ./.github/workflows/mega-linter.yml
  ℹ Found schema in https://www.schemastore.org/api/json/catalog.json ...
  ℹ Validating ./.github/workflows/mega-linter.yml against schema from https://json.schemastore.org/github-workflow.json ...
  ✔ ./.github/workflows/mega-linter.yml is valid
  
  ℹ Processing ./.mega-linter.yml
  ℹ Found schema in https://www.schemastore.org/api/json/catalog.json ...
  ℹ Validating ./.mega-linter.yml against schema from https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json ...
  ✖ ./.mega-linter.yml is invalid
  
  ./.mega-linter.yml# must NOT have additional properties
  ./.mega-linter.yml# must NOT have additional properties

**Comment by nvuillam** [comment]
BUILD_VERSION and MEGALINTER_FLAVOR are not described in the [JSON schema](https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json) because they would not be read by anything, that's what trigger the v8r error :)
