### ISSUE TITLE
Project .lycheeignore file and documentation is in incorrect format

### ISSUE THREAD

**Issue by andrewvaughan** [oxsecurity/megalinter#2865]
**Describe the bug**
The `.lycheeignore` file included in the Megalinter project root is incorrectly formatted and misleads users as the provided example - the lines are supposed to be regex strings, not globs:

https://github.com/lycheeverse/lychee/#ignoring-links

**Expected behavior**
The project's `.lycheeignore` file and associated documentation should be in a Rust regex format, not file globs.

**Comment by nvuillam** [comment]
@DariuszPorowski what is your opinion ? :)

@andrewvaughan may you'd like to submit a Pull Request with the fix ? :)

**Comment by DariuszPorowski** [comment]
It works on both, you can mix and match.

**Comment by andrewvaughan** [comment]
> It works on both, you can mix and match.

That seems like a really bad and ambiguous design, since no regex pattern markers are used, so far as I can tell... these mean very different things between regex and glob:

`https://twitter.com/*`

But I'm presuming that's a decision from Lychee?

**Comment by DariuszPorowski** [comment]
MegaLinter is "proxy" / "orchestrator" / "aggregator"/ "wrapper", etc. for existing tools, so any cons/pros go to each of the tools itself.

**Comment by andrewvaughan** [comment]
Yep - still probably best-practice to update MegaLinter's examples/docs/code to follow the official documentation from Lychee (which only mentions regex), even if the framework does support globs; it's confusing as-is.

**Comment by nvuillam** [comment]
@andrewvaughan would you like to make a PR to update lychee doc in MegaLinter ? :)

It can be done here -> https://github.com/oxsecurity/megalinter/blob/2d48e80e315b4cb8502d48773c06505f17d61a97/megalinter/descriptors/spell.megalinter-descriptor.yml#L144 by adding a linter_test property :)
