### ISSUE TITLE
SECURED_ENV_VARIABLES misbehavior

### ISSUE THREAD

**Issue by NEKETSKI** [oxsecurity/megalinter#2875]
After reading the documentation about the [security of environment variables](https://megalinter.io/latest/configuration/#environment-variables-security), I tried to use them. The documentation says the following:

> Notes:
> 
> * If you override SECURED_ENV_VARIABLES_DEFAULT, it replaces the default list, so it's better to only define SECURED_ENV_VARIABLES to add them to the default list !
> * Environment variables are secured for each command line called (linters, plugins, sarif formatter...) except for [PRE_COMMANDS](https://megalinter.io/latest/configuration/#pre-commands) , as you might need secured values within their code.

So, I need to execute `git config --global url.https://${GITHUB_TOKEN}@github.com/.insteadOf https://github.com/` inside the MegaLinter container to configure `git` and pull private packages with Golang.

**Note: all tested with version 7.2.1.**

I expected the token to be written to `.gitconfig`, but instead I get `[url "https://HIDDEN_BY_MEGALINTER@github.com/"]`.

I also added these pre-commands to test:
```
[Pre] run: [echo ${GITHUB_TOKEN}] in cwd [/]
[Pre] result:
HIDDEN_BY_MEGALINTER

[Pre] run: [echo ${GITHUB_TOKEN} > ~/TOKEN] in cwd [/]
[Pre] result:
```

To check the result, I check the contents of `~/TOKEN` in the MegaLinter container:
```
/ # cat ~/TOKEN 
HIDDEN_BY_MEGALINTER
```

So my question is, is this expected behavior or not? If secured envs aren't hidden from pre-commands, shouldn't we get these results?

P.S. thinking about the security aspect of hiding variables from linters when I need to write the token to `.gitconfig`...

**Comment by nvuillam** [comment]
@NEKETSKI it is on purpose that MegaLinter hides GITHUB_TOKEN, because we don't want all linters to have access to your GITHUB_TOKEN for security reasons.

If you need to access this token in a pre_command anyway, you can define your pre-command with:

```yaml
  secured_env: false
```

It seems it is not documented.... it should, sorry :)

**Comment by NEKETSKI** [comment]
As I discovered only after reading your comment, this condition is written in the Readme file, but not in the documentation on the site. So it just needs to be fixed on the site.
@nvuillam thanks a lot for this info!
