### ISSUE TITLE
lychee 404 errors

### ISSUE THREAD

**Issue by schorlton** [oxsecurity/megalinter#2881]
Running v7.3.0 in GitLab CI

Not sure if this is the GitLab CI environment or the redirect in the URL causing the error...thanks for your help!

```bash
❌ Linted [SPELL] files with [lychee]: Found 3 error(s) - (0.57s) (expand for details)
- Using [lychee v0.13.0] https://megalinter.io/7.3.0/descriptors/spell_lychee
- MegaLinter key: [SPELL_LYCHEE]
- Rules config: identified by [lychee]
- Number of files analyzed: [4]
--Error detail:
✗ [404] https://megalinter.github.io/configuration/ | Failed: Network error: Not Found
✗ [404] https://megalinter.github.io/configuration/ | Failed: Network error: Not Found
✗ [404] https://megalinter.github.io/flavors/ | Failed: Network error: Not Found
```

**Comment by schorlton** [comment]
I'm running in docker...does that still hold true? I tried using `--entrypoint bash` to run the above command in the container but no luck. I also am only upgrading from 7.1.0 so it's not a major upgrade.

**Comment by nvuillam** [comment]
@schorlton  https://megalinter.github.io/configuration/ & https://megalinter.github.io/flavors/ are technically 404 that redirect to https://megalinter.github.io/latest/configuration/ & https://megalinter.github.io/latest/flavors/

`npx mega-linter-runner@latest --upgrade` should replace with the good links, but you can also do it manually :)

**Comment by schorlton** [comment]
Oh that makes a lot more sense. Found those URLs in my codebase and replaced them with https://megalinter.io/latest/configuration/. Thanks :smile:

**Comment by nvuillam** [comment]
You're welcome :)
