### ISSUE TITLE
Proselint and Vale being skipped if config files are in different LINTER_RULES_PATH

### ISSUE THREAD

**Issue by andrewvaughan** [oxsecurity/megalinter#2894]
**Describe the bug**
If `LINTER_RULES_PATH` is configured other than project default, proselint and vale are skipped.

**To Reproduce**

1. Set `LINTER_RULES_PATH` to a different path than the default in `.mega-linter.yml`
2. Create a `.proselintrc` and `vale.ini` file in that path
3. Run a linting session

**Expected behavior**
Megalinter should find the configuration files in the updated path, instead, the following occurs:

```
...

| [Activation] SPELL_PROSELINT has been set inactive, as none of these files has been found: ['.proselintrc', 'proselint/config.json']
| [Activation] SPELL_VALE has been set inactive, as none of these files has been found: ['.vale.ini']

...
```

With `LINTER_RULES_PATH` set to a different directory, vale and proselint will still function if these configuration files are placed in the project root. It seems there needs to be unit tests added for the `LINTER_RULES_PATH` configuration.

**Comment by nvuillam** [comment]
@andrewvaughan the message explains what the doc says: such linters are deactivated if config file is not found at the root ^^

https://megalinter.io/beta/descriptors/spell_proselint/#how-are-identified-applicable-files

https://megalinter.io/beta/descriptors/spell_vale/#how-are-identified-applicable-files

As such linter have great IDE extensions (that won't detect config in LINTER_RULES_PATH folder), it's better if they are defined at the repo root anyway, no ? :)
