### ISSUE TITLE
Upgrade to latest ansible-lint (6.18.0)

### ISSUE THREAD

**Issue by mdrocan** [oxsecurity/megalinter#2918]
**Is your feature request related to a problem? Please describe.**
Currently an old version of ansible-lint is used. Testing locally you get different information.

**Describe the solution you'd like**
Upgrade to latest, ie. 6.18.0
Copy paster from mega-linter-runner's cupcake and python: "- Using [ansible-lint v6.17.2] https://megalinter.io/7.3.0/descriptors/ansible_ansible_lint" and "A new release of ansible-lint is available: 6.17.2 → 6.18.0 Upgrade by running: pip install --upgrade ansible-lint"

**Describe alternatives you've considered**
If not updated then a possibility to upgrade it while running the tests..

**Comment by nvuillam** [comment]
@mdrocan ansible-lint is already upgraded to 6.18.0 in beta version :) https://megalinter.io/beta/descriptors/ansible_ansible_lint/

So use it, you can either:
- use beta version of MegaLinter
- wait for the next minor release
- hack v7.3.0 by using pre-command to upgrade it (example below)

```yaml
PRE_COMMANDS:
  - command: pip install --upgrade ansible-lint
    venv: ansible-lint
```
