### ISSUE TITLE
MegaLinter fails to find PR in ADO

### ISSUE THREAD

**Issue by GitHubUser1339** [oxsecurity/megalinter#2922]
We may have a non-standard setup causing this issue, but maybe there's a solution that can help us.

Our repos have a branch policy that invokes the megalinter pipeline in a central repo. That pipeline clones the source repo for linting and is supposed to report back to the originating PR. 

However, MegaLinter tries to find the PR in the central repo, not the source repo, and therefore cannot find the PR and fails.

[Disclaimer] I don't know how MegaLinter works under the hood, nor do I know Python. Keep that in mind when reading further :-)

In 'AzurecommentReporter.py', I found this comments:

Requires the following vars sent to docker run:
- SYSTEM_ACCESSTOKEN
- SYSTEM_COLLECTIONURI
- SYSTEM_PULLREQUEST_PULLREQUESTID
- SYSTEM_TEAMPROJECT
- BUILD_BUILDID
- BUILD_REPOSITORY_ID

Is there an option to override the 'BUILD_REPOSITORY_ID' with the actual source repo ID?

**Comment by GitHubUser1339** [comment]
To answer my own question: yes, you can override the variable by passing it to the docker image.

**Comment by nvuillam** [comment]
@GitHubUser1339 indeed MegaLinter needs a value to this variable to call Azure APIs, while the value you send succeeds with the API call it's ok :)
