### ISSUE TITLE
Dotnet Format linter is indefinitely called over and over when running via image

### ISSUE THREAD

**Issue by isaac-patterson** [oxsecurity/megalinter#2939]
**Describe the bug**
Dotnet format linter runs over and over indefinitely on a local run, never exiting.

**To Reproduce**

1. Download and extract the zipped folder
2. Run `make lint`
3. Observe dotnet format linter run over and over again without finishing, exiting the container also doesnt tear it down - have to manually tear down the container

Output which is repeating 
```
[dotnet-format] CWD: /tmp/lint
[dotnet-format] result: 0   The dotnet runtime version is '6.0.21'.
  The dotnet CLI version is '6.0.413'.
  Using MSBuild.exe located in '/usr/share/dotnet/sdk/6.0.413/'.
  Formatting code files in workspace '/tmp/lint/HelloWorldService.sln'.
  Loading workspace.
    Determining projects to restore...
  All projects are up-to-date for restore.
  Project HelloWorldService is using configuration from '/tmp/lint/src/HelloWorldService.Api/obj/Debug/net6.0/HelloWorldService.GeneratedMSBuildEditorConfig.editorconfig'.
  Project HelloWorldService is using configuration from '/usr/share/dotnet/sdk/6.0.413/Sdks/Microsoft.NET.Sdk/analyzers/build/config/analysislevel_6_default.editorconfig'.
  Complete in 3588ms.
  Determining formattable files.
  Complete in 489ms.
  Running formatters.
  Running Code Style analysis.
  Determining diagnostics...
  Running 2 analyzers on HelloWorldService.
  Complete in 2938ms.
  Analysis complete in 2939ms.
  Running Analyzer Reference analysis.
  Determining diagnostics...
  Running 143 analyzers on HelloWorldService.
  Complete in 506ms.
  Analysis complete in 506ms.
  Complete in 4356ms.
  Formatted 0 of 31 files.
  Format complete in 8433ms.
```

**Expected behavior**
Dotnet format works and megalinter exits 0

**Screenshots**

**Additional context**
Going into the container and running the exact same command (found via `ps -e`) that megalinter runs [works](url) 🤷 
Ive got the linter to work on different dotnet projects for example the basic one created via `dotnet new webapp`

**Comment by nvuillam** [comment]
I'm sorry i'm no good at all at dotnet :/

@bdovaz any ideas ? :)

**Comment by Kurt-von-Laven** [comment]
One option if you aren't beholden to dotnet-format would be to disable it and use the much faster CSharpier instead. We took this approach ourselves, because I see significantly fewer issues opened about it, and it produces nicer formatting with less configuration IMO.
