### ISSUE TITLE
Terrascan does not scan

### ISSUE THREAD

**Issue by girlpunk** [oxsecurity/megalinter#2941]
**Describe the bug**
Instead of scanning files, Terrascan prints it's command line help

**To Reproduce**

1. Include `TERRAFORM_TERRASCAN` in `ENABLE_LINTERS`
2. Run a scan

**Expected behavior**
Terrascan should scan files and report errors

**Screenshots**
```
- Using [terrascan v1.18.2] https://megalinter.io/7.3.0/descriptors/terraform_terrascan
- MegaLinter key: [TERRAFORM_TERRASCAN]
- Rules config: identified by [terrascan]
[Pre][TERRAFORM_TERRASCAN] run: [terrascan] in cwd [/]
[Pre][TERRAFORM_TERRASCAN] result:
Terrascan

Detect compliance and security violations across Infrastructure as Code to mitigate risk before provisioning cloud native infrastructure.
For more information, please visit https://runterrascan.io/

Usage:
an [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  init        Initializes Terrascan and clones policies from the Terrascan GitHub repository.
  scan        Detect compliance and security violations across Infrastructure as Code.
  server      Run Terrascan as an API server
  version     Terrascan version

Flags:
  -c, --config-path string      config file path
  -h, --help                    help for terrascan
  -l, --log-level string        log level (debug, info, warn, error, panic, fatal) (default "info")
      --log-output-dir string   directory path to write the log and output files
  -x, --log-type string         log output type (console, json) (default "console")
  -o, --output string           output type (human, json, yaml, xml, junit-xml, sarif, github-sarif) (default "human")
      --temp-dir string         temporary directory path to download remote repository,module and templates

ascan [command] --help" for more information about a command.

--Error detail:


```

**Additional context**
Manually adding the scan command via `TERRAFORM_TERRASCAN_ARGUMENTS` does not resolve the issue, however it appears the command is not added.

**Comment by girlpunk** [comment]
Still outstanding

**Comment by nvuillam** [comment]
@girlpunk please can you run with `LOG_LEVEL: DEBUG` to see the exact command line run for TerraScan ?

**Comment by girlpunk** [comment]
2024-06-07T10:46:05.6305023Z [terrascan] command: ['terrascan', 'scan', 'd', '.', '-i', 'terraform', '-t', 'all', '-v', '-o', 'sarif']

**Comment by TommyE123** [comment]
Hi @girlpunk,

I have a few questions to help us troubleshoot your issue if you still have an error:

1. Could you try the `beta` version and let us know if it resolves your problem?
2. If you're still experiencing issues, please share any terrascan-related overrides you've added to your `.mega-linter.yml` file.
3. Also, could you tell me the location of your `.tf` files within your project structure?

If for example your files are all in a folder called `Terrascan` you should add the following to your  `.mega-linter.yml` file.

```
TERRAFORM_TERRASCAN_ARGUMENTS:
  - "--iac-dir"
  - "Terraform"
```

This information will help us better understand and address your situation.

Regards
Tom
