### ISSUE TITLE
Ignore symlink files when VALIDATE_ALL_CODEBASE is false

### ISSUE THREAD

**Issue by mcm-ham** [oxsecurity/megalinter#2944]
**Is your feature request related to a problem? Please describe.**
Currently I get `[error] Explicitly specified pattern "<filepath>" is a symbolic link` with prettier linter. This happens when `VALIDATE_ALL_CODEBASE` is false since specific file path is sent to prettier, it doesn't throw error when passing glob path it ignores symlink files silently.

**Describe the solution you'd like**
I reckon it makes sense to ignore symlink files when VALIDATE_ALL_CODEBASE is false, since original file is modified only that file needs checking not all the symlinked locations since it would be duplicates checks anyway.

**Comment by nvuillam** [comment]
@mcm-ham thanks for reporting, PR is on the way :)
