### ISSUE TITLE
TF_BUILD expects to be True, better woud be true

### ISSUE THREAD

**Issue by DaniRieker** [oxsecurity/megalinter#2946]
**Describe the bug**
Hey, when I want to tell megalinter that we're running in an Azure DevOps environment I need to set the environment variable TF_BUILD to True (upper case). All other variables are checked with true (lowercase). This took me quiet a while when I wanted to find out why I'm not getting the console output in this nice grouped format with the possiblity to expand and collapse ;-)

**To Reproduce**

run megalinter in Azure DevOps pipeline with environment variable TF_BUILD set to true
it will not recognize to be in Azure DevOps until we set TF_BUILD to True.

**Expected behavior**
Megalinter should recognize that it is running in Azure DevOps environment and add ##[group] in the log_section_start method of utils_reporter.py

**Additional context**
The problem is here: 
https://github.com/oxsecurity/megalinter/blob/adc78c568f2aff17cbb72068f48e15f292bfacf6/megalinter/utils.py#L444

**Comment by nvuillam** [comment]
hi @DaniRieker :)

I just followed the official Azure documentation ^^

![image](https://github.com/oxsecurity/megalinter/assets/17500430/9939ba0b-81d1-4035-b97c-39734d723d6a)

And following the Azure setup insall, the good TF_BUILD values finds its way to MegaLinter , you're not supposed to have to define the variabla yourself

https://megalinter.io/latest/install-azure/

**Comment by DaniRieker** [comment]
Hi @nvuillam 

thanks for your explanation, yeah RTFM is always a good Idea ;-)

To have it really error prune, comparing case-insensitve would be best I guess, but for sure this is not the most important thing to change than :D

So what do you think? Should we close the Issue with that?

**Comment by nvuillam** [comment]
@DaniRieker I think that as the default ML script sends the good value, there is no need to add a hack in case someone does custom ^^

And at least there will be this issue to provide guidance .... 

You can also submit a PR in documentation :)
