### ISSUE TITLE
Wrong test_folder for trufflehog?

### ISSUE THREAD

**Issue by pjungermann** [oxsecurity/megalinter#2954]
While looking at the config, I saw that for the trufflehog linter `test_folder: gitleaks` is used.

https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/repository.megalinter-descriptor.yml#L584

Not sure whether this is intended or not.

**Comment by nvuillam** [comment]
@pjungermann test_folder is just used for internal CI tests , to confirm that a linter is in success when it is supposed to be, that its fails when it's supposed to fail, etc :)
So as gitleaks and trufflehog are credential finders, I just reused existing gitleaks test folder :)
