### ISSUE TITLE
IGNORE_GITIGNORED_FILES not applied for cfn-lint

### ISSUE THREAD

**Issue by ashokm** [oxsecurity/megalinter#2955]
**Describe the bug**
The [documentation](https://github.com/oxsecurity/megalinter/blob/main/README.md) states that the `IGNORE_GITIGNORED_FILES` env var has a default setting of `true` and that:
> If set to `true`, MegaLinter will skip files ignored by git using `.gitignore` file

This has been working as expected in v6, but has stopped working when v7 was released.
After v7, we see [cfn-lint](https://megalinter.io/latest/descriptors/cloudformation_cfn_lint/) not behaving as expected and it is now including directories that are set in `.gitignore`.

**To Reproduce**
For a CDK-based project as an example, add `cdk.out` to .gitignore in the project repository.
Run MegaLinter v7 (running v7.3.0 at time of writing).
You'll see in the output (in Azure Pipelines in this case) that `/tmp/lint/cdk.out/manifest.json, /tmp/lint/cdk.out/tree.json` etc are listed as being .gitignored in this line:
```
- Excluding .gitignored files
```
However, after that, these files are still included in the linting scan:
```
...
2023-09-14T07:34:59.9630900Z ##[group][31m❌ Linted [CLOUDFORMATION] files with [cfn-lint]: Found 1 error(s) - (6.41s)[0m (expand for details)
2023-09-14T07:34:59.9632415Z - Using [cfn-lint v0.79.6] https://megalinter.io/7.3.0/descriptors/cloudformation_cfn_lint
2023-09-14T07:34:59.9633131Z - MegaLinter key: [CLOUDFORMATION_CFN_LINT]
2023-09-14T07:34:59.9635473Z - Rules config: [.cfnlintrc.yml]
2023-09-14T07:34:59.9636044Z - Number of files analyzed: [4]
2023-09-14T07:34:59.9636477Z --Error detail:
2023-09-14T07:34:59.9636810Z E1001 Missing top level template section Resources
2023-09-14T07:34:59.9716728Z cdk.out/manifest.json:1:1
2023-09-14T07:34:59.9717319Z 
2023-09-14T07:34:59.9717740Z E1001 Top level template section version is not valid
2023-09-14T07:34:59.9717985Z cdk.out/manifest.json:2:3
2023-09-14T07:34:59.9718177Z 
2023-09-14T07:34:59.9718350Z E1001 Top level template section artifacts is not valid
2023-09-14T07:34:59.9718554Z cdk.out/manifest.json:3:3
...
2023-09-14T07:34:59.9721633Z E1001 Missing top level template section Resources
2023-09-14T07:34:59.9721814Z cdk.out/tree.json:1:1
2023-09-14T07:34:59.9721883Z 
2023-09-14T07:34:59.9722044Z E1001 Top level template section version is not valid
2023-09-14T07:34:59.9722212Z cdk.out/tree.json:2:3
2023-09-14T07:34:59.9722295Z 
2023-09-14T07:34:59.9722438Z E1001 Top level template section tree is not valid
2023-09-14T07:34:59.9722619Z cdk.out/tree.json:3:3
...
```

**Additional context**
- No custom `mega-linter.yml` configuration file is being used
- No custom `.cfnlintrc.yml` configuration file is being used

**Comment by nvuillam** [comment]
@ashokm that's strange, cfn-lint is called with list_of_files so .gitignore files should be indeed ignored (https://megalinter.io/latest/descriptors/cloudformation_cfn_lint/#how-the-linting-is-performed )

Please could you run your workflow with LOG_LEVEL: DEBUG so we can investigate ?

**Comment by nvuillam** [comment]
I think this lint helps :)

Excluding .gitignored files [10772]: /tmp/lint/bin/blah-cdk-stack.d.ts, /tmp/lint/bin/blah-cdk-stack.js, /tmp/lint/cdk.out/asset.099a3112386fa620b3069790dcf92c8e64bb5341760a8b0a76bfa843f8ad41df/aws-sdk-v2-handler.js, /tmp/lint/cdk.out/asset.099a3112386fa620b3069790dcf92c8e64bb5341760a8b0a76bfa843f8ad41df/aws-sdk-v3-handler.bundled.js, /tmp/lint/cdk.out/asset.099a3112386fa620b3069790dcf92c8e64bb5341760a8b0a76bfa843f8ad41df/index.js, /tmp/lint/cdk.out/asset.099a3112386fa620b3069790dcf92c8e64bb5341760a8b0a76bfa843f8ad41df/shared.js, /tmp/lint/cdk.out/asset.b992a5b1efd6715c28d74eda79615c6b4c3cf54e6364f2b2166dacf0f6c68602/update-blah-ip-set.py, /tmp/lint/cdk.out/cdk.out, /tmp/lint/cdk.out/manifest.json, /tmp/lint/cdk.out/tree.json, /tmp/lint/cdk.out/blah-acl-dev.assets.json, /tmp/lint/cdk.out/blah-acl-dev.template.json, /tmp/lint/lib/blah-cdk-stack-stack.d.ts, /tmp/lint/lib/blah-cdk-stack-stack.js, /tmp/lint/node_modules/.bin/acorn, /tmp/lint/node_modules/.bin/browserslist, /tmp/lint/node_modules/.bin/cdk, /tmp/lint/node_modules/.bin/esparse, /tmp/lint/node_modules/.bin/esvalidate, /tmp/lint/node_modules/.bin/import-local-fixture, /tmp/lint/node_modules/.bin/jest, /tmp/lint/node_modules/.bin/js-yaml,
...

I check !

**Comment by nvuillam** [comment]
@ashokm I think i got it, PR on the way :)

**Comment by nvuillam** [comment]
@ashokm please could confirm it's ok with beta version ?

**Comment by nvuillam** [comment]
@ashokm perfect, thanks for the feedback :)
I've been really busy and for the moment I'm the only one handling releases, so there has been none for more than a month, but as I got COVID I have time to manage a new minor release soon, including this fix :)

**Comment by burner1024** [comment]
Looks like it's broken again, or was never fixed.

```
❌ Linted [COPYPASTE] files with [jscpd]: Found 145 error(s) - (62.29s)
- Using [jscpd v3.5.10] https://megalinter.io/7.6.0/descriptors/copypaste_jscpd
- MegaLinter key: [COPYPASTE_JSCPD]
- Rules config: [.jscpd.json]
--Error detail:
Clone found (javascript):
 - .vscode-test/vscode-1.43.2/VSCode-linux-x64/resources/app/out/vs/workbench/contrib/webview/electron-browser/pre/electron-index.js [1:1 - 6:187] (5 lines, 327 tokens)
   .vscode-test/vscode-1.44.2/VSCode-linux-x64/resources/app/out/vs/workbench/contrib/webview/electron-browser/pre/electron-index.js [1:1 - 6:187]
```

```bash
$ grep .vscode .gitignore 
.vscode-test/
```

**Comment by nvuillam** [comment]
@burner1024 if you want to ignore files with jscpd, you need to update .jscpd.json as this is not a linter that takes a list of files as input :)

https://megalinter.io/beta/configuration/#cli-lint-mode

**Comment by burner1024** [comment]
I just ran the command and expected `IGNORE_GITIGNORED_FILES` to be applied to all linters, as the doc suggests.
Is there a list of linters that are ignoring `IGNORE_GITIGNORED_FILES` setting?

**Comment by nvuillam** [comment]
We could indeed update the documentation to precise that it only applies to linters that works with list of files mode (and not run without list of files on the repository root)

Most of linters handle by themselves to ignore files in .gitignore, but some of them like .jscpd.json do not, as in the example of our internal jscpd documentation -> https://megalinter.io/latest/descriptors/copypaste_jscpd/

Please feel free to post an issue on jscpd repo to request such enhancement :)

**Comment by burner1024** [comment]
I see, thank you for explanation.
