### ISSUE TITLE
SPELL_LYCHEE certificate expired

### ISSUE THREAD

**Issue by jpsphaxer** [oxsecurity/megalinter#2956]
**Describe the bug**
Certificate expired for LYCHEE and produces 404 network error when being run in CI pipelines 

**Screenshots**
![CleanShot 2023-09-14 at 09 55 25](https://github.com/oxsecurity/megalinter/assets/48501079/bd140467-7054-4729-b0fb-9081c6912e35)

**Comment by echoix** [comment]
It isn't lychee the problem. The website in question (vim dot org) is indeed not working, by certificate. (And I checked by my side to) So, lychee is proving that is does it job, since the link used is not working, and it flags about it ;)

**Comment by echoix** [comment]
See https://groups.google.com/g/vim_dev/c/SsXNsBhfIRM
And https://groups.google.com/g/vim_dev/c/YAy0EbfpjD0/m/pdlsrWaNEQAJ
And https://github.com/vim/vim/issues/13079

**Comment by nvuillam** [comment]
@jpsphaxer @echoix vim.org updated their certificate :) ( the issue was happening on own MegaLinter linting, and it is not a problem anymore ^^ )
