### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by ajepe** [oxsecurity/megalinter#2970]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_BLACK, PYTHON_ISORT, CSS_STYLELINT, DOCKERFILE_HADOLINT, JAVASCRIPT_ES, MARKDOWN_MARKDOWNLINT, XML_XMLLINT, YAML_PRETTIER

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
This would probably fit only your project :)
May I suggest you use Cupcake flavor and enable only the linters in your list ? :)

https://megalinter.io/latest/flavors/cupcake/
