### ISSUE TITLE
Github action example not documention how to disable more than opne reporter

### ISSUE THREAD

**Issue by vkuehn** [oxsecurity/megalinter#2977]
Hello,

this works fine disabling one reporter

<pre>
  env: # Comment env block if you don't want to apply fixes
  # Apply linter fixes configuration
  FILTER_REGEX_EXCLUDE: (page/.*\.py)
  DISABLE_LINTERS: REPOSITORY_DEVSKIM
</pre>

unfortunatetly this does not

<pre>
 env: # Comment env block if you don't want to apply fixes
  # Apply linter fixes configuration
  FILTER_REGEX_EXCLUDE: (page/.*\.py)
  DISABLE_LINTERS: (REPOSITORY_DEVSKIM, Checkov)
</pre>

this seems to work partially

<pre>
env: # Comment env block if you don't want to apply fixes
  # Apply linter fixes configuration
  FILTER_REGEX_EXCLUDE: (page/.*\.py)
  DISABLE_LINTERS: REPOSITORY_DEVSKIM
  REPOSITORY_CHECKOV_DISABLE_ERRORS: true
</pre>

How could I correctly disable more than one linter in a github  action workflow file ?

**Comment by Kurt-von-Laven** [comment]
See [the example](https://megalinter.io/latest/config-activation/) in the documentation. The correct descriptors are [documented as well](https://megalinter.io/latest/descriptors/repository_checkov/).

**Comment by nvuillam** [comment]
`DISABLE_LINTERS: REPOSITORY_DEVSKIM,REPOSITORY_CHECKOV :)`

Note: it's easier to maintain to define disabled linters within `.mega-linter.yml` :)
