### ISSUE TITLE
Ability to delete current Github Comment rather than editting

### ISSUE THREAD

**Issue by priorax** [oxsecurity/megalinter#2979]
**Is your feature request related to a problem? Please describe.**
As a part of reviewing the PR history, I would like to be able to see the Github Comment reporter at the _end_ of the history.

**Describe the solution you'd like**
This is because if someone proposes a feedback change I feel like it's natural to go back to the PR and see it in the history _after_ the fix commit rather than after.

This should be proposed as a new config value and should not break existing workflows.

This also is in line with how other static analysis tools we use behave (Sonarqube).

**Describe alternatives you've considered**
Constantly looking at edit commits and scrolling up.

**Additional context**

**Comment by priorax** [comment]
<img width="521" alt="image" src="https://github.com/oxsecurity/megalinter/assets/707763/c3a4fa34-3603-40b9-aa6f-0bc11b87ce33">
This kind of shows what I mean by this as a "why I would prefer it after the PR comments"
I can get the value of having full history, but I can check CI logs for that, in this case where I have 10+ commits (due to this being the time that sets up megalinter) _after_ the first execution, the history becomes blurred without going into individual comments edit history.

**Comment by nvuillam** [comment]
I get the request, it's legit :)

It happens here -> https://github.com/oxsecurity/megalinter/blob/75bcff7f9c1c4ea1c3dd4dd4c506932846086f51/megalinter/reporters/GithubCommentReporter.py#L136

Would you like to try to make a PR , that would add a condition like if GITHUB_COMMENT_REPORTER_NO_EDIT is "true" then delete comment and post a new one ? :)

**Comment by priorax** [comment]
Will try once I can get a stable dev environment!

I tried gitlab the other day but it wouldn't start properly

**Comment by nvuillam** [comment]
@priorax you can try to use the "classic" way with the desktop mode :)

https://megalinter.io/latest/contributing/#42-desktop
