### ISSUE TITLE
Create an exception to avoid the linting on a single line of the Dockerfile

### ISSUE THREAD

**Issue by AtlasAleks22** [oxsecurity/megalinter#2981]
Hello. 
Can I create an exception to avoid the linting on a single line of the Dockerfile?
Just as we can configure which erros/warns/info to be ignored in .hadolint.yml file, I want megalinter to ignore a certain line within the Dockerfile.
I am using megalinter directly in my Gitlab pipeline.

**Comment by AtlasAleks22** [comment]
hadolint.

**Comment by echoix** [comment]
In that case look at inline ignores in hadolint's help, such as https://github.com/hadolint/hadolint#inline-ignores

**Comment by AtlasAleks22** [comment]
Thank you very much!

**Comment by nvuillam** [comment]
@AtlasAleks22 for each linter, you have a MegaLinter documentation that points you to the linter documentation for some features, like inline-disable :) 

https://megalinter.io/latest/descriptors/dockerfile_hadolint/
