### ISSUE TITLE
Ability to specify a custom docker image aka a "custom" flavor

### ISSUE THREAD

**Issue by vihangm** [oxsecurity/megalinter#2983]
**Is your feature request related to a problem? Please describe.**
We've found megalinter quite useful, and the plugin system is nice for adding extra linters. However installing
the lint tools is often time consuming and causes lint runs to be very slow. I don't think it makes sense for megalinter
to add every odd lint tool, so we'd like to build and publish our own docker image layered on top of the megalinter image
to use.

**Describe the solution you'd like**
I would like both the mega-lint-runner CLI and github actions workflows to support a "custom" flavor with a docker image
passed in to run the megalinter.

**Describe alternatives you've considered**
We currently use megalinter with plugins to do this.

**Comment by Kurt-von-Laven** [comment]
I believe mega-linter-runner has an `--image` argument for this purpose, but let me know if that doesn't solve your problem since I've never tried using it with a custom Docker image.

**Comment by vihangm** [comment]
Aha, indeed it does. Apologies for not finding it. I'll try it out and let you know if that works! :)

**Comment by Kurt-von-Laven** [comment]
No worries; I overlooked it too initially for some reason. Appreciate it! [Here](https://megalinter.io/latest/mega-linter-runner/#usage) is the link to the pertinent docs in case someone else needs it in the future.

**Comment by vihangm** [comment]
The flag works well for our use case. Thanks again!
