### ISSUE TITLE
Default `mega-linter.yml` workflow generated gets tripped up with ActionLinter

### ISSUE THREAD

**Issue by andrewvaughan** [oxsecurity/megalinter#3025]
**Describe the bug**

```
Results of actionlint linter (version 1.6.26)
See documentation on https://megalinter.io/7.4.0/descriptors/action_actionlint/
-----------------------------------------------

❌ [ERROR] for workspace /tmp/lint
Linter raw log:
.github/workflows/mega-linter.yml:184:13: if: condition "${{ success() }} || ${{ failure() }}" is always evaluated to true because extra characters are around ${{ }} [if-cond]
    |
184 |         if: ${{ success() }} || ${{ failure() }}
    |             ^~~
```

**To Reproduce**

1. Run a newly-generated workflow

---

A clearer way to have this functionality work would be to change the line to:

```yml
  if: '!cancelled()'
```

This makes it clear that the Artifacts should only upload if any action was taken _except_ cancellation. Note that the quotes are necessary so that `!` isn't flagged as a YAML tag.

**Comment by andrewvaughan** [comment]
One other finding - it looks like Prettier doesn't play nicely with GitHub action linting at times. It will update what I wrote above to use double-quotes, which in turn creates an error with the other linter.

A quick and dirty way to get around this is to drop usage of the curly-brackets:

```yaml
  if: success() || failure()
```

They are not required for `if` statements.

**Comment by andrewvaughan** [comment]
I do believe this is an incorrect lint, btw, per:

https://github.com/rhysd/actionlint/issues/367

**Comment by nvuillam** [comment]
`if: '!cancelled()'` seems elegant , it wasn't available on Github Actions when I created the workflow :)

Would u like to make a PR ? :)

**Comment by echoix** [comment]
I'm curious to see if it really works! At the time, it used to be that a if failure() was needed in order to not be skipped when any step failed. Since cancelled() is a status check function, the note in https://docs.github.com/en/actions/learn-github-actions/expressions#failure-with-conditions might mean that it should work ;)

**Comment by andrewvaughan** [comment]
I was able to use `success() || failure()` without the curly brackets with success and no linting errors. Again, I think this is a mistake in the linter - but it does seem like it's best practice to not use curly brackets in `if:` clauses, so both projects can be updated.

**Comment by andrewvaughan** [comment]
> `if: '!cancelled()'` seems elegant , it wasn't available on Github Actions when I created the workflow :)
> 
> Would u like to make a PR ? :)

I tried this, but Prettier insisted on changing this to double quotes with `"!cancelled()"` which caused other linting failures. To not upset the complexity that is all these opinionated linters, I think the best course of action is to simply remove the curly brackets:

```yaml
if: success() || failure()
```

Which seems to be the recommendation, now, to not use curly-brackets in `if` statements.
