### ISSUE TITLE
A way to require all diagnostics to be either OK or ERROR

### ISSUE THREAD

**Issue by quodlibetor** [oxsecurity/megalinter#3044]
**Is your feature request related to a problem? Please describe.**

Hi, I would like to not allow _any_ warnings in my code -- either lint passes cleanly, or it doesn't pass CI.

**Describe the solution you'd like**

Either a a `FAIL_ON_WARNINGS` config that causes megalinter to exit 1 with a message if there were any warnings, or a `DISABLE_WARNINGS` config that fails megalinter because I accidentally configured a linter with a warning config.

**Describe alternatives you've considered**

I'm currently configuring each linter individually, but most of the defaults are what I want, I just want warnings to fail. So it's a bunch of work that is just switching things from WARN to ERROR.

**Additional context**

🤷

**Comment by nvuillam** [comment]
Yes, but the WARN is only for linters that are considered not blocking:
- formatters
- linters defined in [DISABLE_ERRORS_LINTERS](https://megalinter.io/latest/config-activation/)

There is currently nothing within MegaLinter that is able to know if a linter only detected warning errors (we use CLI return code: 0 or > 0 )

**Comment by quodlibetor** [comment]
Okay I see.

I don't think that I've got time to implement the full fix from 1701.

I do think that having a "best effort" setting to convert (known) warnings into errors that would be automatically improved if something like 1701 was merged would be valuable to me.
