### ISSUE TITLE
npx mega-linter-runner causes interactive prompts on first time use which make it unsuitable for use from scripts due to not having the Docker registry prefix in the container image name

### ISSUE THREAD

**Issue by vorburger** [oxsecurity/megalinter#3060]
**Describe the bug**

npx mega-linter-runner causes an interactive prompt to chose image (only on first time use).

This make it unsuitable for use from scripts.

It's because somewhere the Docker registry prefix in the container image name is missing.

You should replace a `docker.io/oxsecurity/megalinter:v7` you have somewhere with a "FQN" of `docker.io/oxsecurity/megalinter:v7` (assuming that you are publishing to Docker Hub, and not Quay, or the GHCR, or GCR, or whichever one you fancy the most).

I would raise a PR myself if only I knew where this is defined.

**To Reproduce**

```sh
$ npx mega-linter-runner
Pulling docker image oxsecurity/megalinter:v7 ... 
INFO: this operation can be long during the first use of mega-linter-runner
The next runs, it will be immediate (thanks to docker cache !)
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
  ▸ registry.fedoraproject.org/oxsecurity/megalinter:v7
    registry.access.redhat.com/oxsecurity/megalinter:v7
    docker.io/oxsecurity/megalinter:v7
    quay.io/oxsecurity/megalinter:v7
```

You should be able to reproduce this easily e.g. in a GitHub Codespace (where I ran into it).

If you don't get it locally, even after you remove the Docker image, then it's because of how your Docker is configured; it varies a bit among different Linux distributions and versions etc.

**Comment by echoix** [comment]
Are you using podman?

**Comment by vorburger** [comment]
> I would raise a PR myself if only I knew where this is defined.

https://github.com/search?q=repo%3Aoxsecurity%2Fmegalinter%20oxsecurity%2Fmegalinter%3Av7&type=code has a number of occurences.

I recommend that all of them are changed... do you want a PR?

To fix this in `npx mega-linter-runner` probably needs changes in https://github.com/oxsecurity/megalinter/blob/main/mega-linter-runner/lib/runner.js

**Comment by vorburger** [comment]
> Are you using podman?

Ah yes, you are right. It appears GitHub Codespaces use this:

```
$ docker version
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Client:       Podman Engine
Version:      4.7.0
API Version:  4.7.0
Go Version:   go1.20.8
Built:        Wed Sep 27 20:24:38 2023
OS/Arch:      linux/amd64
```
I think this is their default. (I don't think [my dotfiles install Podman](https://github.com/vorburger/vorburger-dotfiles-bin-etc) in GitHub Codespaces.)

Either way, it ideally should "just work out of the box" - hope you agree?

**Comment by vorburger** [comment]
> In the meanwhile, the workaround is [specifying the complete image name](https://megalinter.io/latest/mega-linter-runner/)

    npx mega-linter-runner --image docker.io/oxsecurity/megalinter:v7

Ah, thanks; I hadn't seen (looked for) that option, that gets you further, but only ;) a bit:

```
Command: docker run --platform linux/amd64 -v /var/run/docker.sock:/var/run/docker.sock:rw -v /home/vorburger/git/github.com/www-learn-study/saraswati.learn.study:/tmp/lint:rw docker.io/oxsecurity/megalinter:v7
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: statfs /var/run/docker.sock: permission denied
```

I gather it's probably trying to use the "docker in docker" thing with a volume mount of `/var/run/docker.sock`, and that doesn't work out of the box with Podman. I think I knew how to fix this in a past live, but need to dig...

Alternative here may be to switch GitHub Codespace from Podman to Docker... 😿

**Comment by echoix** [comment]
> Ah, thanks; I hadn't seen (looked for) that option, that gets you further, but only ;) a bit:
> 
> ```
> Command: docker run --platform linux/amd64 -v /var/run/docker.sock:/var/run/docker.sock:rw -v /home/vorburger/git/github.com/www-learn-study/saraswati.learn.study:/tmp/lint:rw docker.io/oxsecurity/megalinter:v7
> Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
> Error: statfs /var/run/docker.sock: permission denied
> ```
> 
> I gather it's probably trying to use the "docker in docker" thing with a volume mount of `/var/run/docker.sock`, and that doesn't work out of the box with Podman. I think I knew how to fix this in a past live, but need to dig...
> 
> Alternative here may be to switch GitHub Codespace from Podman to Docker... 😿

Thats #1160 , and why I said there was some other blockers... yet.

**Comment by vorburger** [comment]
> I think this is their default. (I don't think [my dotfiles install Podman](https://github.com/vorburger/vorburger-dotfiles-bin-etc) in GitHub Codespaces.)

> Alternative here may be to switch GitHub Codespace from Podman to Docker... 😿

Oups, I mixed up (in my head) 2 different environments that I'm working on in parallel in different tabs; this problem occurs when using it locally on Fedora; please ignore any references to GitHub Codespaces in this issue. Sorry about the noise.

**Comment by vorburger** [comment]
> Thats https://github.com/oxsecurity/megalinter/issues/1160 , and why I said there was some other blockers... yet.

ACK. Let me close this.
