### ISSUE TITLE
REPOSITORY_GITLEAKS_PR_COMMITS_SCAN missing from the configuration schme

### ISSUE THREAD

**Issue by finnlander** [oxsecurity/megalinter#3064]
**Describe the bug**
Hi, 

First of all, thank you for the great work and effort you put in this great tool 🙇 .

In the latest MegaLinter release version (v7.5.0), when one uses the Gitleaks linter related configuration value `REPOSITORY_GITLEAKS_PR_COMMITS_SCAN`, added earlier this year and described in the [documentation](https://megalinter.io/7.5.0/descriptors/repository_gitleaks/) in the `.megalinter.yml` configuration file, it will make the v8r linter produce validation error as the configuration value key is not included in the MegaLinter config schema

The produced error from the output (MegaLinter executed in GitHub):

```text
  ℹ Processing ./.mega-linter.yml
  ℹ Found schema in https://www.schemastore.org/api/json/catalog.json ...
  ℹ Validating ./.mega-linter.yml against schema from https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json ...
  ✖ ./.mega-linter.yml is invalid
  
  ./.mega-linter.yml# must NOT have additional properties
```

I know there is a workaround to put the configuration directly as an environment variable, but I'd prefer storing all configurations in the same place (i.e. the config file).

**To Reproduce**

- Define Megalinter configuration file (`.mega-linter.yml`) to the repository root
- Include `REPOSITORY_GITLEAKS_PR_COMMITS_SCAN: true` and enable `v8r` linter for YAML files.
- Run the linter to see `v8r` failing stating `.mega-linter.yml` has extra parameters:
  ```text
   ./.mega-linter.yml# must NOT have additional properties
  ```

**Expected behavior**
The source schema file should include the `REPOSITORY_GITLEAKS_PR_COMMITS_SCAN` parameter (if the parameter if still valid; if not then the documentation should be updated).

**Comment by nvuillam** [comment]
Oh it's just we forgot to add the variable in the JSON schema :)
