### ISSUE TITLE
Link to R2DevOps in gitlab doc

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#3065]
Test R2DevOps MegaLinter job and if it works as expected, add a link to R2DevOps in the doc

**Comment by coconux3** [comment]
Thank you for your time and consideration.

Megalinter opensource template is versioned and maintain by R2Devops community.
It allows users to upgrade Megalinter in their CI without copying/pasting YAML code anymore.
The template has been used more than 22k in GitLab-CI pipelines.
All versions are available here: https://r2devops.io/marketplace/gitlab/r2devops/hub/mega_linter 

The community is curious about your feedback, of course open to any suggestion to fit expectations.
