### ISSUE TITLE
including additional eslint plugins

### ISSUE THREAD

**Issue by YElyousfi** [oxsecurity/megalinter#3077]
Hello,

I am trying to add additional eslint plugins to be included when Megalinter runs. How can this be achieved? Couldn't find any documentation or issues relating to this.

Thanks for the help!

**Comment by nvuillam** [comment]
@YElyousfi you can use [PRE_COMMANDS](https://megalinter.io/latest/config-precommands/) , the doc contains an example with an eslint plugin :)
