### ISSUE TITLE
Pylint logo returns a 403

### ISSUE THREAD

**Issue by VictorRos** [oxsecurity/megalinter#3113]
**Describe the bug**

Pylint logo returns a **403** when accessing https://www.pylint.org/pylint.svg

**To Reproduce**

1. Go to https://www.pylint.org/pylint.svg
2. Get a 403 in japanese
3. MegaLinter failed due to linter Lychee checking all links

**Expected behavior**

**Screenshots**

<img alt="Pylint 403" src="https://github.com/oxsecurity/megalinter/assets/6940422/87c4ac81-11fd-4da9-a2b1-5d427647bb56" width="400">

**Additional context**

**Comment by VictorRos** [comment]
Ok, then should MegaLinter accepts `403` status when their website is down? 😂

**Comment by echoix** [comment]
Was fixed in #3116, forgot to name issue. The website has been out of their control for a long time though.
