### ISSUE TITLE
Not able to disable kics

### ISSUE THREAD

**Issue by sodds-eq** [oxsecurity/megalinter#3123]
.mega-linter.yml:
```
DISABLE:
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - BASH_EXEC
```

It disables trivy and bash-exec, but not kics.
Running on:

        uses: oxsecurity/megalinter@v7

Any suggestions on what could be the issue?

**Comment by nvuillam** [comment]
typo in .mega-linter.yml ? :)
