### ISSUE TITLE
Add a grep "linter"

### ISSUE THREAD

**Issue by wesley-dean-flexion** [oxsecurity/megalinter#3146]
**Is your feature request related to a problem? Please describe.**

I would like to know when certain strings are (or are not) included in files that are being scanned.  For example, a scan of in `docs/**/*.md` files should fail if the regex `\b[Uu][Nn][Ii][Xx]\b` matches or if `src/**/*.bash` does NOT include a line matching `^\s*##\s*@license\s*:\s*(CC|0?BSD|L?GPL)` .

**Describe the solution you'd like**

I would like a scanner that could iterate across a list of (glob, status, regular expression) tuples (where status could be 'error' (fail on match), 'warn' (warn on match), or 'pass' (fail when not matching) and apply some kind of regex matcher (e.g., `grep`).

**Describe alternatives you've considered**

I've been able to use [cspell](https://cspell.org/configuration/patterns/#exclude--include-patterns) to make the positive matching mechanism work; however, I haven't looked into the idea of negative matching (which, admittedly, is less common in most situations).  I don't know how to use cspell for the "different globs use different patterns" concept.  Multiple config cspell files, but how do I make cspell run multiple times, each with its own config file..?

**Additional context**

Before MegaLinter, I used a tool by [Cytopia](https://github.com/cytopia) called [awesome-ci](https://github.com/cytopia/awesome-ci) to do some linting and linting-adjacent on repositories.  One of their scanners was [regex-grep](https://github.com/cytopia/awesome-ci/blob/master/bin/regex-grep) which could be used to find strings that match regular expressions in files being scanned.  While not documented, [regex-grep-negative](https://github.com/cytopia/awesome-ci/blob/master/bin/regex-grep-negative) works in the opposite direction; whereas `regex-grep` fails when it finds something, `regex-grep-negative` fails when it does Not find something.

Here are some [examples](https://github.com/cytopia/awesome-ci/blob/master/EXAMPLES.md#regex-grep) and [more examples](https://github.com/cytopia/awesome-ci/blob/master/REGEX_CONTRIBUTIONS.md) of it in action.

**Comment by nvuillam** [comment]
MegaLinter embeds [semgrep](https://megalinter.io/latest/descriptors/repository_semgrep/) , it seems you can locally define custom rules :)

https://semgrep.dev/docs/writing-rules/rule-ideas/

**Comment by wesley-dean-flexion** [comment]
:facepalm: 

Someone should write a semgrep rule to look issues I create with the `enhancement` tag, add the `won't do` tag, and close them immediately.

**Comment by nvuillam** [comment]
@wesley-dean-flexion no, because next time someone will type "grep" is the issues finder, he/she will find the solution in this post :)
