### ISSUE TITLE
Replace R2Devops logo screenshot with the original svg

### ISSUE THREAD

**Issue by Totara-thib** [oxsecurity/megalinter#3173]
## Context

On the README of this project (https://github.com/oxsecurity/megalinter#using-r2devops) and the website (https://megalinter.io/latest/install-gitlab/) there's a R2Devops logo screenshot for GitLab template.

![image](https://github.com/oxsecurity/megalinter/assets/78480448/6f46660d-e085-4cd2-8188-12820f9afe0b)

## Objective

Is it possible to replace this screenshot with the original svg asset ?

**Svg version:**
![logo](https://github.com/oxsecurity/megalinter/assets/78480448/8b34673d-ef4e-414d-b942-32d498dbc4e4)

Thank you and greetings from the R2Devops team

**Comment by nvuillam** [comment]
Please make a pull request and we'll be glad to accept it :)
