### ISSUE TITLE
Visiting https://megalinter.io/7.6.0 causes redirect loop

### ISSUE THREAD

**Issue by rasa** [oxsecurity/megalinter#3186]
**Describe the bug**

Visiting https://megalinter.io/7.6.0 causes a redirect loop that never ends.

https://megalinter.io/7.5.0 works fine
https://megalinter.io/latest works fine

**To Reproduce**

1. Visit https://megalinter.io/7.6.0

**Expected behavior**

Visits https://megalinter.io/latest

**Additional context**

Chrome on iOS
Firefox on iOS

**Comment by nvuillam** [comment]
We had an issue while deploying documentation at the latest release 7.6.0 ... the automated generation & deployment job failed, and I had to manually solve the issue... it seems I did not do a great job 😢

**Comment by rasa** [comment]
Hey @nvuillam, The logs direct the user to https://megalinter.io/7.9.0 which still has the redirect loop bug. :(

**Comment by nvuillam** [comment]
@rasa solved directly on the gh_pages root 404 HTML page javascript :)
