### ISSUE TITLE
MegaLinter reports 1 error found even when yamlint reports multiple errors

### ISSUE THREAD

**Issue by james-garriss** [oxsecurity/megalinter#3195]
**Describe the bug**

When MegaLinter runs yamllint, and yamllint reports multiple errors, MegaLinter reports that there was only 1 error.

**To Reproduce**

1.  Use MegaLinter to lint the [MegaLinter YAML file](https://github.com/oxsecurity/megalinter/blob/main/.mega-linter.yml) and the [yamlint YAML file](https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration). 
2. Add a few linting issues, like extra blank lines.
3. Setup a MegaLinter config file that only runs yamllint.

```
ENABLE_LINTERS:
  - YAML_YAMLLINT
```

4. Run MegaLinter.
5. See that MegaLinter reports that there is only 1 error, but yamllint actually finds multiple errors.

Note:  This appears to be the same error that someone else previously reported about [Bandit](https://github.com/oxsecurity/megalinter/issues/680).

**Expected behavior**

I would expect MegaLinter to report the sum total number of errors that yamllint finds.

**Screenshots**

```
❌ Linted [YAML] files with [yamllint]: Found 1 error(s) - (0.21s)
- Using [yamllint v1.33.0] https://megalinter.io/7.6.0/descriptors/yaml_yamllint
- MegaLinter key: [YAML_YAMLLINT]
- Rules config: [/.yamllint.yml]
- Number of files analyzed: [4]
--Error detail:
.mega-linter.yml
  6:1       error    too many blank lines (1 > 0)  (empty-lines)

megalinter.yml
  17:1      error    trailing spaces  (trailing-spaces)
  63:21     error    no new line character at the end of file  (new-line-at-end-of-file)

yamllint.yml
  35:19     error    no new line character at the end of file  (new-line-at-end-of-file)
```

**Comment by nvuillam** [comment]
@james-garriss good catch, thanks for reporting,  PR is on the way :)
