### ISSUE TITLE
New linter JuliaFormatter.jl

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#3228]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when […]

I stumbled upon a Julia formatter, I didn't know it existed. I haven't used Julia for any project yet. If there is interest one day, ping us back with this issue!

https://github.com/domluna/JuliaFormatter.jl

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nvuillam** [comment]
The repo seems adopted and maintained, so it could be a good candidate for MegaLinter :)
