### ISSUE TITLE
Auto update fails to create PRs for the last 3 days

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#3241]
**Describe the bug**

Quick issue to note this. 

See the action logs.

**To Reproduce**

1. Go to '…'
2. Click on '….'
3. Scroll down to '….'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nvuillam** [comment]
i think it's ok now :)

**Comment by echoix** [comment]
Yep
