### ISSUE TITLE
TERRAFORM_TERRASCAN errors when there is a directory without a .tf file

### ISSUE THREAD

**Issue by NTitmus** [oxsecurity/megalinter#3244]
Error when there is a directory without a .tf file.  This occurs with both Terrascan on local computer AND with megalinter.  See this: https://github.com/tenable/terrascan/issues/1036 

1. In the workspace to be scanned use the following command: terrascan scan d . -i terraform -t all -v -o json
2. Error: directory '/Users/username/Desktop/Folder1/Folder2/Folder3/simple_module_ml/modules' has no terraform config files
3. When using GitHub actions, there is additionally an error: directory '/github/workspace/megalinter-reports' has no terraform config files .  This error can be stopped by using the variable REPORT_OUTPUT_FOLDER: none in the .mega-linter.yml file.

I believe that Super-linter does not have this issue because it runs the Terrascan command on each file individually.  I note that the 
CLI lint mode is project and there is no option to set it to file CLI lint mode.  I'm not sure how to configure things to stop this issue - as some directories will not have .tf files (though it also depends on whether Terrascan are going to do any work to improve functionality).

**Comment by nvuillam** [comment]
Terrascan is not supposed to run if there are no .tf files in the repo

https://megalinter.io/latest/descriptors/terraform_terrascan/#how-are-identified-applicable-files

Please can you share your logs ?

**Comment by NTitmus** [comment]
Thanks for getting back.

.mega-linter.yml file:
APPLY_FIXES: none
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  -   TERRAFORM_TERRASCAN

LOG_LEVEL: DEBUG


Github actions output:

To receive reports as email, please set variable EMAIL_REPORTER_EMAIL
MegaLinter now collects the files to analyse (expand for details)
  Listing all files in directory [/github/workspace], then filter with:
  Root dir content:
  - .mega-linter.yml
  - main.tf
  All found files before filtering:
  - .github/linters/.tflint.hcl
  - .github/workflows/tflint-github-actions.yaml
  - .mega-linter.yml
  - anotherdirectory/afile
  - main.tf
  - File extensions: .tf
  Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'No such file or directory')
  Popen(['git', 'ls-files', '--exclude-standard', '--ignored', '--others', '--cached'], cwd=/github/workspace, stdin=None, shell=False, universal_newlines=False)
  - Excluding .gitignored files [0]: 
  Kept [1] files on [5] found files
  Kept files before applying linter filters:
  - main.tf
  [Filters] {'name': 'TERRAFORM_TERRASCAN', 'filter_regex_include': None, 'filter_regex_exclude_descriptor': None, 'filter_regex_exclude_linter': None, 'files_sub_directory': None, 'lint_all_files': False, 'lint_all_other_linters_files': False, 'file_extensions': ['.tf'], 'file_names_regex': [], 'file_names_not_ends_with': [], 'file_contains_regex': [], 'file_contains_regex_extensions': []}
  TERRAFORM_TERRASCAN linter kept 1 files after applying linter filters:
  - main.tf
  
  +----MATCHING LINTERS----+----------+----------------+------------+
  | Descriptor | Linter    | Criteria | Matching files | Format/Fix |
  +------------+-----------+----------+----------------+------------+
  | TERRAFORM  | terrascan | .tf      | project        | no         |
  +------------+-----------+----------+----------------+------------+
terrascan before_lint_files: terrascan
[terrascan] command: ['terrascan', 'scan', 'd', '.', '-i', 'terraform', '-t', 'all', '-v']
[terrascan] CWD: /github/workspace
[terrascan] result: 5 

Scan Errors -

	IaC Type            :	terraform
	Directory           :	/github/workspace/anotherdirectory
	Error Message       :	directory '/github/workspace/anotherdirectory' has no terraform config files
	
	-----------------------------------------------------------------------
	
	IaC Type            :	terraform
	Directory           :	/github/workspace/megalinter-reports
	Error Message       :	directory '/github/workspace/megalinter-reports' has no terraform config files
	
	-----------------------------------------------------------------------
	


Violation Details -
    
	Description    :	Ensure that your AWS application is not deployed within the default Virtual Private Cloud in order to follow security best practices
	File           :	main.tf
	Module Name    :	root
	Plan Root      :	./
	Line           :	29
	Severity       :	MEDIUM
	Rule Name      :	instanceWithNoVpc
	Rule ID        :	AC_AWS_0153
	Resource Name  :	example
	Resource Type  :	aws_instance
	Category       :	Infrastructure Security
	
	-----------------------------------------------------------------------
	

Scan Summary -

	File/Folder         :	/github/workspace
	IaC Type            :	terraform
	Scanned At          :	2024-01-02 09:03:37.122136051 +0000 UTC
	Policies Validated  :	5
	Violated Policies   :	1
	Low                 :	0
	Medium              :	1
	High                :	0
	


Linter version command: ['/usr/bin/terrascan', 'version']
Linter version result: 0 version: v1.18.3

[Text Reporter] Generated TEXT report: /github/workspace/megalinter-reports/linters_logs/ERROR-TERRAFORM_TERRASCAN.log
❌ Linted [TERRAFORM] files with [terrascan]: Found 1 error(s) - (4.32s) (expand for details)
  - Using [terrascan v1.18.3] https://megalinter.io/7.7.0/descriptors/terraform_terrascan
  - MegaLinter key: [TERRAFORM_TERRASCAN]
  - Rules config: identified by [terrascan]
  [Pre][TERRAFORM_TERRASCAN] run: [terrascan] in cwd [/github/workspace]
  [Pre][TERRAFORM_TERRASCAN] result:
  Terrascan
  
  Detect compliance and security violations across Infrastructure as Code to mitigate risk before provisioning cloud native infrastructure.
  For more information, please visit https://runterrascan.io/
  
  Usage:
    terrascan [command]
  
  Available Commands:
    completion  Generate the autocompletion script for the specified shell
    help        Help about any command
    init        Initializes Terrascan and clones policies from the Terrascan GitHub repository.
    scan        Detect compliance and security violations across Infrastructure as Code.
    server      Run Terrascan as an API server
    version     Terrascan version
  
  Flags:
    -c, --config-path string      config file path
    -h, --help                    help for terrascan
    -l, --log-level string        log level (debug, info, warn, error, panic, fatal) (default "info")
        --log-output-dir string   directory path to write the log and output files
    -x, --log-type string         log output type (console, json) (default "console")
    -o, --output string           output type (human, json, yaml, xml, junit-xml, sarif, github-sarif) (default "human")
        --temp-dir string         temporary directory path to download remote repository,module and templates
  
  Use "terrascan [command] --help" for more information about a command.
  
  --Error detail:
  
  
  Scan Errors -
  
  	IaC Type            :	terraform
  	Directory           :	/github/workspace/anotherdirectory
  	Error Message       :	directory '/github/workspace/anotherdirectory' has no terraform config files
  	
  	-----------------------------------------------------------------------
  	
  	IaC Type            :	terraform
  	Directory           :	/github/workspace/megalinter-reports
  	Error Message       :	directory '/github/workspace/megalinter-reports' has no terraform config files
  	
  	-----------------------------------------------------------------------
  	
  
  
  Violation Details -
      
  	Description    :	Ensure that your AWS application is not deployed within the default Virtual Private Cloud in order to follow security best practices
  	File           :	main.tf
  	Module Name    :	root
  	Plan Root      :	./
  	Line           :	29
  	Severity       :	MEDIUM
  	Rule Name      :	instanceWithNoVpc
  	Rule ID        :	AC_AWS_0153
  	Resource Name  :	example
  	Resource Type  :	aws_instance
  	Category       :	Infrastructure Security
  	
  	-----------------------------------------------------------------------
  	
  
  Scan Summary -
  
  	File/Folder         :	/github/workspace
  	IaC Type            :	terraform
  	Scanned At          :	2024-01-02 09:03:37.122136051 +0000 UTC
  	Policies Validated  :	5
  	Violated Policies   :	1
  	Low                 :	0
  	Medium              :	1
  	High                :	0
  	
  
  
[Post] No commands declared in user configuration

Error: gaLinter](https://megalinter.io/7.7.0) status: ❌ [ERROR](https://github.com/NTitmus/terraform1/actions/runs/7383951835)

| Descriptor |                                 Linter                                 |Files|Fixed|                              Errors                              |Elapsed time|
|------------|------------------------------------------------------------------------|-----|-----|------------------------------------------------------------------|------------|
|❌ TERRAFORM|[terrascan](https://megalinter.io/7.7.0/descriptors/terraform_terrascan)|yes  |     |[1](https://github.com/NTitmus/terraform1/actions/runs/7383951835)|4.32s       |

See detailed report in [MegaLinter reports](https://github.com/NTitmus/terraform1/actions/runs/7383951835)

_MegaLinter is graciously provided by [![OX Security](https://www.ox.security/wp-content/uploads/2022/06/logo.svg?ref=megalinter_comment)](https://www.ox.security/?ref=megalinter)_
Starting new HTTPS connection (1): api.github.com:443
[https://api.github.com:443](https://api.github.com/) "GET /repos/NTitmus/terraform1 HTTP/1.1" 200 None
[https://api.github.com:443](https://api.github.com/) "GET /repos/NTitmus/terraform1/commits/d5307675a71ed7bb228b61fe600433a0652eddf9 HTTP/1.1" 200 None
[https://api.github.com:443](https://api.github.com/) "GET /repos/NTitmus/terraform1/commits/d5307675a71ed7bb228b61fe600433a0652eddf9/pulls?per_page=1 HTTP/1.1" 200 2
[GitHub Comment Reporter] No pull request has been found, so no comment has been posted
[Azure Comment Reporter] No Azure Token found, so skipped post of PR comment
Start updated Sources Reporter
Popen(['git', 'diff', '--abbrev=40', '--full-index', '-M', '--raw', '-z', '--no-color'], cwd=/github/workspace, stdin=None, shell=False, universal_newlines=False)
Updated files :

[Updated Sources Reporter] No source file has been formatted or fixed
[Gitlab Comment Reporter] No Gitlab Token found, so skipped post of MR comment

+----SUMMARY---+-----------+---------+-------+-------+--------+--------------+
| Descriptor   | Linter    | Mode    | Files | Fixed | Errors | Elapsed time |
+--------------+-----------+---------+-------+-------+--------+--------------+
| ❌ TERRAFORM | terrascan | project |   n/a |       |      1 |        4.32s |
+--------------+-----------+---------+-------+-------+--------+--------------+

❌ Error(s) have been found during linting
To disable linters or customize their checks, you can use a .mega-linter.yml file at the root of your repository
More info at https://megalinter.io/7.7.0/configuration/
Cleared MegaLinter runtime config for request cd262e10-a94d-11ee-84b6-0242ac110002


When I run terrascan on my local (terrascan scan -I terraform), I get: 
Scan Errors -

	IaC Type            :	terraform
	Directory           :	/Users/<user>/Desktop/Programming/terraformLearn/learning/terrascan1/anotherdirectory
	Error Message       :	directory '/Users/<user>/Desktop/Programming/terraformLearn/ukhsa_learning/terrascan1/anotherdirectory' has no terraform config files
	
	-----------------------------------------------------------------------
	


Violation Details -
    
	Description    :	Ensure that your AWS application is not deployed within the default Virtual Private Cloud in order to follow security best practices
	File           :	main.tf
	Module Name    :	root
	Plan Root      :	./
	Line           :	29
	Severity       :	MEDIUM
	-----------------------------------------------------------------------
	

Scan Summary -

	File/Folder         :	/Users/<user>/Desktop/Programming/terraformLearn/learning/terrascan1
	IaC Type            :	terraform
	Scanned At          :	2024-01-02 09:47:48.095288 +0000 UTC
	Policies Validated  :	5
	Violated Policies   :	1
	Low                 :	0
	Medium              :	1
	High                :	0

**Comment by NTitmus** [comment]
I note in https://github.com/oxsecurity/megalinter/issues/3258 that the standard command is: 
[terrascan] command: ['terrascan', 'scan', 'd', '.', '-i', 'terraform', '-t', 'all', '-v']

It would probably be more helpful to me if there was an option of running terrascan on a file level (with ability to include/exclude certain files).  I note that the CLI lint mode for terrascan is project - https://megalinter.io/latest/descriptors/terraform_terrascan/ and https://megalinter.io/latest/config-cli-lint-mode/.  Having a file mode might help?  

I think doing this might also get away from the erroring when it encounters an empty directory (the original terrascan tool errors like this even when running on the local machine - https://github.com/tenable/terrascan/issues/1036).  But maybe it will be less efficient than running it in the project mode.

Perhaps this could be a feature for the future.

**Comment by nvuillam** [comment]
@NTitmus this seems to be more a terrascan error than a MegaLinter one... it has no sense to have a return code > 0 when there is no error :/

We could try to use list_of_files or even file cli lint modes, what would be the good call compared to `['terrascan', 'scan', 'd', '.', '-i', 'terraform', '-t', 'all', '-v']` ?

**Comment by NTitmus** [comment]
I agree @nvuillam - it is a terrascan issue - as this https://github.com/tenable/terrascan/issues/1036 shows.

As a standard command I think that it should be ['terrascan', 'scan', 'd', '.', '-i', 'terraform', '-v'].
This allows people to specify TERRAFORM_TERRASCAN_ARGUMENTS e.g. 
- '-t'
- 'aws'

or
- '-t'
- 'azure'


Ideally for me we would have a list_of_files and run this command on each file in the list of files: terrascan scan -i terraform -v -f <file>  
(and ideally we would be able to add the TERRAFORM_TERRASCAN_ARGUMENTS to this command e.g.: terrascan scan -i terraform -v -f <file> -t aws)

We would also be able to filter this list_of_files to exclude certain files e.g. contains_a_remote_module.tf or to only include main.tf and variables.tf.

**Comment by nvuillam** [comment]
Waiting for https://github.com/tenable/terrascan/issues/1036 to be updated...

**Comment by girlpunk** [comment]
For those still encountering this issue, a workaround is to add the following to your `.mega-linter.yml`:

```yaml
TERRAFORM_TERRASCAN_CLI_LINT_MODE: "file"
```

**Comment by nvuillam** [comment]
@girlpunk thanks a lot :)
