### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by tcsenpai** [oxsecurity/megalinter#3255]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_PYLINT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_BANDIT, PYTHON_MYPY, PYTHON_PYRIGHT, PYTHON_RUFF, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, COPYPASTE_JSCPD, CSS_STYLELINT, HTML_DJLINT, HTML_HTMLHINT, JAVASCRIPT_STANDARD, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, REPOSITORY_CHECKOV, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_GRYPE, REPOSITORY_KICS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY, REPOSITORY_TRIVY_SBOM, REPOSITORY_TRUFFLEHOG, TYPESCRIPT_STANDARD, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
What linter do you need that is not present in python flavor ? :)

**Comment by tcsenpai** [comment]
Good question! TBH i just followed the megalinter instructions and was
very late, prolly I misunderstood something :)

On 2023-12-30 16:38, Nicolas Vuillamy wrote: 

> What linter do you need that is not present in python flavor ? :) 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***> =
 

Links:
------
[1]
https://github.com/oxsecurity/megalinter/issues/3255#issuecomment-1872561507
[2]

**Comment by nvuillam** [comment]
Please can you try the python flavor and check the logs ? :)

**Comment by adhil0** [comment]
@nvuillam It looks like the python flavor is missing the JS/TS linters. Maybe it would be a good idea to create a `pythonweb` flavor, similar to `dotnetweb`? It Could cover apps that use Flask, Django, FastAPI, etc.

If you think it's a good idea, could you assign me to this issue? Would like to try contributing

**Comment by nvuillam** [comment]
@adhil0 I'm ok for a pythonweb flavor :)

You can submit a PR, and take inspiration from https://github.com/oxsecurity/megalinter/pull/2778 :)

Note: flavor_factory.py + descriptor yml files are enough to add a new flavor, the rest of the updates are generated during the build

**Comment by echoix** [comment]
I'm curious about the final size it would have compared to another one, like cupcake. I'm not sure only for that framework it would be worth the amount of CI that would be needed each time for that specific framework (Python and web, except for some (older) Django, isn't that common) is something that would benefit enough.
I'm not against, but I'd like to be convinced more with some numbers on what is saved, what is cost to save, etc. It's good to explore though!

**Comment by adhil0** [comment]
These are some good questions, I can help investigate. Of course, anyone else who's interested is more than welcome to join in as well!

**Comment by echoix** [comment]
I have to be the watchdog since we're near the limit of having to reorganize the structure because we are occasionally hitting API limits. The dotnet web flavor was a case where a common workload with ASP.NET didn't fit anything else. And since the size of the dotnet SDK is huge for what is really used (and a bit picky to integrate), it wasn't available in the cupcake flavor (the more balanced flavor), the full image is a bit big when you know the tools you want to use, and the dotnet-only flavor was missing a bit of tools.

**Comment by nvuillam** [comment]
@adhil0 if you make the PR we'll be able to compare size with cupcake flavor :)

@echoix thanks for being more cautious than i am sometimes:)

**Comment by echoix** [comment]
That's why we are a team!
