### ISSUE TITLE
TERRAFORM_TERRASCAN_ARGUMENTS "-t" "aws" do not work

### ISSUE THREAD

**Issue by nicolatitmus** [oxsecurity/megalinter#3258]
**Describe the bug**
When running Terrascan with (.mega-linter.yml file)
`TERRAFORM_TERRASCAN_ARGUMENTS:
- "-t"
- "aws"
- "-l"
- "debug"
`
This runs against all rules including Azure and GCP rules like: 
 {rule 15 0 'AC_GCP_0092' <nil>}
 {rule 15 0 'AC_AZURE_0440' <nil>}
 {rule 15 0 'accurics.azure.LOG.357' <nil>}

Output is different from running Terrascan with (.mega-linter.yml file)
`TERRAFORM_TERRASCAN_CLI_EXECUTABLE: "terrascan scan -t aws -l debug"`

This runs as expected against only AWS rules like: {rule 15 0 'AC_AWS_0312' <nil>}

**Comment by echoix** [comment]
To understand what is going on, one would need to see what is really called for both of the choices. To see the command that is used to call the linter, use 
`LOG_LEVEL: DEBUG` in your configuration. That will show what the built command is.

Come back after that, even if it is enough for you to understand the issue!

**Comment by echoix** [comment]
Note to us: we should document the using log level debug to refer to when answering issues

**Comment by nvuillam** [comment]
@echoix maybe in the issue template ? :)

**Comment by NTitmus** [comment]
Ah thanks!  - having added the LOG_LEVEL: DEBUG to the .mega-linter.yml file, it showed that the standard command run is:
[terrascan] command: ['terrascan', 'scan', 'd', '.', '-i', 'terraform', '-t', 'all', '-v']

If you add commands by using the TERRAFORM_TERRASCAN_ARGUMENTS e.g.:
TERRAFORM_TERRASCAN_ARGUMENTS:
  - "-t"
  - "aws"
  - "-l"
  - "debug"

then the command run is:
[terrascan] command: ['terrascan', 'scan', 'd', '.', '-i', 'terraform', '-t', 'all', '-v', '-t', 'aws', '-l', 'debug']

so the -t aws arguments can't come through because of the earlier -t all in the standard command.  

It's helpful to know the baseline behaviour - I don't think I require a fix to this necessarily (I think my issue is more with https://github.com/oxsecurity/megalinter/issues/3244 - as it would be more helpful for me if there was an option to do terrascan scan -f <filename> was called on a list of .tf files instead of using the -d . argument), but it might be helpful to put the standard terrascan command in the documentation as well as more examples of how to configure it.  I don't mind contributing (but I don't know where to do this - as it's just documentation rather than code).

**Comment by NTitmus** [comment]
I'm not sure if I recorded the initial issue correctly.  When  TERRAFORM_TERRASCAN_CLI_EXECUTABLE: "terrascan scan -t aws -l debug" is added to the .mega-linter.yml file, there is an error: 

terrascan before_lint_files: terrascan
[terrascan] command: ['terrascan scan -t aws -l debug', 'scan', 'd', '.', '-i', 'terraform', '-t', 'all', '-v']
[terrascan] CWD: /github/workspace
[terrascan] result: 999 Fatal error while calling terrascan: [Errno 2] No such file or directory: 'terrascan scan -t aws -l debug'
Linter version command: ['terrascan scan -t aws -l debug', 'version']
Unable to call command [terrascan scan -t aws -l debug version]
Unable to get version for linter [terrascan]
terrascan scan -t aws -l debug version returned output: (666) ERROR
Unable to extract version with regex re.compile('\\d+(\\.\\d+)+') from ERROR
[Text Reporter] Generated TEXT report: /github/workspace/megalinter-reports/linters_logs/ERROR-TERRAFORM_TERRASCAN.log

I think what needs to happen is that you have to give arguments as a list e.g.:
TERRAFORM_TERRASCAN_CLI_EXECUTABLE: ['terrascan', 'scan', '-t', 'aws', '-l', 'debug', '-i', 'terraform', '-d', 'to_scan']

or

```
TERRAFORM_TERRASCAN_CLI_EXECUTABLE: 
  - 'terrascan'
  - 'scan'
  - '-d'
  - 'to_scan'
  - '-t'
  - 'aws'
  - '-i'
  - 'terraform'
  - '-l'
  - 'debug'
```
But it is not clear that the TERRAFORM_TERRASCAN_CLI does a true over-ride.  It appears to just put these cli arguments in front of the standard ones.  

This output is seen:
terrascan before_lint_files: terrascan
[terrascan] command: ['terrascan', 'scan', '-d', 'to_scan', '-t', 'aws', '-i', 'terraform', '-l', 'debug', 'scan', 'd', '.', '-i', 'terraform', '-t', 'all', '-v']
[terrascan] CWD: /github/workspace

but further along:
Unable to get version for linter [terrascan]
/usr/bin/terrascan scan -d to_scan -t aws -i terraform -l debug version returned output: (3) 2024-01-06T13:05:21.535Z	debug	cli/register.go:66	TERRASCAN_CONFIG:
2024-01-06T13:05:21.535Z	debug	config/config-reader.go:55	no config file specified

It also appears to count errors twice: 

Violation Details -
    
	Description    :	Ensure that your AWS application is not deployed within the default Virtual Private Cloud in order to follow security best practices
	File           :	inc_file.tf
	Module Name    :	root
	Plan Root      :	./
	Line           :	1
	Severity       :	MEDIUM
	Rule Name      :	instanceWithNoVpc
	Rule ID        :	AC_AWS_0153
	Resource Name  :	simple
	Resource Type  :	aws_instance
	Category       :	Infrastructure Security
	
	-----------------------------------------------------------------------
	
	Description    :	Ensure that your AWS application is not deployed within the default Virtual Private Cloud in order to follow security best practices
	File           :	inc_file.tf
	Module Name    :	root
	Plan Root      :	./
	Line           :	1
	Severity       :	MEDIUM
	Rule Name      :	instanceWithNoVpc
	Rule ID        :	AC_AWS_0153
	Resource Name  :	simple
	Resource Type  :	aws_instance
	Category       :	Infrastructure Security
	
	-----------------------------------------------------------------------
	

Scan Summary -

	File/Folder         :	/github/workspace/to_scan
	IaC Type            :	terraform
	Scanned At          :	2024-01-06 13:05:21.497473835 +0000 UTC
	Policies Validated  :	10
	Violated Policies   :	2
	Low                 :	0
	Medium              :	2
	High                :	0

**Comment by nvuillam** [comment]
Could you try `TERRAFORM_TERRASCAN_CLI_EXECUTABLE: ["terrascan", "scan", "-t", "aws", "-l", "debug"]` (in .mega-linter.yml, not ENV var) ?

**Comment by NTitmus** [comment]
I have been configuring it via the .mega-linter.yml rather than env var in all the above examples.
