### ISSUE TITLE
JSCPD error  

### ISSUE THREAD

**Issue by bheemvennapureddy** [oxsecurity/megalinter#3278]
<img width="957" alt="Screenshot 2024-01-09 at 9 49 03 AM" src="https://github.com/oxsecurity/megalinter/assets/144472943/23d55067-52c4-4869-b1fd-c5634c0823ce">

**Comment by bheemvennapureddy** [comment]
Am i missing something here ?

**Comment by echoix** [comment]
Usually we have issue templates to help you give the information we need. Here, I see a
picture with a trace error.

What exactly do you want to tell us? With what would you want help with?

If it's a bug that needs to be investigated, we might need a bit more info on your setup and on the variables in play here: the released image versions, as well of the beta images to a certain extent, are already tested summarily that the tools installed are at least able to work.
We would need info on the versions that you used, (like Megalinter and Megalinter runner) not only that tool, and whether there are some customizations that you added, like installing some node packages inside the container. If so, it's pretty hard for us to predict what users could do to break the node environment inside.

At the end, the goal is to determine if there is something that we need to fix, or if it a bug in the linter itself that you happened to discover, and will need to work with the linter's authors. Mentioning if you tried the using the original tool (at the same version) without Megalinter does the same error. With what I see, this might be the case, as no line in the traceback mention Megalinter, and at that stage, Megalinter only has Python code involved.

**Comment by bheemvennapureddy** [comment]
Closing this one will create a new one for more details Thanks @echoix Apologies for the not adding all the info

**Comment by nvuillam** [comment]
I think jscpd.json might be wrongly formatted or contain an invalid value
