### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by jdx** [oxsecurity/megalinter#3284]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_PYLINT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_BANDIT, PYTHON_MYPY, PYTHON_PYRIGHT, PYTHON_RUFF, ACTION_ACTIONLINT, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, DOCKERFILE_HADOLINT, EDITORCONFIG_EDITORCONFIG_CHECKER, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY_SBOM, REPOSITORY_TRUFFLEHOG, RUBY_RUBOCOP, RUST_CLIPPY, XML_XMLLINT, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by echoix** [comment]
I have difficulty finding the trend amongst this, what kind of project is it? A Python + what?

**Comment by nvuillam** [comment]
I'd say Python +Ruby

@jdx i'm not sure of the common pattern on such projects, would it be possible to ignore rubocop linting, or to manually configure it in a separate job ?
