### ISSUE TITLE
Add weggli to the linter for c 

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [oxsecurity/megalinter#3285]
**Is your feature request related to a problem?**
nope

**Describe the solution you'd like**
Enrich security detection capabilities 

**Describe alternatives you've considered**
semgrep 

**Additional context**
- https://github.com/LordCasser/weggli-enhance
- https://security.humanativaspa.it/a-collection-of-weggli-patterns-for-c-cpp-vulnerability-research/

**Comment by nvuillam** [comment]
@Pierre-Gronau-ndaal [semgrep](https://megalinter.io/latest/descriptors/repository_semgrep/) is already integrated within MegaLinter, but activated only when a semgrep rules config var is defined in the analyzed repository

Example: `REPOSITORY_SEMGREP_RULESETS: ["p/docker-compose","p/owasp-top-ten"]`

Are there SemGrep rulesets similar to weggli rules ?

**Comment by Pierre-Gronau-ndaal** [comment]
In principle and for sure there is a overlapping

**Comment by nvuillam** [comment]
@Pierre-Gronau-ndaal > weggli seems dedicated to c & c++ so has probably more capabilities than SemGrep, & probably better performances

Would you like to add it in a PR ? :)

**Comment by Pierre-Gronau-ndaal** [comment]
I will do a PR If it is wished

**Comment by nvuillam** [comment]
@Pierre-Gronau-ndaal do you still wish to make the PR ? :)
