### ISSUE TITLE
DISABLE_ERRORS_LINTERS seems to only work if using .mega-linter in root folder

### ISSUE THREAD

**Issue by SamErde** [oxsecurity/megalinter#3294]
I'm trying to configure MegaLinter wholly in the workflow YML file, and the example file seems to suggest this is fine: 
>          # ADD YOUR CUSTOM ENV VARIABLES HERE OR DEFINE THEM IN A FILE
>          # .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY

However, when I specify a value for `DISABLE_ERRORS_LINTERS` in /.github/workflows/mega-linter.yml, the job log file tells me:
> To disable linters or customize their checks, you can use a .mega-linter.yml file at the root of your repository
More info at https://megalinter.io/7.7.0/configuration/

Which one is correct--or am I missing something simple that says "both?" Thanks!

**Comment by SamErde** [comment]
This may have been a red herring. I deleted the file at my repository's root folder and focused on checking my syntax + formatting in the workflow. It seems to be working now--and I'm just wondering what the pros and cons might be of using the two different methods of configuring MegaLinter.

**Comment by nvuillam** [comment]
@SamErde if the same configuration variable is defined in both ENV var (like in GitHub Actions Workflow) and .mega-linter.yml config file, the ENV var has the priority :)

DISABLE_ERRORS_LINTERS is supposed to work undepending where it is defined :)
