### ISSUE TITLE
Include enhanced GitLeaks ruleset

### ISSUE THREAD

**Issue by anotherbridge** [oxsecurity/megalinter#3296]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The default GitLeaks ruleset is nice to use, yet there are many more types secrets that can be detected. Thus I would like to propose including an enhanced ruleset covering more secrets to aim for a better detection rate:

https://gitlab.com/ndaal_open_source/ndaal_secretes_search/-/blob/master/gitleaks_base.toml?ref_type=heads

**Comment by nvuillam** [comment]
@anotherbridge you can define such ruleset at the root of your repo and it will be taken in account :)

I prefer to let the default one provided by the linter editor, but if you want to make a PR to update the doc to add a reference to such enhanced ruleset, it will be accepted :)

The update should happen around here -> https://github.com/oxsecurity/megalinter/blob/03ed4972b2db33e29564d18b488c1bfda41785df/megalinter/descriptors/repository.megalinter-descriptor.yml#L180
