### ISSUE TITLE
Improve output format of the powershell linter

### ISSUE THREAD

**Issue by efrecon** [oxsecurity/megalinter#3313]
**Is your feature request related to a problem? Please describe.**
The output of the powershell linter is formatted as an 80 chars-wide table. This makes the describing message difficult to read, but will also break the content of the `RuleName` and `ScriptName` columns into several lines.

**Describe the solution you'd like**
Output should adapt to the size of the terminal.

**Describe alternatives you've considered**
I think that the only required changed is to pipe the call to `Invoke-ScriptAnalyzer` into the `Format-Table` cmdlet, as in the example below:

```powershell
Invoke-ScriptAnalyzer -EnableExit -Path path-to-file.ps1 | Format-Table -AutoSize -Wrap
```

**Additional context**

**Comment by nvuillam** [comment]
That seems to be a good idea :)
Would you mike to submit a pull request? :)

**Comment by efrecon** [comment]
It required more than the `Format-Table` above, but PR linked to this issue now.
