### ISSUE TITLE
Multi-Project Repos / Modify Default Run Location For Specific Scanners

### ISSUE THREAD

**Issue by noremacskich** [oxsecurity/megalinter#3316]
Hello!

I've been trying to get MegaLinter working specifically with Typescript / Javascript in sub directory, with no luck.  I've been using a combination of the recommended github action in the documentation, and a stripped down version of one of the example config files.  

The setup I have is client folder, that has all of my front end in it (Vue 3 + Vite + config files). This specifically includes my eslint file, plus the tsconfig.json file.  The rest of the repo is comprised of a c# minimal API.

My  Repo Structure roughly looks like: (Based off of the[ .net 8 vue js minimal api template](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022))

```
/client/*
/client/tsconfig.json
/client/eslintrc.js
/.netProject1/*
/.netProject2/*
.sln
.megalinter.yml
```

I've been unable to get the typescript/javascript scanners to recognize that they should be started in the client sub directory, where everything they need is located, while the C# scanners should be done in the root directory.

The TS Config is currently the only one saying it can't find the tsconfig file (in my case it's a js, not json file).
The eslinter doesn't even run, as the precheck doesn't seem to think it's applicable

I've tried 
 - Setting the default_workspace to the client folder, but that didn't seem to do much (Setting it seems to have broken other things in the github action)
 - With the pre / post commands cd into / out of the folder, using both workspace and root
 - Various different file paths for the TYPESCRIPT_ES_FILE_NAME
 - Different variations on the regex folders

I have downloaded the npm package, and was able to successfully run it in both the client and root folder.  Running it directly in the client folder produces the expected results.  Running it in the root folder also runs into the same issue, it just not recognizing the TS / Javascript files in the client folder.

So, generally speaking, what should the approach here be?

Some other general questions:
 - The default workspace is /tmp/lint, what is the purpose of that folder and how is it being used?
 - What is the overall file location / relationship between the different parsers, where they are specifically run, and is there a way to change the default location of where they are run
 - Does the docker image do anything special with the files it's trying to scan, eg copies what' s in the repo into a special folder, etc

**Comment by nvuillam** [comment]
> The default workspace is /tmp/lint, what is the purpose of that folder and how is it being used?

The `docker run` maps the repository root to the docker container folder /tmp/lint

> What is the overall file location / relationship between the different parsers, where they are specifically run, and is there a way to change the default location of where they are run

JS/TS linters are run but no parser is natively called by MegaLinter

> Does the docker image do anything special with the files it's trying to scan, eg copies what' s in the repo into a special folder, etc

Nope, it just runs in /tmp/lint

Please could you share your .mega-linter.yml config file, or even create a public repository with the same structure so we can investigate the issue ?

**Comment by finnlander** [comment]
Just as a reference, I've managed to get the frontend linters to work from a subdirectory by defining these values into the `.mega-linter.yml` configuration file:

```yml
TYPESCRIPT_STANDARD_ARGUMENTS: "--project ./frontend/tsconfig.json"
TYPESCRIPT_ES_CONFIG_FILE: ".eslintrc.cjs"
TYPESCRIPT_ES_RULES_PATH: "frontend"
TSX_ESLINT_RULES_PATH: "frontend"
```

Perhaps that helps in your case too (changling the `frontend` into `client`, etc.)
