### ISSUE TITLE
BITBUCKET_COMMENT_REPORTER comments on every CI/CD job even though it's unused.

### ISSUE THREAD

**Issue by RelativeSure** [oxsecurity/megalinter#3317]
**Describe the bug**

In the new v7.8.0, the new BITBUCKET_COMMENT_REPORTER reporter has been released with the reporter being default set to true.
It comments in the workflow that it hasn't been setup. `[Bitbucket Comment Reporter] Required Bitbucket CI CD variables not found, so skipped post of PR comment`, this does not happen for any other reporter.

Can this please get removed or do we need to explicit set this to false so we don't get this message in our CI/CD?

**To Reproduce**

1. Go to '…'
2. Click on '….'
3. Scroll down to '….'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by echoix** [comment]
It prints this when running in bitbucket or another?

**Comment by RelativeSure** [comment]
> It prints this when running in bitbucket or another?

We run it towards a GitHub Enterprise where we use the GitHub Comment Reporter.
We run the megalinter-terraform flavor on Jenkins using the GitHub plugin.

**Comment by nvuillam** [comment]
PR on the way to remove useless logs :)

**Comment by RelativeSure** [comment]
Hi again,
Is this fix in v7.8.0 or is it first in v7.9.0 / v8.x.x?

Thanks in advance.

**Comment by echoix** [comment]
Next release, 7.9
