### ISSUE TITLE
PowerShell linter does not count errors properly

### ISSUE THREAD

**Issue by efrecon** [oxsecurity/megalinter#3320]
**Describe the bug**
The powershell linter does not count errors properly. Instead of reporting the number of errors, it report the number of erroneous files.

**To Reproduce**

1. Run the powershell linter on a file with several warnings/errors
2. Megalinter reports "1" error.

**Expected behavior**
The MegaLinter should count the number of errors and probably report warnings as non-blocking errors.

**note**
I believe this is because the [descriptor](https://github.com/oxsecurity/megalinter/blob/ef5bc5e42683a8ca1b9bec5b9e9afb75ba539c7c/megalinter/descriptors/powershell.megalinter-descriptor.yml#L30) does not provide a `cli_lint_errors_count` and `cli_lint_errors_regex` or similar.

**Comment by efrecon** [comment]
Not directly, not that I know. But, as I understand the implementation of the MegaLinter, the two descriptor keys that I mentioned above are able to count the number of occurrences of matches for the `cli_lint_errors_regex` regular expression. Is it so?

In that case, I think that it should be possible to control the order of the columns output from `Format-Table` (see #3318) and arrange for the severity to be placed first. We could then count the occurrences of `^Error` (or `^Warning` for non-blocking errors).

**Comment by nvuillam** [comment]
Indeed cli_lint_errors_count and cli_lint_errors_regex are the way to count errors using output text :)

@efrecon please feel free to add them, even in your current PR about Powershell if you want :)

**Comment by efrecon** [comment]
Merci @nvuillam. I've started to look at that but stumbled upon the following:

If I understand the code correctly, when the `total_errors` is `0` as of [this line](https://github.com/oxsecurity/megalinter/blob/3c21d7413ff141a13d529bad22a29770d07ff38c/megalinter/Linter.py#L1376) -- because there are only warnings or information (possible levels [here](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/Engine/Generic/RuleSeverity.cs)) -- the python code will issue a [warning](https://github.com/oxsecurity/megalinter/blob/3c21d7413ff141a13d529bad22a29770d07ff38c/megalinter/Linter.py#L1402). And, since there was some output, this will end up in being reported as 1 error (there was 1 file with some problems).

+ Is my understanding correct?
+ Is this correct behaviour?
+ How can I support "non-breaking" errors, e.g. `Warning` in the severity table linked above.

**Comment by echoix** [comment]
I'm not sure I understand your message correctly.

If I'm not mistaken, the configuration key DISABLE_ERRORS_LINTERS enables you to have a linter run, but if the linter reports errors, instead of failing the job, it will only report it as warnings. 

https://megalinter.io/latest/configuration/
https://megalinter.io/latest/configuration/#activation-and-deactivation


Is it a bit what you are trying to achieve? 

Or you are trying to "upgrade" the existing linter to be able to report both kinds (warnings AND errors) when it does (or doesn't) currently report it when used by itself manually.

**Comment by nvuillam** [comment]
@efrecon if the CI jobs pass, I'll merge the PR :)

**Comment by efrecon** [comment]
@nvuillam They.. didn't. One line too long, the rest being internal: a network error and a "no space on device error"

**Comment by nvuillam** [comment]
Appears to be solved by https://github.com/oxsecurity/megalinter/pull/3318 :)
