### ISSUE TITLE
Xmllint: also lint xsd files

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#3363]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when […]

See https://github.com/super-linter/super-linter/issues/5248

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nvuillam** [comment]
Agreed :)
I think you just have to add .xsd in the xml descriptor + sample xsd files in test cases :)
