### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by rahul-captionh** [oxsecurity/megalinter#3364]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

ACTION_ACTIONLINT, COPYPASTE_JSCPD, EDITORCONFIG_EDITORCONFIG_CHECKER, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_TABLE_FORMATTER, POWERSHELL_POWERSHELL, POWERSHELL_POWERSHELL_FORMATTER, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY, SPELL_CSPELL, TERRAFORM_TFLINT, TERRAFORM_TERRASCAN, TERRAFORM_TERRAGRUNT, TERRAFORM_TERRAFORM_FMT, YAML_YAMLLINT

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
What typology of project is it ?

If you didn't care about powershell, you could try ci_light flavor
otherwise dotnet flavor :)
