### ISSUE TITLE
Megalinter doesn't update the ts files with prettier ( doesn't format them )

### ISSUE THREAD

**Issue by bheemvennapureddy** [oxsecurity/megalinter#3383]
**Describe the bug**

Megalinter doesn't update the ts files with prettier ( doesn't format them )

**To Reproduce**

1. Update any ts file with bad format
2. Push a commit which runs mega linter and apply fixes on the same pr 
3. Check the fixes pushed by mega linter 
4. Check the screenshots below 

<img width="817" alt="Screenshot 2024-02-20 at 6 28 46 PM" src="https://github.com/oxsecurity/megalinter/assets/144472943/f96957fc-62f9-4878-a070-da8a5597549b">
<img width="958" alt="Screenshot 2024-02-20 at 6 29 06 PM" src="https://github.com/oxsecurity/megalinter/assets/144472943/4f71ad59-b3f3-44fd-bb39-283aaf970a36">
<img width="1058" alt="Screenshot 2024-02-20 at 6 29 35 PM" src="https://github.com/oxsecurity/megalinter/assets/144472943/b93bc332-1fae-4e9a-88d9-8149bd0f3f94">

<img width="850" alt="Screenshot 2024-02-20 at 6 32 13 PM" src="https://github.com/oxsecurity/megalinter/assets/144472943/70f110cd-3e08-4699-97bf-a80173d54f72">

<img width="644" alt="Screenshot 2024-02-20 at 6 32 23 PM" src="https://github.com/oxsecurity/megalinter/assets/144472943/a28266bc-c905-452c-b423-2c749de0eca4">

**Expected behavior**
format the files and push a commit 
**Screenshots**

**Additional context**

**Comment by bheemvennapureddy** [comment]
Here is the example file i am expecting it to format 
<img width="624" alt="Screenshot 2024-02-20 at 6 57 45 PM" src="https://github.com/oxsecurity/megalinter/assets/144472943/e654ef96-a90f-43ba-9563-c28a96564d1f">

**Comment by bheemvennapureddy** [comment]
@nvuillam  any insights ?

**Comment by nvuillam** [comment]
Something seems to ignore ts files, like if ts linters were not present, what flavor are you using ?

Please could you share the full log ? (U can mail it to be if it is not a public repo)

**Comment by bheemvennapureddy** [comment]
@nvuillam ignore looks like a flavor issue - i was using a resuable workflow in github and that made the flavor invisible - we were running dotnet one instead of the generic flavor.

**Comment by nvuillam** [comment]
The mystical bug is explained, thanks for the feedback :)
