### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by sassai** [oxsecurity/megalinter#3385]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

BASH_SHELLCHECK, BASH_SHFMT, COPYPASTE_JSCPD, ENV_DOTENV_LINTER, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, POWERSHELL_POWERSHELL, POWERSHELL_POWERSHELL_FORMATTER, REPOSITORY_CHECKOV, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_GRYPE, REPOSITORY_KICS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY, REPOSITORY_TRIVY_SBOM, REPOSITORY_TRUFFLEHOG, SPELL_CSPELL, SPELL_LYCHEE, TERRAFORM_TFLINT, TERRAFORM_TERRAGRUNT, TERRAFORM_TERRAFORM_FMT, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
What about using the dotnet one ? :) https://megalinter.io/latest/flavors/dotnet/

I think it contains all those linters, and the presence of powershell shows some microsoft presence 

If you don't need powershell linting, I think terraform flavor would do the job :) https://megalinter.io/latest/flavors/terraform/
