### ISSUE TITLE
Explore installing Python with astral's `uv`

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#3389]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when […]

I recently learned the early existence of https://github.com/astral-sh/uv, the next project of the creators of ruff, that installs python packages, like pip. They release very often, it is in the beginnings, but if the quality ends up like ruff (and their testing), it might be interesting, since a lot of time is spent installing python packages. It could be removed immediately from the image if we'd want to limit having an extra tool with extra surface to attack. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nvuillam** [comment]
they are in 0.1.1 version but if it's fast as ruff I'd be more than ok to use it when they reach 1.0.0 :)

Personal note: will everything be rewritten in rust ? 🤣

**Comment by nvuillam** [comment]
We should check for retrocompatibility for existing MegaLiner configs, especially the custom ones installing additional packages with pip in venvs with PRE_COMMANDS

**Comment by echoix** [comment]
https://astral.sh/blog/uv its public announcement is quite new, fev 15, 2024. You've got a point with the compatibility with being updated by pip afterwards.

**Comment by echoix** [comment]
I asked the question here https://github.com/astral-sh/uv/issues/2292

**Comment by echoix** [comment]
The answer is positive, if we make sure that we have pip installed in the venvs, they would be indistinguishable for users using pip to edit it afterwards.

**Comment by nvuillam** [comment]
Amazing, let's hope they soon reach a v1 :)
( I would have to spend weeks to do rollback if they make a breaking change between v0.x & v1 :p )
