### ISSUE TITLE
Kics incorrectly reporting the number of errors in summary

### ISSUE THREAD

**Issue by TommyE123** [oxsecurity/megalinter#3392]
**Describe the bug**
The Kics linter is incorrectly reporting the number of errors. This discrepancy becomes apparent when running the linter on files with multiple warnings or errors, as MegaLinter incorrectly displays "1" error instead of the actual count in the summary.

**To Reproduce**
Run the Kics linter on a file containing several warnings or errors.
Observe the output from MegaLinter, which inaccurately reports "1" error.

**Expected behavior**
MegaLinter should accurately count and report the total number of errors within the file.

**Comment by nvuillam** [comment]
@TommyE123 indeed !

A linter descriptor must contain properties **cli_lint_errors_count** and **cli_lint_errors_regex** to be able to count the errors.

Maybe you'd like to submit a PR to add them on [KICS descriptor](https://github.com/oxsecurity/megalinter/blob/baa70f4b7a5fc1d5793115d63109acca402911e8/megalinter/descriptors/repository.megalinter-descriptor.yml#L292) ? :) 

Example: 

```yaml
    cli_lint_errors_count: regex_number
    cli_lint_errors_regex: "files: ([0-9]+) finding"
```

**Comment by TommyE123** [comment]
The issue has been resolved and is now working as expected in version 7.10.0 following the latest release.
