### ISSUE TITLE
`SPELL_VALE_CONFIG_FILE` not working

### ISSUE THREAD

**Issue by schorlton** [oxsecurity/megalinter#3403]
Thanks as always for the great tool.

Trying to run `oxsecurity/megalinter-documentation:v7.9.0` using docker. Have a `.vale.ini` in `./linter/configs/`

I set `SPELL_VALE_CONFIG_FILE` to this location in `.mega-linter.yaml` but vale doesn't run. If I move `.vale.ini` to the root of my repo, it runs. Any ideas?

cc @wesley-dean-flexion

**Comment by wesley-dean-flexion** [comment]
https://megalinter.io/latest/descriptors/spell_vale/

> To be active within MegaLinter, you need to [initialize a .vale.ini configuration file](https://vale.sh/docs/vale-cli/structure/) at the root of your repository.

So, that behavior you're seeing makes sense.

That said, why wouldn't `SPELL_VALE_CONFIG_FILE` pointing to a different location also change that behavior?  That's... a good question.  I'll look into it and comment back; I just wanted to get something back to you as quickly as possible so as to hopefully unblock you.

**Comment by wesley-dean-flexion** [comment]
https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/spell.megalinter-descriptor.yml#L115

**Comment by wesley-dean-flexion** [comment]
@schorlton a couple of thoughts:

1. I don't know if `active_only_if_file_found` can accept an extended glob (`**/*/.vale.ini`) or a regex (`\.vale\.ini$`) or something like that, so if Vale's only going to run when there's a `.vale.ini` somewhere, I don't know how to have Megalinter look in multiple locations for it
2. running the Vale container without a configuration file causes Vale to throw an error, so allowing Vale to run when there isn't a config file somewhere where it's looking will cause Vale to throw an error.

```
E100 [.vale.ini not found] Runtime error

no config file found

Execution stopped with code 1.
```

I don't think we want Vale to run and fail unnecessarily (I don't think most people use it, actually) so unless there's a way to have that `active_only_if_file_found` to respect the `SPELL_VALE_CONFIG_FILE` parameter, I'm not sure how to proceed.

Would having a symlink from wherever the config file actually lives point back to the project root work?  (e.g., `ln -s "path/to/real/.vale.ini" "$(git rev-parse --show-toplevel)/.vale.ini"`).  If you're stuck having the actual config file reside in a location that's not the project root, that might help get you there.

In my humble opinion, having the `active_only_if_file_found` respect the `SPELL_VALE_CONFIG_FILE` parameter would be the best solution; however, if Megalinter doesn't currently do that -- regardless of how complicated the logic to support it may be -- I don't know if there would be a sufficient return on that investment.. then again, it's not my call.

Someone with more familiarity into that check works may be able to provide more insight.

Sorry... that's all I've got at the moment.

**Comment by wesley-dean-flexion** [comment]
Maybe we should remove that `SPELL_VALE_CONFIG_FILE` parameter so as to reduce potential confusion.  :shrug:

**Comment by schorlton** [comment]
Thanks @wesley-dean-flexion for the quick response! That was my best guess as well - the config should be removed if not possible to make it work or maybe there is some clever solution by the megalinter team. Putting linter configs in a dedicated folder is a practice we are trying to follow for repo organization...putting all of our (mega)linter configs in the root of the repo would increase clutter but is doable if needed.

**Comment by nvuillam** [comment]
@schorlton @wesley-dean-flexion I have an idea, I hope it will work ;)

https://github.com/oxsecurity/megalinter/pull/3409/files

**Comment by nvuillam** [comment]
@schorlton please can you check with MegaLinter beta version ?

Now if SPELL_VALE_CONFIG_FILE is defined, its value will be checked to define if the linter must be activated or not
