### ISSUE TITLE
ANSIBLE_LINT enablement in Megalinter configurations is not checking the ansible yaml validations.

### ISSUE THREAD

**Issue by selvanayaki678** [oxsecurity/megalinter#3424]
**Describe the bug**
ANSIBLE_LINT enablement in Megalinter configurations is not checking the ansible yaml validations.
 enabled the ansible_lint in megalinter configuration file. In output getting like this 
 
![image](https://github.com/oxsecurity/megalinter/assets/67256407/2f608275-35e5-4f29-913c-2957e2019881)

**Expected behavior**
It needs to check the all yaml files inside the directory and subdirectory as well.

**Screenshots**
Megalinter config file:
![image](https://github.com/oxsecurity/megalinter/assets/67256407/3f81a85a-29b8-48b3-a5fa-64a0cef76119)

**Additional context**
Running meglinter as container 
sudo docker run -v  $(pwd):/tmp/lint -e MEGALINTER_CONFIG=.mega-linter.yml -e ANSIBLE_DIRECTORY=any  -e ANSIBLE_ANSIBLE_LINT_DIRECTORY=any -e VALIDATE_ALL_CODEBASE=true  -e ANSIBLE_ANSIBLE_LINT_FILE_EXTENSIONS=[]  oxsecurity/megalinter:v7

**Output **
![image](https://github.com/oxsecurity/megalinter/assets/67256407/96b2b13e-8ae8-4d64-83bd-aa1e1385965c)

I have some wrong ANSIBLE format files inside that directory. But it's not giving anything in output.
Need a guidance for to do that

**Comment by echoix** [comment]
I'm not sure that `any` has a special meaning here, I think what your configuration is doing is specifying that you want to the Ansible linter to lint in the directory named `any`.

**Comment by nvuillam** [comment]
@selvanayaki678 please can you try `ANSIBLE_DIRECTORY=. ANSIBLE_ANSIBLE_LINT_DIRECTORY=.` ?

**Comment by selvanayaki678** [comment]
Will try.Thank you

**Comment by alexanderbazhenoff** [comment]
I have a slightly similar question: how ML detects to turn on ansible-lint?

I have an [ansible project](https://github.com/alexanderbazhenoff/ansible-collection-linux/tree/1_1_10) with correct ansible collection directory structure and [`.ansible-lint`](https://github.com/alexanderbazhenoff/ansible-collection-linux/blob/1_1_10/.ansible-lint) file in the root of repo dir. Ansible lint wasn't started, so I add `ANSIBLE_DIRECTORY: any` to `.mega-linter.yml`. [Nothing happended](https://github.com/alexanderbazhenoff/ansible-collection-linux/actions/runs/8409207536). Then I decided to add options `ANSIBLE_ANSIBLE_LINT_ARGUMENTS: --force-color -p` and [nothing happened again](https://github.com/alexanderbazhenoff/ansible-collection-linux/actions/runs/8409474614). Only when I add `ANSIBLE_DIRECTORY: .` [ansible-lint has started](https://github.com/alexanderbazhenoff/ansible-collection-linux/commit/b6315f34d703491989fe2f569c4012eeb70dc3a3).

Please improve detecting ansible in the project: at least, enable them when ansible-lint default config is found.

**Comment by echoix** [comment]
ie: projects following the directory structure now documented here https://docs.ansible.com/ansible/latest/tips_tricks/sample_setup.html#sample-directory-layout should work without adjustements. Is the current default config aligned to a previous usage pattern that no longer exists?
Its sure changing our defaults would break all the others that currently "just work" with the current defaults

**Comment by alexanderbazhenoff** [comment]
Hmmm... ok, whats wrong in my repo to automatically detect ansible?

Most of ansible collections were usually made with [the following structure](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html).

But if your ansible role inside of ansible collection or project root named as 'common' the directory structure `roles -> common` from your link will be right. Yes, it looks like I have the same structure.

**Comment by plosso** [comment]
Same issue here, did exactly what alexander did. Only when I changed `ANSIBLE_DIRECTORY: .` did the linter run.

**Comment by nvuillam** [comment]
So if I summarize, what would fit the requirement would be something like:

Activate ansible-lint if either ANSIBLE_DIRECTORY is found, either .ansible-lint file is found at the root of the repo ?

**Comment by plosso** [comment]
Yes. Not to complicate matters more but we set our LINTER_RULES_PATH to a subdirectory so if it takes that into account. 
We use a repo to house our linter rules and the workflow pulls that in and stages in the root of the repo; easier than maintaining the same files in multiple repositories. i.e. ./linter-config/.ansible-lint

**Comment by alexanderbazhenoff** [comment]
> Activate ansible-lint if either ANSIBLE_DIRECTORY is found, either .ansible-lint file is found at the root of the repo ?

I think, activate ansible-lint when `roles` folder or `.ansible-lint` file is found. But if `ANSIBLE_DIRECTORY` is set run ansible-lint anyway (doesn't matter `roles` and `.ansible-lint` is found).

Don't what other scans ML performed, but expected that `ANSIBLE_DIRECTORY=any` will lint every `*.yml` in the project.
