### ISSUE TITLE
Issues with TSQLLINT and .NET 8.x

### ISSUE THREAD

**Issue by jberkers42** [oxsecurity/megalinter#3439]
**Describe the bug**
tsqllint fails to run, generating errors to indicate it is looking for .Net version 6.0.0, when .Net 8.0.0 is installed in the image.

**To Reproduce**

1. On a project in GitLab (Self-hosted, with Kubernetes Runner), with MegaLinter integrated
2. Submit code, and wait for Pipeline to run
3. Pipeline reports errors about .Net Versions

**Expected behavior**
It is expected that tsqllint runs and analyses .SQL files

**Screenshots**
Log Dump from run with SQL Files:

```log
Unable to get version for linter [tsqllint]
/root/.dotnet/tools/tsqllint --version returned output: (150) You must install or update .NET to run this application.

App: /root/.dotnet/tools/tsqllint
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/lib/dotnet

The following frameworks were found:
  8.0.2 at [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=alpine.3.20-x64&os=alpine.3.19

Unable to extract version with regex re.compile('\\d+(\\.\\d+)+') from ERROR
❌ Linted [SQL] files with [tsqllint]: Found 2 error(s) - (0.01s) (expand for details)
- Using [tsqllint vERROR] https://megalinter.io/7.10.0/descriptors/sql_tsqllint
- MegaLinter key: [SQL_TSQLLINT]
- Rules config: identified by [tsqllint]
- Number of files analyzed: [2]
[tsqllint] archive-utility/lpuscripts/lrarchiveutil_create_leastprivuser.sql - ERROR - 1 error(s)
--Error detail:
You must install or update .NET to run this application.

App: /root/.dotnet/tools/tsqllint
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/lib/dotnet

The following frameworks were found:
  8.0.2 at [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=alpine.3.20-x64&os=alpine.3.19

[tsqllint] archive-utility/lpuscripts/lrarchiveutil_delete_leastprivuser.sql - ERROR - 1 error(s)
--Error detail:
You must install or update .NET to run this application.

App: /root/.dotnet/tools/tsqllint
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/lib/dotnet

The following frameworks were found:
  8.0.2 at [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=alpine.3.20-x64&os=alpine.3.19
```

**Additional context**
Running latest Megalinter (7.10.0)
Using Flavour: Megalinter dotnet

I understand that there were some issues with the tsqllint project requiring some updates to support later versions of .NET, however, understood this was resolved.

**Comment by echoix** [comment]
@bdovaz did we have to use the roll forward finally? If not, why wasn't tsqllint a problem at that time?

Yesterday I tried to upgrade the project to .net8 on a fork, to see if it was feasible for tsqllint to be single-file and/or trimmed and/or aot compiled. Unfortunately the Tsqllint.Infrastructure project in the solution loads assemblies from textual paths, and also loads for a plugin use. Plus some places where the version is retrieved by examining the assembly, but an alternative way that is trimmable was possible. Plus a part where different classes are loaded, from text, for different feature levels of a SQL Server library. It could be adapted to have a known list of feature levels that would need to be kept updated, so it could be known at compile time. 

Without trimming, (and most of dependencies updated, except problems, and some adjustments), the single-file size of TSQLlint was about 140 MB for windows. So it wasn't a direct win for what I wanted to test out. I wanted to check if it was possible for the project to drop being tied to the .net version.

**Comment by bdovaz** [comment]
Yes, we are using that option:

https://github.com/oxsecurity/megalinter/blob/b2dc54659f1fe3b8c58706d9895af38cf3dfb360/megalinter/linters/DotNetToolLinter.py#L10

**Comment by echoix** [comment]
Ah, I was looking for a file, within Docker or the descriptor
