### ISSUE TITLE
Request new MegaLinter flavor - python and embedded C/C++

### ISSUE THREAD

**Issue by dannystaple** [oxsecurity/megalinter#3441]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_BANDIT, PYTHON_RUFF, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, C_CPPLINT, CPP_CPPLINT, DOCKERFILE_HADOLINT, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_TABLE_FORMATTER, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY_SBOM, REPOSITORY_TRUFFLEHOG, XML_XMLLINT, YAML_YAMLLINT

Would it be possible to create one ? Thanks :relaxed:

**Comment by dannystaple** [comment]
(maybe not KICS)

**Comment by nvuillam** [comment]
Mmmm Python + CPP could look interesting :)

But what if we just add C / C++ to Python ?

**Comment by dannystaple** [comment]
That also sounds reasonable. The repo in question has some makefile and CMAKE stuff (which I don't see in the suggested linter combo), and a light dusting of bash scripts too.
