### ISSUE TITLE
How can I disable 'yamllint' linter to disable checking for quotes for Strings

### ISSUE THREAD

**Issue by svsatish** [oxsecurity/megalinter#3451]
I am using Megalinter with YAML_YAMLLINT and also have the Auto Fix feature enabled within the workflow. yamllint is checking for quotes for String values and although we have single-quotes for these, it is applying double-quote and committing the fix. How Can I disable this as I would like to have single-quotes for String values

**Comment by nvuillam** [comment]
@svsatish you can create a local `.yamllint.yml` file with the requested config for rule quoted_strings

https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.quoted_strings

Default config used by MegaLinter is https://github.com/apeyrat/megalinter/blob/main/TEMPLATES/.yamllint.yml
