### ISSUE TITLE
some information about installing megalinter in custom Dockerfile

### ISSUE THREAD

**Issue by magowiz** [oxsecurity/megalinter#3455]
Hi,
I would like to build my own docker image with mega-linter inside, the main reason for this is that I use have mainly python projects and installing dependencies before scanning it takes longer on alpine based images, so I wanted to create a debian-based mega-linter flavor python.

I saw your repository docker files and they are complex, I would like to know if there is an installable package for at least megalinter program, without linters (I can install them separately and only those I want), if something like `pip install megalinter` or `apt-get install megalinter` or again `npm i megalinter` can be performed.

I saw the mega-linter-runner package but this, for what I understand, creates configuration locally and download standard images.

Please let me know.
Best regards,

magowiz

**Comment by nvuillam** [comment]
Hi @magowiz the "MegaLinter program" kind of is the MegaLinter image, it's not possible to run without it :/

All MegaLinter descriptors contain the installation instructions to build the Dockerfile, and those instructions are specific to alpinelinux (examples: use of apk , reuse of alpine based docker images of linters ... )

So unfortunately I don't see a way to create debian-based ML image without major updates in MegaLinter:
- Add debian related install instructions in all descriptors
- Update CI to build alpine images + debian images

With the 100+ linters, such task seems huge :/

**Comment by echoix** [comment]
I think he was referring to the python logic, that we install in each image. If it were an installable Python package, he would be able to do his images

**Comment by nvuillam** [comment]
Oh I see

MegaLinter is not published on a package manager, but its "core" code is corresponding to the following lines

So you might do something like getting source files on MegaLinter repo then run the lines in your debian image to have MegaLinter python core + descriptors + default config in it

```dockerfile
COPY megalinter /megalinter
RUN PYTHONDONTWRITEBYTECODE=1 python /megalinter/setup.py install \
    && PYTHONDONTWRITEBYTECODE=1 python /megalinter/setup.py clean --all \
    && rm -rf /var/cache/apk/* \
    && find . | grep -E "(/__pycache__$|\.pyc$|\.pyo$)" | xargs rm -rf

#######################################
# Copy scripts and rules to container #
#######################################
COPY megalinter/descriptors /megalinter-descriptors
COPY TEMPLATES /action/lib/.automation
```
