### ISSUE TITLE
Upgrade PHP engine from 8.1 to 8.3

### ISSUE THREAD

**Issue by llaville** [oxsecurity/megalinter#3463]
**Is your feature request related to a problem? Please describe.**
Upgrade default PHP engine from 8.1 to 8.3
PHP 8.1 has reached [End-Of-Life now](https://www.php.net/supported-versions.php) -- only security fixes until end of this year !

PHP 8.4 is planned for [November 2024](https://wiki.php.net/todo/php84) 

Previous operation was a bit old now (see commit b944ba9c859d3be7b9dbe9d857a3e40de72c81b4 when we dropped support to PHP 7)

**Describe the solution you'd like**
Upgrade https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/php.megalinter-descriptor.yml

I can suggest  a PR 

**Describe alternatives you've considered**
No alternative exists, except if we keep on PHP 8.1

**Comment by nvuillam** [comment]
@llaville I'd love to see a PR about it, many thanks :)
