### ISSUE TITLE
Manage list type parameters with EXTENDS

### ISSUE THREAD

**Issue by bdovaz** [oxsecurity/megalinter#3466]
.mega-linter-base.yml

```yml
---
ENABLE_LINTERS:
  - LINTER_1
 ```

.mega-linter.yml

```yml
---
EXTENDS: .mega-linter-base.yml
ENABLE_LINTERS:
  - LINTER_2
 ```

Result:

```yml
---
ENABLE_LINTERS:
  - LINTER_2
 ```

Expected:

```yml
---
ENABLE_LINTERS:
  - LINTER_1
  - LINTER_2
 ```

@nvuillam can you think of a way to solve it?

Could we dynamically pull out which parameters are of list type and instead of replacing, do a concat with a distinct (remove duplicates) or something like that? I have little experience in python so I do not know what APIs exist for these cases.

**Comment by nvuillam** [comment]
We might be technically able to do that, but what is for exemple you want to remove a linter that is present in the base mega-linter.yml ?

That's why i chose property replacement instead of "append values"

**Comment by bdovaz** [comment]
@nvuillam the case I intend to solve with https://github.com/oxsecurity/megalinter/pull/3469 is the following:

1. Imagine you have a configuration template (.mega-linter-base.yml) with certain linters enabled.
2. You have a configuration file for nightly builds that inherits from that template (.mega-linter-base.yml) and adds linters that only have to be executed in that type of builds either because they take a long time to run or because the linter typology only makes sense in that case (`REPOSITORY_*`) and combines with `VALIDATE_ALL_CODEBASE: true`.
3. You have a configuration file for PRs that inherits from that template (.mega-linter-base.yml) and combines with `VALIDATE_ALL_CODEBASE: false` and certain settings that only make sense for the specific case of PRs.

So I came up with this need and created this PR, until now what I did was to duplicate all the linters and add them all again in each file but it was very little maintainable...

cc @echoix

**Comment by bdovaz** [comment]
> We might be technically able to do that, but what is for exemple you want to remove a linter that is present in the base mega-linter.yml ?
> 
> That's why i chose property replacement instead of "append values"

Actually for that specific case it would be necessary to make the "sub configuration" the one that rules and in the new method that I have created in https://github.com/oxsecurity/megalinter/pull/3469 it manages those specific settings of https://megalinter.io/latest/config-activation/, that is to say:

.mega-linter-base.yml

```yml
---
ENABLE_LINTERS:
  - LINTER_1
  - LINTER_2
```

.mega-linter.yml

```yml
---
EXTENDS: .mega-linter-base.yml
DISABLE_LINTERS:
  - LINTER_2
```

Linters that would run: LINTER_1

**Comment by bdovaz** [comment]
@nvuillam @echoix can any of you answer in order to unlock the PR?

Thank you!

**Comment by echoix** [comment]
I wrote this earlier but couldn't send it yet:


I have no preference nor objections on the direction to have. If you have an implementation idea, you can do it, it adds a use case without removing another.

For your question about excluding items, I think what you're looking for is "set operations". (Set vs list). Maybe some of these operations for sets exist for lists that don't have too much overhead (for the projects with lots of files, which we wouldn't want too much overhead)

**Comment by pjungermann** [comment]
I have a proposal at #3490 that would cover this use case. However, it takes a different approach.
