### ISSUE TITLE
devcontainer support

### ISSUE THREAD

**Issue by robinmordasiewicz** [oxsecurity/megalinter#3485]
We are using devcontainers and want to run megalinter from a pre-commit, but devcontainer mounts the workspace repo to a folder in the devcontainer at location "/workspace/reponame" but megalinter is not aware of this mount inside the devcontainer. Is there a way to run megalinter from a pre-commit hook within the devcontainer and pass in an environment variable with the original filesystem mount location ?

**Comment by nvuillam** [comment]
The .devcontainer file in MegaLinter is an inheritance from SuperLinter and i'm not sure it ever worked

It is possible to use MegaLinter as pre-commit ( @Kurt-von-Laven does it a lot ^^ ) , according to the documentation:  https://megalinter.io/latest/mega-linter-runner/#pre-commit-hook

About devcontainer + pre-commit + env variable.... as i'm not a devcontainer user, I'm sorry but on my side I have no answer :(

**Comment by nvuillam** [comment]
@rjaegers would you like to update the .devcontainer of MegaLinter to see if it works ? :)
