### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by napaul07** [oxsecurity/megalinter#3497]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_PYLINT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_BANDIT, PYTHON_MYPY, PYTHON_PYRIGHT, PYTHON_RUFF, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, C_CPPLINT, C_CLANG_FORMAT, COPYPASTE_JSCPD, CPP_CPPLINT, CPP_CLANG_FORMAT, GO_GOLANGCI_LINT, GO_REVIVE, GROOVY_NPM_GROOVY_LINT, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, MAKEFILE_CHECKMAKE, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, REPOSITORY_CHECKOV, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_GRYPE, REPOSITORY_KICS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY, REPOSITORY_TRIVY_SBOM, REPOSITORY_TRUFFLEHOG, RUST_CLIPPY, SPELL_CSPELL, SPELL_LYCHEE, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by echoix** [comment]
It's a kind of weird combination, what type of project would that be named?
I see Python, go, rust, c/cpp, it doesn't seem specialized into something a flavor is appropriate vs other of our larger flavors

**Comment by napaul07** [comment]
We have a small embedded Linux system with a few applications on it. It is all in one repository so there a combination of programming languages used. I use Golang-lint and was looking for Something similar for c code.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nvuillam** [comment]
@napaul07 won't cupcake flavor cover the requirements ? :)

https://megalinter.io/latest/flavors/cupcake/
