### ISSUE TITLE
[7.11] possible regression : need support

### ISSUE THREAD

**Issue by llaville** [oxsecurity/megalinter#3501]
**Describe the bug**
My workflows didn't changed since two weeks, but upgrading from 7.10.0 to 7.11.0 seems to raise an issue

**To Reproduce**
Trigger action on `fix-374` branch of my repo https://github.com/llaville/php-compatinfo to run unit tests workflow (with lint code base)

Got : https://github.com/llaville/php-compatinfo/actions/runs/8802684833/job/24159832968

**Screenshots**

![github com_llaville_php-compatinfo_actions_runs_8802684833_job_24159832968](https://github.com/oxsecurity/megalinter/assets/364342/05308d0b-e1df-4a69-a892-736725a445cf)

BTW, when I run it locally on a PHP 8.1 platform I got no error.

```
sudo rm -rf megalinter-reports/ && time docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:rw -v $(pwd):/tmp/lint:rw oxsecurity/megalinter-php:v7
```

**Additional context**
My workflow to lint code base is located on another repo  (to share it with all my PHP projects)  : https://github.com/llaville/.github/blob/master/.github/workflows/mega-linter.yml

**Comment by nvuillam** [comment]
Investigating :)
You seem to not be the only one -> https://github.com/oxsecurity/megalinter/issues/3421#issuecomment-2072151972

**Comment by llaville** [comment]
@nvuillam Thanks for your quick responsiveness !

**Comment by nvuillam** [comment]
@llaville thanks for reporting so quickly :) 

I tested my fix, I should release a v7.11.1 during the evening :)

**Comment by nvuillam** [comment]
@llaville please can you confirm that all is ok with 7.11.1 ? :)

**Comment by llaville** [comment]
@nvuillam Congratulations. 
I've just tested the new version 7.11.1 locally and online with GitHub Actions (https://github.com/llaville/php-compatinfo/actions/runs/8802684833/job/24182760911) 
Both run fine as excepted. No more regression detected ! Thanks again for your quick fix.
