### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by holtkampjs** [oxsecurity/megalinter#3510]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_PYLINT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_BANDIT, PYTHON_MYPY, PYTHON_PYRIGHT, PYTHON_RUFF, ACTION_ACTIONLINT, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, COPYPASTE_JSCPD, GROOVY_NPM_GROOVY_LINT, JSON_JSONLINT, JSON_V8R, JSON_PRETTIER, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, PERL_PERLCRITIC, POWERSHELL_POWERSHELL, POWERSHELL_POWERSHELL_FORMATTER, REPOSITORY_CHECKOV, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_GRYPE, REPOSITORY_KICS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY, REPOSITORY_TRIVY_SBOM, REPOSITORY_TRUFFLEHOG, SPELL_CSPELL, SPELL_LYCHEE, XML_XMLLINT, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
Python + Groovy + Perl ... that's quite disparate ...  I think the most appropriate is Cupcake flavor :)

https://megalinter.io/beta/flavors/cupcake/
