### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by holtkampjs** [oxsecurity/megalinter#3511]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

SALT_SALTLINT

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
salt-lint is a plugin so you can use it with any flavor :)

If you just need salt-lint, use the tinyest flavor CI_LIGHT  https://megalinter.io/beta/flavors/ci_light/ :)

https://megalinter.io/beta/plugins/#external-plugins-catalog

**Comment by nvuillam** [comment]
@holtkampjs I never thought of it, that's smart because if the installation instructions are in Dockerfile RUN instructions, it should work ! :)

But you should compare with the time to retrieve cupcake version,i'm not sure it would save you so much time
