### ISSUE TITLE
Schema does not support GO_GOLANGCI_LINT_CLI_LINT_MODE:

### ISSUE THREAD

**Issue by dschveninger** [oxsecurity/megalinter#3535]
**Describe the bug**
v8r are failing since the [v7 schema](https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json) in [schema store](https://www.schemastore.org/api/json/catalog.json) in missing [golangci](https://megalinter.io/latest/descriptors/go_golangci_lint/) GO_GOLANGCI_LINT_CLI_LINT_MODE field.

**Comment by nvuillam** [comment]
@dschveninger it's related to https://github.com/oxsecurity/megalinter/pull/3509

Now only project mode is available, so the variable does not exist anymore, please can you remove it from your .mega-linter.yml config file ?

**Comment by dschveninger** [comment]
The other issue we are having is we are still using V6.  Is there a why to place the Megalinter version in the schema so we do not have the issue until we upgrade to v7?  This will also be good for version 8 when it comes.

**Comment by nvuillam** [comment]
@dschveninger unfortunately, schemastore.org does not handle versioning 

This is not hard to upgrade to v7, and v6 is not maintained for a while and probably contains many deprecated linter versions, and maybe CVEs... I strongly advise you to upgrade to v7 :)

`npx mega-linter-runner --upgrade`
