### ISSUE TITLE
Is option `-p` in mega-linter-runner working properly?

### ISSUE THREAD

**Issue by vkucera** [oxsecurity/megalinter#3552]
The documentation of mega-linter-runner says that the `-p` option specifies "Directory containing the files to lint".

The way I understand it is that if I run `npx mega-linter-runner -p <path>` in the root directory of my repository, it will lint files in `<path>` with the configuration taken from `.mega-linter.yml` in the root directory.

However, it seems that what it does instead is to enter `<path>` and run the runner from there, as if `<path>` was the current directory, resulting in running with default settings.

**Comment by nvuillam** [comment]
Would you mind sharing logs  (after removing proprietary data if necessary) ?

Path is indeed used to map your local folder to lint with /tmp/lint in the container

![image](https://github.com/oxsecurity/megalinter/assets/17500430/c2fd6521-4895-45a4-b53c-e9970b8db668)
