### ISSUE TITLE
Specify Configuration File for CSharpier Linter

### ISSUE THREAD

**Issue by NadaMusthafa** [oxsecurity/megalinter#3553]
Currently, there are no environment variables available for CSharpier linter to point to a configuration file, making it challenging to specify rules from a specific configuration file. This limitation inhibits users from customizing linting rules efficiently.Hence, with current implementation, how can we set CSharpier linter to point to a custom configuration file?

**Comment by nvuillam** [comment]
@NadaMusthafa please could you share an example of call to CSharpier with config file, so we can add its management in MegaLinter ?

**Comment by creativehub2000** [comment]
We used the following Settings:

Docker Image (latest): oxsecurity/megalinter-only-csharp_csharpier:beta_20240508-1708

Environment variables:

For MegaLinter:
  MEGALINTER_FILES_TO_LINT : <list_of_comma_seperated_C#_files>
  ENABLE_LINTERS : CSHARP_CSHARPIER
  AZURE_COMMENT_REPORTER : false

For CSharpier:
  CSHARP_CSHARPIER_CONFIG_FILE : '/config/.editorconfig'
  CSHARP_CSHARPIER_CLI_LINT_MODE : list_of_files

With this basic setting, CSharpier throws an exception as shown.

![megalinter_issue](https://github.com/oxsecurity/megalinter/assets/63250919/eb63527f-96ec-4460-8bb9-46e46393c43e)

**Comment by TommyE123** [comment]
Hi @NadaMusthafa,

I’ve taken a look into this for you and have found a few problems with config files and paths both in `csharpier` and `megalinter` itself.

Taking `megalinter` out of the equation for a moment, running `csharpier` manually locally produces these results.

I’ve increased the indent to 8 spaces in the .editorconfig and .csharpierrc for testing purposes.
![image](https://github.com/oxsecurity/megalinter/assets/8810400/201880fb-622d-4183-b3b6-898c2bb5ab6f)

1.	`.editorconfig` only in the root of the directory ✅
2.	`.csharpierrc` only in the root of the directory ✅
3.	`.csharpierrc` in a config folder and use -config-path to point to it ✅
4.	`.editorconfig` in a config folder and use -config-path to point to it ❌
5.	`.editorconfig` in root and use --config-path to point to it ❌

This strongly suggests that csharpier doesn’t support using the `--config-path` to point to a `.editorconfig`. This would require logging an issue with [csharpier](https://github.com/belav/csharpier) directly if you don’t want to put an `.editorconfig` in the root of your code. However its widely recognised as standard practice to place this type of file in the root, hence why I guess they probably don’t support it.

However while doing some testing for this issue I noticed that megalinter doesn’t work when overriding the configuration file name or path for a `.csharpierrc ` file. I’ve created a PR for this here #3664

Hope this helps,
Tom
