### ISSUE TITLE
Tekton integration

### ISSUE THREAD

**Issue by JobaDiniz** [oxsecurity/megalinter#3554]
This [page](https://megalinter.io/latest/install-docker/) provides doc for different integrations. I wonder how would we integrate with [Tekton](https://tekton.dev/)

**Comment by nvuillam** [comment]
@JobaDiniz I'm not a tekton user (even if we have tekton-lint in MegaLinter ^^), but bassically calling MegaLinter is just calling a docker run with arguments, so it shouldn't be much different than with Jenkins for example

https://megalinter.io/latest/install-jenkins/

Would you like to give it a try with tekton then share the script so we can add it in the documentation ?

**Comment by JobaDiniz** [comment]
Does the docker contain all linters/formatters or is there a way to only "select" some formatters?

**Comment by nvuillam** [comment]
@JobaDiniz the main flavor contain all linters , but there are also much lighter flavors that fit to most of projects :)

https://megalinter.io/latest/flavors/
