### ISSUE TITLE
Issue in setting custom configuration  files

### ISSUE THREAD

**Issue by NadaMusthafa** [oxsecurity/megalinter#3556]
![AA](https://github.com/oxsecurity/megalinter/assets/93783722/f2c53f7f-36ae-47fa-a81c-7b2339a41182)
**Describe the bug**
There is an issue in specifying  rules from a specific configuration file. How can we set linter to point to a custom configuration file?

**To Reproduce**
CSHARP_DOTNET_FORMAT :
      MEGALINTER_FILES_TO_LINT = <list of comma seperated files>
      ENABLE_LINTERS = CSHARP_DOTNET_FORMAT
      --
      CSHARP_DOTNET_FORMAT_CONFIG_FILE: '/config/.editorconfig'
      CSHARP_DOTNET_FORMAT_CLI_LINT_MODE: file

**Expected behavior**
It should lint all the changed files.

**Comment by nvuillam** [comment]
Duplicate of https://github.com/oxsecurity/megalinter/issues/3553 (we'll find a way, plz follow the main issue :) )
