### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by Dabitron** [oxsecurity/megalinter#3560]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_PYLINT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_BANDIT, PYTHON_MYPY, PYTHON_PYRIGHT, PYTHON_RUFF, ACTION_ACTIONLINT, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, COPYPASTE_JSCPD, CSS_STYLELINT, CSS_SCSS_LINT, DOCKERFILE_HADOLINT, JAVASCRIPT_STANDARD, JSON_JSONLINT, JSON_V8R, JSON_PRETTIER, JSON_NPM_PACKAGE_JSON_LINT, MAKEFILE_CHECKMAKE, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, OPENAPI_SPECTRAL, REPOSITORY_CHECKOV, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_GRYPE, REPOSITORY_KICS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY, REPOSITORY_TRIVY_SBOM, REPOSITORY_TRUFFLEHOG, SPELL_CSPELL, SPELL_LYCHEE, TYPESCRIPT_STANDARD, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
There are many linters JS + Python ? What kind of project is it ?

Would Cupcake flavor be smaller than the big one and still fit ? :)
