### ISSUE TITLE
Update version of tflint-ruleset-aws

### ISSUE THREAD

**Issue by mg-alanjones** [oxsecurity/megalinter#3573]
**Is your feature request related to a problem? Please describe.**
The version used for `tflint` plugin `tflint-ruleset-aws` is `0.23.1`, which was released [May 23, 2023](https://github.com/terraform-linters/tflint-ruleset-aws/tree/v0.23.1). I sometimes receive errors from `tflint` when they are actually valid, but it's a new feature so the plugin doesn't know of it.

**Describe the solution you'd like**
I suggest updating the version to the current latest, which is [0.31.0](https://github.com/terraform-linters/tflint-ruleset-aws/releases/tag/v0.31.0).

**Describe alternatives you've considered**
No other option really.

**Additional context**
None I can think of.

**Comment by echoix** [comment]
You could make a PR to bump it. I've been exploring using renovate instead of dependabot for this repo, and it has detected this, and would have kept it updated. In the meantime, let's update it manually.

**Comment by echoix** [comment]
Also, the docs link in that template is now bad, as the page moved in the repo.

**Comment by mg-alanjones** [comment]
Thank you team, appreciate this.
