### ISSUE TITLE
Powershell installed twice

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#3583]
**Describe the bug**

Powershell is installed twice, since arm ttk and other tools installs them, but one of them has 7.4.1 and others have 7.4.2, or something like that. When unpacking, the create link fails as there is already a file.

We need to find which one wasn't updated and update it there.

**To Reproduce**

1. Go to '…'
2. Click on '….'
3. Scroll down to '….'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nvuillam** [comment]
Such cases are handled with antique tehnique "copy-paste" :D 

Indeed the common install instructions must be exactly similar from both descriptors so it is not written twice in the generated Dockerfile

**Comment by echoix** [comment]
I didn't have the occasion to find which one was the correct one. But two flavors on beta fail all their builds because of this, continuously.

**Comment by nvuillam** [comment]
Fixed by your PR :)
