### ISSUE TITLE
Powershell error table formatting issue

### ISSUE THREAD

**Issue by TommyE123** [oxsecurity/megalinter#3603]
**Describe the bug**
In release v7.9.0, the output formatting of the PowerShell error table when run in an Azure DevOps pipeline or Github Actions Job is now cut off. The table displaying linting results is not formatted properly, causing misalignment and truncation of information. I believe this issue was introduced by the changes in the following pull request: [PR #3318](https://github.com/oxsecurity/megalinter/pull/3318).

**Expected behavior**
The linting results should be displayed in a properly formatted table with aligned columns and no truncation. Additionally, all columns (Severity, RuleName, ScriptName, Line, Message) should be fully visible.

**Screenshots**
V7.8.0
![image](https://github.com/oxsecurity/megalinter/assets/8810400/d1505b61-fa07-4ae8-9f7c-7ba6a6d2138d)

V7.11.1
![image](https://github.com/oxsecurity/megalinter/assets/8810400/b2f7bd6c-92b9-4c79-a393-786f0eb66fb4)

**Additional context**
- The Azure Devops log can support a much larger table width as it uses scroll bars. However id suggest if possible can we maybe just double the width as the message column can get rather long?

Thanks

**Comment by echoix** [comment]
Can you try setting the env variable COLUMNS, and set it a little bit bigger? In the PR linked, the function called from shutils should respect it. It would give a preview of what the output would look like with a wider terminal, but would apply to all linters.
