### ISSUE TITLE
VSCODE error

### ISSUE THREAD

**Issue by frchalaoux** [oxsecurity/megalinter#3614]
VSCODE and DJLINT last versions
Last MacOSX 

Sometimes, vscode raise this message :

2024-06-04 16:37:46.253 [error] {
	"shortMessage": "Command failed with exit code 1: /Users/frchalaoux/opt/miniconda3/envs/smb3/bin/python -m djlint - --quiet --linter-output-format '<filename>{filename}</filename><line>{line}</line><code>{code}</code><message>{message}</message>'",
	"command": "/Users/frchalaoux/opt/miniconda3/envs/smb3/bin/python -m djlint - --quiet --linter-output-format <filename>{filename}</filename><line>{line}</line><code>{code}</code><message>{message}</message>",
	"escapedCommand": "/Users/frchalaoux/opt/miniconda3/envs/smb3/bin/python -m djlint - --quiet --linter-output-format '<filename>{filename}</filename><line>{line}</line><code>{code}</code><message>{message}</message>'",
	"cwd": "/Users/frchalaoux/opt/miniconda3/envs/smb3/lib/python3.11/site-packages/pydantic",
	"durationMs": 112.615803,
	"failed": true,
	"timedOut": false,
	"isCanceled": false,
	"isTerminated": false,
	"isMaxBuffer": false,
	"exitCode": 1,
	"stdout": "",
	"stderr": "Traceback (most recent call last):\n  File \"<frozen runpy>\", line 189, in _run_module_as_main\n  File \"<frozen runpy>\", line 148, in _get_module_details\n  File \"<frozen runpy>\", line 112, in _get_module_details\n  File \"/Users/frchalaoux/opt/miniconda3/envs/smb3/lib/python3.11/site-packages/djlint/__init__.py\", line 10, in <module>\n    from typing import Dict, List, Optional, Tuple\n  File \"/Users/frchalaoux/opt/miniconda3/envs/smb3/lib/python3.11/site-packages/pydantic/typing.py\", line 2, in <module>\n    from ._migration import getattr_migration\nImportError: attempted relative import with no known parent package\n",
	"stdio": [
		null,
		"",
		"Traceback (most recent call last):\n  File \"<frozen runpy>\", line 189, in _run_module_as_main\n  File \"<frozen runpy>\", line 148, in _get_module_details\n  File \"<frozen runpy>\", line 112, in _get_module_details\n  File \"/Users/frchalaoux/opt/miniconda3/envs/smb3/lib/python3.11/site-packages/djlint/__init__.py\", line 10, in <module>\n    from typing import Dict, List, Optional, Tuple\n  File \"/Users/frchalaoux/opt/miniconda3/envs/smb3/lib/python3.11/site-packages/pydantic/typing.py\", line 2, in <module>\n    from ._migration import getattr_migration\nImportError: attempted relative import with no known parent package\n"
	],
	"pipedFrom": []
}
2024-06-04 16:37:47.003 [error] {
	"shortMessage": "Command failed with exit code 1: /Users/frchalaoux/opt/miniconda3/envs/smb3/bin/python -m djlint - --quiet --linter-output-format '<filename>{filename}</filename><line>{line}</line><code>{code}</code><message>{message}</message>'",
	"command": "/Users/frchalaoux/opt/miniconda3/envs/smb3/bin/python -m djlint - --quiet --linter-output-format <filename>{filename}</filename><line>{line}</line><code>{code}</code><message>{message}</message>",
	"escapedCommand": "/Users/frchalaoux/opt/miniconda3/envs/smb3/bin/python -m djlint - --quiet --linter-output-format '<filename>{filename}</filename><line>{line}</line><code>{code}</code><message>{message}</message>'",
	"cwd": "/Users/frchalaoux/opt/miniconda3/envs/smb3/lib/python3.11/site-packages/pydantic",
	"durationMs": 193.741807,
	"failed": true,
	"timedOut": false,
	"isCanceled": false,
	"isTerminated": false,
	"isMaxBuffer": false,
	"exitCode": 1,
	"stdout": "",
	"stderr": "Traceback (most recent call last):\n  File \"<frozen runpy>\", line 189, in _run_module_as_main\n  File \"<frozen runpy>\", line 148, in _get_module_details\n  File \"<frozen runpy>\", line 112, in _get_module_details\n  File \"/Users/frchalaoux/opt/miniconda3/envs/smb3/lib/python3.11/site-packages/djlint/__init__.py\", line 10, in <module>\n    from typing import Dict, List, Optional, Tuple\n  File \"/Users/frchalaoux/opt/miniconda3/envs/smb3/lib/python3.11/site-packages/pydantic/typing.py\", line 2, in <module>\n    from ._migration import getattr_migration\nImportError: attempted relative import with no known parent package\n",
	"stdio": [
		null,
		"",
		"Traceback (most recent call last):\n  File \"<frozen runpy>\", line 189, in _run_module_as_main\n  File \"<frozen runpy>\", line 148, in _get_module_details\n  File \"<frozen runpy>\", line 112, in _get_module_details\n  File \"/Users/frchalaoux/opt/miniconda3/envs/smb3/lib/python3.11/site-packages/djlint/__init__.py\", line 10, in <module>\n    from typing import Dict, List, Optional, Tuple\n  File \"/Users/frchalaoux/opt/miniconda3/envs/smb3/lib/python3.11/site-packages/pydantic/typing.py\", line 2, in <module>\n    from ._migration import getattr_migration\nImportError: attempted relative import with no known parent package\n"
	],
	"pipedFrom": []
}

**Comment by echoix** [comment]
I'm not quite sure if I understand your issue correctly, and the relation with Megalinter. We aren't creating an extension, so I would need to have more concise information to understand what we have that needs to be fixed

**Comment by nvuillam** [comment]
@frchalaoux please adress your issue on djlint repo :)

https://github.com/djlint/djlint
