### ISSUE TITLE
TFLint - deprecated argument in ".tflint.hcl"

### ISSUE THREAD

**Issue by mg-alanjones** [oxsecurity/megalinter#3618]
**Describe the bug**
The default [.tflint.hcl](https://github.com/oxsecurity/megalinter/blob/a7a0d920309a278226563104f7465629d7c16bf8/TEMPLATES/.tflint.hcl#L3) is using a deprecated argument. See screenshots below. The error message occurs for each error that TFLint finds, meaning it can get quite lengthy if there are lots of errors.

Potential solutions are:

1.  Change `module = false` to `call_module_type = "none"`
2. Remove `module = false`, which means by default it will be `call_module_type = "local"`

**To Reproduce**

1. Run TFLint in MegaLinter.

**Expected behavior**
This error should not occur because the argument should be updated.

**Screenshots**
```shell
❌ Linted [TERRAFORM] files with [tflint]: Found 1 error(s) - (7.58s) (expand for details)
- Using [tflint v0.51.1] https://megalinter.io/7.12.0/descriptors/terraform_tflint
- MegaLinter key: [TERRAFORM_TFLINT]
- Rules config: [.tflint.hcl]
[Pre][TERRAFORM_TFLINT] run: [tflint --init --config /action/lib/.automation/.tflint.hcl] in cwd [/]
[Pre][TERRAFORM_TFLINT] result:
WARNING: "module" attribute in /action/lib/.automation/.tflint.hcl is deprecated. Use "call_module_type" instead.
Installing "aws" plugin...
Installed "aws" (source: github.com/terraform-linters/tflint-ruleset-aws, version: 0.31.0)
```

**Comment by mg-alanjones** [comment]
Also the line 1 comment link is dead. It should be https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/config.md

**Comment by mg-alanjones** [comment]
Sorry, not sure what you mean. I meant the argument name should be updated. Rest of the configuration can stay as it is.

**Comment by echoix** [comment]
What do you think is the better option?

**Comment by mg-alanjones** [comment]
I think it should be changed to `call_module_type = "local"`, local modules should be scanned.

**Comment by echoix** [comment]
Let's go with that then!
