### ISSUE TITLE
Add conftest integration

### ISSUE THREAD

**Issue by csullivannet** [oxsecurity/megalinter#3656]
**Is your feature request related to a problem? Please describe.**
Yes, the general problem that megalinter aims to solve, by making it more convenient to run and integrate code quality analysis tools.

**Describe the solution you'd like**
Integration with [conftest.dev](https://www.conftest.dev/).

**Describe alternatives you've considered**
I can always just run conftest outside of megalinter, but that would be less convenient.

**Additional context**
I'm not sure whether this would really qualify as a "linter" per se. It does however have an [option to output TAP files](https://www.conftest.dev/options/#tap) which should allow it to integrate.

I don't know what the level of effort to integrate a new linter typically is, but I'm willing to give it a shot.

**Comment by nvuillam** [comment]
@csullivannet maybe you could start by creating a MegaLinter plugin, so we can see how it works , and if the adoption is here we can embed it in native MegaLinter ? :)

https://megalinter.io/latest/plugins/
