### ISSUE TITLE
golangci-lint linter fails, as my go.mod has 1.22, but Alpine 3.19 has 1.21

### ISSUE THREAD

**Issue by rasa** [oxsecurity/megalinter#3676]
When I try to run the golangci-lint linter, I get
```
level=error msg="Running error: context loading failed: failed to load packages: 
failed to load packages: failed to load with go/packages: err: exit status 1: stderr:
go: go.mod requires go >= 1.22.2 (running go 1.21.10; GOTOOLCHAIN=local)\n"
```
Unfortunately, I can't downgrade my go.mod file.

It seems Alpine 3.19 has go 1.21.10 per [here](https://pkgs.alpinelinux.org/packages?name=go&branch=v3.19&repo=&arch=&maintainer=). Alpine 3.20 has go 1.22.3 per [here](https://pkgs.alpinelinux.org/packages?name=go&branch=v3.20&repo=&arch=&maintainer=).

Is there any way around this issue, other than upgrading to Alpine 3.20?

**Comment by echoix** [comment]
Does the extra package channels make it possible to install newer packages on 3.19?

**Comment by rasa** [comment]
@echoix Yes, according to [here](https://stackoverflow.com/a/57269868), you can
```sh
echo "@community https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
apk add go@community
```
If I submit a PR implementing this change, would it be considered?

Alternatively, `https://dl-cdn.alpinelinux.org/alpine/v3.20/community` would work as well, but would need to be maintained.

**Comment by echoix** [comment]
Yes, on your image, with pre-commands, you can edit your image before actual starting to lint to adapt to your needs

**Comment by rasa** [comment]
Cool, I haven't played with precommands, but will give it a spin. Thx for the help
