### ISSUE TITLE
gherkin-linter in c_cpp flavor

### ISSUE THREAD

**Issue by andjordan** [oxsecurity/megalinter#3695]
MegaLinter would run faster on my project if c_cpp flavor could include:

- [GHERKIN](https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/gherkin.md)

Rationale:
We have a pure cpp repository, with automated tests described in gherkin files.
Since we moved to c_cpp flavor we are missing the gherkin linter.

**Comment by nvuillam** [comment]
@andjordan ok we'll do that :)
