### ISSUE TITLE
Kotlin Detekt cli_lint_mode= list_of_files support

### ISSUE THREAD

**Issue by enciyo** [oxsecurity/megalinter#3754]
Hi,
I want to run detekt for git diff. Is this possible with the latest changes?

For now I have overcome this by overriding the following value on the CI/CD side. But that doesn't seem like good behavior for us:

KOTLIN_DETEKT_ARGUMENTS: "--config config.yml --report sarif:megalinter-reports/detekt-result.sarif --report html:megalinter-reports/detekt-result.html --report md:megalinter-reports/detekt-result.md -i ${{ steps.diff.outputs.diff }}"

_Originally posted by @enciyo in https://github.com/oxsecurity/megalinter/issues/3579#issuecomment-2213366324_

**Comment by nvuillam** [comment]
@enciyo it was possible just before this PR ^^

https://github.com/oxsecurity/megalinter/pull/3590

I started a PR when we allow to override CLI_LINT_MODE if it is defined as `project`
