### ISSUE TITLE
Megalinter with CSharp Dotnet Format hangs on Mac with ARM chips

### ISSUE THREAD

**Issue by lamttu** [oxsecurity/megalinter#3808]
**Describe the bug**
On a Macbook (M1,2,3), megalitre will hang if csharp dotnet format is enabled.

**To Reproduce**

1. Create a megalinter config file with csharp dotnet format enabled.
2. Create a .NET 8 project
3. Run megalinter

**Expected behavior**
Megalinter finishes as normal

**Screenshots**

**Additional context**
I’m running Megalinter through the official docker image. It finishes normally on Windows and Mac with Intel chips.

When I run docker image inspect on the megalinter image, I could see that the platform is amd64. However, i’m unsure if this is the root cause

**Comment by nvuillam** [comment]
@lamttu ARM-based MegaLinter images is a one year long project that nobody succeeded to complete yet ^^

https://github.com/oxsecurity/megalinter/issues/1180

Unfortunately for now, you can just run it with M1 amd64 compatiblity

If some linter still refuses to work, the best workaround is to disable it :/
