### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by nsraj-7edge** [oxsecurity/megalinter#3823]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_PYLINT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_BANDIT, PYTHON_MYPY, PYTHON_PYRIGHT, PYTHON_RUFF, API_SPECTRAL, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, C_CPPLINT, C_CLANG_FORMAT, CLOUDFORMATION_CFN_LINT, COPYPASTE_JSCPD, CPP_CPPLINT, CPP_CLANG_FORMAT, JAVASCRIPT_ES, JAVASCRIPT_STANDARD, JSON_JSONLINT, JSON_V8R, JSON_PRETTIER, JSON_NPM_PACKAGE_JSON_LINT, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, OPENAPI_SPECTRAL, REPOSITORY_CHECKOV, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_GRYPE, REPOSITORY_KICS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY, REPOSITORY_TRIVY_SBOM, REPOSITORY_TRUFFLEHOG, RST_RST_LINT, RST_RSTCHECK, RST_RSTFMT, SPELL_CSPELL, SPELL_LYCHEE, TERRAFORM_TFLINT, TERRAFORM_TERRASCAN, TERRAFORM_TERRAFORM_FMT, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
Python + C + Javascript... that's a lot :)

Did you try Cupcake flavor ?

https://megalinter.io/latest/flavors/cupcake/
