### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by ofranzen** [oxsecurity/megalinter#3850]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_BANDIT, PYTHON_PYRIGHT, PYTHON_RUFF, API_SPECTRAL, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, COPYPASTE_JSCPD, GHERKIN_GHERKIN_LINT, JSON_JSONLINT, JSON_V8R, JSON_PRETTIER, MARKDOWN_MARKDOWNLINT, OPENAPI_SPECTRAL, REPOSITORY_CHECKOV, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_GRYPE, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY_SBOM, REPOSITORY_TRUFFLEHOG, SPELL_CSPELL, TERRAFORM_TERRAGRUNT, TERRAFORM_TERRAFORM_FMT, YAML_PRETTIER, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by nvuillam** [comment]
Did you try python or cupcake flavors ? :)
