### ISSUE TITLE
Ruff and black not excluding paths defined in linter config in `pyproject.toml`

### ISSUE THREAD

**Issue by johannaengland** [oxsecurity/megalinter#3915]
I know that is it possible to explicitly exclude paths by using `FILTER_REGEX_EXCLUDE`.
But since I already have these paths excluded in the linter configuration of black and ruff and I would like not to have to repeat that. 

But when I don't have `FILTER_REGEX_EXCLUDE` set these linters report errors in files in these excluded paths when using MegaLinter, but do not report error when running locally. 

My MegaLinter workflow file can be found here: https://github.com/johannaengland/zino/blob/workflows/megalinter/.github/workflows/linter.yml
`pyproject.toml`, where the linters are configured can be found here: https://github.com/johannaengland/zino/blob/workflows/megalinter/pyproject.toml
And the most recent failed workflow can be found here: https://github.com/johannaengland/zino/actions/runs/10470424903/job/28995542621

Please let me know if I made any mistakes configuring MegaLinter or if I am required to use `FILTER_REGEX_EXCLUDE`.

**Comment by nvuillam** [comment]
hi @johannaengland :)

Your configuration is good, but I think black and ruff ignore the content of pyproject.toml when we send them a list of files are argument (that's how MegaLinter works with list_of_files mode)

So you can either:
- Ask black & ruff repositories to apply exclude paths even when excluded files are sent as argument (some linters do it, some do not, but maybe the maintainers will accept it)
- Try to switch black and ruff from cli_lint_mode list_of_files to project: in that case, list of files won't be sent, black and ruff will be called without files arguments at the root of the project
  - define `PYTHON_RUFF_CLI_LINT_MODE=project` and `PYTHON_BLACK_CLI_LINT_MODE=project`
  - caution: if it does not work, make you need to send additional arguments, I think black requires a `.` , that you could forec by defining `PYTHON_BLACK_ARGUMENTS: ["."]`
- Use `FILTER_REGEX_EXCLUDE` (or linter scoped  variables` PYTHON_BLACK_FILTER_REGEX_EXCLUDE` and `PYTHON_RUFF_FILTER_REGEX_EXCLUDE` ) to exclude the files you don't want from the list of files sent as arguments to the linters

**Comment by echoix** [comment]
For ruff, see https://docs.astral.sh/ruff/settings/#force-exclude. It's the same problem as pre-commit, that would send a list of files to the tool, unless pre-commit has an exclusion list before calling the tool. Ruff has an option to still apply the exclusions. 


For black, see https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#force-exclude, with the same name

**Comment by nvuillam** [comment]
@johannaengland > @echoix 's reply is as shorter as it is better than mine 😃

**Comment by echoix** [comment]
If it's our expected behaviour, maybe we could consider sending it by default

**Comment by johannaengland** [comment]
Thank you so much for your help, this fixed my issue.

For other people who might have the same problem, here is my updated [`pyproject.toml`](https://github.com/Uninett/zino/blob/92a0c65ec8429a51623eb96e8f7eb08b2dbb784f/pyproject.toml) with the adapted ruff and black configuration.
