### ISSUE TITLE
MegaLinter Fails if LINTER_RULES_PATH does not exist

### ISSUE THREAD

**Issue by hype8912** [oxsecurity/megalinter#3922]
**Describe the bug**
When running "oxsecurity/megalinter-ci_light:v8" the job fails and throws a ValueError when the LINTER_RULES_PATH variable is defined to a path that does not exist. This didn't happen in v7.

**To Reproduce**

1. Create a job.
2. Define the LINTER_RULES_PATH variable to a non-existent path. For me since I was running it in GitLab I had it set to ".gitlab/linters"
3. Execute the pipeline.

**Expected behavior**
Expect it to maybe add a warning message but not error out the whole pipeline. Either way expected behavior is for the pipeline continue linting as if the path did exist.

**Screenshots**

```
- Image Creation Date: 2024-08-19T21:32:00Z
 - Image Revision: c217fe8f7bc9207062a084e989bd97efd56e7b9a
 - Image Version: v8.0.0
----------------------------------------------------------------------------------------------------
The MegaLinter documentation can be found at:
 - https://megalinter.io/8.0.0
----------------------------------------------------------------------------------------------------
MegaLinter initialization (expand for details)
MegaLinter will analyze workspace [/builds/internal/modules/megalinter]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 11, in <module>
    linter = megalinter.Megalinter({"cli": True, "request_id": str(uuid.uuid1())})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/MegaLinter.py", line 1[34](https://redacted-domain/internal/modules/megalinter/-/jobs/516000#L34), in __init__
    self.load_config_vars()
  File "/megalinter/MegaLinter.py", line 513, in load_config_vars
    raise ValueError(
ValueError: LINTER_RULES_PATH should be a valid directory (.gitlab/linters)
```

**Additional context**

**Comment by echoix** [comment]
Having a Python traceback error makes it seem problematic I agree. But is it really better if the job doesn't error out when you think it is using a rules path (that may be stricter than the defaults), but that path doesn't work (or exist)? I still think the job should fail because of that configuration error.

**Comment by nvuillam** [comment]
I agree with @echoix , I prefer that someone making a typo in .mega-linter.yml see this message (which is quite explicit) , instead of searching for hours why its config files in a custom folder are not taken in account :)

**Comment by nvuillam** [comment]
@hype8912 why would you need to have erroneous value not stopping MegaLinter ? Maybe a shared .mega-linter.yml ?

**Comment by hype8912** [comment]
I don't care either way. I was just showing I had my pipelines configured to v7 and it didn't fail by switching to v8 caused the error. The reason I had it set is because we publish GitLab CI/CD components for our internal GitLab instances so we had the path configured similar to the default (".github/linters") therefore in our reusable components we changed it to ".gitlab/linters" to match the typical configuration we would use in GitLab.

**Comment by nvuillam** [comment]
@hype8912 thanks for the feedback :)
If current behavior works for you, let's let it like that, otherwise we can think about some variable LINTER_RULES_PATH_IGNORE_ERROR or something like that, plz tell us ^^

**Comment by hype8912** [comment]
I'm ok with leaving it since the consensus is they like the error message. If more people comment about it and it becomes a major issue then we can revisit the issue. For now I consider this closed. I appreciate the fast response.

**Comment by nvuillam** [comment]
@hype8912 thanks for your understanding :)
