### ISSUE TITLE
Want to have control on the version of linter that is being used 

### ISSUE THREAD

**Issue by guptajag** [oxsecurity/megalinter#4014]
**Is your feature request related to a problem? 
It is important to control the specific version of `CPP_CLANG_FORMAT` used during the linting process. For instance, the current version supported by Mega-Linter is **17.0.6**:
<img width="364" alt="image" src="https://github.com/user-attachments/assets/cb4bab2a-6f7c-4ef3-9e83-b3eb486eb6ef">
However, the project requires [Clang 20.0.0](https://clang.llvm.org/docs/index.html)

**Describe the solution you'd like**
There should be an option in the `.mega-linter.yml` file to specify the desired version of the linter, such as:

```
ENABLE_LINTERS:
  - CPP_CLANG_FORMAT == 20.0.0
```
or 
```
ENABLE_LINTERS:
  - CPP_CLANG_FORMAT =< 17.0.6
```

This feature would dynamically create or update the necessary Mega-Linter container during runtime to ensure the specified version is used.

**Describe alternatives you've considered**
Currently exploring solutions but have not found any suitable alternatives to manually controlling the Clang format version.

**Comment by echoix** [comment]
Clang 19.1 (the first real release) was released yesterday... clang 20 would be something very custom and highly specific

**Comment by nvuillam** [comment]
@guptajag linters are installed during the build of MegaLinter, so if you need to override their version you can re-install the version you need using [PRE_COMMANDS](https://megalinter.io/beta/config-precommands/)
