### ISSUE TITLE
[Feature Request] Extend Summary Comment

### ISSUE THREAD

**Issue by ncalteen** [oxsecurity/megalinter#4028]
**Is your feature request related to a problem? Please describe.**

A team I work with uses MegaLinter and enforces rules at the organization-level using an internal repository where the base `.mega-linter.yml` and linting configuration files are held (each repo in the org extends this base configuration).

We have a process in place where teams can request changes to the current configuration for each linter (e.g. disable/relax rules). At the moment, discoverability is a bit challenging, as teams may not know that the rules are enforced using configuration files in a separate repo.

**Describe the solution you'd like**

It would be helpful if we could extend the summary comment MegaLinter adds to PRs to include additional Markdown content. For example, we could like to add something like this to the bottom of the PR comment.

```plain
Have a question about these results? Want to request a rule change? See [here](github.com/link/to/config/repo)
```

**Describe alternatives you've considered**

Adding a separate step in our linter workflow to do this ourselves, however if we went the route of modifying the comment added by MegaLinter, that would more than likely break the logic used to update the comment each time it runs.

**Comment by nvuillam** [comment]
@ncalteen something like :

```yaml
PR_SUMMARY_ADDITIONAL_MARKDOWN: Have a question about these results? Want to request a rule change? See [here](github.com/link/to/config/repo)
```

That would appear at the end of a PR message ? :)

**Comment by ncalteen** [comment]
That would be beautiful :D

**Comment by nvuillam** [comment]
@ncalteen totally doable, will try tonight ;)

That will just cost you some social media posts to ask for GitHub Stars ⭐   on the repo 😈

**Comment by nvuillam** [comment]
@ncalteen please can you try with beta version ? :)

**Comment by ncalteen** [comment]
![Beautiful](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExeDM4dXhhbjl3NHg3bWM2cXQyNzNsdW0wcjBoaTV2ZTB4eGI5cTMwNiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/i5wNCqyMzY2Oc/giphy.gif)
