### ISSUE TITLE
Internal CI: Docker Hub rate limit reached when using docker build

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#4065]
We never had this problem until now, but many jobs are failing because rate limit on docker hub :/

Example: https://github.com/oxsecurity/megalinter/actions/runs/11109206484/job/30866737149

Do anyone know if docker changed their policy for job running GitHub actions ? (i thought there was no limitations )

**Comment by finnlander** [comment]
There seems to be a rate limit for GitHub runners too, but according to [this](https://github.com/actions/runner-images/issues/1445#issuecomment-2332090826) comment, it is significantly higher than for "regular" Dockerhub users.

The discussion in the linked post gives an impression that this is a recurring issue (annually or so). Perhaps the usage is constantly increasing and therefore, the previous limits are reached, needing increment 🤷.

**Comment by nvuillam** [comment]
thanks @finnlander :)

**Comment by nvuillam** [comment]
Should be fixed by https://github.com/oxsecurity/megalinter/pull/4114
