### ISSUE TITLE
Markdown-link-check is now unusable with autogenerated tables of contents

### ISSUE THREAD

**Issue by chris-grabcad** [oxsecurity/megalinter#4079]
**Describe the bug**

This is a bug in 3.12.x of markdown-link-check which falesly markes autogenated
TOC links as unreachable, for example this piece of markdown will be flagged by
markdown-link-check v 3.12.x, but not by 3.11.x

```
[migrating from <= v1.18.0](#migrating-from--v1180)

### Migrating from `<= v1.18.0`
```

This is copied directly from https://github.com/tcort/markdown-link-check/issues/358

**Expected behavior**
Mega linter should produce consistent, noiseless and silencable errors.

**Additional context**
Downgrading markdown-link-check to v 3.11.x would be a workaround, but we cannot control the versions
of linters in megalinter :-(.

We could try using an earlier version of megalinter, but I believe that a different linter gives issues with
our repo under those circumstances.

**Comment by nvuillam** [comment]
You could disable markdown links check and try lychee instead, scopi'g only markdown files if you don't want to check links on other files

It's way faster abd might replace markdown links check in a future major version :)
