### ISSUE TITLE
GitHub Actions template contains linting errors

### ISSUE THREAD

**Issue by mihaur** [oxsecurity/megalinter#4103]
**Describe the bug**
When using megalinter on [GitHub Actions template](https://raw.githubusercontent.com/oxsecurity/megalinter/main/TEMPLATES/mega-linter.yml) I get errors from Checkov, KICS and Lychee linters.

**To Reproduce**
Run megalinter on a project with GitHub Actions template.

**Expected behavior**
I expected template to be free of linting errors so I can focus on finding issues in my code/IaC.

**Comment by nvuillam** [comment]
@mihaur good catch :)

Would you like to make a PR to fix the template ? :)

**Comment by mihaur** [comment]
Fixed by #4104
