### ISSUE TITLE
AzureCommentReporter fails when using central yaml pipeline repo

### ISSUE THREAD

**Issue by lukelloydagi** [oxsecurity/megalinter#4132]
**Describe the bug**
The AzureCommentReporter Python script relies on the BUILD_REPOSITORY_ID environment variable to get the PR:

![image](https://github.com/user-attachments/assets/d48a1ac8-de3c-4914-9928-a730893c72eb)

However that only works when the yaml pipeline exists in the same repo the PR was raised for.

**To Reproduce**

1. Create a build pipeline (with `AZURE_COMMENT_REPORTER=true`) in a repo separate to code repo
2. Configure branch policy in code repo for build validation (kicks off above created pipeline)
3. Raise PR in code repo
4. Error occurs
![image](https://github.com/user-attachments/assets/efa5d09b-30dc-45c7-8b57-4dd8ce4c2371)

**Expected behavior**
Comment on PR no matter the repository the PR was raised against

**Additional context**
Should be able to use the `SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI` environment variable and use that to locate the correct PR (extracting the repo name and looking up the repo id)

**Comment by nvuillam** [comment]
@lukelloydagi I didn't know that we could create a pipeline with the yaml of other repos ^^

If you want to add the behavior you describe in case  BUILD_REPOSITORY_ID  does not work, I'll gladly accept the PR :)

**Comment by lukelloyd1985** [comment]
> @lukelloydagi I didn't know that we could create a pipeline with the yaml of other repos ^^
> 
> If you want to add the behavior you describe in case BUILD_REPOSITORY_ID does not work, I'll gladly accept the PR :)

I've done that, hopefully I've followed the process successfully? ;)

**Comment by lukelloydagi** [comment]
@nvuillam, I thought using beta docker image used the main branch?

Seems it's using an image date of yesterday? 🤷‍♂️

![image](https://github.com/user-attachments/assets/9995ba96-4427-4198-8140-d355aa1a5d92)

**Comment by echoix** [comment]
> @nvuillam, I thought using beta docker image used the main branch?
> 
> 
> 
> Seems it's using an image date of yesterday? 🤷‍♂️
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/9995ba96-4427-4198-8140-d355aa1a5d92)
> 
> 

Probably not successfully built, we are struggling with recent rate limits (that delayed 8.1.0). I'll try to restart some jobs. But one of the rate limit is per-6-hours.

**Comment by lukelloyd1985** [comment]
👌🏻👍🏻
How often do you do stable releases too?

**Comment by nvuillam** [comment]
@lukelloyd1985 kind of every month or 2 months, depends on the activity :)

About this issue... I confirm it is published in beta, but... there is a crash :'( 

Any hint about how to solve it with a new PR ? :) ( without updating my Azure pipeline or config)

![image](https://github.com/user-attachments/assets/724c8aad-f8dc-402d-a3e5-2021b9d0dbdc)

![image](https://github.com/user-attachments/assets/cb4eedbe-2908-46f3-a61f-2af38bdf19b4)

**Comment by lukelloyd1985** [comment]
> @lukelloyd1985 kind of every month or 2 months, depends on the activity :)
> 
> About this issue... I confirm it is published in beta, but... there is a crash :'( 
> 
> Any hint about how to solve it with a new PR ? :) ( without updating my Azure pipeline or config)
> 
> ![image](https://github.com/user-attachments/assets/724c8aad-f8dc-402d-a3e5-2021b9d0dbdc)
> 
> ![image](https://github.com/user-attachments/assets/cb4eedbe-2908-46f3-a61f-2af38bdf19b4)
> 
> 

Ah it's failing while getting the repository because it wants the project reference. The MS docs say that's not required but docs are clearly never to be trusted 😉 I'll sort and raise a new PR 😎

**Comment by nvuillam** [comment]
@lukelloyd1985 if you can replace the logging.info by logging.debug it will be nice too :) (when it works, no one cares which variable is used ^^ )
