### ISSUE TITLE
Add tool like OctoScan to validate security of Pipelines

### ISSUE THREAD

**Issue by EtienneDeneuve** [oxsecurity/megalinter#4137]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Idea is to check the security of the GitHub Pipelines automatically.

**Describe alternatives you've considered**
this tool https://github.com/synacktiv/octoscan can help to implement it :)

**Comment by nvuillam** [comment]
octoscan is very new, let's wait for its adoption before embedding it within MegaLinter :)

If you are in a hurry, you can create a [MegaLinter Plugin](https://megalinter.io/latest/plugins/#create-your-own-plugin)

Meanwhile, there is already actionlint and all the security linters ^^
