### ISSUE TITLE
checkov only scan changed files

### ISSUE THREAD

**Issue by lukelloydagi** [oxsecurity/megalinter#4144]
Is it possible to have checkov only scan files that have changed (git diff) when VALIDATE_ALL_CODEBASE=false as per other linters?

**Comment by nvuillam** [comment]
@lukelloydagi checkov, as kics, are configured to run on folder, not with list of files ^^

Not even sure the tools allow to do that, i found nothing there for example https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

**Comment by nvuillam** [comment]
@lukelloyd1985 you can try to add the `-f` in how checkov is called :)

`REPOSITORY_CHECKOV_ARGUMENTS: ["-f"]`

To see how MegaLinter calls it, you can add LOG_LEVEL=DEBUG in the `.mega-linter.yml` file :)
