### ISSUE TITLE
Add to installation docs for Azure Pipelines

### ISSUE THREAD

**Issue by lukelloydagi** [oxsecurity/megalinter#4146]
**Is your feature request related to a problem? Please describe.**
Once #4132 is fixed shall I update the installation docs for Azure Pipelines detailing a YAML pipeline that can be used to lint all code repositories?

**Describe the solution you'd like**
In Azure DevOps (ADO) instead of having a build pipeline for each code repo with MegaLinter running you can have a single MegaLinter build pipeline that is ran when a PR is raised under any other code repo.

**Comment by nvuillam** [comment]
@lukelloydagi if such use case is useful for for it can probably be to others, so yes an additional section in the doc would be nice , thanks :)
