### ISSUE TITLE
AzureCommentReporter create active PR comment

### ISSUE THREAD

**Issue by lukelloydagi** [oxsecurity/megalinter#4152]
**Describe the solution you'd like**
AzureCommentReporter currently creates the PR comment as resolved, however it would be more useful to have the comment created as active. This allows for branch policies requiring comments to be resolved to be blocked until the MegaLinter output has been reviewed / alongside a peer review.

Would it be better to have the active vs resolved status as a toggle/environment variable to allow users to select what works for them?

**Additional context**
https://learn.microsoft.com/en-us/azure/devops/repos/git/review-pull-requests?view=azure-devops&tabs=browser#change-comment-status

https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-threads/create?view=azure-devops-rest-7.1&tabs=HTTP#commentthreadstatus

**Comment by nvuillam** [comment]
If i'm not mistaken, the comment is created as resolved if there are no MegaLinter errors, but as Active if there are errors :)

**Comment by nvuillam** [comment]
![image](https://github.com/user-attachments/assets/d0810414-a1f3-4b87-ad1a-f10eab7763fd)

**Comment by lukelloyd1985** [comment]
so it does 👏🏻

**Comment by nvuillam** [comment]
> so it does 👏🏻

this code looks strange with "fixed" or 1 as status, but it seems to work 🤣
