### ISSUE TITLE
Trivy ratelimit issues and workaround doubts

### ISSUE THREAD

**Issue by daantimmer** [oxsecurity/megalinter#4196]
I noticed Megalinter has implemented a workaround for the ratelimits that Trivy is encountering. I am having doubts regarding this workaround issue though.

Its mentioned that the retry is set to an interval of 3 seconds. However, I would assume this has to be more than a one minute interval because the rate limit is per minute?

**Comment by nvuillam** [comment]
@daantimmer I really hope that at some point trivy will make the necessary updates so such ugly workaround won't be needed anymore :/

Do you still have frequent issues with trivy ?

**Comment by daantimmer** [comment]
I had 5 unrelated builds fail in a timespan of 30 minutes (out of 6 builds).

Can't say if they are frequent though, as I don't watch _all_ our builds.

**Comment by nvuillam** [comment]
@daantimmer that's really sad but.... if you need to have stable MegaLinter runs, you might define trivy as non-blocking for now , and trivy itself is not stable and MegaLinter workarounds might not be enough :/

`REPOSITORY_TRIVY_DISABLE_ERRORS: true`

**Comment by daantimmer** [comment]
I'll throw that suggestion in the group! Hopefully trivy fixes their issues.

**Comment by nvuillam** [comment]
I think that between the new updates in trivy and MegaLinter retry management, we are all good :)
