### ISSUE TITLE
Azure DevOps PR status incorrect when using FAIL_IF_UPDATED_SOURCES

### ISSUE THREAD

**Issue by lukelloyd1985** [oxsecurity/megalinter#4210]
**Describe the bug**
Using the `FAIL_IF_UPDATED_SOURCES` variable is meant to fail MegaLinter if there are auto fixed files (which it does).
However the Azure PR comment shows as success:

**To Reproduce**

1. Configure a DevOps pipeline with the `FAIL_IF_UPDATED_SOURCES` variable
2. Raise a PR with a file known to require an auto fix
3. Voila, MegaLinter job should fail (as per screenshot) but PR comment with show "Success" and be raised resolved

**Expected behavior**
PR comment to show the MegaLinter failure and the comment to be in an active state

**Screenshots**
![image](https://github.com/user-attachments/assets/caf70a47-b53e-496b-bdd2-8f08742c9627)

![image](https://github.com/user-attachments/assets/e2ba71b1-c351-40d9-a311-0757089e2e32)

**Comment by nvuillam** [comment]
@lukelloyd1985 on it :)
