### ISSUE TITLE
Filter for Kotlin Detekt is not working

### ISSUE THREAD

**Issue by michael-wirth** [oxsecurity/megalinter#4232]
Excluding files from Kotlin Detekt linter is not working.
None of the documented configuration options has any impact on the list of files

**To Reproduce**

1. Create a Kotlin file in src/main/com/example/MyFile.kt
2. Create a Kotlin file in src/test/com/example/MyTest.kt
3. run ` docker run -it --rm -v $PWD:/tmp/lint -e FLAVOR=java -e ENABLE=KOTLIN -e 'FILTER_REGEX_INCLUDE=src/main' -e 'FILTER_REGEX_EXCLUDE=src/test' -e 'KOTLIN_DETEKT_FILE_NAMES_REGEX=src/main' -e LOG_LEVEL=DEBUG oxsecurity/megalinter`
4. See megalinter report

**Expected behavior**
The files in src/test should be ignored, but the FILTER rules for Detekt have no impact at all. It is not possible to exclude the src/test folder.

**Comment by nvuillam** [comment]
@michael-wirth Kotlin is called using **project** cli_lint_mode, meaning that MegaLinter filters can not apply.

You can use **--excludes** option with **KOTLIN_DETEKT_ARGUMENTS**

Example:

`KOTLIN_DETEKT_ARGUMENTS: ["--excludes", "src/main/**/*.kt"]`

Doc: https://detekt.dev/docs/gettingstarted/cli/
