### ISSUE TITLE
When will v8.2.0 release?

### ISSUE THREAD

**Issue by lukelloydagi** [oxsecurity/megalinter#4255]
When can we get v8.2.0 released? 😎

**Comment by nvuillam** [comment]
@lukelloydagi  I tried last week but trivy has been so boring that I failed and I preferred to not take the risk :D 

I plan next week, saturday or sunday :)

**Comment by nvuillam** [comment]
@lukelloydagi 8.2.0 released :)
https://github.com/oxsecurity/megalinter/releases/tag/v8.2.0
