### ISSUE TITLE
[8.2.0] Updated Sources Reporter issue

### ISSUE THREAD

**Issue by VictorRos** [oxsecurity/megalinter#4270]
**Describe the bug**

The new changes on reporters, more precisely on `UpdatedSourcesReporter` triggered an error once all linters have been run.

```bash
[Updated Sources Reporter] copied 5 fixed source files in folder /tmp/lint/megalinter-reports/updated_sources.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 14, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 304, in run
    reporter.produce_report()
  File "/megalinter/reporters/UpdatedSourcesReporter.py", line 70, in produce_report
    if apply_fixes.lower() != "none":
       ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'lower'
```

Exit code 1, so all runs fail even though all linters are green.

**To Reproduce**

Have a MegaLinter configuration with `APPLY_FIXES`.

Here are the full logs I got and the configuration I have.

- [.mega-linter.yml.txt](https://github.com/user-attachments/files/17799498/default.mega-linter.yml.txt)
- [mega-linter-output.log](https://github.com/user-attachments/files/17799503/mega-linter-output.log)

**Expected behavior**

**Updated Sources Reporter** should not have an impact on the run.

**Screenshots**

None.

**Additional context**

MacOS Sonoma 14.7, Apple M1 Pro

**Comment by lukelloyd1985** [comment]
@VictorRos 😔 I forgot `APPLY_FIXES` can be an array of linters, I was assuming `none` vs `all` values.

I'll try and get a fix to beta later today. In the meantime using value `all` in your `APPLY_FIXES` config should work and/or can MegaLinter be pinned to v8.1.0 🤷🏻‍♂️

Out of interest, are you using Azure DevOps or BitBucket (or other)?
