### ISSUE TITLE
Regression on Azure reporter in 8.2.0

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#4281]
![image](https://github.com/user-attachments/assets/3e10496d-feaf-481f-bfa8-dd23a36f97b5)

cc @lukelloyd1985

**Comment by lukelloyd1985** [comment]
> I think it doesn't like the replacement of %20 by spaces... where there are, it doesn't find the repo anymore :/

@nvuillam, odd as it was working fine when I tested both repo with spaces & repo without spaces when it was originally pushed to beta. The `SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI` passes the URL encoded path to the repository so if the repo contains spaces the `%20` will need replacing else it doesn't find the repository.

Would be interesting to know what the repo name was here? Maybe it's worth some debug logs being added so it can output the project & repo name so can be compared against what it should be?

**Comment by nvuillam** [comment]
@lukelloyd1985 something like `XXXXX%20-%20XXXXX/zzzzzzz`

But I added a fallback so it should be ok in all cases :)

You might have to add an extra variable ^^

![image](https://github.com/user-attachments/assets/94aed735-62f5-4022-aedd-a55e304705b0)
