### ISSUE TITLE
jspcd website github URLs are wrong

### ISSUE THREAD

**Issue by alexanderbazhenoff** [oxsecurity/megalinter#4336]
Visit the next page:

- https://megalinter.io/8.3.0/descriptors/copypaste_jscpd/

Then any Github URL is 404. E.g.:

https://github.com/kucherenko/jscpd/tree/master/packages/jscpd#readme

**Comment by echoix** [comment]
They moved a folder 3 months ago, it is now in apps:

https://github.com/kucherenko/jscpd/tree/master/apps/jscpd

Would you like to make a PR changing the descriptor file?

**Comment by alexanderbazhenoff** [comment]
no prob
https://github.com/oxsecurity/megalinter/pull/4352
