### ISSUE TITLE
Megalinter throwing errors on note findings

### ISSUE THREAD

**Issue by fostermarcp** [oxsecurity/megalinter#4344]
I may be misunderstanding how megalinter behaves here but I seem to be getting failing errors on "note" findings. I'm trying to only hard fail when an actual error is found, But am unable to find a way to do this. the only config option I have found is DISABLE_ERRORS which I don't wish to do. 

I would appreciate any help with this. 

MegaLinter Config:
```
# global settings
APPLY_FIXES: none
FLAVOR_SUGGESTIONS: false
SHOW_ELAPSED_TIME: true
ENABLE_LINTERS:
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRASCAN
  - REPOSITORY_GITLEAKS
  - REPOSITORY_TRIVY
  - YAML_YAMLLINT
  - SQL_SQLFLUFF
PRINT_ALPACA: false
VALIDATE_ALL_CODEBASE: false
PRINT_ALL_FILES: false

## logging settings
LOG_LEVEL: INFO
CLEAR_REPORT_FOLDER: true

## reporting settings
SARIF_REPORTER: true
AZURE_COMMENT_REPORTER: true
AZURE_COMMENT_REPORTER_LINKS_TYPE: build
REPORTERS_MARKDOWN_TYPE: simple
CONFIG_REPORTER: false
EMAIL_REPORTER: false
TAP_REPORTER: false

## linter settings
TERRAFORM_TFLINT_PRE_COMMANDS:
  - command: tflint --init
    cwd: "workspace"
```

Example "Errors" which are just note findings:
![image](https://github.com/user-attachments/assets/084af439-b162-4543-b0e5-cbe20595fefb)
![image](https://github.com/user-attachments/assets/ad434aa9-0545-4d0e-9f56-1155be94b89a)

**Comment by nvuillam** [comment]
This is a terrascan issue, please can you ask on their repo ?

https://github.com/tenable/terrascan

**Comment by nvuillam** [comment]
Oops I answered too fast ^^

`note` is the lowest level of issue severity with SARIF format

Both tflint and terrascan detect such issues, that's why you see them in output

You need to find which parameter to send to tflint and terrascan so their return code is 0 when "note" issues are found

**Comment by fostermarcp** [comment]
Appreciate the quick response :) this is exactly what I needed.

**Comment by nvuillam** [comment]
@fostermarcp once you have the answers, don't hesitate to update the linters documentation so it can help the future users with the same issue :)

(in properties `linter_text` in [descriptors](https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/terraform.megalinter-descriptor.yml), it will then be automatically propagated to documentation :) )
