### ISSUE TITLE
Linting swift code does not work. Error: No lintable files found at paths: '/tmp/lint'

### ISSUE THREAD

**Issue by r3econ** [oxsecurity/megalinter#440]
**Describe the bug**

Linting swift code does not work. The error appears:
```
...
Status: Downloaded newer image for norionomura/swiftlint:latest
The `swiftlint autocorrect` command is no longer available.
Please use `swiftlint --fix` instead.
Error: No lintable files found at paths: '/tmp/lint'
Correcting Swift files at paths /tmp/lint
```

**To Reproduce**

1. Follow the quick start CLI to add mega-linter to the iOS Swift project
2. Accept default values (except one case where you choose that it's a Swift project)
3. Push to the repo, create a PR to trigger the GitHub Action
4. See swift-lint error (not related to the codebase)

**Expected behavior**

- `swift-lint` starts linting the code base.

**Screenshots**

<img width="834" alt="Screenshot 2021-04-29 at 13 26 35" src="https://user-images.githubusercontent.com/505054/116544147-0d605800-a8ef-11eb-9c4d-d2ba95158a38.png">

- Contents of `ERROR-SWIFT_SWIFTLINT.log`
```
Results of swiftlint linter (version 0.43.1)
See documentation on https://nvuillam.github.io/mega-linter/descriptors/swift_swiftlint/
-----------------------------------------------

❌ [ERROR] for workspace /github/workspace
Linter raw log:
Unable to find image 'norionomura/swiftlint:latest' locally
latest: Pulling from norionomura/swiftlint
34667c7e4631: Pulling fs layer
d18d76a881a4: Pulling fs layer
119c7358fbfc: Pulling fs layer
2aaf13f3eff0: Pulling fs layer
969975223755: Pulling fs layer
1ea85296b57d: Pulling fs layer
178f29677290: Pulling fs layer
5f015d65fccd: Pulling fs layer
2aaf13f3eff0: Waiting
969975223755: Waiting
1ea85296b57d: Waiting
178f29677290: Waiting
5f015d65fccd: Waiting
d18d76a881a4: Verifying Checksum
d18d76a881a4: Download complete
119c7358fbfc: Verifying Checksum
119c7358fbfc: Download complete
2aaf13f3eff0: Verifying Checksum
2aaf13f3eff0: Download complete
1ea85296b57d: Verifying Checksum
1ea85296b57d: Download complete
34667c7e4631: Verifying Checksum
34667c7e4631: Download complete
5f015d65fccd: Verifying Checksum
5f015d65fccd: Download complete
969975223755: Verifying Checksum
969975223755: Download complete
34667c7e4631: Pull complete
178f29677290: Verifying Checksum
178f29677290: Download complete
d18d76a881a4: Pull complete
119c7358fbfc: Pull complete
2aaf13f3eff0: Pull complete
969975223755: Pull complete
1ea85296b57d: Pull complete
178f29677290: Pull complete
5f015d65fccd: Pull complete
Digest: sha256:2b118a4b74998159c4aa3cd3ccf6d73074bec6ad70cfab0be28f4459754a0640
Status: Downloaded newer image for norionomura/swiftlint:latest
The `swiftlint autocorrect` command is no longer available.
Please use `swiftlint --fix` instead.
Error: No lintable files found at paths: '/tmp/lint'
Correcting Swift files at paths /tmp/lint
```

- Contents of `.swiftlint.yml`
```
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - force_try # Remove when done
  - type_name
  - identifier_name
  - type_body_length
  - file_length

cyclomatic_complexity:
  ignores_case_statements: true
```

**Comment by nvuillam** [comment]
@r3econ I can, but i have a lot of work for the job i'm actually paid for, but I promise I'll try to solve that in y available free time :)
If someone else want to give it a try before that, it would be very welcome of course !

**Comment by r3econ** [comment]
I could also try to solve it but I'd need some hints. Do you know what is causing the problem there, where to start looking?.

**Comment by nvuillam** [comment]
You could try to replace --fix by autocorrect in the swift descriptor, maybe it would solve the issue

**Comment by nvuillam** [comment]
@r3econ i made the update I suggested, the test case passes, but please you check if it works with latest/insiders version ? ( not V4) and close the issue if it is fixed ?

**Comment by r3econ** [comment]
Thanks a lot! I tested, changed the action invocation in the workflow to use the latest tag like in the screenshot below.

<img width="468" alt="Screenshot 2021-05-17 at 11 58 28" src="https://user-images.githubusercontent.com/505054/118470701-35c9be00-b707-11eb-81f8-675caad25df6.png">

However, I'm still getting the same error `ErrCorrecting Swift files at paths /tmp/lint or: No lintable files found at paths: '/tmp/lint'`. Am I testing it correctly? I'm using the swift flavor.

Contents of `ERROR-SWIFT_SWIFTLINT.log`:
```
Results of swiftlint linter (version 0.43.1)
See documentation on https://nvuillam.github.io/mega-linter/descriptors/swift_swiftlint/
-----------------------------------------------

❌ [ERROR] for workspace /github/workspace
Linter raw log:
Unable to find image 'norionomura/swiftlint:latest' locally
latest: Pulling from norionomura/swiftlint
34667c7e4631: Pulling fs layer
d18d76a881a4: Pulling fs layer
119c7358fbfc: Pulling fs layer
2aaf13f3eff0: Pulling fs layer
969975223755: Pulling fs layer
1ea85296b57d: Pulling fs layer
178f29677290: Pulling fs layer
5f015d65fccd: Pulling fs layer
969975223755: Waiting
1ea85296b57d: Waiting
178f29677290: Waiting
5f015d65fccd: Waiting
2aaf13f3eff0: Waiting
119c7358fbfc: Verifying Checksum
119c7358fbfc: Download complete
d18d76a881a4: Verifying Checksum
d18d76a881a4: Download complete
2aaf13f3eff0: Verifying Checksum
2aaf13f3eff0: Download complete
1ea85296b57d: Verifying Checksum
1ea85296b57d: Download complete
34667c7e4631: Verifying Checksum
34667c7e4631: Download complete
5f015d65fccd: Verifying Checksum
5f015d65fccd: Download complete
969975223755: Verifying Checksum
969975223755: Download complete
34667c7e4631: Pull complete
178f29677290: Verifying Checksum
178f29677290: Download complete
d18d76a881a4: Pull complete
119c7358fbfc: Pull complete
2aaf13f3eff0: Pull complete
969975223755: Pull complete
1ea85296b57d: Pull complete
178f29677290: Pull complete
5f015d65fccd: Pull complete
Digest: sha256:2b118a4b74998159c4aa3cd3ccf6d73074bec6ad70cfab0be28f4459754a0640
Status: Downloaded newer image for norionomura/swiftlint:latest
ErrCorrecting Swift files at paths /tmp/lint
or: No lintable files found at paths: '/tmp/lint'
```

**Comment by nvuillam** [comment]
To be honest, switch linting has been tested only from test cases, so the error you see is probably a real bug and not a mistake from you

Do you have a public repo where I could reproduce the problem ?

**Comment by nvuillam** [comment]
not stale

**Comment by goncalo-frade-iohk** [comment]
@nvuillam this is still happening. I believe the problem is with the paths: `SwiftLint lint --path '/tmp/lint'` this path should be the GitHub action repo workspace. Is there any way to change this path on the configurations?

**Comment by goncalo-frade-iohk** [comment]
Any suggestion around this? :)

**Comment by nvuillam** [comment]
I just made an attempt... let's see what CI says ^^

**Comment by goncalo-frade-iohk** [comment]
Sure if you need any help. :) As far as I understand the problem is with the path passed down to SwiftLint `SwiftLint lint --path '/tmp/lint'` Im not sure what is in this folder. But if you would change for the workspace path of the GitHub action it should work.

**Comment by nvuillam** [comment]
If you had an example of a full docker run command with swiftlint image it would help a lot :)

**Comment by goncalo-frade-iohk** [comment]
Well there is this GitHub action that I know works that also uses docker :).

https://github.com/norio-nomura/action-swiftlint

And this as the entrypoint:
https://github.com/norio-nomura/action-swiftlint/blob/master/entrypoint.sh

But don't know if this can help you.

**Comment by keithrfung** [comment]
This isn't stale and is still currently happening.

**Comment by nvuillam** [comment]
Reopened.... any help will be appreciated :)

**Comment by Noraldeno** [comment]
@nvuillam Could we reopen this issue? It is still occurring. :(

I see that you opened this [PR](https://github.com/oxsecurity/megalinter/pull/1757) a while back. Can we get this PR merged in? I added some comments in your PR. Hopefully, it helps.

**Comment by nvuillam** [comment]
@Noraldeno , as @echoix suggested, we would love you to make a new PR with the fixes, as non of us maintainers have experience with swift :)

**Comment by Noraldeno** [comment]
> @Noraldeno , as @echoix suggested, we would love you to make a new PR with the fixes, as non of us maintainers have experience with swift :)
> 
> 
> 
> 

@nvuillam. Yeap! I'll open a new PR. Thx!

**Comment by Noraldeno** [comment]
@echoix This issue is still occurring in the beta image.

Here is a sample action run using swiftlint's docker:

https://github.com/Noraldeno/My-Sample-iOS/actions/runs/12509434367/job/34898863086#step:3:1

Action run using Megalinter beta image that includes the fixes I made:

https://github.com/Noraldeno/My-Sample-iOS/actions/runs/12509434367/job/34898862997#step:4:74

Could you point me to where else I can look at in the code to fix the issue? Maybe it has to do with how the volume is mounted in the docker container. I can continue to look into it.

**Comment by Noraldeno** [comment]
@echoix Hope you are well. Following up on this.

The following is the latest run from the latest image:

https://github.com/Noraldeno/My-Sample-iOS/actions/runs/13016216798/job/36305936123#step:4:74


Here's the latest run using swiftlint's docker directly:

https://github.com/Noraldeno/My-Sample-iOS/actions/runs/13016216798/job/36305935721

**Comment by natebytes** [comment]
Hey @Noraldeno 

I was wondering if you got this to work? I'm currently experiencing the same issue, but just wanted to check before I poke around to see if I can work out why.
