### ISSUE TITLE
Install PHPStan with PHIVE rather than with Composer

### ISSUE THREAD

**Issue by llaville** [oxsecurity/megalinter#822]
**Describe the solution you'd like**
Install PHPStan with PHIVE rather than with Composer will reduces disk usage.

**Additional context**
When you install PHPStan with Composer, it's already contains a PHAR version of distribuable version. 
See https://github.com/phpstan/phpstan and `phpstan.phar` at root of repository

A PR will follows

**Comment by llaville** [comment]
@nvuillam PR is ready to review/merge

**Comment by nvuillam** [comment]
Merge , thanks or your contribution :)
