### ISSUE TITLE
Python Black: turn warnings into errors (e.g. `--strict`)

### ISSUE THREAD

**Issue by bittner** [oxsecurity/megalinter#871]
I'm using Black to lint Python code, and when it finds code it would reformat Mega-Linter identifies them as warnings. Hence the pipeline job succeeds.

```
✅ Linted [PYTHON] files with [black]: Found 1 non blocking error(s) - (0.35s)
```

According to [Black's usage screen](https://nvuillam.github.io/mega-linter/descriptors/python_black/#help-content) `black --diff --check` exits with a non-zero status code, hence I assume the command should fail.

There doesn't seem to be any configuration switch to turn such warnings into errors (something like a `--strict` argument).

Is this by design? Is there no way treat all warnings as errors, to avoid overlooking linter complaints?

**Comment by nvuillam** [comment]
You can add arguments in .mega-linter.yml file :)

In your case, it would be `PYTHON_BLACK_ARGUMENTS: --strict`

**Comment by llaville** [comment]
@nvuillam the `--strict` option does not exists in black linter. It was just a suggestion by @bittner

**Comment by nvuillam** [comment]
MegaLinter fails when the return code is > 0, is there a way to make black return 1 or more in case of warnings ?
