### ISSUE TITLE
Add gitleaks

### ISSUE THREAD

**Issue by t3mi** [oxsecurity/megalinter#876]
Please consider adding gitleaks for secret scanning in addition to secretlint.

**Comment by Kurt-von-Laven** [comment]
[gitleaks](https://github.com/zricethezav/gitleaks) looks like a worthwhile inclusion to me. Full disclosure that we probably don't have the bandwidth to add this ourselves for a while, but we are happy to support if someone picks this issue up.

**Comment by nvuillam** [comment]
Not stale, will be there in v6 :)

**Comment by nvuillam** [comment]
Done in v6-alpha 😇

**Comment by onedr0p** [comment]
Any word on when v6 will be done? Otherwise this could be close.

**Comment by nvuillam** [comment]
It is planned for next month :)

cc @InbarRose

**Comment by onedr0p** [comment]
Hi

**Comment by Kurt-von-Laven** [comment]
Thanks to the hard work of @nvuillam and others, v6 was just released with gitleaks!
